### ISSUE TITLE
BlenderBIM - Circular dependency when adding IfcDistributionSystem

### ISSUE THREAD

**Issue by TZwielehner** [IfcOpenShell/IfcOpenShell#1576] opened 2021-07-20 06:18 UTC
When I add an empty object and assign the class "IfcDistributionSystem" there is an error that no spatial container is selected. However, I can only add a spatial container after I assigned a class.
Current workaround is to assign a random class (IfcElement), then a container and afterwards switch to IfcDistributionSystem

**Comment by Moult** [comment] 2021-07-20 06:20
Systems are currently not supported at all in authoring, so the workflows and UX for it is completely untested. Let's keep this issue open until systems start becoming more of a thing.

**Comment by dedicos** [comment] 2021-07-20 06:27
As you probably know, IfcSystems coming out of Revit are a mess (or, in terms of electrical systems, do not exist). I'm trying a few "clean ups" to post-process the IFCs. I'll keep you updated about my findings.

**Comment by Moult** [comment] 2021-07-20 06:30
Agreed, I actually have the exact same problem. I am developing "clean up" scripts to fix IFCs from projects. Systems from Revit are an absolute nightmare. One thing I have missed (just today, in fact) is a proper IFC system UI in the BlenderBIM Add-on. Would you like to help build it? If so, take a look at the group module, and create a new "system" module using the group module code as a starting point.

**Comment by Moult** [comment] 2021-07-20 07:06
The groups system only implements IfcGroup and no subtypes for now. This is by design. The reasoning is that subtypes of IfcGroup are likely to be specialised for a discipline, and so I wanted to put it in a separate panel with discipline-specific features (e.g. IfcSystem).

They will never show in the outliner because the outliner currently will only show the spatial hierarchy. In the future, I plan to build different outliner hierarchy options - to switch between a spatial tree, a class tree, a group-based tree, etc.

The way assignment works is you click an object, and you press the diamond to either assign or unassign. The diamond shows the currently assigned status of the actively selected object (if you have multiple objects selected, only the active one determines the outcome). Therefore, whenever pressing the diamond, you should always have an active object selected otherwise it may look like it "doesn't work". This is a UX issue.

**Comment by dedicos** [comment] 2021-07-20 08:19
I understand. Will test it again then. Maybe my computer is slow on that specific concern, too.

**Comment by Moult** [comment] 2021-07-22 07:56
As of this commit https://github.com/IfcOpenShell/IfcOpenShell/commit/8071e079b37c3ced99768a87a1aeaf83aa93ce3d it is now possible to add, edit and assign things to IfcSystem (but not subtypes, as you want to do).

When I address subtypes, I'll close this bug.

**Closed** 2022-01-20 07:22 UTC
Labels: BlenderBIM
