### ISSUE TITLE
Error install blender bim

### ISSUE THREAD

**Issue by blenderarc** [IfcOpenShell/IfcOpenShell#4869] opened 2024-06-13 22:49 UTC
os: Windows
os_version: 10.0.22621
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 141 Stepping 1, GenuineIntel
blender_version: 4.1.1
blenderbim_version: 0.7.9.240611
last_actions: 
last_error: Traceback (most recent call last):
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\__init__.py", line 95, in <module>
    import blenderbim.bim
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\__init__.py", line 25, in <module>
    from . import handler, ui, prop, operator, helper
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\handler.py", line 25, in <module>
    import blenderbim.tool as tool
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\tool\__init__.py", line 30, in <module>
    from blenderbim.tool.document import Document
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\tool\document.py", line 23, in <module>
    from blenderbim.bim import import_ifc
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\bim\import_ifc.py", line 38, in <module>
    import ifcopenshell.util.shape
  File "C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\shape.py", line 26, in <module>
    from ifcopenshell.geom import ShapeElementType, ShapeType
ImportError: cannot import name 'ShapeElementType' from 'ifcopenshell.geom' (C:\Users\Sahru\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\geom\__init__.py)

**Comment by Moult** [comment] 2024-06-13 22:50
Duplicate of #4868.

**Closed by Moult** 2024-06-13 22:50 UTC
Labels: BlenderBIM
