### ISSUE TITLE
No geometry and collection after opening file

### ISSUE THREAD

**Issue by piotr-smolira** [IfcOpenShell/IfcOpenShell#4354] opened 2024-02-22 12:12 UTC
IFC doesn't load (no collection, nothing, even waiting it out doesn't help). However, I have this window on 'Project Info' as in the screenshot. I'm doing multiple saves right now due that issue, and could be that a file with just a small change yield this result. 
 *(bbim 0.0.240220, blender 4.02, py3.10 (but also didn't work in [3.3)*.

It happens when 1) I delete elements, and then saves;  2) or delete elements, and purge profiles and types .

[File for reference](https://github.com/IfcOpenShell/IfcOpenShell/files/14373656/ano.zip)

**Comment by Andrej730** [comment] 2024-02-23 06:47
Full error traceback was (can be obtained from Window - Toggle System Console):
```
  File "\blenderbim\bim\module\project\operator.py", line 734, in execute
    ifc_importer.execute()
  File "\blenderbim\bim\import_ifc.py", line 250, in execute
    self.create_native_elements()
  File "\blenderbim\bim\import_ifc.py", line 827, in create_native_elements
    mesh = self.create_native_faceted_brep(element, mesh_name, native_data)
  File "\blenderbim\bim\import_ifc.py", line 1166, in create_native_faceted_brep
    if props.has_blender_offset and self.is_point_far_away(self.mesh_data["co"][0:3], is_meters=False):
  File "\blenderbim\bim\import_iTraceback (most recent call last):
  File "\blenderbim\bim\module\project\operator.py", line 630, in load_handler
    self.finish_loading_project(context)
  File "\blenderbim\bim\module\project\operator.py", line 657, in finish_loading_project
    bpy.ops.bim.load_project_elements()
  File "\Blender\4.0\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "\blenderbim\bim\module\project\operator.py", line 734, in execute
    ifc_importer.execute()
  File "\blenderbim\bim\import_ifc.py", line 250, in execute
    self.create_native_elements()
  File "\blenderbim\bim\import_ifc.py", line 827, in create_native_elements
    mesh = self.create_native_faceted_brep(element, mesh_name, native_data)
  File "\blenderbim\bim\import_ifc.py", line 1166, in create_native_faceted_brep
    if props.has_blender_offset and self.is_point_far_away(self.mesh_data["co"][0:3], is_meters=False):
  File "\blenderbim\bim\import_ifc.py", line 299, in is_point_far_away
    return abs(coords[0]) > limit or abs(coords[1]) > limit or abs(coords[2]) > limit
IndexError: list index out of range
```

Also validation check:
```
2024-02-23:11:28:48,158 ERROR   [validate.py:386] For instance:
    #363131=IfcOwnerHistory($,$,$,$,$,$,$,0)
                            ^
With attribute:
    <attribute OwningUser: <entity IfcPersonAndOrganization>>
Not optional

2024-02-23:11:28:48,158 ERROR   [validate.py:386] For instance:
    #363131=IfcOwnerHistory($,$,$,$,$,$,$,0)
                              ^
With attribute:
    <attribute OwningApplication: <entity IfcApplication>>
Not optional

2024-02-23:11:29:18,087 ERROR   [validate.py:402] For instance:
    #46422=IfcShapeRepresentation(#19,'Body','MappedRepresentation',())
                                                                    ^^
With attribute:
    <attribute Items: <set [1:?] of <entity IfcRepresentationItem>>>
Value:
    ()
Not valid

2024-02-23:11:29:24,830 ERROR   [validate.py:386] For instance:
    #2=IfcOwnerHistory($,$,$,$,$,$,$,0)
                       ^
With attribute:
    <attribute OwningUser: <entity IfcPersonAndOrganization>>
Not optional

2024-02-23:11:29:24,832 ERROR   [validate.py:386] For instance:
    #2=IfcOwnerHistory($,$,$,$,$,$,$,0)
                         ^
With attribute:
    <attribute OwningApplication: <entity IfcApplication>>
Not optional

2024-02-23:11:29:25,122 ERROR   [validate.py:402] For instance:
    #5183=IfcShapeRepresentation(#19,'Body','MappedRepresentation',())
                                                                   ^^
With attribute:
    <attribute Items: <set [1:?] of <entity IfcRepresentationItem>>>
Value:
    ()
Not valid

2024-02-23:11:29:25,126 ERROR   [validate.py:402] For instance:
    #5171=IfcShapeRepresentation(#19,'Body','MappedRepresentation',())
                                                                   ^^
With attribute:
    <attribute Items: <set [1:?] of <entity IfcRepresentationItem>>>
Value:
    ()
Not valid

2024-02-23:11:29:25,130 ERROR   [validate.py:402] For instance:
    #5159=IfcShapeRepresentation(#19,'Body','MappedRepresentation',())
                                                                   ^^
With attribute:
    <attribute Items: <set [1:?] of <entity IfcRepresentationItem>>>
Value:
    ()
Not valid

2024-02-23:11:29:25,583 ERROR   [validate.py:402] For instance:
    #9572=IfcShapeRepresentation(#19,'Body','MappedRepresentation',())
                                                                   ^^
With attribute:
    <attribute Items: <set [1:?] of <entity IfcRepresentationItem>>>
Value:
    ()
Not valid

2024-02-23:11:31:59,275 ERROR   [rule_executor.py:250] On instance:
    #363149=IfcShapeRepresentation(#363150,'Axis','Curve2D',(#363151))
Rule IfcShapeModel.WR11:
    (sizeof(self.OfProductRepresentation) == 1) ^ (sizeof(self.RepresentationMap) == 1) ^ (sizeof(ofshapeaspect) == 1)
Violated by:
    ((5 == 1 ^ 0 == 1) ^ 0 == 1)
     +  where 5 = sizeof((#363148=IfcProductDefinitionShape($,$,(#363149,#363153)), #363176=IfcProductDefinitionShape($,$,(#363149,#363177)), #...)), #363209=IfcProductDefinitionShape($,$,(#363149,#363210)), #363232=IfcProductDefinitionShape($,$,(#363149,#363233))))
     +    where (#363148=IfcProductDefinitionShape($,$,(#363149,#363153)), #363176=IfcProductDefinitionShape($,$,(#363149,#363177)), #...)), #363209=IfcProductDefinitionShape($,$,(#363149,#363210)), #363232=IfcProductDefinitionShape($,$,(#363149,#363233))) = #363149=IfcShapeRepresentation(#363150,'Axis','Curve2D',(#363151)).OfProductRepresentation
     +  and   0 = sizeof(())
     +    where () = #363149=IfcShapeRepresentation(#363150,'Axis','Curve2D',(#363151)).RepresentationMap
     +  and   0 = sizeof(())
2024-02-23:11:31:59,355 ERROR   [rule_executor.py:250] On instance:
    #363143=IfcWallStandardCase('28FWmrxZP9Ig2nKB5iEK8Z',#363131,'Rabbit','Rabbit',$,#363144,#363148,$,$)
Rule IfcWallStandardCase.HasMaterialLayerSetUsage:
    (sizeof([temp for temp in usedin(self, 'ifc4x3_add1.ifcrelassociates.relatedobjects') if 'ifc4x3_add1.ifcrelassociatesmaterial' in typeof(temp) and 'ifc4x3_add1.ifcmateriallayersetusage' in typeof(temp.RelatingMaterial)]) == 1)
Violated by:
    (0 == 1)
     +  where 0 = sizeof([])
2024-02-23:11:31:59,360 ERROR   [rule_executor.py:250] On instance:
    #363171=IfcWallStandardCase('28FWmrxZP9Ig2nKB5iEK8N',#363131,'Rabbit','Rabbit',$,#363172,#363176,$,$)
Rule IfcWallStandardCase.HasMaterialLayerSetUsage:
    (sizeof([temp for temp in usedin(self, 'ifc4x3_add1.ifcrelassociates.relatedobjects') if 'ifc4x3_add1.ifcrelassociatesmaterial' in typeof(temp) and 'ifc4x3_add1.ifcmateriallayersetusage' in typeof(temp.RelatingMaterial)]) == 1)
Violated by:
    (0 == 1)
     +  where 0 = sizeof([])
2024-02-23:11:31:59,364 ERROR   [rule_executor.py:250] On instance:
    #363185=IfcWallStandardCase('28FWmrxZP9Ig2nKB5iEKN3',#363131,'Rabbit','Rabbit',$,#363186,#363148,$,$)
Rule IfcWallStandardCase.HasMaterialLayerSetUsage:
    (sizeof([temp for temp in usedin(self, 'ifc4x3_add1.ifcrelassociates.relatedobjects') if 'ifc4x3_add1.ifcrelassociatesmaterial' in typeof(temp) and 'ifc4x3_add1.ifcmateriallayersetusage' in typeof(temp.RelatingMaterial)]) == 1)
Violated by:
    (0 == 1)
     +  where 0 = sizeof([])
2024-02-23:11:31:59,367 ERROR   [rule_executor.py:250] On instance:
    #363189=IfcWallStandardCase('28FWmrxZP9Ig2nKB5iEKMs',#363131,'Rabbit','Rabbit',$,#363190,#363148,$,$)
Rule IfcWallStandardCase.HasMaterialLayerSetUsage:
    (sizeof([temp for temp in usedin(self, 'ifc4x3_add1.ifcrelassociates.relatedobjects') if 'ifc4x3_add1.ifcrelassociatesmaterial' in typeof(temp) and 'ifc4x3_add1.ifcmateriallayersetusage' in typeof(temp.RelatingMaterial)]) == 1)
Violated by:
    (0 == 1)
     +  where 0 = sizeof([])
2024-02-23:11:31:59,371 ERROR   [rule_executor.py:250] On instance:
    #363193=IfcWallStandardCase('28FWmrxZP9Ig2nKB5iEKIf',#363131,'Rabbit','Rabbit',$,#363194,#363197,$,$)
Rule IfcWallStandardCase.HasMaterialLayerSetUsage:
    (sizeof([temp for temp in usedin(self, 'ifc4x3_add1.ifcrelassociates.relatedobjects') if 'ifc4x3_add1.ifcrelassociatesmaterial' in typeof(temp) and 'ifc4x3_add1.ifcmateriallayersetusage' in typeof(temp.RelatingMaterial)]) == 1)
Violated by:
    (0 == 1)
     +  where 0 = sizeof([])
2024-02-23:11:31:59,373 ERROR   [rule_executor.py:250] On instance:
    #363205=IfcWallStandardCase('28FWmrxZP9Ig2nKB5iEKHT',#2,'Rabbit','Rabbit',$,#363206,#363209,$,$)
Rule IfcWallStandardCase.HasMaterialLayerSetUsage:
    (sizeof([temp for temp in usedin(self, 'ifc4x3_add1.ifcrelassociates.relatedobjects') if 'ifc4x3_add1.ifcrelassociatesmaterial' in typeof(temp) and 'ifc4x3_add1.ifcmateriallayersetusage' in typeof(temp.RelatingMaterial)]) == 1)
Violated by:
    (0 == 1)
     +  where 0 = sizeof([])
2024-02-23:11:31:59,377 ERROR   [rule_executor.py:250] On instance:
    #363216=IfcWallStandardCase('28FWmrxZP9Ig2nKB5iEK8A',#363131,'Rabbit','Rabbit',$,#363217,#363176,$,$)
Rule IfcWallStandardCase.HasMaterialLayerSetUsage:
    (sizeof([temp for temp in usedin(self, 'ifc4x3_add1.ifcrelassociates.relatedobjects') if 'ifc4x3_add1.ifcrelassociatesmaterial' in typeof(temp) and 'ifc4x3_add1.ifcmateriallayersetusage' in typeof(temp.RelatingMaterial)]) == 1)
Violated by:
    (0 == 1)
     +  where 0 = sizeof([])
2024-02-23:11:31:59,379 ERROR   [rule_executor.py:250] On instance:
    #363220=IfcWallStandardCase('28FWmrxZP9Ig2nKB5iEKJj',#363131,'Rabbit','Rabbit',$,#363221,#363197,$,$)
Rule IfcWallStandardCase.HasMaterialLayerSetUsage:
    (sizeof([temp for temp in usedin(self, 'ifc4x3_add1.ifcrelassociates.relatedobjects') if 'ifc4x3_add1.ifcrelassociatesmaterial' in typeof(temp) and 'ifc4x3_add1.ifcmateriallayersetusage' in typeof(temp.RelatingMaterial)]) == 1)
Violated by:
    (0 == 1)
     +  where 0 = sizeof([])
2024-02-23:11:31:59,382 ERROR   [rule_executor.py:250] On instance:
    #363224=IfcWallStandardCase('28FWmrxZP9Ig2nKB5iELpg',#363131,'Rabbit','Rabbit',$,#363225,#363148,$,$)
Rule IfcWallStandardCase.HasMaterialLayerSetUsage:
    (sizeof([temp for temp in usedin(self, 'ifc4x3_add1.ifcrelassociates.relatedobjects') if 'ifc4x3_add1.ifcrelassociatesmaterial' in typeof(temp) and 'ifc4x3_add1.ifcmateriallayersetusage' in typeof(temp.RelatingMaterial)]) == 1)
Violated by:
    (0 == 1)
     +  where 0 = sizeof([])
2024-02-23:11:31:59,385 ERROR   [rule_executor.py:250] On instance:
    #363228=IfcWallStandardCase('28FWmrxZP9Ig2nKB5iEKIr',#2,'Rabbit','Rabbit',$,#363229,#363232,$,$)
Rule IfcWallStandardCase.HasMaterialLayerSetUsage:
    (sizeof([temp for temp in usedin(self, 'ifc4x3_add1.ifcrelassociates.relatedobjects') if 'ifc4x3_add1.ifcrelassociatesmaterial' in typeof(temp) and 'ifc4x3_add1.ifcmateriallayersetusage' in typeof(temp.RelatingMaterial)]) == 1)
Violated by:
    (0 == 1)
     +  where 0 = sizeof([])
2024-02-23:11:31:59,388 ERROR   [rule_executor.py:250] On instance:
    #363238=IfcWallStandardCase('28FWmrxZP9Ig2nKB5iEKJ1',#363131,'Rabbit','Rabbit',$,#363239,#363197,$,$)
Rule IfcWallStandardCase.HasMaterialLayerSetUsage:
    (sizeof([temp for temp in usedin(self, 'ifc4x3_add1.ifcrelassociates.relatedobjects') if 'ifc4x3_add1.ifcrelassociatesmaterial' in typeof(temp) and 'ifc4x3_add1.ifcmateriallayersetusage' in typeof(temp.RelatingMaterial)]) == 1)
Violated by:
    (0 == 1)
     +  where 0 = sizeof([])
2024-02-23:11:31:59,392 ERROR   [rule_executor.py:250] On instance:
    #363242=IfcWallStandardCase('28FWmrxZP9Ig2nKB5iEKNG',#363131,'Rabbit','Rabbit',$,#363243,#363176,$,$)
Rule IfcWallStandardCase.HasMaterialLayerSetUsage:
    (sizeof([temp for temp in usedin(self, 'ifc4x3_add1.ifcrelassociates.relatedobjects') if 'ifc4x3_add1.ifcrelassociatesmaterial' in typeof(temp) and 'ifc4x3_add1.ifcmateriallayersetusage' in typeof(temp.RelatingMaterial)]) == 1)
Violated by:
    (0 == 1)
     +  where 0 = sizeof([])
2024-02-23:11:31:59,395 ERROR   [rule_executor.py:250] On instance:
    #363246=IfcWallStandardCase('28FWmrxZP9Ig2nKB5iEKNz',#363131,'Rabbit','Rabbit',$,#363247,#363176,$,$)
Rule IfcWallStandardCase.HasMaterialLayerSetUsage:
    (sizeof([temp for temp in usedin(self, 'ifc4x3_add1.ifcrelassociates.relatedobjects') if 'ifc4x3_add1.ifcrelassociatesmaterial' in typeof(temp) and 'ifc4x3_add1.ifcmateriallayersetusage' in typeof(temp.RelatingMaterial)]) == 1)
Violated by:
    (0 == 1)
     +  where 0 = sizeof([])
2024-02-23:11:31:59,402 ERROR   [rule_executor.py:250] On instance:
    #363250=IfcWallStandardCase('28FWmrxZP9Ig2nKB5iEK8m',#363131,'Rabbit','Rabbit',$,#363251,#363209,$,$)
Rule IfcWallStandardCase.HasMaterialLayerSetUsage:
    (sizeof([temp for temp in usedin(self, 'ifc4x3_add1.ifcrelassociates.relatedobjects') if 'ifc4x3_add1.ifcrelassociatesmaterial' in typeof(temp) and 'ifc4x3_add1.ifcmateriallayersetusage' in typeof(temp.RelatingMaterial)]) == 1)
Violated by:
    (0 == 1)
     +  where 0 = sizeof([])
Info: Check validation results in the system console.
```

It seems the main problem is that .ifc has some invalid representations - representations without any items:
```
2024-02-23:11:29:25,583 ERROR   [validate.py:402] For instance:
    #9572=IfcShapeRepresentation(#19,'Body','MappedRepresentation',())
                                                                   ^^
With attribute:
    <attribute Items: <set [1:?] of <entity IfcRepresentationItem>>>
Value:
    ()
Not valid
```

As a workaround you can remove those representation running the script below in Blender text editor.
```python
import ifcopenshell
filepath = r"C:\Users\Andrej\Desktop\pomoika\w8\ano\ano - Copy.ifc"
ifc_file = ifcopenshell.open(filepath)

for representation in ifc_file.by_type("IfcShapeRepresentation"):
    if not representation.Items:
        print(representation)
        for inverse in ifc_file.get_inverse(representation):
            print(f"--> {inverse.ShapeOfProduct[0]}")
        ifc_file.remove(representation)

ifc_file.write(filepath)

# #5159=IfcShapeRepresentation(#19,'Body','MappedRepresentation',())
# --> #9640=IfcBuildingElementProxy('2ZXytf$s51iBaOuJ4C9mNT',#2,'Rabbit','Rabbit',$,#9641,#9644,$,$)
# #5171=IfcShapeRepresentation(#19,'Body','MappedRepresentation',())
# --> #9645=IfcBuildingElementProxy('2ZXytf$s51iBaOuJ4C9mNS',#2,'Rabbit','Rabbit',$,#9646,#9649,$,$)
# #5183=IfcShapeRepresentation(#19,'Body','MappedRepresentation',())
# --> #9665=IfcBuildingElementProxy('2ZXytf$s51iBaOuJ4C9mNR',#2,'Rabbit','Rabbit',$,#9666,#9669,$,$)
# #9572=IfcShapeRepresentation(#19,'Body','MappedRepresentation',())
# --> #87083=IfcBuildingElementProxy('2ZXytf$s51iBaOuJ4C9mNL',#2,'Rabbit','Rabbit',$,#87084,#87087,$,$)
# #46422=IfcShapeRepresentation(#19,'Body','MappedRepresentation',())
# --> #46417=IfcBuildingElementProxy('2ZXytf$s51iBaOuJ4C9mNM',#2,'Rabbit','Rabbit',$,#46418,#46421,$,$)
```

It will remove representations without items and file will load.

Do you have a previous version of the file that was valid and some steps to reproduce the issue, so I could investigate any further?

**Comment by piotr-smolira** [comment] 2024-02-29 15:03
This is the latest version that loaded geometry and collection.

1. Hidden element of GUID= 2Vn_t_c39EXwI0dCj7iWIu
2. IFCDelete all elements that were in the exact location of that hidden element as in picture.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/55686155/bf4b35be-a1f4-4037-b55b-141fbeea30ad)

3. Save, close.
4. Open. It is empty.


[File](https://github.com/IfcOpenShell/IfcOpenShell/files/14449585/ano01.zip)

**Comment by Andrej730** [comment] 2024-03-01 07:43
It seems the ifc file was invalid in the first place, so it's not element deletion issue.

In the file below I've removed all other elements except a few plates, removing any of them would lead to this issue.
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/cdac610f-4f84-4438-99ea-4ff51645f7b9)

[ano01_removed_elements.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/14457950/ano01_removed_elements.zip)

The problem with them that they are both (guids `2ZXytf$s51iBaOuJ4C9mVk` and `2ZXytf$s51iBaOuJ4C9mNT`) are using the same representation `#5159=IFCSHAPEREPRESENTATION(#19,'Body','MappedRepresentation',(#5160));` which [is not allowed in IFC](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcShapeModel.htm#8.18.3.16.4-Formal-propositions) and therefore removing one elements removes representation for both of them which leads to issues loading second element.
There are also other parts of the file that have invalid ifc which may lead to other issues.

What software this model comes from?

**Comment by Moult** [comment] 2024-09-03 04:57
Closing as this seems to be just an inherently invalid file, not sure where it originally came from. It's also using an incorrect schema.

**Closed by Moult** 2024-09-03 04:57 UTC
Labels: Bonsai
