### ISSUE TITLE
BlenderBIM: it appears 'add grid' and 'add sections' is not working

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1284] opened 2021-01-31 21:02 UTC
could be missing something, but it appears 'add grid' and 'add sections' is not working

https://www.dropbox.com/s/rku6wx81zwu5p4b/2021-01-31_15-00-40.mp4?dl=0

blender28-bim-210131-win
2.91

**Comment by Moult** [comment] 2021-01-31 23:25
Known regression as part of preparing for #1153. Will address. We can use this issue to track progress.

**Comment by Moult** [comment] 2022-09-04 03:31
These seems to be fixed with the new reference generation system, which generates grids and section references on the fly.

![2022-09-04-133008_601x623_scrot](https://user-images.githubusercontent.com/88302/188295900-64594984-b014-4930-b009-2e73819b2124.png)

**Closed by Moult** 2022-09-04 03:31 UTC
Labels: BlenderBIM

**Comment by TZwielehner** [comment] 2022-10-25 14:38
Where should the grid be created? The button seems to be missing.

**Comment by theoryshaw** [comment] 2022-10-25 15:27
good question.. not sure. 
If you use `F3`, you can search and still execute the command...
![image](https://user-images.githubusercontent.com/507113/197816156-8b4c7df7-aaa8-456c-b0fd-6b5eb55be821.png)

**Comment by TZwielehner** [comment] 2022-10-25 15:53
Learing something new every day, thanks!
