### ISSUE TITLE
Error related to instance #0.

### ISSUE THREAD

**Issue by piotr-smolira** [IfcOpenShell/IfcOpenShell#4304] opened 2024-02-08 16:42 UTC
So steps: 
1. Open IFC4 
2.  Select elements. 
3. Unlink element 
4. Join (blender feature) 
5. Assign IFC Class (IfcBuildingElementProxy) 
6. Assign Type 
7. Assign Spatial container 
8. Save 
9. Error (Instance #0 not found)

Version 240201, py3.10, windows.

**Comment by theoryshaw** [comment] 2024-02-08 17:40
I could not replicate this. 

Can you share the .ifc file, or parred-down version of it?

**Comment by theoryshaw** [comment] 2024-02-08 17:47
Also, maybe try the following after step 2. 
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/74352996-1736-40f7-8889-995e7de542fa)

And/or  the following after step 6. 
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/2ebd9866-0bdd-4e49-bd65-681aa7c2f5d8)


Also, for step 6?  Are you assigning a 'type' or the 'PredefinedType' of the instance?

**Comment by Andrej730** [comment] 2024-02-12 08:42
Couldn't reproduce it. Need some .ifc example to investigate any further.

**Comment by aothms** [comment] 2024-03-26 10:09
I will close this due to inability to reproduce. @piotr-smolira feel free to reopen if you can provide an .ifc example to investigate further.

**Closed by aothms** 2024-03-26 10:09 UTC
Labels: BlenderBIM

**Comment by piotr-smolira** [comment] 2024-03-26 14:20
Yeah @aothms, I tried to find the right IFC I was getting the error but I couldn't make it happen. Once I'll stumble upon, I'll come back.
