### ISSUE TITLE
Not able to use IfcOpenShell-python on Ubuntu 20.04

### ISSUE THREAD

**Issue by SteezoTheEngineer** [IfcOpenShell/IfcOpenShell#5280] opened 2024-09-02 09:11 UTC
Hi all

Recently, it has not been possible to import ifcopenshell. During the import, the following exception occurs:

```Traceback (most recent call last):
  File "/app/.venv/lib/python3.11/site-packages/ifcopenshell/__init__.py", line 81, in <module>
    from . import ifcopenshell_wrapper
  File "/app/.venv/lib/python3.11/site-packages/ifcopenshell/ifcopenshell_wrapper.py", line 13, in <module>
    from . import _ifcopenshell_wrapper
ImportError: /lib64/libm.so.6: version `GLIBC_2.35' not found (required by /app/.venv/lib/python3.11/site-packages/ifcopenshell/_ifcopenshell_wrapper.cpython-311-x86_64-linux-gnu.so)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/.venv/bin/say-hi", line 5, in <module>
    from bim_dq.test import cli
  File "/app/.venv/lib/python3.11/site-packages/bim_dq/test.py", line 8, in <module>
    import ifcopenshell
  File "/app/.venv/lib/python3.11/site-packages/ifcopenshell/__init__.py", line 83, in <module>
    raise ImportError("IfcOpenShell not built for '%s'" % python_distribution)
ImportError: IfcOpenShell not built for 'linux/64bit/python3.11'
```

It seems that GLIBC_2.35 cannot be installed on Ubuntu 20.4. Is there a way to use ifcopenshell with lower versions of Ubuntu? Unfortunately, we are unable to update the versions quickly.

Thank you in advance, and best regards,
Stefan

**Comment by Moult** [comment] 2024-09-02 09:13
Duplicate of #5111

**Closed by Moult** 2024-09-02 09:13 UTC
Labels: IfcOpenShell-Python
