### ISSUE TITLE
bimtester switch_locale fails

### ISSUE THREAD

**Issue by CyrilWaechter** [IfcOpenShell/IfcOpenShell#1910] opened 2021-12-01 15:14 UTC
When running bimtester from BlenderBIM Add-on I get an error message:
```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.9/gettext.py", line 592, in translation
    raise FileNotFoundError(ENOENT,
FileNotFoundError: [Errno 2] No translation file found for domain: 'messages'
```
Failure happens here:
https://github.com/IfcOpenShell/IfcOpenShell/blob/d1caa3242f58c86673c81928cbb13bdd3c0a6b51/src/ifcbimtester/bimtester/lang.py#L11-L15
Arguments passed are:
* `locale_dir = '/home/cyril/git/IfcOpenShell/src/ifcbimtester/bimtester/locale'`
* `locale_id = 'en'`

I do not really know how `gettext.translation` is supposed to work so I don't get what's wrong.

A quick workaround is to set lang as an empty string `""` instead of `"en"` here:
https://github.com/IfcOpenShell/IfcOpenShell/blob/d1caa3242f58c86673c81928cbb13bdd3c0a6b51/src/blenderbim/blenderbim/bim/module/bimtester/operator.py#L59

**Comment by berndhahnebach** [comment] 2021-12-02 23:10
you need to create the binary translation files as described in the README of BIMTester I just used the German on I have created month ago ... 

We should make it work in english if files are not provided. I will have a look.

**Comment by CyrilWaechter** [comment] 2021-12-08 11:04
Thanks. I missed bimtester specific readme. It works after compiling but the error should be handled on BlenderBIM side or on BIMTester side so I leave this issue open.

**Comment by berndhahnebach** [comment] 2021-12-08 12:50
Would you test BIMTester outside BlenderBIM? ATM for me it works without any translation file. There is just nothing translated.

IMHO BIMTester should work without any translation file too. But as stated ATM I am not able to reproduce this outside BlenderBIM.

**Comment by berndhahnebach** [comment] 2021-12-08 13:39
As stated before. If python is used, or the gui is used or FreeCAD AddOn is used the lang argument `lang : ""` is passed to BIMTester behave. Thus no problem. See https://community.osarch.org/discussion/comment/9690/#Comment_9690  As soon as a some value is passed as lang it is passed to behave. See https://github.com/IfcOpenShell/IfcOpenShell/blob/ee56e06d860a16989489e372eab69d4e381cda0b/src/ifcbimtester/bimtester/run.py#L123-L124 and thus in environment module behave tries to switch the localse here https://github.com/IfcOpenShell/IfcOpenShell/blob/ee56e06d860a16989489e372eab69d4e381cda0b/src/ifcbimtester/bimtester/features/environment.py#L18-L19

I will do some code in switch locale to catch the error if the files do not exist.

bernd

**Comment by berndhahnebach** [comment] 2021-12-08 13:46
@CyrilWaechter 
@Moult 
@aothms 

Just to be sure. IMHO we should not add the binary translation files to the repository. They should be added to the release version which could be downloaded, or they should be added it BIMTester is provided with some other tool like BlenderBIM or FreeCAD. This would meand someone who used the repository directly would need to create them himself. Am I on the right track here?

**Comment by CyrilWaechter** [comment] 2021-12-08 14:00
Yes. No binary in repo.
However a custom error should be raised to explain what is going on in bimtester and warning + fallback to `"lang": ""` in blenderbim.

**Comment by berndhahnebach** [comment] 2021-12-08 15:07
reopen the issue to disscuss ... 

ATM:
language for the error messages is passed by the behave argument.
How about to use the language from the feature file. This one: https://github.com/IfcOpenShell/IfcOpenShell/blob/b66792f9816d268cb459aa203e1ba9e08659e65f/src/ifcbimtester/examples/01_ifcschema_translated/features/de_grundlagen.feature#L1  It is possible to read this and to set the language to this language

the report has been set to use the same language which has been used in the json report see https://github.com/IfcOpenShell/IfcOpenShell/commit/b66792f9816d268cb459aa203e1ba9e08659e65f This makes most sense IMHO

**Comment by berndhahnebach** [comment] 2021-12-09 07:09
> Yes. No binary in repo. However a custom error should be raised to explain what is going on in bimtester and warning + fallback to `"lang": ""` in blenderbim. (I can prepare a PR if you like. I just need to find how to warn user in blender.)

https://github.com/IfcOpenShell/IfcOpenShell/commit/195af0c850dfa3476731c9e301afbe7f1956d218

**Comment by berndhahnebach** [comment] 2021-12-09 10:21
very good reads in this regard ... 
https://github.com/behave/behave/issues/334
https://github.com/behave/behave/issues/357

especially this post helps not to mix stuff ... https://github.com/behave/behave/issues/357#issuecomment-137397708

**Comment by berndhahnebach** [comment] 2021-12-09 10:44
Translation is split in to to parts ...

1. Parsing of the .feature files - behave parses .feature files in english by default (so the Given, When, Then steps have to be written in English). There is a way of changing that default language to your chosen one so that you can write the steps in that language (for Spanish: `Given` becomes `Dado`, `When` becomes `Cuando` and `Then` becomes `Entonces`). This is set in the first line of the feature file


2. The language of the output messages which will be printed during BIMTester run. Mainly the ones if a step fails. The ones in the code which looks like _("the print messags"). This is set with the behaves lang argument.


I will implement the following behaviour: 
If "" is parsed as bimtester (and behave) `lang` argument the output messages language will be taken from feature files language. Means if 2. is not given for 2. the language of 1. will be taken.

cheers bernd

**Comment by berndhahnebach** [comment] 2021-12-09 11:09
@Moult IMHO it is best to parse "" as lang argument to BIMTester.

It is what I will do in FreeCAD AddOn and at my company. See my last post feature file, messages, json report, html report will use this language than. If mo files are missing just no message and some of the html report will not be translated. But BIMTester runs. 

IMHO is fixed now. I leave it open to get a response from Dion on this post. 

cheers bernd

**Comment by Moult** [comment] 2022-01-04 02:29
Sorry I didn't have time to look at this, but happy to close. BIMTester is set to be back on my dev radar in the coming months I believe as IDS becomes more of a real thing.

**Closed by Moult** 2022-01-04 02:29 UTC
Labels: BlenderBIM, BIMTester
