### ISSUE TITLE
BlenderBIM. Import more than one IFC

### ISSUE THREAD

**Issue by GOBA-esp** [IfcOpenShell/IfcOpenShell#852] opened 2020-05-14 13:34 UTC
I am not sure if it’s prepared to import more than one IFC, but, it seems to me that something's happening when the second IFC its imported.

I try to explain myself. This is an IFC, imported into Blender:

![Blender1](https://user-images.githubusercontent.com/65341572/81940491-ee8e8600-95f7-11ea-84ed-ab3d0d310c67.PNG)

And this is the same IFC imported after another one (not visible in the image):
![Blender2](https://user-images.githubusercontent.com/65341572/81940659-1ed62480-95f8-11ea-86c9-352f8e125210.PNG)

Some elements are not well positioned.

**Comment by Moult** [comment] 2020-05-14 21:52
That is interesting ... I generally keep separate IFCs into separate Blender files, but when I have had the need to import two IFCs into one Blender file I have not seen issues and there is in theory no problem with doing so.

There are known issues with importing the _same_ IFC twice into the same Blender file, which I have on my to-do list, but I didn't expect it to cause elements to move elsewhere. I tried to reproduce with the two files you gave me but it works fine with them (I see a duplicate of elements one on top of another). Can you send me that test file so that I can recreate your issue and fix it?

**Comment by GOBA-esp** [comment] 2020-05-15 06:12
I've sent you an email. Thanks!

**Comment by Moult** [comment] 2020-05-15 06:40
Thanks for your email! I see the bug now. It is related to the new feature introduced [last week](https://github.com/IfcOpenShell/IfcOpenShell/commit/b857d9a37b98ffd1c1cfb9611de7d8beee200ed3).

This is now fixed: https://github.com/IfcOpenShell/IfcOpenShell/commit/e3c36a28f26cef3d7432f0dd6ed1b92038d01d49

Replace your `import_ifc.py` with https://raw.githubusercontent.com/IfcOpenShell/IfcOpenShell/v0.6.0/src/ifcblenderexport/blenderbim/bim/import_ifc.py

**Comment by GOBA-esp** [comment] 2020-05-15 11:18
It works! Thank you very much!

I just have tried to export it (the IFC combined), and I have now this error:

Traceback (most recent call last):
  File "C:\Users\helen\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blenderbim\bim\operator.py", line 67, in execute
    ifc_exporter.export(context.selected_objects)
  File "C:\Users\helen\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blenderbim\bim\export_ifc.py", line 1127, in export
    self.ifc_parser.parse(selected_objects)
  File "C:\Users\helen\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blenderbim\bim\export_ifc.py", line 161, in parse
    self.get_products()
  File "C:\Users\helen\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blenderbim\bim\export_ifc.py", line 217, in get_products
    self.add_product(self.get_product(product))
  File "C:\Users\helen\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blenderbim\bim\export_ifc.py", line 417, in get_product
    self.get_product_relating_structure(product, obj)
  File "C:\Users\helen\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blenderbim\bim\export_ifc.py", line 518, in get_product_relating_structure
    self.parse_product_collection(product, collection)
  File "C:\Users\helen\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blenderbim\bim\export_ifc.py", line 525, in parse_product_collection
    reference = self.get_spatial_structure_element_reference(collection.name)
  File "C:\Users\helen\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blenderbim\bim\export_ifc.py", line 1065, in get_spatial_structure_element_reference
    for e in self.spatial_structure_elements].index(name)
ValueError: 'IfcBuildingStorey/Techo 4ª.001' is not in list

location: <unknown location>:-1

**Comment by Moult** [comment] 2020-05-15 12:03
@GOBA-esp when you import two IFCs into one file, it creates two IfcProjects. During export-time, if you select both projects, it will get confused because IFC only allows a single IFC project per file. That is why it fails.

The only correct way to export two IFC models is to combine them into a single project before exporting. However, I understand why you expect it to work, and how it is unintuitive for a user if it gives an error.

I will investigate this in more detail tomorrow and try to think of a good solution.

**Comment by GOBA-esp** [comment] 2020-05-15 12:19
Ok, thank you. I know this can seem strange :)

It's incredible what you hav accomplished. Nice weekend!

**Comment by Moult** [comment] 2020-05-16 05:14
@GOBA-esp this is now fixed (https://github.com/IfcOpenShell/IfcOpenShell/commit/588549ca91f2decd19d236807da91884c0237d2f). By default, now, if you select elements from two IfcProjects, they will get merged into a single IfcProject on export (buildingSMART only allows one IfcProject per file).

To apply the fix, please replace `export_ifc.py` with the latest: https://raw.githubusercontent.com/IfcOpenShell/IfcOpenShell/v0.6.0/src/ifcblenderexport/blenderbim/bim/export_ifc.py

So after I export both your projects, if I then try importing the result again, you can see a duplication of IfcSite, IfcBuilding, and so on. I do not want the software to make any more assumptions on merging this data... so, I believe this is a good compromise on user expectations and what is allowed in IFC... :)

![image](https://user-images.githubusercontent.com/88302/82111296-b1f19480-9787-11ea-9234-d2df19dbc1f5.png)

**Comment by GOBA-esp** [comment] 2020-05-16 09:07
Hi, I understand what you explain, thank you.

I just want to say one thing I’ve seen, when I import 1 IFC into Blender, and then I export it into IFC.

This is the original IFC (image from BIMCollab):

![Blender_Exportar 1](https://user-images.githubusercontent.com/65341572/82115712-d7b97200-9764-11ea-828b-d69e53ed6d0c.PNG)

This is the IFC generated from Blender:

![Blender_Exportar 2](https://user-images.githubusercontent.com/65341572/82115719-de47e980-9764-11ea-91f5-8a525d482ec1.PNG)

It seems to me that something is happening with the location: top elevation and height. Is this normal?

If I repeat the process importing 2 IFC, and merging them, I see this:

![Blender_Exportar 3](https://user-images.githubusercontent.com/65341572/82115741-e6078e00-9764-11ea-8b81-6fe7288b1feb.PNG)

Ok, I can see the duplication of the IfcSite (Entorno). If I make non visible the IfcSite (Entorno) at the bottom, I see this:

![Blender_Exportar 4](https://user-images.githubusercontent.com/65341572/82115762-0df6f180-9765-11ea-90e7-44a18ead63a3.PNG)

But, what has been storage in each IfcSite? It is not each original IfcProjects. I am not sure if I am explaining myself, I don’t really know much about IFC structure, and maybe this is what we can expect from merging…

**Comment by GOBA-esp** [comment] 2020-05-16 09:48
Maybe I should have created another issue, sorry.

**Comment by Moult** [comment] 2020-05-16 09:52
The BlenderBIM Add-on does not currently import IfcBuildingStorey locations. This is, well, wrong behaviour and need to be fixed. Therefore, when exporting, the relative location of the building storey is lost, and it is measured from the origin. I can fix this and it _should_ be fixed but previously was not a high priority, and will let you know when I have done so.

The "Top elevation", "Bottom elevation" and "Height" of the building storey are not true IFC properties - they do not exist in the IFC specification, so BIMCollab is taking some creative license here. There is only an `Elevation` property, which the BlenderBIM Add-on _does_ import, and should retain. But maybe it doesn't correlate to the BIMCollab properties, so who knows what it is actually mapped to.

I see what you mean that the IfcSite's don't correspond correctly. I will investigate.

**Comment by Moult** [comment] 2020-05-16 10:05
The incorrect IfcSite categorisation has been fixed: https://github.com/IfcOpenShell/IfcOpenShell/commit/3235d2495ae285de069bba117b50d65f643c9553

Replace `export_ifc.py` with https://raw.githubusercontent.com/IfcOpenShell/IfcOpenShell/v0.6.0/src/ifcblenderexport/blenderbim/bim/export_ifc.py

The lack of importing `IfcBuildingStorey` locations is still pending.

**Comment by Moult** [comment] 2020-05-16 11:37
Fixed: https://github.com/IfcOpenShell/IfcOpenShell/commit/e44eaf0ccd5082a98778d7759abedccd9093b4ed

Now, the BlenderBIM Add-on will import the placements of IfcBuildingStorey and any spatial element, and during export, it will export positions relative to their spatial container (instead of absolute placements, like currently).

Replace `import_ifc.py` with https://raw.githubusercontent.com/IfcOpenShell/IfcOpenShell/v0.6.0/src/ifcblenderexport/blenderbim/bim/import_ifc.py

... and also replace `export_ifc.py` with https://raw.githubusercontent.com/IfcOpenShell/IfcOpenShell/v0.6.0/src/ifcblenderexport/blenderbim/bim/export_ifc.py

By the way, relative placements can get quite complex in IFC. The implementation I wrote should be pretty straightforward, but keep an eye out for bugs, especially with mapped geometry and scaled transformations which can get pretty messy. Hopefully it works a bit better for you now.

**Comment by GOBA-esp** [comment] 2020-05-16 16:04
Hi, it seems it works:

![Blender3](https://user-images.githubusercontent.com/65341572/82124446-634ff480-979f-11ea-9e15-1d62ef423c68.PNG)

Only for one element it seems strange:

![Blender4](https://user-images.githubusercontent.com/65341572/82124449-677c1200-979f-11ea-852a-e67e2af75dfd.PNG)

But maybe this is what you are explaining about complexity. It works fine for me, I just tell you because I suppose it’s good to know 😊

**Comment by Moult** [comment] 2020-05-16 22:31
Interesting ... on my screen, I do not see that one element. This one _could_ be a bug with BIMCollab instead.

Keep an eye out and let me know if any other quirks show up.

![image](https://user-images.githubusercontent.com/88302/82131435-794dcb80-9818-11ea-989a-99297d3f8c3a.png)

**Closed** 2020-05-16 22:31 UTC
