### ISSUE TITLE
BlenderBIM: exterior walls missing. IFC import

### ISSUE THREAD

**Issue by brunoperdigao** [IfcOpenShell/IfcOpenShell#1287] opened 2021-02-01 21:44 UTC
I tested the new release (210131) with and IFC sample file from the OSArch wiki. The model was imported with some exterior walls missing, but it shows no error message. I am not sure if this is a bug, but I imported the same file into Archicad and it worked.
Here is the import configuration: 
![image](https://user-images.githubusercontent.com/57102715/106521196-a3d1d880-64bc-11eb-993a-bf8cab19ebc2.png)

Here the result:
![image](https://user-images.githubusercontent.com/57102715/106521282-c3690100-64bc-11eb-80fa-b4d5bb20b16e.png)

Here is the IFC file:
https://ln.sync.com/dl/7374d1210/jeb3ychd-f36exf6i-d8d997xi-nmgabuwv/view/default/4253114480009

Windows 10
Blender 2.91.1
BlenderBIM v210131

**Comment by Moult** [comment] 2021-02-02 09:58
The wall is there, but turns invisible due to the failed Blender boolean. The boolean fails because the opening element consists of two breps, which kinda merge to create a non-manifold shape. Ping @aothms is this legal?

If it is legal, I'm not really sure what a good fix would be... I could go back to fast booleans...

**Comment by Moult** [comment] 2021-02-02 10:11
@brunoperdigao can you please file an upstream bug to Howard Trickey and ask him whether or not this is a bug or expected behaviour? I suspect it could be an upstream Blender bug.

**Comment by aothms** [comment] 2021-02-02 10:16
> which kinda merge to create a non-manifold shape. Ping @aothms is this legal?

How precisely? We have a similar issue here https://github.com/IfcOpenShell/IfcOpenShell/issues/992 not because it's a problem in OCCT, but because of the checks in IfOpSh assume manifold output.


In general though, I don't have a lot of confidence in these mesh-based booleans. I think you should add some sort of sanity check on the output and revert to OCCT automatically for elements that don't look correct (e.g volume less than First Op minus Second Op, or whatever)

**Comment by brunoperdigao** [comment] 2021-02-02 12:47
@Moult Ok, I just want to try to understand the problem a bit better. The problem is that the opening element has an internal face, it works after I deleted these faces. But this is expected to cause a problem with the boolean operation, right? The Blender bug would be the fact that the wall turns invisible. Did I get it right?

**Comment by Moult** [comment] 2021-02-02 21:51
@aothms the opening element itself is non-manifold. I've screenshotted what the opening elements look like as well as highlighted in orange the two internal shared faces. The actual opening element representation is made out of two faceted breps, which I assume IfcOpenShell welds vertices as a final step which causes the non-manifold representation, which then blender fails to handle.

![2021-02-03-084749_701x619_scrot](https://user-images.githubusercontent.com/88302/106667087-928fe580-65fc-11eb-959c-e69c8eb7b1ef.png)


@brunoperdigao correct. Though Howard is well within his rights to say "naaaah it's not a bug non-manifold mesh boolean is illegal", in which case maybe I should fall back and follow @aothms 's suggestion to default to IfcOpenShell, and then allow the user to convert on a case by case basis (say, if the user wishes to edit the mesh representation of an object which has openings).

... which I think I might do anyway. IfcOpenShell is battle tested with booleans... Blender has a reputation for being hit and miss.

**Comment by aothms** [comment] 2021-02-02 22:18
But that's something we can indeed probably fix, assuming that the two parts of the opening are different representation items I can reset the "welding map" probably when iterating over the items. Is that something we should try?

**Comment by Moult** [comment] 2021-02-02 22:38
@aothms I guess, though I just checked in Blender to manually split them into 2 manifold boxes, but the Blender booleans still doesn't handle it well, so I guess from the user perspective it still looks broken.

I would not call it a high priority item. I think I'll implement the OCCT subtractions by default, and give the user the option to on-demand switch to a non-subtracted mesh. That way the user gets a better first experience, and can optionally switch to editing things in Blender's environment when they wish.

**Closed** 2021-02-03 02:49 UTC
Labels: BlenderBIM

**Comment by aothms** [comment] 2021-02-03 13:50
@Moult well I've just implemented something like that. I think there are still ways you can get this to work, like applying the opening parts in multiple modifiers (Blender has a Separate by loose parts I think, so that's relatively quick). Or doing a union on the opening parts first. I wouldn't abandon the Blender booleans that quickly.

**Comment by Moult** [comment] 2021-02-03 20:57
@aothms hmm, I'll try to think of a way to implement it. Right one one Blender object = one IFC product, so splitting it may complicate things. Unioning may work, though...

**Comment by Moult** [comment] 2021-02-03 20:57
Ahh just noticed the fix commit! Awesome, that'll be super useful when trying to build a better Blender-based system. Thanks so much!
