### ISSUE TITLE
How to rotate a specific object of IFC model?

### ISSUE THREAD

**Issue by JosephLZD** [IfcOpenShell/IfcOpenShell#1516] opened 2021-06-09 14:41 UTC
Hi! I'm currently working on translating and rotating a specific object of IFC model with IfcOpenShell.

Translating a specific object is simple, we just need to edit its Location:
_def edit_part_location(ifc_file, ifc_guid, new_x, new_y, new_z): 
    part = ifc_file.by_guid(ifc_guid)
    new_location = new_x, new_y, new_z
    new_point = ifc_file.createIfcCartesianPoint(new_location)
    part.ObjectPlacement.RelativePlacement.Location = new_point
    return ifc_file_

However, I'm stuck at rotation operation. I've tried to rotate the geometry shape which is converted into PythonOCC, then add it as a new geometry for replacement in IFC file. But this doesn't work and it costs much time (at creating shape). 

Is there any straightforward ways for me to rotate its geometry **by editing IFC file by IfcOpenShell**, just as simple as what I've done for translation? (Assuming I know the angle of rotation around the x, y, and z axes, respectively)

Any help would be much appreciated! Thank you in advance!

**Comment by Moult** [comment] 2021-06-09 22:40
@JosephLZD changing the matrix of an object is a tricky object (whether it be location or rotation) because it depends on all of the inherited placements. Similarly, if you change it, you need to ensure that all downstream inherited placements are also updated. There is no need to create_shape at all.

The good news is that the IfcOpenShell API takes care of all of this automagically. First, let's get the existing matrix of your object.

```
part = ifc_file.by_guid(ifc_guid)
old_matrix = ifcopenshell.util.placement.get_local_placement(part.ObjectPlacement)
```

Now you have a matrix, you can apply your rotation to it. The method depends on whether you know new axes, euler angles, quaternion, and so on, as well as whether you're using numpy (in this example) or some other library (e.g. mathutils module offers a lot of convenience functions)

When you have a new matrix with the rotation applied, simply:

```
new_matrix = np.eye(4) # Specify a numpy matrix with the newly desired location / rotation
ifcopenshell.api.run("geometry.edit_object_placement", ifc_file, product=part, matrix=new_matrix)
```

**Comment by Moult** [comment] 2021-06-12 11:15
Closing as not a bug :) By the way, feel free to reach out at community.osarch.org for future questions and discussions like this :)

**Closed by Moult** 2021-06-12 11:15 UTC

**Comment by JosephLZD** [comment] 2021-06-14 04:08
@Moult  Thanks for replying! 
But I don't know how to install IfcOpenShell/src/ifcopenshell-python/ifcopenshell/ in conda environment. I now have IfcOpenShell installed by "conda install -c conda-forge -c oce -c dlr-sc -c ifcopenshell ifcopenshell", but get error when importing ifcopenshell-python: 
_raise ImportError("IfcOpenShell not built for '%s'" % python_distribution)
ImportError: IfcOpenShell not built for 'darwin/64bit/python3.7'_

**Comment by aothms** [comment] 2021-06-14 09:30
I would not add so many channels. Probably -c conda-forge is best. The most up to date builds are provided on the website though that you can just extract in your python site-packages directory. http://ifcopenshell.org/python

**Comment by Herzdame** [comment] 2021-07-07 14:06
Hey :-) 
I tried to change the location of a Wall, but the windows stayed at their old location. How can I be sure that they will be also moved with their parent wall?

**Comment by Moult** [comment] 2021-07-07 22:18
@Herzdame can you please post questions like this on https://community.osarch.org/ ? This is not the right location for questions unfortunately, only bug reports.
