### ISSUE TITLE
IfcConvert not showing pipe elbows for IFC4 format

### ISSUE THREAD

**Issue by alikucukavci** [IfcOpenShell/IfcOpenShell#1277] opened 2021-01-26 15:51 UTC
Hello there, 

When converting from Ifc4 to COLLADA, pipe elbows are missing. Please see picture 1
When converting from ifc2x3 to COLLADA, pipe elbows are NOT missing. Please see picture 2. 

Can anyone explain why it happens and how it can be fixed?

### Picture of ifc4
![IFC4](https://user-images.githubusercontent.com/22770558/105868419-738ac580-5ff6-11eb-83dc-71f1e7da779e.PNG)

### Picture of ifc2x3
![IFC2x3](https://user-images.githubusercontent.com/22770558/105868412-71c10200-5ff6-11eb-9374-bdccbd1591cd.PNG)

**Comment by aothms** [comment] 2021-01-28 09:10
This is probably a duplicate of
https://github.com/IfcOpenShell/IfcOpenShell/issues/1269 Can you try again
with the latest version of v0.6?

Sent from a mobile device. Excuse my brevity. Kind regards, Thomas

Op di 26 jan. 2021 16:51 schreef alikucukavci <notifications@github.com>:

**Comment by CyrilWaechter** [comment] 2023-01-08 05:39
@alikucukavci I just tested it on a large file and I see no issue so I think everything is now fixed. Feel free to reopen if you can provide a failing case.

**Closed by CyrilWaechter** 2023-01-08 05:39 UTC
