### ISSUE TITLE
False origin loading project not working

### ISSUE THREAD

**Issue by smarnav2904** [IfcOpenShell/IfcOpenShell#5721] opened 2024-11-08 09:30 UTC
Hi, first of all sorry if this is a redundant question but architecture/modelling are not my main framework. I'm trying to change the origin of a project so every coordinate of elements are positive (negative coordinates are not much desired in computing), however, opening the project in advanced and setting it to a point where all coordinates should be positive does not fix the problem. I attach an image that represents what i want to accomplish. Thanks in advance. 
![Screenshot from 2024-11-08 10-20-39](https://github.com/user-attachments/assets/edf104fc-a399-4ce1-b43a-0fe745fedd65)

**Comment by Andrej730** [comment] 2024-11-08 12:08
@smarnav2904 
Could reproduce this.

Import without false origin:
![image](https://github.com/user-attachments/assets/b38cc911-18e6-4432-bd1f-2c28a93c46b3)

False origin `-5000, -5000, 0`:
![image](https://github.com/user-attachments/assets/63970154-2a65-4d1c-8f54-c32f8c6dfbba)

Are you sure you're using the correct units? False origin suppose to be in project units

it's hard to tell without the example file. Please share the .ifc example and steps to what coordinates are you using for the false origin. Perhaps isolate issue in a simpler project.

**Comment by smarnav2904** [comment] 2024-11-08 12:32
Project units are meters, so setting like 1000,1000,0 should be notable, which it is not my case. Model attached.
[model.zip](https://github.com/user-attachments/files/17678627/model.zip)

**Comment by Andrej730** [comment] 2024-11-12 14:20
@smarnav2904 still couldn't reproduce this.

E.g. element 39_kVZd6bAnPzKQvhf51al loaded without false origin:
![image](https://github.com/user-attachments/assets/16aac6c7-1327-44a7-a44f-1bc4381e3e6c)

With false origin 207,-17,0
![image](https://github.com/user-attachments/assets/e4e227fb-8774-4c70-ae67-db65ce296c5e)

Origin 1000,1000,0
![image](https://github.com/user-attachments/assets/0ac60c17-29ab-4f79-a459-c877b950f92d)

Do you get different results with those false origins? Are you sure you're using the latest version of Bonsai?

**Comment by Andrej730** [comment] 2024-12-06 10:49
@smarnav2904 Hi! Is this still an issue?

**Comment by Andrej730** [comment] 2024-12-23 06:56
Closing this. Please, reopen if there will be any new information.

**Closed as completed by Andrej730** 2024-12-23 06:56 UTC
Labels: Bonsai
