### ISSUE TITLE
Triangulation removed

### ISSUE THREAD

**Issue by ninichki** [IfcOpenShell/IfcOpenShell#2133] opened 2022-04-08 15:04 UTC
https://github.com/IfcOpenShell/IfcOpenShell/blob/564c4b7644e79d8bc6d96a8a3fe8794a3dfde875/src/ifcgeom/IfcGeom.h#L229

This line removes all the same faces.
It would be better if the first of the faces would be added.
If it would be compared by adress it should work. But vectors seems to be compared in whole.

Maybe somebody knows, how to fix it.

I have a Representation in which all faces a repeated once. So nothing is to see anymore.

**Comment by aothms** [comment] 2022-04-09 07:10
Could you provide a test file? The way I read the code, duplicates_ will not get populated for the "first occurence of a duplicate", only when edge_sets already contains a prior duplicate of a set of vertex pairs, will the subsequent duplicates be flagged. So I'd have to better understand this.

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcgeom/IfcGeomFunctions.cpp#L5614-L5618

**Comment by ninichki** [comment] 2022-04-11 06:39
In this  file are the pipes not visible. I know that it makes no sense to make the indexes double but it should'nt make them unvisible.
[kanal.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/8461600/kanal.zip)
.

**Comment by aothms** [comment] 2022-04-11 12:12
Great, thanks, I think I see the issue now indeed.

When we're dealing with the tesselated data (a) , the definition is of the helper class is:

`faceset_helper<std::vector<double>, std::vector<int>>`

So loops are `std::vector<int>`. These are compared by value, so duplicate int vectors affect both the first and successive occurences.

In case of connected faceset (b) , the helper is typed as

`faceset_helper<const IfcSchema::IfcCartesianPoint*, const IfcSchema::IfcPolyLoop*>`

So loops are compared by pointer address and registered duplicates only affect the successive occurrences. 

That's where my confusion came from and your initial observation is indeed correct.

---

The good news is that also in case (a) we're dealing with stable data so we can just take the address of the vector and compare that. It's ugly and requires some work because of the template usage, but it seems like the quickest way out to get consistent behaviour in these two cases. See 460fd5ca87bac666ab0b14d3133e9444899a15ec

**Comment by ninichki** [comment] 2022-04-12 10:41
Thanks, it works create

**Closed** 2022-04-12 11:03 UTC
