### ISSUE TITLE
IDS update?

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#4466] opened 2024-03-25 16:40 UTC
Hi,

There are some changes in IDS ([official source](https://www.buildingsmart.org/the-information-delivery-specification-ids-final-standard-is-now-out-for-review-by-the-standards-committee/)).

Are these changes already implemented in IfcTester?

> 4. Schema clarifications
During the validation phase feedback from users and implementers was gathered. This resulted in
fine-tuning of the schema, extended documentation and improved clarifications of the test-cases.
Multiple publicly available meetings have been hosted during the second half of 2023 and the first
two months of 2024.
The following schema clarifications have been made to the XSD schema for IDS since the candidate
standard. All these clarifications have been approved by the SCTE.
 Classification system is now required
Specifying *any* classification is against the spirit of the schema, it is too generic to be useful in
the context of a CDE. It’s still possible to be broad by using a catch-all pattern.
 Specification cardinality is moved
The ‘attributeGroup’ reference to ‘xsd:occurs’ has been moved from ‘specificationType’ to
‘applicabilityType’.
This better reflects the purpose and scope of the minimum and maximum values, as they apply
to the facets included in the ‘applicabilityType’. Its previous position was confusing.
 Property ‘dataType’ attribute has been made optional
A previous implementation agreement expected the ‘dataType’ to be left blank (i.e. “”) when
irrelevant (e.g. for Prohibited properties) or specify any valid IFC class name in uppercase.
Making the ‘dataType’ optional achieves the same objectives improving the clarity of the schema
and making the uppercase constraint explicit in XSD via a custom type.
 Cardinality of requirement facet
The existing implementation agreements on the use of cardinality for requirement facets has
been consolidated in the schema via explicit enumerations.
Since the previous expression of cardinality through ‘minOccurs’ and ‘maxOccurs’ could produce
invalid configurations, explicit enumeration types have been introduced to ensure compliance
with the implementation agreements.
 Formalised relations
The list of relations available for the ‘partOf’ facet has been clarified to clarify that Void/Fill
relationships should be considered together as per implementation agreements.
 Property ‘name’ change to ‘baseName’
A change to help educate the users and implementers that the property ‘name’ should be the
computer interpretable coding of the property, and not the human readable name. Options like
‘code’ were suggested, but ‘baseName’ was chosen to stay close to the future IFC developments.
All these clarifications have been approved and agreed by the SCTE by online voting.
These clarifications improve the reliability of software implementations and do not limit the usability
of the IDS compared to the candidate standard.

**Comment by Andrej730** [comment] 2024-03-26 05:41
It seems they are "out for review" until 30 May 2024, so they might not be final.

**Comment by Moult** [comment] 2024-03-28 09:13
Closing as duplicate of #4465.

**Closed by Moult** 2024-03-28 09:13 UTC
Labels: IfcTester
