### ISSUE TITLE
blenderbim addon not work

### ISSUE THREAD

**Issue by Mannshoch** [IfcOpenShell/IfcOpenShell#3216] opened 2023-05-30 09:33 UTC
After `apt install blender ` I started blender and tried to install one of the blenderbim-230530-py... files. 
(I tested all of them, because I do not know how to decide which to use)

Installation seems working on all three, but I get this error If I try to activate:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/7795891/60ec0994-8c9c-4f19-9686-24b42e89fb3f)

I'm not so good with decrypting error message.
Please enhance the error message to something useful, add some installation instruction or simply tell me what to do now.

**Comment by brunopostle** [comment] 2023-05-30 09:59
The blender download from blender.org contains numpy, but it looks like your distro blender doesn't.

Try `apt install python-numpy`

**Comment by brunopostle** [comment] 2023-05-30 10:24
The blenderbim installer is tested with the blender installer that you can download from blender.org.

Running on a distro provided blender is fine (I do this on fedora), but blenderbim can't predict all the possible things that may be missing.

In this case the problem is that blenderbim provides a modern shapely library, but your system already has an older shapely. The solution is to remove the system shapely. ie `apt remove python3-shapely`

**Comment by Mannshoch** [comment] 2023-05-30 11:30
I understand, that It has not to solve all Problems, but It would help If the Error Message collect all missing lib in one Message.

Kind of: 
```
We miss following Lib on your system:
Lib:        minimal version:
numpy       >xxxx
shapely     >xxxx
...
```

**Comment by Moult** [comment] 2023-05-30 11:45
@Mannshoch can you check whether scripts/addons/blenderbim/libs/site/packages/shapely.libs exists? Note that it is `shapely.libs` with an `s` at the end.

Your error message seems to ask for `shapely.lib` which confuses me because it doesn't have the `s`.

**Comment by Andrej730** [comment] 2023-05-30 15:08
is it that blender installed with `apt install blender` is using system python and or it's own python instance but it's just missing some libraries?

**Comment by brunopostle** [comment] 2023-05-30 17:58
The apt-installed blender is using system python and system libraries, one library was missing and another was too old

**Comment by Moult** [comment] 2023-05-30 23:37
That explains numpy, but shapely still seems suspicious: if @Mannshoch actually installed the latest BlenderBIM Add-on, why is the shapely version too old? The error message has definitely found the shapely version in the BlenderBIM Add-on folder, not a system shapely library. Also, our packages path takes precedence over system paths.

Maybe he didn't actually install the latest or didn't cleanly uninstall an older version (i.e. he has to disable, **restart**, then remove).

@Mannshoch BTW instructions on which download to choose are here: https://blenderbim.org/docs/devs/installation.html#unstable-installation

**Comment by Mannshoch** [comment] 2023-06-01 07:36
For the Record: On this PC I never before installed Blender. 

- Ubuntu 23.04
  `python3 -V` -> Python 3.11.2
- `apt show blender`
  **Package:** blender
  **Version:** 3.4.1+dfsg-2build3
  **Depends:**
 blender-data (= 3.4.1+dfsg-2build3)
 fonts-dejavu
 libavcodec59 (>= 7:5.0)
 libavdevice59 (>= 7:5.0)
 libavformat59 (>= 7:5.0)
 libavutil57 (>= 7:5.0)
 libboost-locale1.74.0 (>= 1.74.0)
 libc6 (>= 2.35)
 libembree3-3 (>= 3.13.5+dfsg)
 libepoxy0 (>= 1.3)
 libfftw3-double3 (>= 3.3.10)
 libfreetype6 (>= 2.9.1)
 libgcc-s1 (>= 4.0)
 libgmp10 (>= 2:6.2.1+dfsg1)
 libgomp1 (>= 6)
 libimath-3-1-29 (>= 3.1.6)
 libjack-jackd2-0 (>= 1.9.10+20150825) | libjack-0.125
 libjemalloc2 (>= 5.3.0)
 libjpeg8 (>= 8c)
 libopenal1 (>= 1.14)
 libopencolorio2.1 (>= 2.1.2+dfsg1)
 libopenexr-3-1-30 (>= 3.1.5)
 libopenimageio2.4 (>= 2.4.7.1+dfsg)
 libopenjp2-7 (>= 2.0.0)
 libopenvdb10.0 (>= 10.0.1)
 libosdcpu3.5.0 (>= 3.5.0)
 libosdgpu3.5.0 (>= 3.5.0)
 libpcre3
 libpng16-16 (>= 1.6.2-1)
 libpotrace0
 libpugixml1v5 (>= 1.6)
 libpulse0 (>= 0.99.1)
 libpython3.11 (>= 3.11.0)
 libsdl2-2.0-0 (>= 2.0.12)
 libsndfile1 (>= 1.0.20)
 libspnav0 (>= 1.0)
 libstdc++6 (>= 12)
 libswscale6 (>= 7:5.0)
 libtbb12 (>= 2021.4.0)
 libtiff6 (>= 4.0.3)
 libwebp7 (>= 1.2.4)
 libx11-6
 libxfixes3 (>= 1:4.0.1)
 libxi6 (>= 2:1.1.2)
 libxml2 (>= 2.7.4)
 libxxf86vm1
 libzstd1 (>= 1.5.2)
 zlib1g (>= 1:1.2.3.4)

**Comment by Moult** [comment] 2023-06-01 07:43
@Mannshoch would you be available for a screenshare if things still don't work?

**Comment by Moult** [comment] 2023-06-05 05:14
Ping @Mannshoch

**Comment by Mannshoch** [comment] 2023-06-05 13:17
Sorry I took some time to test the cases.
BlenderBIM Works on Ubuntu SNAP

But not if I install Blender with APT eg here on a VM.

1. Downlad Ubuntu 23.04 ISO
2. Installed Virtualbox
3. Installed Ubuntu on Virtualbox
4. Installed Blender 
5. Installed addon
6. Tick to activate the Addon
7. Posted error appear.

If you wish we could do a screenshare on this Virtualbox VM.

**Comment by Moult** [comment] 2023-06-07 10:49
@Mannshoch let's do a screenshare, if the error is the numpy error, that's expected. If it's the shapely one, I'd like to investigate further. Let me know a time/day that works for you during the Sydney / Australia timezone and we can meet at https://meet.jit.si/openbim

**Comment by Moult** [comment] 2023-07-04 00:31
@Mannshoch ping, are you available to screenshare and debug this on a VM?

**Comment by Mannshoch** [comment] 2023-07-04 07:28
It seems you didn't got my email:
--------
> Sydney, that's the most worse possible timezone difference 😅
> 
> Ar you sure you do not want to recreate the problem with a VM yourself? According to https://github.com/IfcOpenShell/IfcOpenShell/issues/3216#issuecomment-1576786992

**Comment by Moult** [comment] 2023-07-04 08:07
Ah, I read it but it got lost in the inbox. I'm available during 9am to 5pm Sydney timezone. Does any of that time range work for you? I'm pretty sure I'd prefer to see your setup instead of getting a VM running here.

**Comment by Andrej730** [comment] 2023-07-06 12:28
Someone on OS Arch got the similar issue on Mac - https://community.osarch.org/discussion/1555/blenderbim-addon-in-upbge

**Comment by Moult** [comment] 2023-07-26 07:36
See https://community.osarch.org/discussion/1583/blenderbim-no-module-named-shapely-lib-error-while-installing-addon#latest

Can you confirm the Blender Python version?

**Comment by Moult** [comment] 2023-07-26 23:02
Closing seems OP seems to have disappeared but it's highly likely to be the same issue reported in two other locations.

**Closed by Moult** 2023-07-26 23:02 UTC
Labels: BlenderBIM

**Comment by cutec-chris** [comment] 2023-08-30 05:55
Ive run into the same issue on manjaro, 
installed python-shapely but it has no affect to blender
does blender uses some sort of venv ?
how should that work ?

**Comment by Moult** [comment] 2023-08-31 08:18
@cutec-chris are you using the version from blender.org or from your distro's repos?
