### ISSUE TITLE
Blender BIM - Adding Door to wall Error

### ISSUE THREAD

**Issue by ChubbyQuark** [IfcOpenShell/IfcOpenShell#3371] opened 2023-07-03 07:53 UTC
Blender 3.5
Blender BIM - 230701
Mac m1

Adding a door to a new wall in an existing project produces the following error:

```python
Python: Traceback (most recent call last):
  File "/Users/user/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/bim/module/model/product.py", line 67, in invoke
    return self.execute(context)
  File "/Users/user/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/bim/module/model/product.py", line 70, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "/Users/user/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/bim/ifc.py", line 414, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "/Users/user/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/bim/module/model/product.py", line 157, in _execute
    parent_obj = tool.Ifc.get_object(parent)
  File "/Users/user/Library/Application Support/Blender/3.5/scripts/addons/blenderbim/tool/ifc.py", line 89, in get_object
    return IfcStore.get_element(element.id())
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by Andrej730** [comment] 2023-07-03 08:48
related to #3370 ?

**Comment by Moult** [comment] 2023-07-03 08:58
Agreed there is something more fundamental at play here. I'm also available for a screenshare tomorrow during the sydney timezone if you want.

**Comment by ChubbyQuark** [comment] 2023-07-03 09:14
Rolled back to 230418 and adding doors to walls is working again. I'm around today if you need a screenshare?

**Comment by Moult** [comment] 2023-07-04 00:30
@ChubbyQuark I'm around in the OSArch chat, just ping me when you're online :)

**Comment by Moult** [comment] 2023-07-06 07:19
Bump @ChubbyQuark

**Comment by Moult** [comment] 2023-07-07 08:03
Duplicate of #3349

**Closed by Moult** 2023-07-07 08:03 UTC
Labels: BlenderBIM
