### ISSUE TITLE
Tried to add a new IfcBeam

### ISSUE THREAD

**Issue by Ave-5D** [IfcOpenShell/IfcOpenShell#4978] opened 2024-07-04 11:46 UTC
```
os: Windows
os_version: 10.0.19045
python_version: 3.10.13
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
blender_version: 4.0.2
blenderbim_version: 0.7.9.240626
last_actions: 
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_enable_add_type
# operator: BIM_OT_add_type
# ifcopenshell.api: root.create_entity
>>> {"ifc_class": "IfcBeamType", "predefined_type": "BEAM", "name": "Timber 50x76"}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 7996, "Name": "Timber 50x76"}, "matrix": {"cast_type": "ndarray", "value": [[1.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 1.0]]}}
# ifcopenshell.api: material.assign_material
>>> {"products": [{"cast_type": "entity_instance", "value": 7996, "Name": "Timber 50x76"}], "type": "IfcMaterialProfileSet"}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: material.add_profile
>>> {"profile_set": {"cast_type": "entity_instance", "value": 7998, "Name": null}, "material": {"cast_type": "entity_instance", "value": 1112, "Name": "Green"}}
last_error: Traceback (most recent call last):
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\ifc.py", line 381, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\type\operator.py", line 396, in _execute
    material_profile = ifcopenshell.api.run(
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 184, in run
    return usecase_function(ifc_file, should_run_listeners=should_run_listeners, **settings)
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 363, in wrapper
    listener(usecase_path, ifc_file, settings)
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\model\product.py", line 517, in ensure_material_assigned
    elements = settings["products"]
KeyError: 'products'

ifc: 1bd house-IFC4X3.ifc
schema: IFC4X3
preprocessor_version: IfcOpenShell 0.0.0
originating_system: BlenderBIM 0.7.9.240626-de00429
```
```
os: Windows
os_version: 10.0.19045
python_version: 3.10.13
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
blender_version: 4.0.2
blenderbim_version: 0.7.9.240626
last_actions: 
# operator: BIM_OT_add_type
# ifcopenshell.api: root.create_entity
>>> {"ifc_class": "IfcBeamType", "predefined_type": "BEAM", "name": "Timber 50x76"}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: geometry.edit_object_placement
>>> {"product": {"cast_type": "entity_instance", "value": 7996, "Name": "Timber 50x76"}, "matrix": {"cast_type": "ndarray", "value": [[1.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 1.0]]}}
# ifcopenshell.api: material.assign_material
>>> {"products": [{"cast_type": "entity_instance", "value": 7996, "Name": "Timber 50x76"}], "type": "IfcMaterialProfileSet"}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: material.add_profile
>>> {"profile_set": {"cast_type": "entity_instance", "value": 7998, "Name": null}, "material": {"cast_type": "entity_instance", "value": 1112, "Name": "Green"}}
# operator: BIM_OT_duplicate_type
# ifcopenshell.api: root.copy_class
>>> {"product": {"cast_type": "entity_instance", "value": 7996, "Name": "Timber 50x76"}}
# operator: BIM_OT_load_type_thumbnails
last_error: Traceback (most recent call last):
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\ifc.py", line 381, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\type\operator.py", line 573, in _execute
    bpy.ops.bim.load_type_thumbnails(ifc_class=new.is_a())
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\ifc.py", line 381, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\model\product.py", line 396, in _execute
    if tool.Model.update_thumbnail_for_element(element):
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\tool\model.py", line 802, in update_thumbnail_for_element
    tool.Profile.draw_image_for_ifc_profile(draw, profile, size)
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\tool\profile.py", line 40, in draw_image_for_ifc_profile
    shape = ifcopenshell.geom.create_shape(settings, profile)
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\geom\main.py", line 361, in create_shape
    ifcopenshell_wrapper.create_shape(settings, inst.wrapped_data, repr.wrapped_data if repr is not None else None),
AttributeError: 'NoneType' object has no attribute 'wrapped_data'
Location: C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py:109


ifc: 1bd house-IFC4X3.ifc
schema: IFC4X3
preprocessor_version: IfcOpenShell 0.0.0
originating_system: BlenderBIM 0.7.9.240626-de00429
```
[1bd house-IFC4X3.txt](https://github.com/user-attachments/files/16098132/1bd.house-IFC4X3.txt)

Hi, I tired to add a new IfcBeam and got the follwoing error messages, hope this helps.
Thanks for your effort.

**Comment by Moult** [comment] 2024-07-09 01:38
OK this explains the root cause, during the duplication of the beam, it hit a bug which caused broken state. This is unfortunate but also expected as @Andrej730 is currently working on materials / styles - which actually should be fixed as of this commit 12 hours ago: https://github.com/IfcOpenShell/IfcOpenShell/commit/dd561d37032e667a805bb55f19a4edc978e7a0a8

**Closed by Moult** 2024-07-09 01:38 UTC
Labels: BlenderBIM

**Comment by Ave-5D** [comment] 2024-07-09 07:06
Thanks a million Dion, it looks like it is working now.

It is amazing to see how you and your team is moving a mountain one stone at a time, keep it up.
