### ISSUE TITLE
Space transparency not set as per IFC file

### ISSUE THREAD

**Issue by ssg3d** [IfcOpenShell/IfcOpenShell#2624] opened 2022-11-28 11:45 UTC
Consider an IfcSpace and an IfcBuilding, both having a simple cube geometry representation. Both have a transparency set to 90% in the Ifc File. While IfcParse respects the transparency of the IfcBuilding and that can be seen in the triangulated facets, it does not do so for IfcSpace and keeps them as opaque.

**Comment by aothms** [comment] 2022-11-28 12:35
Can you share an example to reproduce this issue?

**Comment by ssg3d** [comment] 2022-11-29 06:02
[debug.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/10110196/debug.zip)
Attached debug.ifc. Its got a red space (which is opaque despite being transparent in IFC) and a green building which retains transparency.

**Comment by Moult** [comment] 2022-11-29 06:28
Works in the BlenderBIM Add-on but maybe that's not what you're doing :)

![2022-11-29-172736_360x330_scrot](https://user-images.githubusercontent.com/88302/204455134-a9ebf50b-9d90-4a2f-ae1c-66b06548b892.png)

**Comment by ssg3d** [comment] 2022-11-29 06:41
Nope, not using BlenderBIM. I am using the triangulated output emitted by IfcParse which emits transparency value of 0 for spaces, but emits the correct ones for buildings.

**Comment by ssg3d** [comment] 2022-12-01 08:55
@aothms were you able to reproduce this?

**Comment by aothms** [comment] 2022-12-01 09:23
I can't reproduce this. Converting the model to dae using IfcConvert both have a transparency encoded in their effect.

```
  <library_effects>
    <effect id="surface-style-49-fx">
      <profile_COMMON>
        <technique sid="common">
          <lambert>
            <diffuse>
              <color>1 0 0 1</color>
            </diffuse>
            <transparency>
              <float>0.09803921568627449</float>
            </transparency>
          </lambert>
        </technique>
      </profile_COMMON>
    </effect>
    <effect id="surface-style-61-fx">
      <profile_COMMON>
        <technique sid="common">
          <lambert>
            <diffuse>
              <color>0 1 0 1</color>
            </diffuse>
            <transparency>
              <float>0.1999999999999999</float>
            </transparency>
          </lambert>
        </technique>
      </profile_COMMON>
    </effect>
  </library_effects>
```

**Comment by ssg3d** [comment] 2022-12-01 11:42
@aothms the issue occurs in the following code (inspired from IfcConvert.cpp):
```
    SerializerSettings settings;
    settings.set(IfcGeom::IteratorSettings::WELD_VERTICES, false);
    settings.set(IfcGeom::IteratorSettings::APPLY_DEFAULT_MATERIALS, true); 

    // leave out openings
    std::vector<IfcGeom::filter_t> filter_funcs;
    {
        IfcGeom::entity_filter entity_filter;
        std::set<std::string> entities;
        entities.insert("IfcOpeningElement");
        entity_filter.entity_names = entities;
        filter_funcs.push_back(entity_filter);
    }

    IfcGeom::Iterator geomIter(settings, &ifcFile, filter_funcs, 5);
    if (!geomIter.initialize())
        return;

    do
    {
        const IfcGeom::TriangulationElement* o = static_cast<const IfcGeom::TriangulationElement*>(geomIter.get());
        const std::vector<IfcGeom::Material>& omaterials = o->geometry().materials();
        for (size_t i = 0; i < omaterials.size(); ++i)
        {
            // hasTransparency returns yes in both cases, but for spaces transparency() returns 0.
            double transparency = omaterials[i].hasTransparency() ? omaterials[i].transparency() : 0;
        }
    }
    while (geomIter.next());
```
I do see however that recent code in IfcConvert.cpp has stuff like 
```
if (vmap.count("force-space-transparency")) {
		settings.force_space_transparency(force_space_transparency);
		IfcGeom::update_default_style("IfcSpace").Transparency().reset(force_space_transparency);
```
but I am yet to understand it fully and debug it to see if it has an impact.

**Comment by aothms** [comment] 2022-12-01 13:35
It could be that this force_space_transparency is not correctly initialized: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcgeom_schema_agnostic/IfcGeomIteratorSettings.h#L182 It doesn't seem to get default initiatialized in the constructor. So maybe in your code you can try to set explicitly settings.force_space_transparency(-1.) to make sure it's not applied?

**Comment by ssg3d** [comment] 2022-12-02 08:15
That worked! Thanks @aothms !

**Comment by Moult** [comment] 2022-12-02 10:10
Before closing this should we confirm that there isn't a bug that can be fixed here? (i.e. default initialisation of the setting in the constructor?)

**Closed** 2022-12-02 12:43 UTC
Labels: IfcOpenShell-Core
