### ISSUE TITLE
Merge files / IfcPatch 

### ISSUE THREAD

**Issue by TZwielehner** [IfcOpenShell/IfcOpenShell#1478] opened 2021-05-20 14:24 UTC
I tried to use the following script to merge multiple IFC-files into one model. These were exported from the same Revit file so the IfcProject, IfcSite, IfcBuilding and IfcBuildingStoreys are "identical" (all attributes, but not the STEP-number). 

```
import ifcopenshell

new_file = ifcopenshell.file(schema='IFC4')

old_files = list(map(ifcopenshell.open, [
    r'C:\Users\***\walls.ifc',
    r'C:\Users\***\win_doors.ifc',
    r'C:\Users\***\rest.ifc'
]))

for old in old_files:
    for inst in old:
        #print(inst)
        new_file.add(inst)

projects = new_file.by_type("IfcProject")
# Process all but the first project
for p in projects[1:]:
    # Get instances that relate to this project
    refs = new_file.get_inverse(p)
    is_project = lambda inst: inst == p
    assign_first = lambda inst: projects[0]
    # Assign the first project wherever the other project is assigned
    for ref in refs:
        for index, attr in enumerate(ref):
            ref[index] = ifcopenshell.entity_instance.walk(
                is_project,
                assign_first,
                ref[index])
    # Remove from file
    new_file.remove(p)

new_file.write(r'C:\Users\***\federated.ifc')
```

However, this leads to an error that reads:

> Traceback (most recent call last):
>   File "C:/Users/***/AppData/Local/Programs/Python/Python38/ifc_merge.py", line 52, in <module>
>     new_file.add(inst)
>   File "C:\Users\***\AppData\Local\Programs\Python\Python38\Lib\ifcopenshell\file.py", line 128, in add
>     return entity_instance(self.wrapped_data.add(inst.wrapped_data))
>   File "C:\Users\***\AppData\Local\Programs\Python\Python38\Lib\ifcopenshell\ifcopenshell_wrapper.py", line 1524, in add
>     return _ifcopenshell_wrapper.file_add(self, entity)
> RuntimeError: Unable to map instance to file

Any ideas how to solve this?

**Comment by dedicos** [comment] 2021-05-21 08:32
Maybe a python2/python3 conflict?

**Comment by dedicos** [comment] 2021-05-21 10:26
I tried a different approach, loading the same e.g. IfcProject(all attributes set to none, STEP number is #1 for both). However, Python does not consider them being idendical. Is there a way to check that they are the same without going through all the attributes?

**Comment by aothms** [comment] 2021-05-21 10:53
> Python does not consider them being idendical

The equality check specifically includes the file it is part of so instances from different files are never equal.

> Is there a way to check that they are the same without going through all the attributes?

What you can do is call `inst.get_info(include_identifier=False, recursive=True)` to get a native python dictionary of all attribute values that you can compare.

> Any ideas how to solve this?

Testing the most obivous first, `schema='IFC4'` are all files in old_files indeed IFC4?

**Comment by dedicos** [comment] 2021-05-21 13:19
Putting all of it into dictionaries was a good hint. Especially because I can recreate the instances quite easily using the **kwargs and the create_entity method. So I dump everything into a temporary IFC, check for duplicates, and then put create the new file. Still have to check all the dependencies as they rely on the STEP ID but do far it looks promising.

**Comment by vulevukusej** [comment] 2024-03-14 10:41
Also getting this same error message when trying to merge files:

```
Exception has occurred: RuntimeError
Unable to map instance to file
  File "..\Patcher\patcher.py", line 32, in patch
    self.result.add(element)
```

**Comment by vulevukusej** [comment] 2024-03-14 10:46
@aothms I can share the files with you privately if that'd help.. ?

**Comment by vulevukusej** [comment] 2024-03-15 09:44
@Andrej730 Sent 👍

**Comment by Andrej730** [comment] 2024-03-20 09:18
@vulevukusej on merging which projects it fails? is there some code example?

**Comment by vulevukusej** [comment] 2024-03-20 09:46
@Andrej730 I've tried a few different methods, but here's one as an example:

```
from datetime import datetime
from typing import List
import ifcopenshell
import ifcopenshell.util.element


class Patcher:
    def __init__(self, files: List[str]):
        self.result = None
        self.files = files
        self.num_files = len(files)

    def patch(self):
        if len(self.files) == 0:
            return self.result
        if not self.result and len(self.files) > 1:
            self.result = ifcopenshell.open(self.files.pop())
        
        model_2 = ifcopenshell.open(self.files.pop())
        print(f"merging {self.num_files - len(self.files)} / {self.num_files}...")

        self.existing_contexts = self.result.by_type("IfcGeometricRepresentationContext")
        self.added_contexts = set()

        original_project = self.result.by_type("IfcProject")[0]
        project_to_add = self.result.add(model_2.by_type("IfcProject")[0])

        for element in model_2.by_type("IfcGeometricRepresentationContext"):
            new = self.result.add(element)
            self.added_contexts.add(new)
        for element in model_2:
            self.result.add(element)
        for inverse in self.result.get_inverse(project_to_add):
            ifcopenshell.util.element.replace_attribute(inverse, project_to_add, original_project)
        self.result.remove(project_to_add)
        self.reuse_existing_contexts()

        return self.patch()

    def reuse_existing_contexts(self):
        to_delete = set()

        for added_context in self.added_contexts:
            equivalent_existing_context = self.get_equivalent_existing_context(added_context)
            if equivalent_existing_context:
                for inverse in self.result.get_inverse(added_context):
                    ifcopenshell.util.element.replace_attribute(inverse, added_context, equivalent_existing_context)
                to_delete.add(added_context)

        for added_context in to_delete:
            ifcopenshell.util.element.remove_deep2(self.result, added_context)

    def get_equivalent_existing_context(self, added_context):
        for context in self.existing_contexts:
            if context.is_a() != added_context.is_a():
                continue
            if context.is_a("IfcGeometricRepresentationSubContext"):
                if (
                    context.ContextType == added_context.ContextType
                    and context.ContextIdentifier == added_context.ContextIdentifier
                    and context.TargetView == added_context.TargetView
                ):
                    return context
            elif (
                context.ContextType == added_context.ContextType
                and context.ContextIdentifier == added_context.ContextIdentifier
            ):
                return context
            


# get all the files in the folder
import os
folder = "C://Users//vpaji//OneDrive//Desktop//patch fail"
filenames = os.listdir(folder)
filepaths = [folder + "//" + file for file in filenames]
num_files = len(filepaths)

# open the files with ifcopenshell
start = datetime.now()

print(f"Finished opening files in {(datetime.now() - start).total_seconds()}s. Starting patching...")

patcher = Patcher(filepaths)
patcher.patch()

```

**Comment by Andrej730** [comment] 2024-03-20 12:27
@vulevukusej 

To solve this kind of error you usually need to narrow it down to the exact files and entities that fail on `file.add(entity)` and run validation on that file.

It seems the problem was that one of the .ifc files had `#190=IFCAPPLICATION(#1,'','','');` referring to `#1` entity which didn't existed in the file. So adding any entity that's referring to `#150=IFCOWNERHISTORY(#160,#190,.READWRITE.,.ADDED.,$,$,$,0);` failed with `Unable to map instance to file`.

And there also was the other prolem - some other file had `#40= IFCAPPLICATION(#1,'','','');`
referring to `#1= IFCPROJECT('0000',#41,'001',$,$,'',$,(#7),#20);` and it crashed ifcopenshell which is also invalid ifc since this attribute expected to be IfcOrganization type, not IfcProject. Replacing `#1` in `IFCAPPLICATION` atleast with `$` (None) helps. 

I've sent you more details in the email.

Script I was using for tests:
```python
import ifcpatch
import ifcopenshell

# list of filepaths
files: str = [
    ...
]

ifc_file = ifcopenshell.open(files[-1])

for filepath in files[0:-1][::-1]:
    print(filepath)
    ifc_file = ifcpatch.execute(
        {
            "input": "input.ifc",
            "file": ifc_file,
            "recipe": "MergeProject",
            "arguments": [filepath],
        }
    )

ifc_file.write(r"L:\test.ifc")
```

@aothms 

Any ideas if it's intended behaviour if entity is referring to some invalid entity? It seems to work in the case if entity has an aggregate attribute that's referring to the invalid entity.

Example script to reproduce this:

```python
import ifcopenshell

source_file_str = """ISO-10303-21;
HEADER;
FILE_DESCRIPTION(('ViewDefinition[DesignTransferView]'),'2;1');
FILE_NAME('test.ifc','2024-03-15T18:02:35+05:00',(),(),'IfcOpenShell v0.7.0-eaa2aa05a','BlenderBIM 0.0.999999-ee27bc3','Nobody');
FILE_SCHEMA(('IFC4'));
ENDSEC;
DATA;
#1=IFCPROJECT('2LL4zm0tz6XBx1Fgm1C_70',$,'My Project',$,$,$,$,$,#9999);
#2=IFCPROJECT('2LL4zm0tz6XBx1Fgm1C_71',$,'My Project',$,$,$,$,(#9999),$);
#3=IFCPROJECT('2LL4zm0tz6XBx1Fgm1C_72',$,'My Project',$,$,$,$,$,#4);
#4=IFCGEOMETRICREPRESENTATIONCONTEXT($,'Model',3,1.E-05,#9999,$);
#5=IFCPROJECT('2LL4zm0tz6XBx1Fgm1C_73',$,'My Project',$,$,$,$,(#6),$);
#6=IFCGEOMETRICREPRESENTATIONCONTEXT($,'Model',3,1.E-05,#9999,$);
ENDSEC;
END-ISO-10303-21;
"""

ifc_file = ifcopenshell.file()
source = ifcopenshell.file().from_string(source_file_str)
def try_to_add(entity_id: int):
    print(entity_id)
    try:
        ifc_file.add(source.by_id(entity_id))
        print('fine')
    except Exception as e:
        print(type(e), e.args)

# RuntimeError: Instance #9999 not found
# trying to add
# 1=IFCPROJECT('2LL4zm0tz6XBx1Fgm1C_70',$,'My Project',$,$,$,$,$,#9999);`
try_to_add(1)

# trying to add
# 2=IFCPROJECT('2LL4zm0tz6XBx1Fgm1C_71',$,'My Project',$,$,$,$,(#9999),$);`
# works fine
try_to_add(2)

# RuntimeError: Unable to map instance to file
# trying to add:
# 3=IFCPROJECT('2LL4zm0tz6XBx1Fgm1C_71',$,'My Project',$,$,$,$,$,#4);
# 4=IFCGEOMETRICREPRESENTATIONCONTEXT($,'Model',3,1.E-05,#9999,$);
try_to_add(3)

# RuntimeError: Unable to map instance to file
# trying to add:
# 5=IFCPROJECT('2LL4zm0tz6XBx1Fgm1C_71',$,'My Project',$,$,$,$,(#6),$);
# 6=IFCGEOMETRICREPRESENTATIONCONTEXT($,'Model',3,1.E-05,#9999,$);
try_to_add(5)
```

And another issue I've found - not sure if real IFC has any cases where element's referring to another element that's referring to original element - but it seems to crash IfcOpenShell.

Example script:

```python
import ifcopenshell

source_file_str = """ISO-10303-21;
HEADER;
FILE_DESCRIPTION(('',''),'');
FILE_NAME('','',(''),(''),'','','');
FILE_SCHEMA(('IFC4'));
ENDSEC;

DATA;
#1= IFCPROJECT('0PJ607Qb5DWA6JDLqlvSVn',#2,'001',$,$,'',$,$,$);
#2= IFCOWNERHISTORY(#1,$,$,.NOCHANGE.,$,$,$,0);
ENDSEC;

END-ISO-10303-21;
"""

ifc_file = ifcopenshell.file()
source = ifcopenshell.file().from_string(source_file_str)

print('script started')
ifc_file.add(source.by_id(1))
print('script finished') # never printed because of the crash
```

**Comment by Andrej730** [comment] 2024-03-21 11:06
Just for everyone who is going to met `RuntimeError: Unable to map instance to file` in the future - you can turn on detailed logging with `ifcopenshell_wrapper.turn_on_detailed_logging()` which helps locating the root of the issue (usually it's a reference to some entity that doesn't exist in the .ifc file).

```python
source_file_str = """ISO-10303-21;
HEADER;
FILE_DESCRIPTION(('ViewDefinition[DesignTransferView]'),'2;1');
FILE_NAME('test.ifc','2024-03-15T18:02:35+05:00',(),(),'IfcOpenShell v0.7.0-eaa2aa05a','BlenderBIM 0.0.999999-ee27bc3','Nobody');
FILE_SCHEMA(('IFC4'));
ENDSEC;
DATA;
#1=IFCPROJECT('2LL4zm0tz6XBx1Fgm1C_70',$,'My Project',$,$,$,$,$,#9999);
#2=IFCPROJECT('2LL4zm0tz6XBx1Fgm1C_71',$,'My Project',$,$,$,$,(#9999),$);
#3=IFCPROJECT('2LL4zm0tz6XBx1Fgm1C_72',$,'My Project',$,$,$,$,$,#4);
#4=IFCGEOMETRICREPRESENTATIONCONTEXT($,'Model',3,1.E-05,#9999,$);
#5=IFCPROJECT('2LL4zm0tz6XBx1Fgm1C_73',$,'My Project',$,$,$,$,(#6),$);
#6=IFCGEOMETRICREPRESENTATIONCONTEXT($,'Model',3,1.E-05,#9999,$);
ENDSEC;
END-ISO-10303-21;
"""

import ifcopenshell.ifcopenshell_wrapper
ifcopenshell.ifcopenshell_wrapper.turn_on_detailed_logging()

import ifcopenshell
ifc_file = ifcopenshell.file()
source = ifcopenshell.file().from_string(source_file_str)

# Output will be:
# Scanning file...
# Done scanning file
# [Error] [2024-03-21 15:56:38] Failed to visit forward references of
# # 6=IfcGeometricRepresentationContext($,'Model',3,1.E-05,# 9999,$)
# [Error] [2024-03-21 15:56:38] Failed to visit forward references of
# # 5=IfcProject('2LL4zm0tz6XBx1Fgm1C_73',$,'My Project',$,$,$,$,(# 6),$)
# Traceback (most recent call last):
#   File "test.py", line 29, in <module>
#     ifc_file.add(source.by_id(5))
#   File "\ifcopenshell\file.py", line 440, in add
#     result = entity_instance(self.wrapped_data.add(inst.wrapped_data, -1 if _id is None else _id), self)
#                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#   File "\ifcopenshell\ifcopenshell_wrapper.py", line 4595, in add
#     return _ifcopenshell_wrapper.file_add(self, entity, id)
#            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# RuntimeError: Unable to map instance to file
ifc_file.add(source.by_id(5))
```

**Comment by vulevukusej** [comment] 2024-03-21 11:17
@Andrej730 I never knew about that option, thanks again!!

**Comment by pyprince** [comment] 2024-04-07 09:18
@Andrej730 
I have more than 500 ifc files. I have to combine & merge them by discipline. There are about 10 disciplines like GEO, ROA, STR...
How can I do this? I tried to use IfcPatch but got so many errors. Is there any automatic way(resolving conflicts automatically) to merge them?

**Comment by Andrej730** [comment] 2024-04-07 09:26
> I have more than 500 ifc files. I have to combine / merge them by discipline. There are about 10 disciplines like GEO, ROA, STR...
> How can I do this? I tried to use IfcPatch but got so many errors. Is there any automatic way(resolving conflicts automatically) to merge them?

@pyprince what errors?

**Comment by pyprince** [comment] 2024-04-07 09:29
This is my code to merge.
```python
import os
import ifcopenshell
import ifcpatch

from ifc_disciplines import get_files_by_discipline

ifcopenshell.ifcopenshell_wrapper.turn_on_detailed_logging()

ifc_directory = './data1'
files_by_discipline = get_files_by_discipline(ifc_directory)
for discipline in files_by_discipline.keys():
    ifc_file = ifcopenshell.open(os.path.join(ifc_directory, files_by_discipline[discipline][-1]))

    print("+++++++++++++++++++")
    print(discipline, ':', len(files_by_discipline[discipline]))
    print("+++++++++++++++++++")

    for file_name in files_by_discipline[discipline][0:-1]:
        print(file_name, os.path.join(ifc_directory, file_name))
        ifc_file = ifcpatch.execute(
            {
                "input": ifc_directory + '/' + files_by_discipline[discipline][-1],
                "file": ifc_file,
                "recipe": "MergeProject",
                "arguments": [os.path.join(ifc_directory, file_name)],
            }
        )
    ifc_file.write(ifc_file, './' + discipline + '.ifc')
```

I resolved many errors manually but at last got this.
```error
RuntimeError: Argument is not a string
```

And this is just about first two ifc files merging.
How to fix it?

**Comment by Andrej730** [comment] 2024-04-08 07:40
> I resolved many errors manually but at last got this.
> 
> ```
> F:\agol>C:/Users/Administrator/AppData/Local/Programs/Python/Python311/python.exe f:/agol/ifc_merge.py
> Scanning file...
> Done scanning file   
> +++++++++++++++++++
> GEO : 60
> +++++++++++++++++++
> SB_ES_01_3DM_GEO_STA_010701_GroundStabilization.ifc ./data1\SB_ES_01_3DM_GEO_STA_010701_GroundStabilization.ifc
> Scanning file...
> Done scanning file   
> Traceback (most recent call last):
>   File "f:\agol\ifc_merge.py", line 20, in <module>
>     ifc_file = ifcpatch.execute(
>                ^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\ifcpatch\__init__.py", line 80, in execute
>     patcher.patch()
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\ifcpatch\recipes\MergeProject.py", line 64, in patch
>     self.file.add(element)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\ifcopenshell\file.py", line 407, in add
>     result = entity_instance(self.wrapped_data.add(inst.wrapped_data, -1 if _id is None else _id), self)
>                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 4631, in add
>     return _ifcopenshell_wrapper.file_add(self, entity, id)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> RuntimeError: Argument is not a string
> ```
> 
> And this is just about first two ifc files merging. How to fix it?

@pyprince hard to tell without the .ifc files. Are you sure those files are valid IFC? It looks like they might have some issues in them (e.g. non string data in some string attribute). You can validate them with ifcopenshell or [BBIM](https://wiki.osarch.org/index.php?title=BlenderBIM_Add-on/BlenderBIM_Add-on_FAQ#How_to_validate_IFC_file_for_issues_.3F).

**Comment by pyprince** [comment] 2024-04-08 09:03
Thanks for you advice @Andrej730 
But it is showed well in SimpleBIM or other IFC viewers. And if it's not valid, what can I do for it? My final goal is to integrate them with AGOL. Could you give me any advice for me?

**Comment by Andrej730** [comment] 2024-04-08 09:08
> But it is showed well in SimpleBIM or other IFC viewers. And if it's not valid, what can I do for it? My final goal is to integrate them with AGOL. Could you give me any advice for me?

@pyprince Even if it opens in viewers it still might have some invalid parts and you'll need to run validation check to see what issues there are. I'd look first for validation errors like "non string data in some string attribute".

**Comment by pyprince** [comment] 2024-04-08 09:12
If they are not valid, what can I do for it? Should I fix them manually?

**Comment by Andrej730** [comment] 2024-04-08 09:14
> If they are not valid, what can I do for it? Should I fix them manually?

It depends on what issues they have. You might be able to patch them with some ifcopenshell script or it might highlight some issues in the source where those .ifc files came from and it can be fixed there.

**Comment by pyprince** [comment] 2024-04-08 09:21
I have tons of files and some of them are more than 300MB. And it's impossible for me to require valid ifc files. So I am trying to make merge script that resolves conflicts automatically. Is it possible in ifcopenshell? If ifc viewers can render all of these files even if there are some crashes, then it shows I can do that. Hope your kind suggestions.

**Comment by Andrej730** [comment] 2024-04-08 09:24
> I have tons of files and some of them are more than 300MB. And it's impossible for me to require valid ifc files. So I am trying to make merge script that resolves conflicts automatically. Is it possible in ifcopenshell? If ifc viewers can render all of these files even if there are some crashes, then it shows I can do that. Hope your kind suggestions.

Need to investigate files first, it's impossible to tell how to overcome the issues without the knowing what the issues are.

**Closed** 2024-04-19 13:04 UTC
Labels: IfcPatch

**Comment by aothms** [comment] 2024-04-20 11:46
For reference:

https://github.com/IfcOpenShell/IfcOpenShell/blob/3ef823db239843bdd1104055f2229336d824cc9a/src/ifctester/test/ids_doc_generator.py#L60-L72

The above is some light weight example of how you could programmatically apply fixes based on the validation module.
