### ISSUE TITLE
Plan level doesn't support showing a negative prefix, when in inches. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3448] opened 2023-07-14 18:41 UTC
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/9b50e543-41b9-4818-8306-fa23db4311d9)

**Comment by Moult** [comment] 2023-07-15 11:57
Duplicate of #3441

**Closed by Moult** 2023-07-15 11:57 UTC
Labels: BlenderBIM
