### ISSUE TITLE
BB: error when creating drawing

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2349] opened 2022-08-17 17:56 UTC
BB 0.0.220816

Using [this](https://gitlab.com/osarch/FreeMVD_WorkFlow/-/blob/master/Example%20Projects/BlenderBIM%20-%20annotation%20file/untitled.ifc) file. 

video: https://www.dropbox.com/s/dqg9wap05tjsehg/2022-08-17_12-55-14_Blender_blender.mp4?dl=0

error. 

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 160, in execute
    annotation_svg = self.generate_annotation(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\bim\module\drawing\operator.py", line 448, in generate_annotation
    self.svg_writer.create_blank_svg(svg_path).draw_annotations(annotations).save()
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\bim\module\drawing\svgwriter.py", line 160, in draw_annotations
    self.draw_text_annotation(obj, obj.location)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\bim\module\drawing\svgwriter.py", line 532, in draw_text_annotation
    literal = literal.replace(variable, selector.get_element_value(product, variable[2:-2]) or "")
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\selector.py", line 226, in get_element_value
    info = element.get_info()
AttributeError: 'NoneType' object has no attribute 'get_info'

location: <unknown location>:-1

```

**Comment by ChubbyQuark** [comment] 2022-08-23 07:39
Also getting a similar error on BB 0.0.220823:

Python: Traceback (most recent call last):
  File "/Users/owner/Library/Application Support/Blender/3.2/scripts/addons/blenderbim/bim/module/drawing/operator.py", line 160, in execute
    annotation_svg = self.generate_annotation(context)
  File "/Users/owner/Library/Application Support/Blender/3.2/scripts/addons/blenderbim/bim/module/drawing/operator.py", line 448, in generate_annotation
    self.svg_writer.create_blank_svg(svg_path).draw_annotations(annotations).save()
  File "/Users/owner/Library/Application Support/Blender/3.2/scripts/addons/blenderbim/bim/module/drawing/svgwriter.py", line 79, in save
    self.svg.save(pretty=True)
  File "/Users/owner/Library/Application Support/Blender/3.2/scripts/addons/MeasureIt_ARCH/libs/svgwrite/drawing.py", line 122, in save
    self.write(fileobj, pretty=pretty, indent=indent)
  File "/Users/owner/Library/Application Support/Blender/3.2/scripts/addons/MeasureIt_ARCH/libs/svgwrite/drawing.py", line 110, in write
    xml_string = self.tostring()
  File "/Users/owner/Library/Application Support/Blender/3.2/scripts/addons/MeasureIt_ARCH/libs/svgwrite/base.py", line 189, in tostring
    xml_utf8_str = etree.tostring(xml, encoding='utf-8')
  File "/Applications/Blender.app/Contents/Resources/3.2/python/lib/python3.10/xml/etree/ElementTree.py", line 1109, in tostring
    ElementTree(element).write(stream, encoding,
  File "/Applications/Blender.app/Contents/Resources/3.2/python/lib/python3.10/xml/etree/ElementTree.py", line 748, in write
    serialize(write, self._root, qnames, namespaces,
  File "/Users/owner/Library/Application Support/Blender/3.2/scripts/addons/blenderbim/libs/site/packages/behave/reporter/junit.py", line 130, in _serialize_xml3
    return orig(write, elem, qnames, namespaces, short_empty_elements)
TypeError: _serialize_xml_with_CDATA_support() takes 4 positional arguments but 5 were given
owner

**Comment by aothms** [comment] 2022-08-24 09:01
@ChubbyQuark your issue is a duplicate of https://github.com/IfcOpenShell/IfcOpenShell/issues/2159

**Comment by Moult** [comment] 2023-01-29 04:15
So there have been an umber of changes since and I cannot recreate it now, but I've just added a bit more defensive code which should address the possibility of the original error.

**Closed** 2023-01-29 04:15 UTC
Labels: BlenderBIM
