### ISSUE TITLE
Parametric door in a wall assembly produces an error

### ISSUE THREAD

**Issue by trhyder** [IfcOpenShell/IfcOpenShell#3533] opened 2023-08-01 18:43 UTC
A parametric door in a wall assembly produces an error when confirming Finish Editing.

[door tests.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/12232941/door.tests.ifc.zip)
![ezgif com-video-to-gif (1)](https://github.com/IfcOpenShell/IfcOpenShell/assets/59872808/6a2f1948-18cf-449b-98a8-2c7ba4bdfe4f)

**Comment by Andrej730** [comment] 2023-08-02 06:54
Fixed.

@trhyder I've noticed one more issue here - when you start editing the door it changes it's height. 
Meaning there is a condradiction between door's representation and door's parametric data (door pamateric data from property set `BBIM_Door`). Door's representation height is ~2.10m when door's height in parametric data is ~2.4m. Any ideas how this issue can be reproduced?

**Comment by trhyder** [comment] 2023-08-03 02:56
Sorry not sure I follow. I do manually edit the door type height from 2.1 to 2.4, and then I change it back again after I put it in the wall assembly to demonstrate the error.

**Comment by Andrej730** [comment] 2023-08-03 05:46
Note the door changing it's height when you just started editing it:
https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/785edc30-a7c0-430d-802d-2a3889f4356c

**Comment by trhyder** [comment] 2023-08-03 14:07
Ah, I see. I can't reproduce creating a door type that does that. Often I forget to click Finish Editing so I tried creating a door type, editing the height, and saving the file without clicking Finish Editing. But when I opened the file, both the door's representation and the door's parametric data were back to 2.0m, as I would expect.

Could it have been that the door's representation and parametric data got out of sync because of the error that you just fixed?

The only other thing I can think of is that I have an unhelpful habit of triggering undo via shortcut whenever something unexpected happens.

**Comment by Andrej730** [comment] 2023-08-07 17:20
> Could it have been that the door's representation and parametric data got out of sync because of the error that you just fixed?
No, it's something different.

Will close it for now since not sure how to reproduce it and if it's possible to reproduce it now.

**Closed** 2023-08-07 17:19 UTC
Labels: BlenderBIM
