### ISSUE TITLE
IfcElement filled in IfcopeningElement

### ISSUE THREAD

**Issue by greeshmaunni1990** [IfcOpenShell/IfcOpenShell#1686] opened 2021-08-23 12:38 UTC
Hi
I am using ifcopenshell with python OCC. Currently I am implementing some codes which requires finding doorways without doors. In order to do that I have extracted IfcOpeningElements. Now I have to find out which elements are used to fill the IfcOpeningElement to exclude them. The documentation states that "The IfcOpeningElement shall not participate in the containment relationship, i.e. it is not linked directly to the spatial structure of the project. It has a mandatory VoidsElements inverse relationship pointing to the IfcElement that is contained in the spatial structure. Could someone help me with this

Thank you

**Comment by Moult** [comment] 2021-08-23 22:27
In chapter 4 in the IFC documentation (Fundamental concepts and assumptions) it explains how filling works under the "4.7.4 Element Filling" section.

In short, an opening may be filled with another element. So all you need to do is for each IfcOpeningElement, check its `HasFillings` attribute. It it is non empty, then there is a filling. If not, it is just an opening.

By the way, you might be interested either in the "Discussions" section or https://community.osarch.org/ for questions like these in the future.

**Comment by greeshmaunni1990** [comment] 2021-08-24 13:24
Thank you for the response. I will check the documentation

**Comment by Moult** [comment] 2021-08-24 22:36
Closing as not a bug :)

**Closed by Moult** 2021-08-24 22:36 UTC
