### ISSUE TITLE
Using IfcOpenShell with VisualStudio and C++ language

### ISSUE THREAD

**Issue by pierrenavarra** [IfcOpenShell/IfcOpenShell#1379] opened 2021-03-12 11:41 UTC
Hi,
I'd like to use IfcOpenShell with VisualStudio with C++ language because I'd like to use it in Unreal Engine.
At the moment, I wrote my code with Python. It works. 
Into unreal environnement, I can run my Python script and passing arguments, etc.
The problem is : in Unreal, no way to get Python Script into BluePrint.
But in Unreal, it is possible to code in C++ and call function into BluePrint. 
How to use ifcOpenShell in C++?
Can't find it.
Thx

**Comment by aothms** [comment] 2021-03-12 12:55
Have a look at https://github.com/IfcOpenShell/IfcOpenShell#using-visual-studio and https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/examples/IfcOpenHouse.cpp https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/examples/IfcParseExamples.cpp

**Comment by pierrenavarra** [comment] 2021-03-12 14:24
Thx aothms for this exemples
The think is not clear for me is the process to install ifcopenShell into Visual Studio.
Could you help me a little bit?
In visual Studio using C# it's easy to add GitUb package but with C++ I don't know why... Sorry maybe it's a little bit ridiculous...

**Comment by aothms** [comment] 2021-03-12 14:52
This is all a matter of personal preference. You could use CMake, to setup your project in a cross-platform fashion. Or create a visual studio solution and manually set the header and library paths and files. A visual studio C++ tutorial on the web should cover this. It's not a matter of installation, but setting the correct paths in the MSVC project properties.

**Comment by pierrenavarra** [comment] 2021-03-12 15:46
> Or create a visual studio solution and manually set the header and library paths and files. 
Do you mean, for exemple, if I just want to open and ifc file a get the version, I'll have to copy the src files like wich one? 
>but setting the correct paths in the MSVC project properties. 
What do you mean ?
Sorry to keep your time..

**Comment by aothms** [comment] 2021-03-13 08:37
Not not source, IfcOpenShell src is going to be compiled into static library files (.lib on windows). These provide the implementation. Then the header files the declarations (API definition if you wish). Setting the correct paths will make sure that MSVC can find these files.

**Comment by pierrenavarra** [comment] 2021-03-15 14:03
Hi.
I've installed Git : version 2.30.2windows.1
Also CMake 3.20.0-rc4
I've downloaded the last sourcesCodes 
When I'm with powerShell (as admin) into win direxctory I've got this error....

`

bluids-deps.cmd: The term "bluids-deps.cmd" is not recognized as the name of cmdlet, function, file
script or executable program. Check the spelling of the name, or if a path exists, verify that the path
access is correct and try again.
At character Line: 1: 1
+ bluids-deps.cmd
+ ~~~~~~~~~~~~~~~
    + CategoryInfo: ObjectNotFound: (bluids-deps.cmd: String) [], CommandNotFoundException
    + FullyQualifiedErrorId: CommandNotFoundException`

**Comment by aothms** [comment] 2021-03-15 20:11
> bluids-deps.cmd

build-deps.cmd

Instead of powershell, you should use the `x86 Native Tools Command Prompt for VS 2017` or `x86` or something else that comes with your version of visual studio. It's in your start menu.

**Comment by Moult** [comment] 2024-07-30 01:44
Closing as this is not a bug, just a question on how to use C++

**Closed by Moult** 2024-07-30 01:44 UTC
Labels: IfcOpenShell-Core
