### ISSUE TITLE
Error when assigning an attribute with boolean value (it was working a week ago)

### ISSUE THREAD

**Issue by Jesusbill** [IfcOpenShell/IfcOpenShell#1679] opened 2021-08-21 18:30 UTC
It seems that some of the latest commits may have caused this error I am experiencing when trying to edit structural boundary conditions, which have properties that can be either boolean or floats. About one week ago everything worked as expected, I am kind of suspecting this commit (296bf0387db1abb941) but I am not sure and I have not been able to understand what is wrong.
@Gorgious56 do you have any idea?

The message in Blender is:
```
location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "/home/jesusbill/.config/blender/2.92/scripts/addons/blenderbim/bim/module/structural/operator.py", line 173, in execute
    new.enum_value = "IfcBoolean"
TypeError: bpy_struct: item.attr = val: enum "IfcBoolean" not found in ()
```
It appears when clicking on "Enable editing" here:
![image](https://user-images.githubusercontent.com/6861582/130331637-6e167a69-b3a2-4e5c-81af-8b9338d8cf73.png)

**Comment by Gorgious56** [comment] 2021-08-21 21:52
Hey ! Might very well be caused by this commit. 
I couldn't replicate the error though, could you elaborate on the steps you took to get there ? I'll investigate further in the morning (in my end of the world ^^). Could you try with the very last release ? The "cancel" icons were very recently changed and the change does not appear in your screenshot.

![image](https://user-images.githubusercontent.com/25156105/130335646-621814a4-d6c3-4bbc-b64e-1971703392b8.png)

This is also the first time I realize some attributes can have both an `enum_value` and a `float_value` which I never considered.

**Comment by Moult** [comment] 2021-08-22 01:06
Sorry my bad I revised `attribute.get_primitive_type` to be a bit more robust: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcopenshell-python/ifcopenshell/util/attribute.py#L1 and forgot to review the existing handling of edge cases.

The new utility is smarter because it handles sets, as well as correctly handles the ordering of nested data types (e.g. a type of select of a set of lists...).

For example, given this definition:

```
<select IfcTranslationalStiffnessSelect: (<type IfcBoolean: <boolean>> | <type IfcLinearStiffnessMeasure: <real>>)>
```

In the past it would just say "hey, I'm a select". Now, it'll say I'm a `('select', ('boolean', 'float'))`.

Personally I don't like select data types.

**Comment by Moult** [comment] 2021-08-22 02:25
I guess this also brings up the issue of test suites. Historically, I would practice TDD and religiously write tests for everything. However, between learning Python, learning the Blender API, and rebuilding everything at the beginning of this year (from a previously monolithic and untestable import/export function) this never happened.

My current strategy is that decoupling and the miniaturization of modules and functions mitigate the impact of a lack of tests. The BlenderBIM Add-on is largely UI code, which is always more annoying to test. The API and utils ideally needs tests, but writing "database" / repository tests isn't fun either, but that isn't an excuse. Also given that we don't use dependency injection, maybe that needs to be solved first.

Open for suggestions. I don't think tests would've caught this problem though, since I can't imagine a scalable test suite for the UI which changes so often and depends so much on the graphical contexts of Blender.

**Comment by Jesusbill** [comment] 2021-08-22 10:08
@Moult I am reopening this issue as the problem has been fixed but I see that the `isNull` property is not updated automatically when entering a value (it remains blue). As a result when stop editing it does not keep the values inserted, unless you manually click `isNull`
I actually see now that this applies in all panels, like the class attributes. I am pretty sure before the isNull was changing automatically when entering a value in the field

**Comment by Jesusbill** [comment] 2021-08-22 10:11
@Gorgious56 thanks for the prompt response, I am using the latest version (actually soft linked the add-on to this repo). The image I uploaded is before "enable editing" (the check marks are images here not actual clickable boxes).

**Comment by Moult** [comment] 2021-08-22 10:53
It's a result of this change: https://github.com/IfcOpenShell/IfcOpenShell/commit/296bf0387db1abb9417824c3f3d28efa5eb83b73#diff-8c3dd5d968cdeffccfd25969c0a45144d36d1f6ea5bae2099ae2be4d0767d637

The code committed code is nicer, but unfortunately we can't always rely on data_type in the case of selects. I'll fix it.

**Closed** 2021-08-22 10:54 UTC
Labels: BlenderBIM

**Comment by Gorgious56** [comment] 2021-08-22 13:06
Yup sorry I didn't take into account Attributes can be more complicated than a single value. Thansk for the fix :)
