### ISSUE TITLE
Compiling build-deps throws 403-error for npcglib

### ISSUE THREAD

**Issue by Hasashi** [IfcOpenShell/IfcOpenShell#310] opened 2017-12-14 10:20 UTC
Just wanted to mention that it seems like npcglip switched to https, thats why the error was thrown. Fixed it by changing http to https in build-deps.
Did not know where/who I can inform about this "bug", so I opened a new issue. Sorry if this was wrong.

**Comment by thorade** [comment] 2017-12-14 10:20
This seems to be a duplicate of #309 or at least related.

**Comment by aothms** [comment] 2017-12-14 10:56
> If you submit a pull request with a fix

Indeed thanks for tracking this down. A PR would be appreciated :)

> it will run the automated tests

Not for the build scripts unfortunately, they take too much time on the free Travis instances (understandable).

**Closed** 2017-12-16 08:25 UTC
