### ISSUE TITLE
Unicode characters in IFC file made OBJ conversion fail.

### ISSUE THREAD

**Issue by iras** [IfcOpenShell/IfcOpenShell#101] opened 2016-07-11 11:10 UTC
#11= IFCSURFACESTYLE('\X2\00C70130\X0\ZG\X2\0130\X0\-RRR',.BOTH.,(#10));

OBJ format fails to convert on that unicode name.

It used to work fine...

**Comment by iras** [comment] 2016-07-13 08:09
Hi @Stinkfist0, would the proposed fix in #73 for XML apply to OBJ too?

**Comment by Stinkfist0** [comment] 2016-07-13 09:13
If fixing would mean writing the character in escaped form instead, yeah I'd think so.

**Comment by iras** [comment] 2016-07-13 09:21
I mean IfcOpenShell used to accept unicode chars just fine and now it seems it doesn't anymore and the whole OBJ conversion fails if unicode characters are found in the IFC file.

**Comment by iras** [comment] 2016-07-13 09:22
Any suggestion about how to fix it is much more than welcome.

**Comment by Stinkfist0** [comment] 2016-07-13 09:30
A quick workaround would be to set `IfcCharacterDecoder::mode` back to `IfcCharacterDecoder::JSON`

**Comment by iras** [comment] 2016-07-13 09:40
Cool. Would that also fix the XML issue at #73?

**Comment by Stinkfist0** [comment] 2016-07-13 09:45
A good proper fix would be to make this behavior configurable via command-line argument.

**Comment by iras** [comment] 2016-07-13 09:48
Totally.

**Comment by aothms** [comment] 2016-07-18 14:35
The issue is actually that this string is invalid: in `'\X2\00C70130\X0\ZG\X2\0130\X0-RRR'` the second `\X0\` misses the closing `\`. Not sure if this would have worked 'better' before, but in general it is hard to recover from parsing errors such as these.

**Comment by iras** [comment] 2016-07-19 07:04
Thanks @aothms. I agree that that specific string above is invalid.

Setting `IfcCharacterDecoder` back to `JSON` seems to allow IfcConvert to get to the end of the OBJ conversion process though and incapsulates IFC misspellings which is safe, so to say.

**Comment by aothms** [comment] 2016-07-19 12:08
If I set `IfcCharacterDecoder::ConversionMode IfcCharacterDecoder::mode = IfcCharacterDecoder::JSON;` I also do not get any geometry output from IfcConvert. Error message can be improved, but as said, I don't think it is feasible to recover from this parsing error.

**Comment by iras** [comment] 2016-07-19 13:01
Yes you're right. We could close this issue if that's all right with you.

**Comment by aothms** [comment] 2016-07-19 14:44
I added another line in the log, awfully verbose now, but at least it is clear what is going on.

~~~
[Error] Unexpected '-' at 2266. Parsing terminated
[Error] No geometries found
[Error] Unable to parse input file 'acad2010_walls_uni.ifc' or no geometrical en
tities found
~~~

https://github.com/IfcOpenShell/IfcOpenShell/commit/fd4086aa8d7b22eed9c9e6535007f8c66e9bf0e7

**Closed by aothms** 2016-07-19 14:44 UTC
