### ISSUE TITLE
Reading outside file limits

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#2427] opened 2022-09-20 09:33 UTC
I'm running a migrate patch, which migrates IFC2X3 to IFC4 by creating a new file and attempting to copy elements over as best it can. Usually it works fine. It also usually terminates with an error if it comes across some invalid data it can't handle, like for example if there is a mandatory attribute that _isn't_ filled in IFC2X3 (i.e. the source file is invalid) then it'll give up and won't migrate it.

However, I have an invalid IFC2X3 source file and I tried to disable these error checks, and simply copy what attributes it can, and leave the rest as NULL ($). This is garbage in, garbage out, so the resulting IFC4 should be also invalid.

However what surprised me is that I ran into this error when trying to do write() on the resulting IFC4 file object. What might cause this? Is it because the file is invalid to begin with, or is it a different reason?

```
Error: Python: Traceback (most recent call last):
  File "/home/dion/.config/blender/3.3/scripts/addons/blenderbim/bim/module/patch/operator.py", line 131, in execute
    core.run_migrate_patch(tool.Patch, infile=self.infile, outfile=self.outfile, schema=self.schema)
  File "/home/dion/.config/blender/3.3/scripts/addons/blenderbim/core/patch.py", line 21, in run_migrate_patch
    patch.run_migrate_patch(infile, outfile, schema)
  File "/home/dion/.config/blender/3.3/scripts/addons/blenderbim/tool/patch.py", line 36, in run_migrate_patch
    ifcpatch.write(output, outfile)
  File "/home/dion/.config/blender/3.3/scripts/addons/blenderbim/libs/site/packages/ifcpatch/__init__.py", line 59, in write
    output.write('/home/dion/test2.ifc')
  File "/home/dion/.config/blender/3.3/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3566, in write
    return _ifcopenshell_wrapper.file_write(self, fn)
RuntimeError: Reading outside of file limits
```

Interestingly when I open test2.ifc I see it has started to write, but only written a little bit, then stopped:

```
ISO-10303-21;
HEADER;
FILE_DESCRIPTION(('ViewDefinition [CoordinationView]'),'2;1');
FILE_NAME('','2022-09-20T19:27:44',(),(),'IfcOpenShell v0.7.0-dc67287d','IfcOpenShell v0.7.0-dc67287d','');
FILE_SCHEMA(('IFC4'));
ENDSEC;
DATA;
#1=IFCRELASSIGNSTOGROUP('2s9BwxWrn3o8B$GEHkooBJ',#2,'\X2\6554747347206F727075\X0\','\X2\65547473442073657263706969746E6F\X0\',$,$,$);
#2=IFCOWNERHISTORY(#3,#6,$,.NOCHANGE.,$,$,$,1646904240);
#3=IFCPERSONANDORGANIZATION(#4,#5,$);
#4=IFCPERSON($,$,'Trimble Solutions Sandvika AS',$,$,$,$,$);
#5=IFCORGANIZATION($,'Trimble Solutions Sandvika AS','International pioneer and the market leader in Scandinavia within civil engineering software for designing transport infrastructure.',$,$);
#6=IFCAPPLICATION(#5,'22.00',$,'Trimble Quadri');
#7=IFCSYSTEM('0cmWSxYa910QtQDIZFK_YQ',#2,'Trimble Solutions Sandvika AS','International pioneer and the market leader in Scandinavia within civil engineering software for designing transport infrastructure.',$);
```

**Comment by Moult** [comment] 2022-09-20 10:34
Cheers :) let me know if you spot anything.

**Comment by aothms** [comment] 2022-09-20 10:59
Doing a simple copy to a new file doesn't trigger this issue.

It seems instance `#7` is complete so there might not be a whole lotta io buffering going on. Which might imply that the issue is simply with instance `#8`. What if you just do `print(output[8])` or `for ia in enumerate(output[8]): print(*ia)` from Python?

**Comment by Moult** [comment] 2022-09-20 11:08
```
Traceback (most recent call last):
  File "/home/dion/.config/blender/3.3/scripts/addons/blenderbim/bim/module/patch/operator.py", line 131, in execute
    core.run_migrate_patch(tool.Patch, infile=self.infile, outfile=self.outfile, schema=self.schema)
  File "/home/dion/.config/blender/3.3/scripts/addons/blenderbim/core/patch.py", line 21, in run_migrate_patch
    patch.run_migrate_patch(infile, outfile, schema)
  File "/home/dion/.config/blender/3.3/scripts/addons/blenderbim/tool/patch.py", line 36, in run_migrate_patch
    ifcpatch.write(output, outfile)
  File "/home/dion/.config/blender/3.3/scripts/addons/blenderbim/libs/site/packages/ifcpatch/__init__.py", line 59, in write
    print(output[8])
  File "/home/dion/.config/blender/3.3/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/entity_instance.py", line 204, in __repr__
    return repr(self.wrapped_data)
  File "/home/dion/.config/blender/3.3/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3704, in __repr__
    return _ifcopenshell_wrapper.entity_instance___repr__(self)
RuntimeError: Unexpected token while parsing entity instance
```

```
0 BuildingEnergyTargetValue
1 None
Traceback (most recent call last):
  File "/home/dion/.config/blender/3.3/scripts/addons/blenderbim/bim/module/patch/operator.py", line 131, in execute
    core.run_migrate_patch(tool.Patch, infile=self.infile, outfile=self.outfile, schema=self.schema)
  File "/home/dion/.config/blender/3.3/scripts/addons/blenderbim/core/patch.py", line 21, in run_migrate_patch
    patch.run_migrate_patch(infile, outfile, schema)
  File "/home/dion/.config/blender/3.3/scripts/addons/blenderbim/tool/patch.py", line 36, in run_migrate_patch
    ifcpatch.write(output, outfile)
  File "/home/dion/.config/blender/3.3/scripts/addons/blenderbim/libs/site/packages/ifcpatch/__init__.py", line 60, in write
    print(*ia)
  File "/home/dion/.config/blender/3.3/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/entity_instance.py", line 204, in __repr__
    return repr(self.wrapped_data)
  File "/home/dion/.config/blender/3.3/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/ifcopenshell_wrapper.py", line 3704, in __repr__
    return _ifcopenshell_wrapper.entity_instance___repr__(self)
```

output[8].is_a() = IfcPropertySingleValue

Searching in the source, the source definition is `#253332 = IFCPROPERTYSINGLEVALUE('BuildingEnergyTargetValue', $, IFCREAL(0.), $);` which looks OK to me?

**Comment by aothms** [comment] 2022-09-20 11:19
Yes, so my guess is this is the first selected simpletype you're trying to emit. How did you create those?

**Comment by Moult** [comment] 2022-09-20 11:26
It's created using the migrate utility.

```
output = ifcopenshell.file()
infile = ifcopenshell.open('/path/to/2x3.ifc')
migrator = ifcopenshell.util.schema.Migrator()
new = migrator.migrate(infile.by_id(253332), output)
print(new) # this works fine
```

The only difference between the borked version and the working snippet is that the borked version is a full migration of every element: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcpatch/ifcpatch/recipes/Migrate.py#L31-L36

**Comment by Moult** [comment] 2022-09-20 11:31
A note that if you want to test the full migration you'll need to modify the code a little to allow invalid data:

Delete these lines https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/util/schema.py#L222-L223

Change to return self.default_entities.get(attribute.name(), None) https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/util/schema.py#L252

Change https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/util/schema.py#L217 to if value is not None: setattr(new_element, attribute.name(), value)

**Comment by aothms** [comment] 2022-09-20 12:11
Scanning through the code I guess it's something related to not really accounting for simple types (remember id=0). Not sure if it's something that can be fixed in the Migrator code.

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/util/schema.py#L127

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/util/schema.py#L209

What happens if you don't store anything in `migrated_ids` for id=0?

**Closed** 2022-09-20 12:46 UTC

**Comment by Moult** [comment] 2022-09-20 12:48
You're absolutely right! It's the id=0 issue. Reading through the code again, I have no idea how this worked previously, since the migrator code was written back in 2020 (before I knew about id=0) and I've been running this on large, complex Revit produced IFCs regularly for the past 2 years. I can't believe I'm only running into this now.

Weird :) Thanks so much!

**Comment by Damian-Coutts** [comment] 2022-11-07 03:11
I am seeing a similar issue with a file that contains some large mesh elements.
''' 4622 def write(self, fn):
   4623     """write(file self, std::string const & fn)"""
-> 4624     return _ifcopenshell_wrapper.file_write(self, fn)

RuntimeError: Reading outside of file limits

Can you guys please explain the id=0 issue?

**Comment by Moult** [comment] 2022-11-07 04:09
In a shared call we worked out that the source file by @Damian-Coutts contained:

```
#4134=IFCPROPERTYSINGLEVALUE('Feature Definition',$,IFCTEXT('Mesh\Earthworks\Topsoil Fill'),$);
```

This is an invalid IFC encoding so a quick search/replace \ with \\ fixed it.

**Comment by aothms** [comment] 2022-11-07 07:44
https://github.com/IfcOpenShell/step-file-parser might also help here as it can validate the express text encoding sequences.

**Comment by Damian-Coutts** [comment] 2022-11-07 09:00
That looks usefuil.
It seems to me the
```
RuntimeError: Reading outside of file limits
```
happens when the file hasn't been completely parsed, but the error is reported on file_write() (or to_string())
