### ISSUE TITLE
I am getting errors using IfcConvert.exe 

### ISSUE THREAD

**Issue by webdada** [IfcOpenShell/IfcOpenShell#168] opened 2016-12-01 14:06 UTC
Not sure what the following error means and how to correct it. I can open the Ifc file in Solibri Viewer without issue. 

C:\tools\IfcConvert-0.4.0-rc2-win64>IfcConvert.exe ABC.ifc ABC.dae
Scanning file...
Done scanning file
Creating geometry...
Done creating geometry

Log:
[Error] Failed to convert:
#1179630=IfcExtrudedAreaSolid(#1020183,#1161618,#3,2951.41766197325)

**Comment by Stinkfist0** [comment] 2016-12-01 14:44
The code for IfcConvert-0.4.0-rc2 is probably two years old - can you try building IfcConvert from the latest code yourself and see if the problem persists?

**Comment by aothms** [comment] 2016-12-09 15:36
In addition note that such an error does not necessarily mean something went less well than in Solibri. E.g. other viewers might silently discard instances that did not process successfully.

**Comment by aothms** [comment] 2017-04-03 13:28
Closing this issue. Feel free to reopen if you have more information.

**Closed by aothms** 2017-04-03 13:28 UTC

**Comment by webdada** [comment] 2017-04-03 13:32
Thank you - I will try the newer version of IfcConvert

Regards,

Sam

Sam

Email: dada.sam@gmail.com

Text:   (703) 794-5716

**Comment by ibrahimdh2** [comment] 2024-09-12 15:34
I built IFCConvert myself but still for some IFC models it says "There is no geometry" However, I was able to convert from the same ifc to .dae.

**Comment by aothms** [comment] 2024-09-12 16:10
> I built IFCConvert myself but still for some IFC models it says "There is no geometry" However, I was able to convert from the same ifc to .dae.

I would say this is logically not possible given how the code is organized,

https://github.com/IfcOpenShell/IfcOpenShell/blob/51211dc5275da21c2eb35f7bcd1be93d7bbf9b2c/src/ifcconvert/IfcConvert.cpp#L1017-L1021

Maybe it's different command line arguments affecting output?

**Comment by ibrahimdh2** [comment] 2024-09-15 13:29
I have tried with these command line arguments (I have tried on both Windows and Linux):

1. "./IfcConvert ./file.ifc   ./file.svg"

2. "./IfcConvert -v test.ifc test.svg --exclude entities IfcOpeningElement"

However, although I am able to generate proper collada models for the file but it doesn't generate .svg and says that there is no geometry:

"IfcOpenShell IFC2X3 IfcConvert 0.5.0-dev
Scanning file...
Done scanning file   

Log:
[Notice] include entities IfcSpace
[Error] No geometrical entities found
"

I managed to generate floorplans with python (although it is very slow) with this code :

`draw_settings = ifcopenshell.draw.draw_settings(auto_floorplan=True)
  output_data = ifcopenshell.draw.main(draw_settings, files=[ifc_file], merge_projection=False)`
  
  but the problem is it works for 2 MB ifc file  but for 18 MB ifc file even after an hour it doesn't produce anything, and if I pass a method as an argument to see the progress - although the progress is shown in both cases with small sized file and big sized file, it produces no output.

**Comment by aothms** [comment] 2024-09-20 11:58
By default IfcConvert does not do the projection of elements in front of the drawing plane, only the sections of those that intersect with the drawing plane. You can add `--svg-project` for that purpose. But as you observed it can be slow on detailed elements.

**Comment by ibrahimdh2** [comment] 2024-10-01 11:44
I tried with --svg-project flag but it still doesn't work
