### ISSUE TITLE
BBim - Annotation performance is very slow with smart tags?

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#4697] opened 2024-05-19 17:35 UTC
I have a project that has about 33 Ifc Spaces, 
after bulk tagging with a space tag the performance dropped dramatically with just those 33 tags.

Essentially dropping annotation performance to a crawl

I've attached an example IFC file

On Average with Smart tags & annotations on:

selecting an object takes 5 seconds
opening (pressing tab) to edit an annotation takes 5 seconds
closing (pressing tab) to get out of an edit takes 5 seconds
saving (after the pop up for lines) takes 5 seconds
activating the drawing takes 12 seconds
printing the drawing takes 12 seconds

With Dumb tags:

selecting an object takes < 1 seconds
opening (pressing tab) to edit an annotation takes < 1 second
closing (pressing tab) to get out of an edit takes < 1 second
saving (after the pop up for lines) takes < 1 second
activating the drawing takes < 1 second
printing the drawing takes 3 seconds

With No tags:

Activate is less than 1 second
print is less than 1 second

I believe the annotation performance was better in the past, I believe I've used it for a file with 150-300 smart tags before? so not certain what update changed the performance here, or perhaps I am mistaken haha.

It seems even with the smart tags not linked to anything they slow down the performance

Here is the Ifc file: (just rename to .ifc)

[Smart tag test.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/15370231/Smart.tag.test.txt)

edit to add the specs:

Windows 10
blender 4.1
blenderbim240519

**Comment by theoryshaw** [comment] 2024-05-19 21:01
might be related.
https://github.com/IfcOpenShell/IfcOpenShell/issues/4633

**Comment by Plae-Blue-Dot** [comment] 2024-05-19 22:03
That is definitely the culprit!

The lag is completely gone in the viewport and the print to SVG is actually faster! it's less than 1second

**Comment by Moult** [comment] 2024-05-20 02:50
Closing as duplicate of #4633.

**Closed by Moult** 2024-05-20 02:50 UTC
