### ISSUE TITLE
Warnings + Errors + Crash on that file

### ISSUE THREAD

**Issue by Vilo176** [IfcOpenShell/IfcOpenShell#1914] opened 2021-12-03 11:30 UTC
Hi Friends,

I'm facing many issues on that file.
This is not a complex IFC, but IfcOpSh seams to have trouble dealing with it.
I've also attached a log file produced by "IfcConvert.exe" before it crashes.
Maybe you'll have some more infos on what's going on with it.

XBimToolkit, that uses OCCT too, seams to have no problem with it.
I don't mean XBim is better (I've tested both XBim & IfOpSh and for now I would love to stay on IfOpSh), but it shows that this file can be successfully treated by mean of OCCT, probably with other tricks than IfcOpSh's ones.

Thanks a lot for your amazing toolkit !

[Test II.log](https://github.com/IfcOpenShell/IfcOpenShell/files/7649149/Test.II.log)
[Test II.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/7649141/Test.II.zip)

**Comment by aothms** [comment] 2021-12-03 13:53
I don't get any issues on a recent version of v0.7. Could be the occt version also which is 7.5 by default on the v0.7 branch. What version did you use?

**Comment by Vilo176** [comment] 2021-12-03 14:12
Hi aothms,

Thanks for your rapid answer & concern.
I've compiled IfcOpSh 0.7 under Windows + VS2019, with default scripts under "win".
The code version I'm using is not old, less than a month.
I've used "IfcConvert.exe" that is compiled under "IfcOpenShell-0.7.0\_installed-vs2019-x64\bin" after building process.

The fact you have no issue leads me to a compilation problem, but the process went well ...

**Comment by aothms** [comment] 2021-12-03 14:17
> less than a month.

It could be that you were just a bit unlucky. v0.7 had a bit of a rough start. One month ago was around the time we all jumped ship from 0.6 to 0.7 and there were a couple of loose ends. Could you try again after pullling the latest v0.7

**Comment by Vilo176** [comment] 2021-12-03 14:18
Yes I will retry with very latest code base.
I'll come back to let you know result.
Thanks again !

**Comment by Vilo176** [comment] 2021-12-03 15:35
Having a compilation issue ...
![image](https://user-images.githubusercontent.com/25245090/144629381-8cf144d7-c108-461b-9516-8fe457949c19.png)

Any idea ?

**Comment by aothms** [comment] 2021-12-03 19:47
Hm, apparently they forced push to that repo so the commit we were tracking doesn't exist anymore.

For now maybe quickest is to switch mpfr to my own local copy which still contains that commit: https://github.com/aothms/mpfr/commit/2ebbe10

You can change `BrianGladman` to `aothms` in the win/build-deps. If it works. Feel free to send in a PR. Others will soon run into this as well.

**Comment by Vilo176** [comment] 2021-12-04 10:11
Compilation OK => IfcConvert OK on file (with remaining errors, see log)
[Test IIb.log](https://github.com/IfcOpenShell/IfcOpenShell/files/7653729/Test.IIb.log)

**Comment by aothms** [comment] 2021-12-04 10:19
Unless you see clear visual differences, I wouldn't worry about the errors. IfcOpenShell can be a bit verbose in it's output. Do you send in a Pull Request for the build-deps changes?

**Comment by Vilo176** [comment] 2021-12-04 10:22
> Do you send in a Pull Request for the build-deps changes?

I haven't clone the git and thus cannot make PR (or maybe there are other means to do that ?).
So non I haven't ...

**Comment by aothms** [comment] 2021-12-04 10:23
Ah you can also edit it online https://docs.github.com/en/repositories/working-with-files/managing-files/editing-files

**Comment by Vilo176** [comment] 2021-12-04 10:43
After checking, I see that errors in log file are not false positives ...

Expected :

![image](https://user-images.githubusercontent.com/25245090/144706552-524a1ac0-af0b-45cc-bc56-9936b19f3362.png)

Obtained :
![image](https://user-images.githubusercontent.com/25245090/144706547-db22f802-fe8e-4e0c-841e-6d3bb62bacfa.png)

**Comment by Moult** [comment] 2021-12-08 22:56
I managed to replicate this in Blender but I'm not sure if this is a real bug. Yes, the opening (highlighted in orange) for the sliding door on the top floor aren't cut out fully out of the wall (only partially cut out) but the openings aren't a simple prism, they are made out of 4 extruded area solid items (for door rebates), which I assume need to be boolean unioned together prior to performing the opening void. I've duplicated the opening and shown it in an exploded view to help explain (all in orange).

![2021-12-09-095251_832x785_scrot](https://user-images.githubusercontent.com/88302/145304250-b39bdf06-a14b-48c7-9ef1-96dc54daf9f8.png)

**Comment by Vilo176** [comment] 2021-12-09 07:39
Thank you Moult for your investigations.

I guess the openings on floors 1/2 are the same "multi-layered" solids than on floor 3/4 ?
Because on floor 1/2 the cut is good.
The opening being layered should not be a problem as far as all layers are touching.

In OCCT, like in every geometry kernel, CSG are very (very very) sensible, and I know you are aware of that.
I've not dug very far in IfcOpSh code, but my guess is that the CSG tree has to be narrow down as much as possible, because doing successive CSG always leads to multiplicative errors.

Other thing, OCCT introduced the "Fuzzy" parameter in CSG, and theoretically it seams to make CSG more reliable, but after months of testing it deeply, I can say this is not the case at all.
Fuzzy can improve robustness in some cases, and degrade it other times. It's a kind of lottery.

So, as far as CSG are concerned, I think that the number of effective CSG should be minimized :
- by merging all IfcOpeningElement before cutting a wall, or by using Arg/Tools paradigm of recent OCCT.
- by using a Fuzzy value calculated according to size of operands, so that Fuzzy is the highest value slightly beyond the minimal dimension of operands (for example minimal edge length of all solids), to avoid operand collapse and self-intersection acquirement.
- When possible, cutting operand should be enlarged to avoid floating point issue (for example when doing half space cutting).

Thanks again Moult

**Comment by aothms** [comment] 2021-12-10 08:28
@Vilo176 it sounds like you know your stuff around booleans and occt. Any help here is greatly appreciated.

Going over some of the points you mentioned:

Yes we do use fuzziness with a multiple args invocation.

We exactly take into account the (1/3 of the) minimal edge length for an upper bound on the fuzziness

But we start with the precision in the IFC model and increase fuzziness to that upper bound until boolean result succeeds and is valid.

Valid means passing quite a bit of extra checks. Where we compare vertex-edge distance and face-face distance on the output. If these distances are small we retry with a higher fuzz. We also check manifoldness (but this gives some issues as sometimes the valid result is non-manifold).

We also sort openings based on their edge length. And apply them in batches of similar edge length. So that we can use a higher fuzz on the first batches. But also so that in case boolean fails mid way we at least have the most significant openings subtracted.

So as you can see there is already quite a bit of stuff going on. If you're interested I can point you to the relevant bits in the code. We currently have the following issues:

* These fixes and ideas are implemented over the coarse of the 10y history of ifcopenshell. We don't always know which fixes and workarounds are still relevant for newer versions of OCCT.
* The code is structured poorly, adhoc and not configurable.
* It would be interesting to know the performance overheads of all these pre-checks and post-checks.
* And probably many other things.
* I think there may also be general suboptimal tolerances coming out of the shape creation routines.

---

I'll find some time again to look into the issue with this particular wall.

**Comment by Vilo176** [comment] 2021-12-10 09:17
Thank you aothms for this pretty dense explanation.

I'm indeed pretty involved in IFC world for more than 20 years, and more specifically in the CAD world.
I've been fighting with all that stuff since 2001 (inside French BuildingSmart chapter), and implementing it for a french software editor.

As soon as somebody tries to deal with CSG, being with OCCT or not, he falls sooner or latter on the exact same issues.
Moreover, IFC "standard" (shouldn't have been accepted as a standard ...) is so permissive geometry wise, that working with it at "reader" side is really tough.

IfcOpSh is a pretty cool stuff, and if I have knowledge / time, I would be very very pleased to try to enhance it.
Maybe in a couple of months ...

That being said :

The most reliable way to check if an OCCT CSG is ok is ```BRepCheck_Analyzer(shape).IsValid();```
I'm taking that from OCCT dev themselves, others means are not reliable (including ```BOPAlgo_Options.HasWarnings``` / ```BOPAlgo_ArgumentAnalyzer```).

As far as Fuzzy is concerned, its value should always be less than 5E-5 (value from y own observations).
Setting Fuzzy higher, even on very large solids, leads to almost unpredictable results (vertex collapse, edge intersections, and many weird things).
Moreover, trying to play with Fuzzy value to make a failing CSG ok is a pretty tricky way, I'm yet to make it work reliably.

I've also tested the "jitter" method consisting of moving operands slightly is case of failure, to avoid floating point issues.
Total failure.
Same result by scaling up/down operands slightly.

It would be very interesting to have a discussion with OCCT staff on that, but this is not really possible without paying a lot ...

**Comment by aothms** [comment] 2021-12-11 08:14
> The most reliable way to check if an OCCT CSG is ok is BRepCheck_Analyzer(shape).IsValid();

We use that. But I think it's quite expensive performance wise.

> As far as Fuzzy is concerned, its value should always be less than 5E-5 (value from y own observations).

That I haven't seen. I can think of quite a few cases where 1e-1 finally resulted in the appropriate result. But yes I agree it's rather unpredictable.

> I've also tested the "jitter" method consisting of moving operands slightly is case of failure, to avoid floating point issues.

Perhaps I'd have more faith in a projection approach. Where you project 2nd operand vertices onto the faces of 1st operands. There's BRepAlgo_NormalProjection for that. But it'd might be tricky maintaining internal tolerances of 2nd operand shape.

> It would be very interesting to have a discussion with OCCT staff on that, but this is not really possible without paying a lot ...

One potential avenue there is that OCCT uses IfcOpenShell in one of their commercial offerings https://www.opencascade.com/components/ifc-import-component/ So this could be phrased as sth in their own best interest as well.

One last comment: we have also done quite a bit of work on a CGAL implementation of the geometry conversion functions https://github.com/tudelft3d/IfcOpenShell/tree/cgal It's quite a different approach (only polyhedral, not a lot of direct support for cad primitives). But their "exact computation" (= number type of binary trees of arbitrary precision operands) and exact predicates/constructions are really rock solid. All things discussed here like booleans under tolerance we need to implement ourselves though using dilation/scaling/snapping.

**Comment by Vilo176** [comment] 2021-12-11 09:56
CGAL framework is really powerful, and can indeed deal well with floating numbers errors thanks to its exact kernels.
But the final phase "rational geometry" => "floating point geometry" is error prone.
Moreover, the whole process is very slow.

I don't think it is a real alternative to OCCT for IFC management.

There are a few other attempts to make robust CSG kernels (Libigl / TetWild / EPUG / ...).
I've tested all, but all these products are not well suited for production, and I've always ended up returning to OCCT, despite its limitations.

I didn't know IfcOpSh was used by OCCT for their IFC comp ... very interesting !
Is it a fork or a direct usage ?

**Comment by aothms** [comment] 2021-12-11 10:12
> I don't think it is a real alternative to OCCT for IFC management.

I'm not entirely sure yet about it either. I have mixed feelings. But I think some sort of hybrid between occt and cgal, with fallback and user configurable sounds quite powerful.

> Is it a fork or a direct usage ?

They aren't very clear about it, tbh I don't know.

**Comment by Vilo176** [comment] 2021-12-11 10:25
Giving end user the possibility to choose strategy is always a good thing.

According to me, the most promising approach would be to leverage the fact that, while importing an IFC, we know before doing the CSG what we are trying to do.

For example, a CSG could be needed to cut a hole in a wall.
Is that very case, we can try to adapt operands to limit errors, by enlarging the IfcOpeningElement in the direction of the width of the wall.
Of course this is not always possible, and should be done wisely.

Another thing that could be done : when a solid is represented as a CSG tree, we can reduce the tree before doing the actual CSG.
For example if we want to cut a wall B with 3 openings C / D / E, we end up with the tree :
A = (((B - C) - D) - E)
This tree should be reduced to A = B - (C + D + E)
There are not many cases to deal with, but this can greatly improve robustness.

Maybe your are already doing these kind of tweaks ?

**Comment by aothms** [comment] 2021-12-11 11:02
>  A = (((B - C) - D) - E)
> This tree should be reduced to A = B - (C + D + E)

Yes, we do this, we collect all 2nd operands of the csg tree and feed it into the multi arg opencascade option. Not very generally, only when all operations are subtractions.

https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcgeom/IfcGeomShapes.cpp#L566-L598

But strangely, this performed very poorly on many halfspace subtractions, so we have set some arbitrary limit there.

>  Is that very case, we can try to adapt operands to limit errors, by enlarging the IfcOpeningElement in the direction of the width of the wall.

This is exactly what we do in our CGAL impl (or more precisely an application that uses the ifopsh cgal impl), where we use a Minkowski sum of Opening x Edge to enlarge the opening where Edge is an nef polyhedron of a line segment orthogonal to the wall axis. Conceptually great, but soooo slow, especially on non-convex cases.

Yes and we have an additional check we can do that if the IfcOpeningElement ObjectType is 'Opening' the surface genus of the result needs to be affected. Unfortunately the distinction Opening/Recess isn't assigned very consistently.

Generally what most viewers do though is do these kind of openings in 2D (when possible). It's so much more efficient to have an additional inner bound on the face and extrude that, than do the boolean subtraction in 3D. We have similar bits implemented in the CGAL implementation, but not in OCCT, which is really a shame.

**Comment by aothms** [comment] 2021-12-15 12:37
I committed a fix for this case. It remains a bit like stacking work-around onto work-around. And the question is whether #1472 deserves such as pronounced code path. But the issue is solved now.

The issue was that applying openings is batches sorted by min edge length, due to the layered openings, caused an initial inner void, which was then supposed to be connected to the outer shell as a true opening by the 2nd batch of opening layers. However, This first result was flagged as invalid due to the logic for #1472. This logic is now tied specifically only to non-closed first operands.

**Comment by Vilo176** [comment] 2021-12-15 13:28
Great news Thomas,

I'm not sure to fully understand the whole thing, but it seams that some boolean operands are not Solid themselves, but rather a bunch of faces forming an opened Shell ?
And the "missing face" of that opened Shell is part of another boolean operand of the same batch ?
The whole batch forming a valid watertight Solid (with inner faces) ?

If this is the case, why not :
1. List all operands that are to be cut from wall
2a. If all operands are valid watertight solid/shell, perform the CSG
2b. If at least one of them is not watertight, perform a MakerVolume with all the faces involved, and cut the wall with the result

Maybe I'm completely missing the point out ...

**Comment by Moult** [comment] 2023-02-14 03:00
For some closure it seems everything works well now:

![2023-02-14-140003_1158x736_scrot](https://user-images.githubusercontent.com/88302/218627947-21304213-8f6b-4567-ba01-8d8b02f429fe.png)

**Closed by Moult** 2023-02-14 03:00 UTC
