### ISSUE TITLE
ifcStairs bug  - RuntimeError: Unable to find keyword in schema: STRAIGHT

### ISSUE THREAD

**Issue by imparpaulo** [IfcOpenShell/IfcOpenShell#5869] opened 2024-12-10 17:01 UTC
```
os: Linux
os_version: #9-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct 14 13:19:59 UTC 2024
python_version: 3.11.9
architecture: ('64bit', 'ELF')
machine: x86_64
processor: x86_64
blender_version: 4.3.0
bonsai_version: 0.8.0
bonsai_commit_hash: None
last_actions: 
# operator: BIM_OT_enable_add_type
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_add_type
# ifcopenshell.api: root.create_entity
>>> {"ifc_class": "IfcStairType", "predefined_type": "STRAIGHT_RUN_STAIR", "name": "ESCADAS 1"}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# operator: BIM_OT_add_stair
# ifcopenshell.api: pset.add_pset
>>> {"product": {"cast_type": "entity_instance", "value": 1443, "Name": "ESCADAS 1"}, "name": "BBIM_Stair"}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: pset.edit_pset
>>> {"pset": {"cast_type": "entity_instance", "value": 1444, "Name": "BBIM_Stair"}, "properties": "{'Data': IfcText('{\"stair_type\": \"CONCRETE\", \"width\": 1.2000000476837158, \"height\": 1.0, \"number_of_treads\": 6, \"tread_run\": 0.30000001192092896, \"nosing_length\": 0.0, \"nosing_depth\": 0.0, \"base_slab_depth\": 0.25, \"top_slab_depth\": 0.25, \"has_top_nib\": true, \"tread_depth\": 0.25, \"custom_first_last_tread_run\": [0.0, 0.0]}')}"}
last_error: Traceback (most recent call last):
  File "/home/paulo/.config/blender/4.3/extensions/.local/lib/python3.11/site-packages/bonsai/bim/ifc.py", line 408, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paulo/.config/blender/4.3/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/type/operator.py", line 448, in _execute
    bpy.ops.bim.add_stair()
  File "/snap/blender/5562/4.3/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/home/paulo/.config/blender/4.3/extensions/.local/lib/python3.11/site-packages/bonsai/bim/ifc.py", line 408, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paulo/.config/blender/4.3/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/model/stair.py", line 221, in _execute
    update_ifc_stair_props(obj)
  File "/home/paulo/.config/blender/4.3/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/model/stair.py", line 97, in update_ifc_stair_props
    element.PredefinedType = "STRAIGHT"
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paulo/.config/blender/4.3/extensions/.local/lib/python3.11/site-packages/ifcopenshell/entity_instance.py", line 325, in __setattr__
    self[index] = value
    ~~~~^^^^^^^
  File "/home/paulo/.config/blender/4.3/extensions/.local/lib/python3.11/site-packages/ifcopenshell/entity_instance.py", line 361, in __setitem__
    self.method_list[idx](self.wrapped_data, idx, entity_instance.unwrap_value(value))
  File "/home/paulo/.config/blender/4.3/extensions/.local/lib/python3.11/site-packages/ifcopenshell/ifcopenshell_wrapper.py", line 6583, in setArgumentAsString
    return _ifcopenshell_wrapper.entity_instance_setArgumentAsString(self, i, a)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Unable to find keyword in schema: STRAIGHT
Location: /snap/blender/5562/4.3/scripts/modules/bpy/ops.py:109


ifc: TESTE 2.ifc
schema: IFC4
preprocessor_version: IfcOpenShell 0.8.0
originating_system: Bonsai 0.8.0

Does someone know how to fix this issue?
Thank you
```

**Comment by Andrej730** [comment] 2024-12-11 08:14
Duplicate of #5261, fixed in the latest build from the releases - https://github.com/IfcOpenShell/IfcOpenShell/releases/tag/bonsai-0.8.1-alpha2412101311

**Closed as completed by Andrej730** 2024-12-11 08:14 UTC
Labels: Bonsai
