### ISSUE TITLE
BlenderBIM SQLalchemy v2.0+ 

### ISSUE THREAD

**Issue by OrionSehn** [IfcOpenShell/IfcOpenShell#4258] opened 2024-01-26 16:40 UTC
Hello

I just want to put on the radar moving forward the BlenderBIM SQLalchemy dependency to 2.0+ 
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/97123736/06949488-df36-4e31-95da-1fa57cd9310a)

> this is the dependency in the latest release

Just because the new version of SQLalchemy supports operations like pushing to databases with UUID types, and this is specifically useful for people who want to have that sort of functionality in scripts. 

I'm not sure where this dependency is defined for BlenderBIM, otherwise I'd do it myself. I figured it might be around here somewhere? but I don't see it, is it a dependency for an older pandas version?

https://github.com/IfcOpenShell/IfcOpenShell/blob/0da3270c7f18259b09ee8c3795082e0a7a8162c9/src/blenderbim/Makefile#L429

**Comment by Moult** [comment] 2024-01-27 10:57
I vaguely recall SQLAlchemy is a sub-dependency of Brickschema.

**Comment by Moult** [comment] 2024-01-28 21:44
Ping @gtfierro - here's the dependency which currently is locked to <v2.0.

https://github.com/BrickSchema/py-brickschema/blob/master/pyproject.toml#L29-L30

**Comment by OrionSehn** [comment] 2024-01-29 15:07
Thanks For chasing this down <3 I might try and make a PR for that on that repo, but maybe we should close this issue here, cause its a issue with a dependent repo?

**Comment by gtfierro** [comment] 2024-01-30 17:04
Thanks for the heads up @Moult and @OrionSehn ! The dependency is via https://github.com/RDFLib/rdflib-sqlalchemy, which I've noticed is in maintenance mode. I'll have to look into what it takes to bump the SQLalchemy dependency, perhaps through a fork of rdflib-sqlalchemy. It may be easier for me to swap the brickschema persistence solution to a different database (like oxigraph) rather than a SQL database, so let me know if that would be preferred. If you would like to stick with a SQL-based persistence implementation then this may take a bit longer to fix due to having to upgrade rdflib-sqlalchemy. Let me know!

**Comment by OrionSehn** [comment] 2024-01-30 17:32
I'd mostly be interested in the faster solution. I can always just go import the later version of SQLalchemy. Conflicting versions of the same library between two different add-ons is a kind of nightmare I'd rather avoid.

**Comment by gtfierro** [comment] 2024-02-10 00:21
Hey @OrionSehn wanted to give you a quick update! The direct dependency of `brickschema` which itself uses SQLAlchemy is `rdflib-sqlalchemy`, which is now in maintenance mode and suck on SQLAlchemy `<2.0`. I've created my own fork which updates the SQLAlchemy API usage to work with 2.0, and I have https://github.com/BrickSchema/py-brickschema/pull/109 outstanding to see if the changes I made work ok with `brickschema`. This will allow you to update your dependency while we continue to iron out challenges/migration issues in working with SQLAlchemy 2.0 . I'll ping you when the PR is merged and the new release of `brickschema` is published!

**Comment by OrionSehn** [comment] 2024-02-10 00:50
@gtfierro You're my hero, thank you so much for taking this up and following up on this. I appreciate the update and am eagerly looking forward to when that PR is merged. 

Again, I can't thank you enough.

**Comment by OrionSehn** [comment] 2024-03-14 20:53
@Moult 
Was this ever resolved for your guys's dependency chain?

**Comment by Moult** [comment] 2024-03-15 00:40
I have some uncommitted code which bumps the dep but let's leave this open until I can confirm.

**Comment by OrionSehn** [comment] 2024-03-26 14:54
I noticed that the latest build has sqlalchemy 2.0+ included

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/97123736/ae6be40b-5f61-421e-b6e6-f1d5cbb53ed3)

Has this issue been resolved then? or should we wait until the next release to close this?

**Closed** 2024-03-26 21:25 UTC
Labels: BlenderBIM
