### ISSUE TITLE
HDF5 cache became invalid after a binary update ?

### ISSUE THREAD

**Issue by CyrilWaechter** [IfcOpenShell/IfcOpenShell#2147] opened 2022-04-17 09:35 UTC
Approximate steps to reproduce (I'll try to reproduce more consistently next time I get binary update):
1. compile ifcopenshell on ??? (unknown commit unfortunately but I saw c++ changes, maybe hdf5 related changes ?)
2. Import an ifc file => successful
3. compile ifcopenshell on [6fb3c28](https://github.com/IfcOpenShell/IfcOpenShell/commit/6fb3c28f1a72055dada5906a919743d88c5d19be)
5. Import ifc file from step 1 => get stuck and never complete

Workaround: delete hdf5 cache in `~/.config/blender/3.1/scripts/addons/blenderbim/bim/data/cache/`

If it is an issue that occurs always when there is a binary upgrade maybe there is a way to check binary version against the one used to generate hdf5 cache to auto clear cache ?

**Comment by Moult** [comment] 2022-04-17 09:54
Hmm possibly a duplicate of #2143 and https://github.com/IfcOpenShell/IfcOpenShell/issues/2053#issuecomment-1079877716

I really need to figure out how to narrow this down to a test case so that @aothms can replicate it.

If you disable strict tolerance both at import as well as in the cache does that help?

**Comment by Moult** [comment] 2022-05-04 23:56
OK, sorry for the delay but I managed to replicate this. The main reason I've been delaying doing a public release is due to this bug so hopefully this fixes it.

I think the problem is that I reuse the cache for multiple iterators. The iterator for 3D has strict tolerance enabled but the iterator for 2D (include_curves=True) didn't have strict tolerance enabled whereas the cache does have strict tolerance enabled and so it got upset and hung.

I managed to replicate the hang:

I use the script here: https://github.com/IfcOpenShell/IfcOpenShell/issues/2081#issuecomment-1094404953
I edit the script to use this IFC file: [untitled.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/8627984/untitled.ifc.txt)
I am using this build: https://github.com/IfcOpenBot/IfcOpenShell/commit/1b1fd1e6c5777cb27ca3a65357855421a8e77bf9 (I would use a later one, but this is the latest one available for public users cross platform)

```
$ python standalone_blender_import.py
Created #2011=IfcAnnotation('0xxWkokEL16x$vAME_F_bN',$,'EAST ELEVATION',$,'DRAWING',#2152,#2022)
Created #1350=IfcOpeningElement('3D5FU0qAXEugKdOI$mlGBn',$,'Opening',$,$,#1516,#1368,$,$)
Created #1148=IfcWall('3mI9VQn69CB8yqBqn3wOsC',$,'Wall',$,$,#1441,#1199,$,$)
Created #2667=IfcBeam('1ECt_K7EbDMgshB5$QZUqk',$,'Beam',$,$,#2779,#2689,$,$)
[ ... snip ... ]
Done creating geometry
Created #1901=IfcAnnotation('0HMyhZ3QrEugm20OMT6Ps3',$,'IfcAnnotation/NORTH SECTION',$,'SECTION',#2041,#1911)
Created #2573=IfcAnnotation('1MoZ$NeCT0cx8m4PRPAvWX',$,'HIDDEN_LINE',$,'HIDDEN_LINE',#2588,#2583)
Created #2265=IfcAnnotation('3epDUg6LXFQOflz1DnnD$0',$,'01',$,'GRID',#2270,#2275)
[ ... snip ... ]
Done creating geometry

$ python standalone_blender_import.py
Created #1350=IfcOpeningElement('3D5FU0qAXEugKdOI$mlGBn',$,'Opening',$,$,#1516,#1368,$,$)
Created #1148=IfcWall('3mI9VQn69CB8yqBqn3wOsC',$,'Wall',$,$,#1441,#1199,$,$)
Created #1843=IfcOpeningElement('0A7jCWtpPAvxft$BeDgjAK',$,'Opening',$,$,#6895,#1861,$,$)
Created #2011=IfcAnnotation('0xxWkokEL16x$vAME_F_bN',$,'EAST ELEVATION',$,'DRAWING',#2152,#2022)
Created #2691=IfcBeam('1aztMnV$TClx4uSlRIMYn_',$,'Beam',$,$,#2784,#2713,$,$)
Created #2715=IfcBeam('2Rv89jfbv6UxSvIn6F4dev',$,'Beam',$,$,#2823,#2730,$,$)
Created #1036=IfcWall('0J7AA1mGn1rfC9IKKf_RxS',$,'Wall',$,$,#1375,#1089,$,$)
Created #1203=IfcWall('1ygtPJuFv9gwIsPx8EZLES',$,'Wall',$,$,#1523,#1235,$,$)
[ ... snip ... ]
Done creating geometry
********* at this point it hangs, notice how it successfully does
^C^C^C[1]    17164 bus error  python standalone_blender_import.py
```

So... treating this as fixed unless it pops up again.

**Closed** 2022-05-04 23:58 UTC
Labels: bug, BlenderBIM
