### ISSUE TITLE
IfcConvert project appears without color, but in BlenderBIM has.

### ISSUE THREAD

**Issue by csritter** [IfcOpenShell/IfcOpenShell#5075] opened 2024-07-24 15:19 UTC
Hi, I have a project where the colors appear correctly in BlenderBIM, but when I use IfcConvert, the project has no color (just gray).

Using IfcConvert:
![image](https://github.com/user-attachments/assets/08a6d1c3-4454-436a-928d-9a1edbf08474)

BlenderBIM:
![image](https://github.com/user-attachments/assets/07ccbd90-2432-4d52-820c-cf8cd37dc9d6)

IfcConvert version 0.8.0, commit 8b29e50f11da2730a19d21327c22a257d0434c9e
BlenderBIM version 240602

I will send an email with the project to @aothms and @Moult already to speed it up.
I hope you don't mind.

**Comment by Moult** [comment] 2024-07-25 12:26
So this is an interesting one and something most people aren't aware of. It's basically a duplicate of #2509 but long story short what IfcConvert is doing is actually correct - it's showing the rendering diffuse colour, which is defined oddly enough as a normalised ratio of 0 (e.g. always black).

So in Blender, if you switch from regular solid viewport shading to a rendered mode, you'll see that Blender also displays everything (correctly) as black! In the screenshot below you can see the black result in rendered mode, the top left shows the non-rendered pink colour, the top right shows the glTF compatible shader definition in your IFC, and the right hand side shows the original IFC definition where you'll notice that SurfaceColour is pink (slightly cut off) and DiffuseColour is an IfcNormalisedRatioMeasure of 0 (therefore 0 multiplied by anything is black).

![2024-07-25-222311_1580x1034_scrot](https://github.com/user-attachments/assets/980eca70-3825-4a4a-a7a9-7554ce955375)

**Closed by Moult** 2024-07-25 12:26 UTC

**Comment by csritter** [comment] 2024-07-25 18:40
From what I understand, @aothms had the idea of ​​adding a flag to get the surface colors, but apparently, nothing was implemented.
Would you have any suggestions on how to get this using the C++ Serializer (like GlbSerializer) or Python?

**Comment by Moult** [comment] 2024-07-25 23:17
In Python it's really straightforward, prior to running [serialisation to glb](https://docs.ifcopenshell.org/ifcopenshell-python/geometry_processing.html#geometry-serialisation) do something like:

```python
for style in ifc_file.by_type("IfcSurfaceStyleRendering"):
    style.DiffuseColour = style.SurfaceColour
```

**Comment by aothms** [comment] 2024-07-26 00:41
In v0.8 implementing a command line flag to trigger this behaviour is also much more straightforward. If you define something in conversionsettings.h it's immediately exposed as a setting and available in mapping.cpp L505 where the IFC data regarding styles is mapped to our "taxonomy". Contributions very welcome :)

**Comment by csritter** [comment] 2024-07-26 18:27
I'll take a look. If I can understand and apply it, I will make a PR.
Thank you for the tips.

**Comment by csritter** [comment] 2024-08-23 18:27
@aothms I did a PR and did some tests and I think it's working well. Can you or some contributor check for any issues or suggestions?
