### ISSUE TITLE
Replacing the opencdeserver code with code from the Kontroll OpenCDE API:s project

### ISSUE THREAD

**Issue by marwiss** [IfcOpenShell/IfcOpenShell#4276] opened 2024-01-31 18:03 UTC
With a notice to @aothms, as discussed with @Moult, and as mentioned on OsArch...

...about replacing the opencdeserver code in:

[https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.7.0/src/opencdeserver](https://github.com/IfcOpenShell/IfcOpenShell/tree/v0.7.0/src/opencdeserver)

...with code from the Kontroll OpenCDE API:s project on:

[https://github.com/marwiss/kontroll](https://github.com/marwiss/kontroll)

I made a pull request from a fork to merge the code into upstream. The PR is located here:

https://github.com/IfcOpenShell/IfcOpenShell/pull/4289

The Kontroll OpenCDE API:s project is a functional implementation in python of all three buildingSMART OpenCDE API:s such as BCF API, Foundation API and Documents API. Neo4J is used as database. OAuth2 is also implemented using Neo4J.

According to @Moult the next step would be to send a pull request for review.

Then I (@marwiss) should ask to be added to the dev list, so I can continue working directly on this project in the future.

I created a fork, commited the code changes, and made pull request.

I am interested to see how the Kontroll project could integrate with IfcOpenShell and BlenderBIM. The Kontroll API:s project is a server implementing buildingSMART open API:s. In the future maybe BlenderBIM could be used as a client to access this server. And the server could be adapted to support BlenderBIM better. The server could run both on localhost and on remote for collaboration.

The Kontroll OpenCDE API:s project have AGPL license. This AGPL license should be kept.

Please be aware that the code was produced as a POC just to test some idéas. This means that some documentation is lacking, some features are lacking, and that some refactoring of the code would help.

Summary:

1. @marwiss would like to be added to the dev list.

2. Will make a pull request of the code on https://github.com/marwiss/kontroll.

3. The license of this code should be AGPL.

Best regards,
Martin

**Comment by Moult** [comment] 2024-01-31 21:56
This is the process to create a PR :)

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

It would be awesome to replace the current barebones and "barely functional" opencdeserver with a real implementation! Also writing down ideas for more integration before I forget:

 - Integration with BBIM to run a local CDE to collaborate or manage issues locally
 - Integration with IfcFM for document handover with the document API

**Comment by Moult** [comment] 2024-02-04 03:54
Ping @aothms - Martin has been building a server implementation of OpenCDE and I mentioned that it might be worth considering building it under the IfcOpenShell umbrella with the usual logic (lots of potential integration with the OpenCDE client code we already have, Blender UI, and potential further integration with IfcTester / IfcClash results, and of course visibility to other devs who can help contribute and tie everything together nicely).

We also already have code in src/opencdeserver (which is really bad, unmaintained, barebones barely functional implementation only good for minimal testing). So I figured that his code could supersede it.

But of course this is:

 1. A Big PR.
 2. The usual argument between monorepos/multiple repos.

Thoughts?

**Comment by aothms** [comment] 2024-02-05 08:42
Sounds like plan! Thank you @marwiss for your work and your interest in maintaining it as part of the ifcopenshell project.

I think it makes sense especially if we seriously start integrating this into blenderbim. I think we also really need to priorititize some guidance on collaborative usage of blenderbim / ifcopenshell. Contrast ifcgit / opencde / ifc-db (@Krande https://github.com/Krande/ifcdb) so that we can help users decide. I'm probably rushing things here I know, but we should come up with a vision I think.

**Comment by Krande** [comment] 2024-02-05 09:43
Really interesting stuff @marwiss! 

@aothms, by all means, feel free to rush (otherwise, nothing gets done) :) 

Regarding Ifcdb, it's been a while since I worked on it. Lately, I have been spending a lot of time trying to make Code Aster (a free and open source finite element solver) available as a conda package. So I haven't gotten a chance to see if the EdgeDB Team have solved some of the issues I raised way back then. I know they've issued a ton of new releases since I worked with it, so maybe it has solved some of the larger inefficiencies regarding schema creation. 

But if I recall correctly, the biggest hurdle for me wasn't necessarily regarding the database implementation itself, but perhaps more regarding schema-complexities related to synchronizing partial updates of an IFC project. Ie. serializing to/from the database and doing queries was easy. But synchronizing partial changes from local IFC sources without relying on the numeric STEP ID required some work to "anchor" updates of non-rooted elements to their "rooted element parents". 

I think it is solvable, but it does require more time and focus to establish a robust and more generalized partial change sync workflow.

I think also @Moult made some progress on using SQLITE as a database for IFC inside BlenderBIM? It would probably be a good idea to try to summarize some of the experiences we've had so far in storing IFC in databases, and try to make a vision/road map for how it might get solved?

**Comment by aothms** [comment] 2024-02-05 10:06
Should we write a paper? E.g https://cibw78-conference.org/

I think we have a lot to compare:
- rdbms (sqlite)
- schema graph (edgedb) 
- generic graph (arrangodb)
- git
- opencde

@Krande Did you consider applying @Moult's approach in sqlite to the edgedb backend? Just have a drop in replacement basically for ifcopenshell.file? That way we can plug it into blenderbim almost seamlessly? What would it take to make that work? Can be pure python.

**Comment by marwiss** [comment] 2024-02-05 13:26
We are discussing at least two aspects to compare, at the same time.

1. One topic is how to store the IFC data on the database. This will determine how difficult it is to create, query and manipulate this data directly in the db, it will determine the possibility to validate data against a schema, and it will determine the performance of the db.

2. The other topic is how to communicate with the database. This will determine what kind of collaboration is possible and it will determine what clients are supported.

One benefit of a server implementing open standards for the API (such as the buildingSMART OpenCDE API:s) is that people will be able to use various clients to connect to the same server, to access the same kind of data in predictable ways.

Just like IFC was created to enable multiple software companies to work on the same building information data (instead of using proprietary file formats) I guess we also like to support the idea of using open standards for API as much as possible.

The API does not care how data is stored. But it seems like many people agree that IFC data generally have some kind of graph structures, so it makes sense to store IFC data in some kind of graph database. This will enable easy query and more complex analysis of data (without having to generate extremely complex SQL-query with dozens of joins).

When it comes to creating a production environment for a server, important factors to consider are: up-time, performance, reliability. It is also important to find developers who can maintain and develop the server or integrate it with other services. This means a problem for databases that are too new, too unknown, too small or esoteric. This is a general problem for all graph databases compared to the more well known relational database technology.

Neo4j is the most established graph database with most users. The con of Neo4j is the lack of a schema and the lack of strict typing. This doesn't matter as long as you don't need to perform editing and validation directly in the database.

Personally I think that schema validation and strict typing for IFC data is a good idea. But it is probably not easy or maybe not possible to implement the full Express schema in any graph database. I was thinking of using C++ object store instead: https://en.wikipedia.org/wiki/ObjectStore. But didn't have time to evaluate this.

There are some options for graph databases:

ArangoDB
TypeDB
OrientDB
Redis graph
And many many more...
And then you have triple stores 

The problem is that most of them implement their own query language. Neo4j on the other hand uses cypher as query language and has supported the adoption of cypher as open standard. https://opencypher.org/ Some other graph databases have implemented parts of cypher. For example Redis graph. Soon we will have an ISO graph query language(GQL)  standard: https://www.gqlstandards.org/ and it will be inspired by cypher.

We could separate the project into MVC. The database and schema is the domain/model (M). The client or viewer (such as BlenderBIM or IFC.js is the view (V). And the API is the controller (C).

I think it is a good idea to store the IFC data in EdgeDB, or in any graph database with a schema, such as TypeDB. However, I doubt that we will be able to implement the full EXPRESS schemas directly into any existing graph database. And then maybe the schema doesn't matter anyway. I think that Neo4j has some benefits just because it is a relatively well known technology. There are many other projects out there that want to be able to use neo4j. For example: https://community.osarch.org/discussion/1653/topologicpy-to-neo4j-and-back-to-topologicpy

It could be possible to implement an API that can choose between EdgeDB or Neo4j at the same time. Just like SQLAlchemy is db-agnostic. I decided to use Neo4j just because it is well know and I wanted to get the POC done as fast as possible. I would be happy to implement the OpenCDE API:s with EdgeDB as well.

STEP text file storage is also a good option. It only makes sense to use a database if you have a system that need to frequently read IFC data from many buildings. Otherwise I guess you will just parse the STEP file with IfcOpenShell as normal, read the data, do the analysis, manipulate the STEP file, and then write the file to disk and close the file again.

**Comment by Moult** [comment] 2024-02-05 22:55
Hehehe we should also write this paper https://github.com/IfcOpenShell/IfcOpenShell/issues/3245

**Comment by marwiss** [comment] 2024-02-06 19:01
I was looking at Memgraph DB. It can load data from Neo4j, implements the same open cypher query language as Neo4j, but is written in C/C++, can load modules written in python/C/C++, and the cypher can be extended by user defined procedures written in python/C/C++. Thinking about the possibility to integrate IfcOpenShell directly into the database itself.

https://memgraph.com/docs/custom-query-modules/python

**Comment by aothms** [comment] 2024-02-07 08:22
> can load modules written in python/C/C++, and the cypher can be extended by user defined procedures written in python/C/C++. 

Yes, you have similar options for example using some of the Java based RDF stores. But these direct integrations come with downsides. You have to invest a lot effort in bundling very platform specific logic, whereas in a lot of cases you can also materialize directly in the graph that what you would otherwise calculate adhoc. You also remove the freedom for endusers to choose their own platform/tooling. I would really advocate for data interfaces not code interfaces in these kind of ecosystems.

> Thinking about a scenario where IfcOpenShell can be used in "graph-database-mode" where creating and updating Ifc python objects using IfcOpenShell, will create and update the graph database immediately, without the need to send any cypher queries.

I think that is indeed the aim we should work towards at some point. For 10y I already want to attempt something like that with sparql, but never found the time. This day and age there are probably better suited and more performant graph databases, such as your example, edgedb or dgraph.

> Personally I think that schema validation and strict strong typing for IFC data is a good idea. But it is probably not easy or maybe not possible to implement the full EXPRESS schema in any graph database schema. I was thinking of using a C++ object store instead: https://en.wikipedia.org/wiki/ObjectStore. But didn't have time to evaluate this concept for the POC.

This is indeed the core of the topic. And it's hard to move forward on this, because experiments take a lot of effort and without them it's impossible to verify.

Whether the database / object store needs to do schema validation is also an interesting topic. But there are two sides to this as well. The simple forward attribute types are easiest to assert, but are also not typically wrongly populated. The more complex validation criteria such as domain where rules and functions and maybe inverse attribute cardinalities are likely hard to implement within the database and might also really hinder collaborative editing if always enforced, but are ultimately most valuable for assessing the intergrity of the final product.

For me the biggest gains from offloading storage to a (graph) database server is:

- partial loading (currently entire model is read from disk; general purpose access on streaming data is hard on spf)
- multi-user interaction

So as far as I'm concerned storage doesn't necessarily even need to be graph based. It can also be a distributed key-value store (apache ignite?) and implement the logic in C++ in ifcopenshell.

**Comment by marwiss** [comment] 2024-02-07 19:45
Partial loading - this is of course nice, but I can't remember that any of the OpenCDE API:s were tailored for that purpose. Might have to implement this as a feature outside the standard Documents API specification. BCF API have a deprecated "BIM snippet" endpoint for partial editing of IFC that never was implemented by any software, due to IFC mainly used for exports (up until BlenderBIM).

Multi user interaction - yes, this is what the Documents API and BCF API is all about.

It seems like your use case is aiming at partial loading of, and collaboration on, one very large project at a time. In this case I guess ignite can work well, as in-memory cache, for partial loading.

I was interested in a different use case. Imagine a system (such as a BIM-server) that could potentially store tens of thousands of projects. Where you might want to frequently query for small bits of information (such as some properties of some IfcSlab objects) from hundreds of projects (or from alla projects), simultaneously, without having to repeatedly, frequently and completely parse hundreds or thousands of step text files simultaneously (just to be able to read those tiny bits of information). In this case you probably need disk storage.

Graph databases are nice when you want to find specific information from data with lots of relationships, or when you want to analyse the structure of the data directly in the database using a query language. For example, some spatial structure. I guess you don't need this feature if you just want partial loading.

It will be a lot of work to convert the project to apache ignite, but it is not necessary to avoid cypher and graph databases in order to achieve in-memory caching and partial loading.

- For example, memgraph can run in in-memory storage mode, just like apache ignite. Memgraph can also run in disk storage mode. https://memgraph.com/docs/fundamentals/storage-memory-usage

- Memgraph use the same openCypher query language as Neo4j. This means existing code already works (no extra work needed). It will be easier to switch between many different graph database products in the future if openCypher is used. https://opencypher.org/projects/ EdgeDB and Dgraph instead use their own unique query languages.

- I like that Memgraph cypher can potentially be extended with python and C++, because IfcOpenShell is using python and C++ already.
 
My suggestion is to keep using any openCypher-compliant database (such as Neo4j or Memgraph), to be able to use any openCypher/GQL-compliant graph database also in the future. This could be an in-memory database like Memgraph, or a database that reads from the disk like Neo4j.

**Comment by aothms** [comment] 2024-02-08 08:12
> handle queries from thousands of projects simultaneously

I like that use case. This is for sure where I know that IfcOWL stored triple models will fall flat on their face performance wise. I don't know about the property graph databases.

There is something else though. Ultimately these models will all be disjoint graphs. Even if they relate to e.g the same material, these will be separate materials stored in disjoint graphs. This is also my main critique with all the conceptual RDF use cases, people always talk about how powerful it is to be able to establish arbitrary links, but in the end nobody is going to actually do that manually. And doing so programatically is equilly difficult, perforamance wise, but also ontologically, expressing these kind of equivalences has really far stretching implications on e.g inference.

Also, the ability to be able to ask arbitrary graph queries on composite project data sounds compelling, but in the end there is only a handful of people being able to compose such queries and you have to account in your queries for all the various modelling idioms and varieties that IFC offers. It's an inconsistent mess that you need to unify **in** your query.

I think, currently, the most feasible approach to this is to have a batch processing script, analyse the files and output in simplified unified form the kind of metrics you're interested in.

That said, I don't want to slow you down in any way if you want to explore these ideas. I would happily collaborate on them, but since you mentioned production environments, I personally think this direction is more on the academic front, but equally interesting.

**Comment by marwiss** [comment] 2024-02-08 20:38
The semantic web, is an interesting set of technologies, but the software I tested (jena fuseki) was not user friendly to deploy in production. Seems like jena fuseki is mostly used by academia.

I did not intend to develop yet another ontology that reasoners can use to infer new knowledge (new triples) from rdf. I think that technology is more interesting for building knowledge graphs.

Open data in itself is a good thing, even though the tools are mostly used by academia. But open data can be achieved also using LPG. You can egen make some data from LPG available as RDF if you wish. https://neo4j.com/labs/neosemantics/

On the other hand I think LPG databases can deliver such performance if necessary. Especially if running in a distributed clusters. Here are some examples.

https://memgraph.com/blog/handling-large-graph-datasets
https://www.tigergraph.com/blog/trillion-edges-benchmark-new-world-record-beyond-100tb-by-tigergraph-and-amd-epyc/
https://neo4j.com/press-releases/neo4j-scales-trillion-plus-relationship-graph/

**Comment by aothms** [comment] 2024-04-02 07:55
@marwiss I saw your GSOC of code proposal text. Very cool. Only comment would be to remember that gsoc participants come from a wide vartiety of backgrounds. I would take a couple more sentences to explain:

- BIM as recent paradigm shift to exchange information on construction assets in a standardized fashion that enables many novel use cases
- IFC as the predominant open  standard to do so
- BlenderBIM and the significance of open source BIM in democratizing access to built asset information and NativeIFC to operate on such models without data loss
- What is currently missing in terms of API / networked access / etc.

Also remember to set the labels so that the issue is correctly categorized.

**Comment by Moult** [comment] 2024-05-11 10:24
Closing as original topic seems to be resolved, great discussion here though :)

**Closed by Moult** 2024-05-11 10:24 UTC
Labels: BCF
