### ISSUE TITLE
Geometry iterator returns incorrect material list

### ISSUE THREAD

**Issue by cvillagrasa** [IfcOpenShell/IfcOpenShell#1377] opened 2021-03-11 13:39 UTC
Hi! I was trying to use BlenderBIM as a viz tool, and get the following error message when importing an IFC from Istram:
```python
File "C:\Users\CarlosV\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blenderbim\bim\import_ifc.py", line 128, in assign_material_slots_to_faces
  slot_index = [self.canonicalise_material_name(s.name) for s in obj.material_slots].index(material)
ValueError: '22599' is not in list
```

I guess there is something wrong with materials in this actual IFC...

I leave the issue in case it makes sense for BlenderBIM to deal with whatever problem the file has.

[19-117-L2_CAT_PB05_F-R-V0069_MOD_VIL_JPF1-AP01.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/6123296/19-117-L2_CAT_PB05_F-R-V0069_MOD_VIL_JPF1-AP01.zip)

Thanks in advance!

**Comment by Moult** [comment] 2021-03-13 11:19
Ping @aothms - with the test file provided by @cvillagrasa , I suspect the issue is that the geometry iterator is returning incorrect results. Minimal code:

```
import ifcopenshell
import ifcopenshell.geom

f = ifcopenshell.open("/home/dion/surfacestyle.ifc")
s = ifcopenshell.geom.settings()

e = f.by_id(22955)
shape = ifcopenshell.geom.create_shape(s, e)
print(e)
print([m.name for m in shape.geometry.materials])

iterator = ifcopenshell.geom.iterator(s, f)
iterator.initialize()
while True:
    shape = iterator.get()
    if shape.guid == e.GlobalId:
        print(f.by_guid(shape.guid))
        print([m.name for m in shape.geometry.materials])
        break
    if not iterator.next():
        break
```

Ouput:

```
#22955=IfcBuildingElementProxy('00Cm04054p8G0500000002',#5,'VIL_SEN_SVE','','VIL_SEN_SHO',#22962,#22957,$,.ELEMENT.)
['surface-style-22683', 'surface-style-22708', 'surface-style-22733', 'surface-style-22770', 'surface-style-22798', 'surface-style-22874', 'surface-style-22899', 'surface-style-22936', 'surface-style-22952']
#22955=IfcBuildingElementProxy('00Cm04054p8G0500000002',#5,'VIL_SEN_SVE','','VIL_SEN_SHO',#22962,#22957,$,.ELEMENT.)
['surface-style-22599']
```

The first output, from create_shape, looks good. The second, the style `22599` has no relationship. Not sure where it's coming from.

**Comment by cvillagrasa-tec4** [comment] 2021-03-16 15:13
Hi @Moult and @aothms , I really don't know much yet about the internals of the IFC schema, so I barely follow the two approaches to get geometry materials from _IfcBuildingElementProxy_ with ID 22955.

However, I've tried [https://view.ifcopenshell.org/](https://view.ifcopenshell.org/) and the model does display, even if with these two errors for two _IfcLocalPlacement_:

```
() not valid for <inverse PlacesObject: set [1:1] of <entity IfcProduct> for <attribute ObjectPlacement?: <entity IfcObjectPlacement>>> | #7475=IfcLocalPlacement(#7464,#7474)
() not valid for <inverse PlacesObject: set [1:1] of <entity IfcProduct> for <attribute ObjectPlacement?: <entity IfcObjectPlacement>>> | #7457=IfcLocalPlacement($,#7456)
```

Does that help to isolate the importing issue or is non-related?

**Comment by Moult** [comment] 2021-03-16 21:42
@cvillagrasa-tec4 I cannot see a relationship, but perhaps I'm wrong :) This one unfortunately is out of my field right now - hopefully @aothms can replicate using the code sample and offer some insights.

**Comment by aothms** [comment] 2021-03-20 12:50
Well, one thing that doesn't help is that there are three elements with that guid. So when you check `shape.guid == e.GlobalId` you break early. When I test on numeric ID I get the same output for create_shape() and iterator. See updated script below, does that help?

	Line 22609: #22602=IFCBUILDINGELEMENTPROXY('00Cm04054p8G0500000002',#5,'VIL_SEN_SVE','','VIL_SEN_SHO',#22609,#22604,$,.ELEMENT.);
	Line 22660: #22653=IFCBUILDINGELEMENTPROXY('00Cm04054p8G0500000002',#5,'VIL_SEN_SVE','','VIL_SEN_SHO',#22660,#22655,$,.ELEMENT.);
	Line 22962: #22955=IFCBUILDINGELEMENTPROXY('00Cm04054p8G0500000002',#5,'VIL_SEN_SVE','','VIL_SEN_SHO',#22962,#22957,$,.ELEMENT.);


```
import ifcopenshell
import ifcopenshell.geom

f = ifcopenshell.open("19-117-L2_CAT_PB05_F-R-V0069_MOD_VIL_JPF1-AP01.ifc")
s = ifcopenshell.geom.settings()

e = f.by_id(22955)
shape = ifcopenshell.geom.create_shape(s, e)
print(e)
print([m.name for m in shape.geometry.materials])

iterator = ifcopenshell.geom.iterator(s, f)
iterator.initialize()
while True:
    shape = iterator.get()
    if shape.id == e.id():
        print(f.by_guid(shape.guid))
        print([m.name for m in shape.geometry.materials])
        break
    if not iterator.next():
        break
```

**Comment by cvillagrasa** [comment] 2021-03-20 15:20
Thank you @aothms!, I will check whether the fact of ending up with three different elements with the same guid is either a bug in the software (Istram) or a result of a particular wrong workflow.

With a very gross overview of this part of the BlenderBIM code from far away, I have the intuition that with a proper file with unique guids, _material_ in [import_ifc.py#L113-L122](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcblenderexport/blenderbim/bim/import_ifc.py#L113-L122) will point to the expected material and _slot_index_ just won't be -1.

I let @Moult confirm in case I am missing something before closing.

**Comment by Moult** [comment] 2021-03-21 00:12
Aaah you're right I completely missed that the GlobalId wasn't unique. In that case, it is not a bug with IfcOpenShell :)

Closing issue. Yes @cvillagrasa I expect that with a valid file, you shouldn't come across this issue.

**Closed by Moult** 2021-03-21 00:12 UTC
