### ISSUE TITLE
Remove svg faceting/triangulation from round surfaces

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#4536] opened 2024-04-09 16:47 UTC
I'm sure this is the roadmap, and thought there was an issue for it, but can't find it, but would be nice to remove the faceting/triangulation from round surfaces....

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/bf97d5e0-0e13-4992-8b1a-cdbdfc622eee)
 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/bcedb7b3-3a70-4156-9caf-f89292e0faf4)

Newbie question: I wonder, could there be a way in the svg processing to iterate through all the paths, and remove those paths that are internal?

![2024-04-09_11-35-36_chromeERDGESCHOSS_PLAN svg_-_Google_Chromechrome](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/4cddbd9f-fe8d-4eaf-9b07-ceb182dda8dc)

**Comment by theoryshaw** [comment] 2024-04-09 17:00
> I wonder, could there be a way in the svg processing to iterate through all the paths, and remove those paths that are internal?

or perhaps give those 'inner' and 'outer' paths a designated css, so their visibility can be controlled. 

Because i can see wanting to control closed paths when using 'Calculate Shapely Surfaces'.

**Comment by Moult** [comment] 2024-04-09 22:36
This is a duplicate of #3668

**Closed by Moult** 2024-04-09 22:36 UTC
Labels: BlenderBIM
