### ISSUE TITLE
Bonsai - Bug when opening an exsisting Perspective view  (+ 'NoneType' object has no attribute 'remove' bug)

### ISSUE THREAD

**Issue by jes-r** [IfcOpenShell/IfcOpenShell#5412] opened 2024-09-18 12:05 UTC
Hi,

I can't open a persepctive view that's made in a previous session and saved in Ifc.

Steps:

- Create new project
- Save it
- Add walls
- Create persepctive drawing and move it a bit around (my tests were all done with views that were not parallel to an axis)
- Create drawing (in my second test nothing showed up but ok, might be something else)
- Save Ifc
- Reopen Ifc
- Open the perspective drawing
- Get this error:

Python: Traceback (most recent call last):
  File "C:\Users\Gebruiker\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 1791, in invoke
    return self.execute(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gebruiker\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 1806, in execute
    core.activate_drawing_view(tool.Ifc, tool.Blender, tool.Drawing, drawing=drawing)
  File "C:\Users\Gebruiker\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\core\drawing.py", line 488, in activate_drawing_view
    camera = drawing_tool.import_drawing(drawing)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gebruiker\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\drawing.py", line 696, in import_drawing
    camera = tool.Loader.create_camera(drawing, representation, shape)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gebruiker\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\loader.py", line 695, in create_camera
    width = max(x) - min(x)
            ^^^^^^
ValueError: max() arg is an empty sequence

In my tests I did create sheets and generated them before saving and reopening the Ifc, but I think thats not connected.

Another error/ bug is the "AttributeError: 'NoneType' object has no attribute 'remove'" error that frequently (almost always but not always) shows up when I click print. It doesnt print the drawing but if I click print drawing again most times it would let me. I have a feeling it happens more often after I just edited an object. 

The error:

- Python: Traceback (most recent call last):
  File "C:\Users\Gebruiker\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 272, in execute
    linework_svg = self.generate_linework(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gebruiker\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 720, in generate_linework
    [cache.remove(guid) for guid in invalidated_guids]
  File "C:\Users\Gebruiker\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 720, in <listcomp>
    [cache.remove(guid) for guid in invalidated_guids]
     ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'remove'

**Comment by Moult** [comment] 2024-09-18 12:16
The first is fixed in #5241. The second is a duplicate of #5395.

**Closed by Moult** 2024-09-18 12:16 UTC
Labels: Bonsai
