### ISSUE TITLE
Deleting the ifcopeningelement along with the deleting the ifcdoor/window

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2572] opened 2022-11-07 14:17 UTC
It current UI approach, it would seem if you hit shift-g after deleting a window/door in a wall, that the corresponding ifcopeningelement would also be deleted as well.

Perhaps i'm missing something.

**Comment by theoryshaw** [comment] 2022-11-07 14:46
hmm.. the void is deleted in 3.2 w/ .221107,
but does not in 3.3. w/ .221107.

**Comment by theoryshaw** [comment] 2022-11-09 16:23
I narrowed this problem down to CAD_Sketcher.  Not sure what the problem is.
should i close?

**Comment by Moult** [comment] 2023-03-05 00:21
This is most likely a duplicate of #2645 .

**Closed by Moult** 2023-03-05 00:21 UTC
Labels: BlenderBIM
