### ISSUE TITLE
Crash in Blender on import with "Process relations" enabled

### ISSUE THREAD

**Issue by janoc** [IfcOpenShell/IfcOpenShell#368] opened 2018-04-10 09:28 UTC
Hello, 

It seems that the Blender importer does not work correctly when the "Process relations" option is enabled. 

While importing the file http://www.ifcwiki.org/images/e/e3/AC20-FZK-Haus.ifc I get the following crash in the Swig wrappers:

Traceback (most recent call last):
  File "C:\Users\jciger\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_import_scene_ifc\__init__.py", line 264, in execute
    if not import_ifc(self.filepath, self.use_names, self.process_relations, self.blender_booleans):
  File "C:\Users\jciger\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_import_scene_ifc\__init__.py", line 181, in import_ifc
    parent_ob = iterator.getObject(parent_id)
  File "C:\Users\jciger\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\io_import_scene_ifc\ifcopenshell\ifcopenshell_wrapper.py", line 451, in getObject
    return _ifcopenshell_wrapper.iterator_double_precision_getObject(self, id)
RuntimeError: An unknown error occurred

location: <unknown location>:-1

The scene is imported incorrectly, the parts of the house are in wrong places. 

With the option disabled the import succeeds but there is no hierarchy preserved (all objects are parented to the root of the scene).

**Comment by aothms** [comment] 2018-04-11 09:35
This is a duplicate of #261 Two options are discussed there (a) using IfcConvert with DAE output which results into a correct hierarchy when imported into blender or (b) make a small modification to the .py source until new releases are distributed. Let me know if you need additional assistance.

**Closed by aothms** 2018-04-11 09:35 UTC
