### ISSUE TITLE
Header reset after upgrade from IFC2x3 to IFC4

### ISSUE THREAD

**Issue by mrfcoelho** [IfcOpenShell/IfcOpenShell#5903] opened 2024-12-22 21:32 UTC
Hi,
just upgraded a project from IC2x3 to IFC4. After opening it, when I try to edit the project info, the error below pops up. It led me to suspect that the author name was missing which was the case. However, it was also missing in the original project and this error was not showing when I tried to edit its project info. This should be a minor bug, still maybe someone can take a look at it.  Thanks!

Log below:
```
Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\project\operator.py", line 577, in execute
    author = self.file.wrapped_data.header.file_name.author
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 7988, in author
    return _ifcopenshell_wrapper.FileName_author(self, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Type held at index 2 is class Blank and not class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > >
```

**Comment by Andrej730** [comment] 2024-12-23 07:40
@mrfcoelho 

The error is duplicate of #5246, fixed in the latest release from https://github.com/IfcOpenShell/IfcOpenShell/releases/

But there was another issue - ifcpatch Migrate (that's used for upgrading IFC file) wasn't migrating the header, should be fixed now. Thank you for the bug report.

**Closed as completed** 2024-12-23 07:45 UTC
Labels: Bonsai
