### ISSUE TITLE
[IfcConvert] Geometry issue

### ISSUE THREAD

**Issue by ketourneau** [IfcOpenShell/IfcOpenShell#4012] opened 2023-11-14 09:58 UTC
We got some issue with a customer's file when we convert it with IfcConvert to dae file.

It seems that we got some extra geometry when we convert the ifc file.

This is what we got in dae file :
<img width="786" alt="Capture d’écran 2023-11-14 à 10 43 24" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/39763266/79a87bc7-0fcb-4fda-83fb-b1329a32197f">

This is what we expect :
<img width="937" alt="Capture d’écran 2023-11-14 à 10 43 53" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/39763266/f83ae5cc-8759-4dd6-9f30-f523f8444ad1">

For exemple, we see some extra "box geometry" for object id "201IcoiaD1nOLoLPTIMSM3"

<img width="310" alt="Capture d’écran 2023-11-14 à 10 52 21" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/39763266/e3d5c422-7052-4b7a-bc75-9e2f7cf2442c">

We convert ifc file with the command :
```
IfcConvert --use-world-coords --center-model-geometry --use-element-guids file.ifc file.dae
```

[file.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/13347253/file.ifc.zip)

Can you explain why we got those geometries ?
Is there a way to delete those geometries using another command or parameter ?
We search for related issues but find none if this ring a bell please forward us to any issue.

**Comment by aothms** [comment] 2023-11-14 10:02
This is likely a duplicate of https://github.com/IfcOpenShell/IfcOpenShell/issues/2044

See where this is introduced https://github.com/IfcOpenShell/IfcOpenShell/pull/1743

We always had the suspicion this would lead to these kind of issues. My proposal in https://github.com/IfcOpenShell/IfcOpenShell/issues/2044 is to come up with some IfcConvert command line argument to specifically enable IfcBoundingBox conversion and otherwise simply not emit them.

**Comment by ketourneau** [comment] 2023-11-14 10:09
Ok thanks @aothms 
We will see if we can make a PR with the fix

**Comment by aothms** [comment] 2023-11-14 10:44
>  We will see if we can make a PR with the fix

The approach we have been considering so far is based on the command line flag, in IfcConvert.cpp loop over the IfcBoundingBox (or IfcShapeRepresentation[RepresentationType=BoundingBox]) and delete them from the file, prior to invoking the iterator. This saves a bunch of effort having to propagate these settings which is still very messy in 0.7, but which I'm streamlining in v0.8.

**Comment by aothms** [comment] 2023-11-14 15:55
No that's currently only for IfcProduct subtypes, such as IfcWall. Not for
the representation items such as IfcExtrudedAreaSolid or IfcBoundingBox. It
could be extended, but I don't know whether that would make sense for end
users. In that case I recommend v0.8 only. I'll post some details once the
settings refactoring is completed in that branch.

Sent from a mobile device, excuse my brevity. Kind regards, Thomas

Op di 14 nov. 2023 16:09 schreef Etourneau Kévin ***@***.***>:

**Comment by ketourneau** [comment] 2023-11-15 08:30
We tried to see what we can do but we don't have enough c++ skills to modify IfcConvert 😢

**Comment by Pourfex** [comment] 2023-11-15 10:30
For those who want to have an easy fix of ifc files using ifcopenshell (python script)
- pip install ifcopenshell
- create input folder with all ifc files you want to convert
- ``` import ifcopenshell
import os

for (_,_,files) in os.walk('./input', topdown=True):
    for file in files:
        file_name, file_extension = os.path.splitext(file)
        if(file_extension =='.ifc'):
            f = ifcopenshell.open("input/"+file_name+".ifc")

            for bbox in [
                rep
                for rep in f.by_type("IfcShapeRepresentation")
                if rep.RepresentationType == "BoundingBox"
            ]:
                f.remove(bbox)
            f.write("output/"+file_name+".ifc")
```
Get them from output folder.

**Comment by aothms** [comment] 2024-02-18 13:04
Sorry for the delay on this. With the latest commit the default is now to exclude bounding boxes. There is an option --keep-bounding-boxes to retain the old behaviour. This is implemented by actually going into the file in memory and removing the occurences of bounding boxes as it saves the trouble of propagating the settings all the way through the code base and is authored in a way to prevent error messages.

**Closed by aothms** 2024-02-18 13:04 UTC
Labels: IfcConvert
