### ISSUE TITLE
Not loading on macOS with Blender version 4.2

### ISSUE THREAD

**Issue by cesarecaoduro** [IfcOpenShell/IfcOpenShell#5058] opened 2024-07-22 04:47 UTC
I am trying to run blenderbim on macos and I am receiving this error...

```extensions.blender.org: [Errno 2] No such file or directory: '/Users/cesarecaoduro/Library/Application Support/Blender/4.2/extensions/blender_org'```

<img width="1094" alt="image" src="https://github.com/user-attachments/assets/b224eb8c-6276-414d-8b92-edfdac4f6069">

Any suggestions?

**Comment by Moult** [comment] 2024-07-22 05:19
Blender 4.2 has a different way of handling extensions and the current stable release only supports Blender <=4.1.

Duplicate of #4373 #4981.

In theory, latest daily builds do work on Blender 4.2 now, but there are still a few ongoing changes so I don't recommend using it. Also Blender has an issue where it seems to not properly uninstall so you need to manually clean things in certain scenarios so it's best to wait for the dust to settle a bit.

**Closed by Moult** 2024-07-22 05:19 UTC
Labels: BlenderBIM

**Comment by Andrej730** [comment] 2024-07-22 05:23
You can try this for 240602 - https://github.com/IfcOpenShell/IfcOpenShell/issues/4373#issuecomment-2242113593
