### ISSUE TITLE
Wall regen missing in horz. menu

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5445] opened 2024-09-22 13:55 UTC
Wall regen missing in horz. menu...

![image](https://github.com/user-attachments/assets/5458b7be-446a-4191-87dc-59ebd76a7518)

**Comment by trhyder** [comment] 2024-09-22 17:30
Hey @theoryshaw, the intention, at this stage, is for the Header and N-panels to be the same (except for labeling).

In working on the icons, I noticed that some properties were shared between the active tool and the selected object, so I separated them and added a new section label for the selected object tools. The regen fields are further over to the right.

<img width="2045" alt="image" src="https://github.com/user-attachments/assets/48621a0e-5230-48ae-8bb8-480daf0162fc">

The header layout on your screen capture looks different to mine, specifically, the field that has  "DIAGRAMATIC WALL" seems to take up a lot of space. Do you have any idea why it is so large?

**Comment by theoryshaw** [comment] 2024-09-22 18:33
> Do you have any idea why it is so large?
i'm not sure. 

Seems like would clean up the interface if these 2 areas were consolidated into one.  Perhaps i'm missing something. 

![image](https://github.com/user-attachments/assets/3a44b63b-75ac-4c0e-96b9-21700db2f017)

**Comment by trhyder** [comment] 2024-09-22 18:53
In my view, the issue is that the Wall Tool serves two purposes: it provides a UI for drawing new walls and a UI for modifying any selected object, not just walls.

For example, if you have the Slab Tool active and a wall object selected (as shown in my screenshot), would you expect the input fields to be tied to the Slab Tool for placing a new slab, or to the Wall Tool for modifying the selected object?

Perhaps modifying selected objects should be a separate tool?

**Comment by theoryshaw** [comment] 2024-09-22 20:47
> Perhaps modifying selected objects should be a separate tool?

Maybe.  Currently it's a little confusing to me. 

...

Maybe it's worth bringing [this](https://github.com/IfcOpenShell/IfcOpenShell/issues/3707) up again.

Would it be possible for the UI to both accommodate changing selected types, as well as instantiating types?

Could see it be helpful to select a wall that was 10x10, and then you `bim.add_constr_type_instance` and the newly created wall was 10x10 as well. 

Maybe if you deselected the selected wall, and then `bim.add_constr_type_instance` then it would create a new wall with the parameters that were set before you selected the wall.  _(this is a subtle idea, that might not even be necessary however)_

**Comment by theoryshaw** [comment] 2024-09-22 21:00
Or simply when object(s) are selected the active tool UI, disappears.
And when nothing is selected the active tool, shows up.

**Comment by trhyder** [comment] 2024-09-23 01:03
Thanks for linking to the previous issue.

I agree that the current setup is a bit confusing and could definitely benefit from simplification.

It’s a tricky balance. As it stands, both the Door/Window Tool needs to be active, and a wall must be selected to insert doors or windows.

For your suggestion to work, which I think has potential, we’d need to rethink how doors and windows are added. One approach could be that when the “Add Door/Window” operator is triggered, it pauses and waits for a wall to be selected before completing the operation. This would preserve an intuitive process while supporting your idea for the active tool UI to disappear when an object is selected.

**Comment by Moult** [comment] 2024-09-23 01:14
I completely agree with both of you.

Only show Add or Edit. Don't show both at one time. Although we can (and do) show both and it's not a technical limitation, it's a really confusing UI. You'll notice there is now also the new Item mode, which also is mutually exclusive.

> One approach could be that when the “Add Door/Window” operator is triggered, it pauses and waits for a wall to be selected before completing the operation.

This is a beautiful solution and really intuitive. People expect to add a window, then click on the wall the window should be inserted into. The current situation (must preselect single wall, place 3D cursor, add window) is really, really bad and people need tutorials to get it right, and I always accidentally add windows without inserted them because I forget to select a wall or misclick. Ping @brunoperdigao - we can reuse the raycast / snapping selector for this.

**Comment by Moult** [comment] 2024-09-23 08:22
> ... the field that has "DIAGRAMATIC WALL" seems to take up a lot of space ...

This is because he likely has a a type which has a very long name, and so the dropdown interface expands to accommodate that long name.

This is now fixed in the latest commit which changes it into a launch button instead.

**Comment by Gorgious56** [comment] 2024-09-23 14:34
Is it possible to make the fields smaller ? It pushes the icons to the right and my header is to small to see them, I have to middle mouse-drag to get them and it resets every time I select an item. I don't have a 4K monitor :)

![image](https://github.com/user-attachments/assets/46d6b3b4-5a9b-49ee-a2c8-1f13c6a31563)


![image](https://github.com/user-attachments/assets/ba3f2348-e492-421a-9f24-0bf2ef263146)

**Closed** 2024-10-08 04:47 UTC
