### ISSUE TITLE
Blender 4.2 ModuleNotFoundError: No module named 'blenderbim'

### ISSUE THREAD

**Issue by GameAIMaster** [IfcOpenShell/IfcOpenShell#4981] opened 2024-07-05 09:41 UTC
os: Windows
os_version: 10.0.22621
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 183 Stepping 1, GenuineIntel
blender_version: 4.2.0 Beta
blenderbim_version: 0.0.240602
last_actions: 
last_error: Traceback (most recent call last):
  File "C:\Users\10105\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\blenderbim\__init__.py", line 96, in <module>
    import blenderbim.bim
ModuleNotFoundError: No module named 'blenderbim'

It is a Release version compiled from source code.

**Comment by Andrej730** [comment] 2024-07-05 11:11
@GameAIMaster Thanks for the report!

0.0.240602 doesn't work with Blender 4.2 as an extension, only BBIM versions after 1fc56585dd3b157f71fc4625d006ceebed1ef73e do.
So you can either install newer build (though daily builds are a bit broken atm, you can see when they will start working again in #4924) or install 0.0.240602 as a Legacy Blender addon.

How to install BBIM as a Legacy Blender addon in Blender 4.2
(legacy install is hidden and we'll need to locate it through Blender search):
1) Preferences -> Interface -> Developer Extras (make sure it is checked)
2) F3 (or Edit - Menu Search) -> Type "install addon" and select it
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/b69484c1-ae5e-4f4e-91de-747dc6363d70)
3) Select .zip with BBIM addon and install it
4) Preferences -> Addons -> Find "BlenderBIM" and enable it.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/3134bf5e-bb36-4834-b44d-8244c6077567)

**Comment by Moult** [comment] 2024-07-22 05:20
Closing as duplicate of #4373

**Closed by Moult** 2024-07-22 05:20 UTC
Labels: BlenderBIM
