### ISSUE TITLE
Nice number snapping in wall polyline tool

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#5436] opened 2024-09-21 05:28 UTC
Blender's default snap is "increment" snap. I.e. it snaps to a nice number like 1m, 2m, 3m, etc. If you are more zoomed in, the the snap increment is more granular like 1.1m, 1.2m, etc. I think the wall polyline tool should default to an increment snap enabled. Architects draw walls that have nice dimensions so that they can be built easily :)

Revit also has this feature by default when drawing walls. Not sure about ArchiCAD.

Currently if I want to draw a 3x3 room, I need to keep switching between my mouse and keyboard to type in the number 3. With incremental snap, I can just eyeball it with my mouse and guarantee that the wall will be 3m :)

**Comment by brunoperdigao** [comment] 2024-10-08 01:32
This feature should be implemented by c5f27e9 and 774791c.

**Comment by Moult** [comment] 2024-10-08 03:02
How do I test this? I just tried drawing a wall and didn't notice any change in the distance.

**Comment by brunoperdigao** [comment] 2024-10-08 11:58
I think the problem is that it doesn't work when you are locked to an axis or an angle. I should add this.
But, it should just be available when the tool is active:
![blender_dODLMNZDdi](https://github.com/user-attachments/assets/099c3362-fd16-4fa1-9660-83351b8e40a6)

**Comment by brunoperdigao** [comment] 2024-10-08 21:46
@Moult I've updated this feature, let me know if you fell it's better now. @theoryshaw I would appreciate if you could test this to see how it's working with imperial units.

**Comment by Moult** [comment] 2024-10-08 22:06
Ah yes now I'm starting to see it. If I zoom in when in perspective view, I am able to see the snap increment become more granular same as in your GIF, but if I'm in a top-down view even if I zoom in, the snap granularity doesn't change (different to your GIF).

**Comment by brunoperdigao** [comment] 2024-10-09 16:45
I've updated this with a new implementation. It's not snapping to the grid, but it is rounding distance and angle to nice numbers.
The rounding is still sensitive to the zoom, so in meters it rounds the distance in 1m intervals and in a closer zoom to 0.1m. It should work similarly for feet and inches.
If you type a specific number it will not be rounded.

**Comment by brunoperdigao** [comment] 2024-10-09 18:41
@theoryshaw Please, forget my previous GIF, it shouldn't snap to the grid anymore.
The idea is that the UI will only show "nice numbers", as Dion described in the original post. In imperial units,  I assumed those nice numbers would be inches, without fractions. If you want a specific number you can still type it. Does that make sense?

**Comment by brunoperdigao** [comment] 2024-10-09 18:48
One fix to be made, that is, if you click a snapping point, it should not round: https://github.com/IfcOpenShell/IfcOpenShell/issues/5545#issuecomment-2402987733

**Comment by brunoperdigao** [comment] 2024-10-09 18:49
Also, does it make sense to disable this feature for measure tool?

**Comment by theoryshaw** [comment] 2024-10-09 19:42
@brunoperdigao cool, i got the snapping to work!

**Comment by Moult** [comment] 2024-10-09 22:07
Awesome! Yes it's much more inline with the intention that designers generally draw walls with nice lengths and nice distances.

I'm experiencing a few issues:

 1. It sometimes too aggressively snaps to an angle.
 2. Nice angle snap is a bit too coarse, I'd say angle increments should be 5 degrees.
 3. Nice distance snap is also a bit too coarse. For example when it is snapping to the nearest 100mm, I mostly feel as though it should instead snap to the nearest 50mm or 10mm even.
 4. Object snaps should override nice number snapping


https://github.com/user-attachments/assets/8f78e7bd-ac52-4a0f-9c31-625ee416d358

**Comment by brunoperdigao** [comment] 2024-10-11 00:18
The last commits address those issue:
1. The angle snap should work as expected now. There was an error that was hard to spot, but I think I finally figure it out.
2. Done.
3. I added more "layers" and tried to improve the zoom threshold where the increment value changes. Let me know if you feel its better.
4. Done

**Comment by Moult** [comment] 2024-10-11 10:36
Really awesome! It's working much, much better now. I did somehow manage to trigger a couple errors (not sure yet how to reproduce predictably):

```
IndexError: list index out of range
Error: Python: Traceback (most recent call last):
  File "/home/dion/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/model/wall.py", line 335, in modal
    self.handle_mouse_move(context, event)
  File "/home/dion/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/model/polyline.py", line 352, in handle_mouse_move
    self.snapping_points = tool.Snap.select_snapping_points(context, event, self.tool_state, detected_snaps)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dion/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/tool/snap.py", line 496, in select_snapping_points
    mixed_snap = cls.mix_snap_and_axis(snapping_points[0], axis_start, axis_end)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dion/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/tool/snap.py", line 247, in mix_snap_and_axis
    return (sorted_intersections[0], "Mix"), (sorted_intersections[1], "Mix")
                                              ~~~~~~~~~~~~~~~~~~~~^^^

```

and this one:

```
A 
Traceback (most recent call last):
  File "/home/dion/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/model/decorator.py", line 588, in draw_measurements
    center = sum(polyline_verts, Vector()) / len(polyline_verts)  # Center between all polyline points
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: Vector division: divide by zero error
```

**Comment by brunoperdigao** [comment] 2024-10-11 13:39
Thanks, I fixed those.

**Comment by Moult** [comment] 2024-10-11 21:34
Super awesome :) Closing bug, I think it's now really, really slick!

**Comment by Moult** [comment] 2024-10-13 22:28
Agreed, this should be off for the measure tool.

**Comment by brunoperdigao** [comment] 2024-10-16 00:28
Done. f763e4b0a761a2ecc80c3fa89ba914c4bc3dcb3a

**Comment by Moult** [comment] 2024-10-16 01:34
I get this error when clicking measure tool in the UI or doing Shift-M?

```
Error: Python: Traceback (most recent call last):
  File "/home/dion/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/bonsai/bim/module/project/operator.py", line 2426, in modal
    self.handle_instructions(context)
TypeError: PolylineOperator.handle_instructions() missing 1 required positional argument: 'custom_instructions'
```

**Comment by brunoperdigao** [comment] 2024-10-16 02:23
Should be fixed now.

**Closed** 2024-11-08 19:30 UTC
Labels: Bonsai
