### ISSUE TITLE
Error after file open

### ISSUE THREAD

**Issue by EdgarWesterhoven** [IfcOpenShell/IfcOpenShell#5162] opened 2024-08-08 10:19 UTC
I have no clue what happened and posted the full error log.

I opened a file that has opened in the past ( 1 hr ago ) without issues. Now it does open but, with the red error message.

```
os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
blender_version: 4.2.0
blenderbim_version: 0.7.11-alpha240730
blenderbim_commit_hash: 2070071
last_actions: 
# ifcopenshell.api: grid.create_grid_axis
>>> {"axis_tag": "01", "uvw_axes": "VAxes", "grid": {"cast_type": "entity_instance", "value": 1478646, "Name": "Grid"}}
# ifcopenshell.api: grid.create_axis_curve
>>> {"axis_curve": "<bpy_struct, Object(\"IfcGridAxis/01.002\") at 0x00000249E36B3908>", "grid_axis": {"cast_type": "entity_instance", "value": 1478669, "Name": null}}
# ifcopenshell.api: grid.create_grid_axis
>>> {"axis_tag": "02", "uvw_axes": "VAxes", "grid": {"cast_type": "entity_instance", "value": 1478646, "Name": "Grid"}}
# ifcopenshell.api: grid.create_axis_curve
>>> {"axis_curve": "<bpy_struct, Object(\"IfcGridAxis/02.002\") at 0x00000249E385E408>", "grid_axis": {"cast_type": "entity_instance", "value": 1478673, "Name": null}}
# ifcopenshell.api: grid.create_grid_axis
>>> {"axis_tag": "03", "uvw_axes": "VAxes", "grid": {"cast_type": "entity_instance", "value": 1478646, "Name": "Grid"}}
# ifcopenshell.api: grid.create_axis_curve
>>> {"axis_curve": "<bpy_struct, Object(\"IfcGridAxis/03.002\") at 0x00000249E385F908>", "grid_axis": {"cast_type": "entity_instance", "value": 1478677, "Name": null}}
# operator: BIM_OT_save_project
# operator: BIM_OT_save_project
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_save_project
last_error: Traceback (most recent call last):
  File "C:\Users\xxxxx\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\blenderbim\bim\ifc.py", line 386, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\blenderbim\bim\module\project\operator.py", line 1307, in _execute
    ifc_exporter.export()
  File "C:\Users\xxxxxxx\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\blenderbim\bim\export_ifc.py", line 51, in export
    self.sync_all_objects()
  File "C:\Users\xxxxxxx\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\blenderbim\bim\export_ifc.py", line 102, in sync_all_objects
    result = self.sync_object_placement(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxxxx\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\blenderbim\bim\export_ifc.py", line 145, in sync_object_placement
    element = self.file.by_id(obj.BIMObjectProperties.ifc_definition_id)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxxx\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\file.py", line 463, in by_id
    return self[id]
           ~~~~^^^^
  File "C:\Users\xxxxxxx\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\file.py", line 448, in __getitem__
    return entity_instance(self.wrapped_data.by_id(key), self)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 8253, in by_id
    return _ifcopenshell_wrapper.file_by_id(self, id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Instance #1,316,826 not found

ifc: TOR-000-VPA-LifeSafety_240808.ifc
schema: IFC4
preprocessor_version: IfcOpenShell 0.7.11-alpha240730
originating_system: BlenderBIM 0.7.11-alpha240730-2070071
```

**Comment by Andrej730** [comment] 2024-08-08 10:37
Open or save? From the log it seems issue occurs when you save file file, not open - given the traceback and `BIM_OT_save_project` operator executed. 

See [common issues](https://docs.blenderbim.org/users/troubleshooting.html#common-issues) that describes why this might occur. So currently to resolve it you can reopen .ifc file instead of using .blend file. 

If you have some way to reproduce this - to make some object in .blend file to go out of sync with .ifc, then please share.

**Comment by EdgarWesterhoven** [comment] 2024-08-08 12:45
I was switching between models successfully all morning, cleaning up models ( grids ) here and there. So a save was definately part of it at some point. 

I tried to retrace my steps before sending the screenshot but without "success".

**Comment by Andrej730** [comment] 2024-09-01 06:11
I'll close this as this looks like .blend<->.ifc syncing issue. Feel free to reopen this if there will be any new information.

**Closed by Andrej730** 2024-09-01 06:11 UTC
Labels: Bonsai
