### ISSUE TITLE
BlenderBIM : Softlock on project creation when selecting an ifc file which doesn't exist yet

### ISSUE THREAD

**Issue by Gorgious56** [IfcOpenShell/IfcOpenShell#1597] opened 2021-07-27 13:14 UTC
Using BlenderBIM v 210726
I just created an ifc project. I Used the folder icon to locate where I want it to be stored. 
 
![image](https://user-images.githubusercontent.com/25156105/127159203-98e9df30-cd16-4784-99d3-1da309c510d4.png)

The operator let me do it but didn’t create a file. It complains that the file is not loaded. I go to File > Export > Ifc file but it throws a warning :
 
![image](https://user-images.githubusercontent.com/25156105/127159235-f99addce-b428-4b19-a8d5-8cb27d6b508e.png)

I’m effectively soft locked out of creating an ifc file. Unless I'm missing something ?

I found a workaround but there is a catch :
Delete the text entry with the file path.
Problem :
I’m back to step 1 and I’m asked to create a project, but the collection and files of the 1st aborted project are still there :

![image](https://user-images.githubusercontent.com/25156105/127159318-17ff602c-4cdb-4072-a351-5da5f7396b56.png)

 
If I click on the “Create Project” operator, all the objects and collections are duplicated and I don’t know which ones to use. I’m forced to go back to step 1 before I clicked the button for the first time if I want a clean slate.

![image](https://user-images.githubusercontent.com/25156105/127159349-14f3a693-7647-4185-85e7-a7be1550a73a.png)

 
Expected behaviour :

- Automatically create the file if I use the Folder icon when the path is not yet defined

OR

- Prevent me from using the folder icon (disable the operator)

Food for thought :

- Delete the hierarchy if we lose the connection to the ifc file ?

OR

- Automatically re-link everything if I create a new project and the correct hierarchy exists ?

**Comment by Moult** [comment] 2021-07-28 08:28
This could be a UX issue more than an actual bug. That filepath points to the IFC file, not the Blend file. It is created the first time you export your IFC. So it is blank because you haven't yet exported your IFC for the first time. You're not meant to set it manually, unless you move your IFC file or rename it.

Once you make a bunch of updates, instead of saving your Blender file, you need to export your IFC (File->[E]xport->[I]FC). That will synchronise everything between Blender and IFC, as well as save your Blend file in the process. Don't forget - your Blend file stores nothing at all ... everything is in the IFC.

So, auto creating the file - no, it happens explicitly when you press export. Using the folder icon is still useful in case you rename or move your IFC file, so it shouldn't be disabled. The hierarchy shouldn't be deleted, but indeed how it generates an overlapping hierarchy is definitely strange and unexpected behaviour, which I will fix. Auto relinking doesn't quite make sense as there is nothing to link to, as all data is in the IFC.

**Comment by Gorgious56** [comment] 2021-07-28 10:08
@Moult Thanks for the thorough explanation, It makes sense ! 
But I still think there is a problem in the behavior if I use the folder icon and choose a file which doesn't exist yet. I just realized my screenshot is confusing because it shows a .blend extension, but even if I type a .ifc (which doesn't exist yet), the operator executes correctly and the path is updated but then if I go to File > Export > ifc it throws an error message prompting me to create or import a project first, which I can't do at that point because the option is not there anymore.

Maybe don't set the path to a file which doesn't exist when using the folder icon (cancel the opertor) ? Or the error message that's displayed when using the File > Export > ifc needs to be reworked and instead create the file at the path that's been entered previously ?

**Comment by Moult** [comment] 2021-07-28 10:32
@Gorgious56 I like the idea that the file browse operator should not be allowed to select a non-existant file, I'm reopening the issue, and I think this is a great idea for another quick and easy contribution to make. This is where you want to make your change: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/blenderbim/blenderbim/bim/operator.py#L148

File->Export->IFC can never create a file at that path because File->export->IFC never actually creates data, it only serialises existing data that it already had in memory... and that data in memory comes from the IFC... which doesn't exist :)

**Comment by Gorgious56** [comment] 2021-07-29 07:02
Created PR :
https://github.com/IfcOpenShell/IfcOpenShell/pull/1604

**Comment by Moult** [comment] 2021-07-29 07:04
Great work! Merged and closed!

**Closed by Moult** 2021-07-29 07:04 UTC
Labels: BlenderBIM

**Comment by Gorgious56** [comment] 2021-07-29 08:57
@Moult Thanks :) 
I noticed while working on this that some (most) operators use `bpy.context` instead of the `context` provided by the `execute` method which may not be the same context depending on evaluation time, potentially leading to invalid context errors. 
Is it worth refactoring these operators to use the `execute` context ?

**Comment by Moult** [comment] 2021-07-29 10:04
@Gorgious56 yes indeed. When I first started coding this, it was the first add-on I had built for Blender. I'm sure there are plenty of simple mistakes you would recognise immediately :) Please do not hesitate to submit PRs for fixes!
