### ISSUE TITLE
ifcgeomserver Branch: v0.6.0 - exception thrown during geometry extraction

### ISSUE THREAD

**Issue by ArturSuchowierski** [IfcOpenShell/IfcOpenShell#500] opened 2018-11-07 14:27 UTC
The case described in the title appears only for this certain model, linked below (zipped, as I couldn't upload .ifc file here).
[171210PlayersTheater_param.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/2557642/171210PlayersTheater_param.ifc.zip)

 After uploading this .ifc file the app runs in following error: 

**org.bimserver.plugins.renderengine.RenderEngineException: Exited with non-zero exit code: 134**

 After this file gets done "rendering", its content displays as it was empty. This file actually runs on autodesk.

**Comment by aothms** [comment] 2018-11-14 15:48
Hi, I couldn't reproduce this using the most recent builds of the ifcopenshell tools, ie. [1]. Could also be that the issue is in the interaction between bimserver and ifcopenshell. Can you share a bit more on the details of your environment?

Also cc'ing @rubendel to see if you encountered this as well.

[1] https://github.com/IfcOpenBot/IfcOpenShell/commit/ba274bb1642d7be236199dbfa5031746aee10b3d#commitcomment-31291366

**Comment by rubendel** [comment] 2018-11-14 19:43
It was, this is fixed in the mentioned commit, will be in BIMserver 1.5.115.

There is only one remaining error that I couldn't solve. @aothms Any idea? IfcPlate 1xu4GXMcgPIgRDiscTSj6k is missing geometry. Other viewers do come up with something, I am probably still missing something.

[IfcPlate.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/2582367/IfcPlate.ifc.txt)

**Comment by ArturSuchowierski** [comment] 2018-11-16 13:40
Thanks guys for yours helpful response and quick feedback 👍

**Comment by aothms** [comment] 2018-11-19 10:51
> There is only one remaining error that I couldn't solve. @aothms Any idea? IfcPlate 1xu4GXMcgPIgRDiscTSj6k is missing geometry. Other viewers do come up with something, I am probably still missing something.

@rubendel that particular plate is an extrusion of the following polyline. After removing duplicate points, only two points remain. That is not a valid area definition according to IfcOpenShell. I think she's right ;)

~~~
#175=IFCPOLYLINE((#176,#177,#178,#179,#176));
#176=IFCCARTESIANPOINT((6.999159,0.));
#177=IFCCARTESIANPOINT((6.999159,0.));
#178=IFCCARTESIANPOINT((7.0,0.));
#179=IFCCARTESIANPOINT((7.0,0.));
~~~

**Closed by aothms** 2018-11-19 10:51 UTC
