### ISSUE TITLE
nix/build-all.sh fails due to "Command "/home/richter/IfcOpenShell/build/Linux/x86_64/install/swig/bin/swig -swiglib" failed with output: -- Could NOT find SWIG (missing:  SWIG_DIR)"

### ISSUE THREAD

**Issue by krichter722** [IfcOpenShell/IfcOpenShell#132] opened 2016-09-10 15:07 UTC
In a clean checkout `cd nix && bash build-all.sh` fails due to

```
Command "/home/richter/IfcOpenShell/build/Linux/x86_64/install/swig/bin/swig -swiglib" failed with output:

-- Could NOT find SWIG (missing:  SWIG_DIR) 
```

in `build/Linux/x86_64/logs/20160910.log`. The script output is

```
$ bash ./build-all.sh 
This script fetches and builds IfcOpenShell and its dependencies

Script configuration:
* Target Architecture    = x86_64
 - Whether 32-bit (i686) or 64-bit (x86_64) will be built.
* Dependency Directory   = /home/richter/IfcOpenShell/build/Linux/x86_64
 - The directory where IfcOpenShell dependencies are installed.
* Build Config Type      = RelWithDebInfo
 - The used build configuration type for the dependencies.
   Defaults to RelWithDebInfo if not specified.
* IFCOS_NUM_BUILD_PROCS  = 9
 - How many compiler processes may be run in parallel.

Logging to file /home/richter/IfcOpenShell/build/Linux/x86_64/logs/20160910.log
Collecting dependencies:
Installed cmake-3.4.1     
Installed pcre-8.38     
Found existing swig
Installed oce-0.16     
Installed libxml2-2.9.3     
Installed OpenCOLLADA     
Installed python-2.7.10     
Installed python-3.2.6     
Installed python-3.3.6     
Installed python-3.4.4     
Installed python-3.5.1     
Installed boost-1.59.0     
Installed icu-56.1     
Building IfcOpenShell:
Configuring python 2.7.10 wrapper...
```

[20160910.log.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/465464/20160910.log.zip)

experienced with e2d127b on Ubuntu 16.04

**Comment by aothms** [comment] 2016-09-10 17:07
Can I ask what operating system you are on? The script has mostly been tested on Debian and OS X, perhaps there are subtleties on other distros that have been overlooked?

How come it says `Found existing swig` when none of the other dependencies are found? The only path where is being searched is in the local build path [1]. I.e. `/home/richter/IfcOpenShell/build/Linux/x86_64/install/swig`. Is there actually something there?

The CMake error probably boils down to `/home/richter/IfcOpenShell/build/Linux/x86_64/install/swig/bin/swig -swiglib` returning a non-zero exit code (it might simply be absent). What is output if you run this manually?

I don't think the issue is due to `-DSWIG_EXECUTABLE` being specified rather than `-DSWIG_DIR` [2]. But this could also be something to look into.

[1] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/nix/build-all.sh#L183
[2] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/nix/build-all.sh#L384

**Comment by aothms** [comment] 2017-04-03 13:30
So, thanks to @krichter722 we have a different build script now, I assume we can close this.

**Closed by aothms** 2017-04-03 13:30 UTC
