### ISSUE TITLE
IfcTester doesn't Accept Annotations for some IDS XML Elements

### ISSUE THREAD

**Issue by hesrah** [IfcOpenShell/IfcOpenShell#2929] opened 2023-04-03 08:37 UTC
_IfcTester_ doesn't accept the following `xs:annotation` elements:
```
                ...
                <entity>
                    <name>
                        <simpleValue>IfcBuildingElementProxy</simpleValue>
                        <xs:annotation>
                            <xs:documentation>Identifkation: FB-1, Art der Verortung: linear</xs:documentation>
                        </xs:annotation>
                    </name>
                    <predefinedType>
                        <simpleValue>USERDEFINED</simpleValue>
                    </predefinedType>
                </entity>
                ...
```
Or also:
```
                ...
                <property measure="IfcLabel" minOccurs="1" maxOccurs="unbounded" instructions="Schichttyp">
                    <propertySet>
                        <simpleValue>CHTBAZH_Oberbau</simpleValue>
                    </propertySet>
                    <name>
                        <simpleValue>LayerType</simpleValue>
                    </name>
                    <value>
                        <xs:annotation>
                            <xs:documentation>Typ Deckschicht</xs:documentation>
                        </xs:annotation>
                        <xs:restriction>
                            <xs:enumeration value="Deckschicht, AC Asphaltbeton"/>
                            <xs:enumeration value="Deckschicht, AC MR Rauhasphalt"/>
                            ...
                            <xs:enumeration value="Deckschicht, SMA Splittmastix-Asphalt"/>
                        </xs:restriction>
                    </value>
                </property>
                ...
```
Shouldn't these be accepted?

**Comment by Moult** [comment] 2023-04-03 09:37
@hesrah can you provide a sample file please?

**Comment by hesrah** [comment] 2023-04-03 09:43
```
<ids xmlns="http://standards.buildingsmart.org/IDS" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://standards.buildingsmart.org/IDS http://standards.buildingsmart.org/IDS/ids_1_0.xsd">
    <info>
        <title>DBM für Betriebsphase aufbereiten</title>
        <copyright>FHNW</copyright>
        <version>IDS 0.9.3</version>
        <description>DBM für Betriebsphase aufbereiten</description>
        <author>Schildknecht (FHNW): lukas.schildknecht@fhnw.ch</author>
        <date>2023-03-13</date>
        <purpose>TBA ZH FDK</purpose>
        <milestone>Projekt abgeschlossen</milestone>
    </info>
    <specifications>
        <specification name="Deckschicht" minOccurs="0" maxOccurs="unbounded" ifcVersion="IFC4">
            <applicability>
                <entity>
                    <name>
                        <simpleValue>IfcBuildingElementProxy</simpleValue>
                        <xs:annotation>
                            <xs:documentation>Identifkation:	FB-1
Art der Verortung:	Linear, Linie
eBKP-Zuweisung:	Zuweisung offen
LOGO-Klasse:	Schicht</xs:documentation>
                        </xs:annotation>		
                    </name>
                    <predefinedType>
                        <simpleValue>USERDEFINED</simpleValue>
                    </predefinedType>
                </entity>
            </applicability>
            <requirements>
                <property measure="IfcLabel" minOccurs="1" maxOccurs="unbounded" instructions="Eigentümer">
                    <propertySet>
                        <simpleValue>CHTBAZH_Organisation</simpleValue>
                    </propertySet>
                    <name>
                        <simpleValue>Owner</simpleValue>
                    </name>
                </property>
                <property measure="IfcLabel" minOccurs="1" maxOccurs="unbounded" instructions="Verantworlicher baulicher Unterhalt">
                    <propertySet>
                        <simpleValue>CHTBAZH_Organisation</simpleValue>
                    </propertySet>
                    <name>
                        <simpleValue>StructuralMaintenance</simpleValue>
                    </name>
                </property>
                <property measure="IfcLabel" minOccurs="1" maxOccurs="unbounded" instructions="Verantworlicher betrieblicher Unterhalt">
                    <propertySet>
                        <simpleValue>CHTBAZH_Organisation</simpleValue>
                    </propertySet>
                    <name>
                        <simpleValue>OperationalMaintenance</simpleValue>
                    </name>
                </property>
                <property measure="IfcLabel" minOccurs="1" maxOccurs="unbounded" instructions="Schichttyp">
                    <propertySet>
                        <simpleValue>CHTBAZH_Oberbau</simpleValue>
                    </propertySet>
                    <name>
                        <simpleValue>LayerType</simpleValue>
                    </name>
                    <value>
                        <xs:annotation>
                            <xs:documentation>TypDeckschicht</xs:documentation>
                        </xs:annotation>	
                        <xs:restriction>
                            <xs:enumeration value="Deckschicht, AC Asphaltbeton"/>
                            <xs:enumeration value="Deckschicht, AC MR Rauhasphalt"/>
                            <xs:enumeration value="Deckschicht, AC TDS"/>
                            <xs:enumeration value="Deckschicht, DSK Kalt-Mikrobelag"/>
                            <xs:enumeration value="Deckschicht, MA Gussasphalt"/>
                            <xs:enumeration value="Deckschicht, OB Oberflächenbehandlung"/>
                            <xs:enumeration value="Deckschicht, SDA 4-12 Semidichter Asphalt"/>
                            <xs:enumeration value="Deckschicht, SDA 4-16 Semidichter Asphalt"/>
                            <xs:enumeration value="Deckschicht, SDA 8-12 Semidichter Asphalt"/>
                            <xs:enumeration value="Deckschicht, SMA Splittmastix-Asphalt"/>
                        </xs:restriction>
                    </value>
                </property>
                <property measure="IfcLabel" minOccurs="1" maxOccurs="unbounded" instructions="Körnung: Körnung der Schicht">
                    <propertySet>
                        <simpleValue>CHTBAZH_Oberbau</simpleValue>
                    </propertySet>
                    <name>
                        <simpleValue>Körnung</simpleValue>
                    </name>
                </property>
                <property measure="IfcLabel" minOccurs="1" maxOccurs="unbounded" instructions="Bindemittel">
                    <propertySet>
                        <simpleValue>CHTBAZH_Oberbau</simpleValue>
                    </propertySet>
                    <name>
                        <simpleValue>Bindemitteltyp</simpleValue>
                    </name>
                    <value>
                        <xs:annotation>
                            <xs:documentation>Bindemitteltyp</xs:documentation>
                        </xs:annotation>	
                        <xs:restriction>
                            <xs:enumeration value="? Unbekannt">
                                <xs:annotation>
                                    <xs:documentation>? Unbekannt</xs:documentation>
                                </xs:annotation>
                            </xs:enumeration>
                            <xs:enumeration value="B 100/150">
                                <xs:annotation>
                                    <xs:documentation>B 100/150</xs:documentation>
                                </xs:annotation>
                            </xs:enumeration>
                            <xs:enumeration value="B 120/150">
                                <xs:annotation>
                                    <xs:documentation>B 120/150</xs:documentation>
                                </xs:annotation>
                            </xs:enumeration>
                            <xs:enumeration value="B 20/30">
                                <xs:annotation>
                                    <xs:documentation>B 20/30</xs:documentation>
                                </xs:annotation>
                            </xs:enumeration>
                            <xs:enumeration value="B 40/50">
                                <xs:annotation>
                                    <xs:documentation>B 40/50</xs:documentation>
                                </xs:annotation>
                            </xs:enumeration>
                            <xs:enumeration value="B 50/70">
                                <xs:annotation>
                                    <xs:documentation>B 50/70</xs:documentation>
                                </xs:annotation>
                            </xs:enumeration>
                            <xs:enumeration value="B 55/70">
                                <xs:annotation>
                                    <xs:documentation>B 55/70</xs:documentation>
                                </xs:annotation>
                            </xs:enumeration>
                            <xs:enumeration value="B 70/100">
                                <xs:annotation>
                                    <xs:documentation>B 70/100</xs:documentation>
                                </xs:annotation>
                            </xs:enumeration>
                            <xs:enumeration value="B 80/100">
                                <xs:annotation>
                                    <xs:documentation>B 80/100</xs:documentation>
                                </xs:annotation>
                            </xs:enumeration>
                            <xs:enumeration value="Bitumen">
                                <xs:annotation>
                                    <xs:documentation>Bitumen</xs:documentation>
                                </xs:annotation>
                            </xs:enumeration>
                            <xs:enumeration value="Emulsion">
                                <xs:annotation>
                                    <xs:documentation>Emulsion</xs:documentation>
                                </xs:annotation>
                            </xs:enumeration>
                            <xs:enumeration value="HB Hartbitumen">
                                <xs:annotation>
                                    <xs:documentation>HB Hartbitumen</xs:documentation>
                                </xs:annotation>
                            </xs:enumeration>
                            <xs:enumeration value="hydraulischer Kalk">
                                <xs:annotation>
                                    <xs:documentation>hydraulischer Kalk</xs:documentation>
                                </xs:annotation>
                            </xs:enumeration>
                            <xs:enumeration value="PmB-E 10/30-70 (CH-E)">
                                <xs:annotation>
                                    <xs:documentation>PmB-E 10/30-70 (CH-E)</xs:documentation>
                                </xs:annotation>
                            </xs:enumeration>
                            <xs:enumeration value="PmB-E 30/50-65 (CH-E)">
                                <xs:annotation>
                                    <xs:documentation>PmB-E 30/50-65 (CH-E)</xs:documentation>
                                </xs:annotation>
                            </xs:enumeration>
                            <xs:enumeration value="PmB-E 50/70-65 (CH-E)">
                                <xs:annotation>
                                    <xs:documentation>PmB-E 50/70-65 (CH-E)</xs:documentation>
                                </xs:annotation>
                            </xs:enumeration>
                            <xs:enumeration value="PmB 10/40 (CH-E)">
                                <xs:annotation>
                                    <xs:documentation>PmB 10/40 (CH-E)</xs:documentation>
                                </xs:annotation>
                            </xs:enumeration>
                            <xs:enumeration value="PmB 25/55 (CH-E)">
                                <xs:annotation>
                                    <xs:documentation>PmB 25/55 (CH-E)</xs:documentation>
                                </xs:annotation>
                            </xs:enumeration>
                            <xs:enumeration value="PmB 30/50-65 (CH-E)">
                                <xs:annotation>
                                    <xs:documentation>PmB 30/50-65 (CH-E)</xs:documentation>
                                </xs:annotation>
                            </xs:enumeration>
                            <xs:enumeration value="PmB 45/80 (CH-E)">
                                <xs:annotation>
                                    <xs:documentation>PmB 45/80 (CH-E)</xs:documentation>
                                </xs:annotation>
                            </xs:enumeration>
                            <xs:enumeration value="PmB 65/105 (CH-E)">
                                <xs:annotation>
                                    <xs:documentation>PmB 65/105 (CH-E)</xs:documentation>
                                </xs:annotation>
                            </xs:enumeration>
                            <xs:enumeration value="PmB Polymodifizierte Bindelmittel (alt)">
                                <xs:annotation>
                                    <xs:documentation>PmB Polymodifizierte Bindelmittel (alt)</xs:documentation>
                                </xs:annotation>
                            </xs:enumeration>
                            <xs:enumeration value="PmB Polymodifizierte Bindemittel">
                                <xs:annotation>
                                    <xs:documentation>PmB Polymodifizierte Bindemittel</xs:documentation>
                                </xs:annotation>
                            </xs:enumeration>
                            <xs:enumeration value="Spez NV">
                                <xs:annotation>
                                    <xs:documentation>Spez NV</xs:documentation>
                                </xs:annotation>
                            </xs:enumeration>
                            <xs:enumeration value="Zement">
                                <xs:annotation>
                                    <xs:documentation>Zement</xs:documentation>
                                </xs:annotation>
                            </xs:enumeration>
                        </xs:restriction>
                    </value>
                </property>
                <property measure="IfcLabel" minOccurs="1" maxOccurs="unbounded" instructions="Code">
                    <propertySet>
                        <simpleValue>CHTBAZH_Oberbau</simpleValue>
                    </propertySet>
                    <name>
                        <simpleValue>Code</simpleValue>
                    </name>
                </property>
                <property measure="IfcLabel" minOccurs="1" maxOccurs="unbounded" instructions="RC-Anteil">
                    <propertySet>
                        <simpleValue>CHTBAZH_Oberbau</simpleValue>
                    </propertySet>
                    <name>
                        <simpleValue>RC-Anteil</simpleValue>
                    </name>
                </property>
                <property measure="IfcLabel" minOccurs="1" maxOccurs="unbounded" instructions="Sekundarsplit">
                    <propertySet>
                        <simpleValue>CHTBAZH_Oberbau</simpleValue>
                    </propertySet>
                    <name>
                        <simpleValue>Sekundarsplit</simpleValue>
                    </name>
                </property>
            </requirements>
        </specification>
        <specification name="Bindeschicht" minOccurs="0" maxOccurs="unbounded" ifcVersion="IFC4">
            <applicability>
                <entity>
                    <name>
                        <simpleValue>IfcBuildingElementProxy</simpleValue>
                        <xs:annotation>
                            <xs:documentation>Identifkation:	FB-2
Art der Verortung:	Linear, Linie
eBKP-Zuweisung:	Zuweisung offen
LOGO-Klasse:	Schicht</xs:documentation>
                        </xs:annotation>	
                    </name>
                    <predefinedType>
                        <simpleValue>USERDEFINED</simpleValue>
                    </predefinedType>
                </entity>
            </applicability>
            <requirements>
                <property measure="IfcLabel" minOccurs="1" maxOccurs="unbounded" instructions="Eigentümer">
                    <propertySet>
                        <simpleValue>CHTBAZH_Organisation</simpleValue>
                    </propertySet>
                    <name>
                        <simpleValue>Owner</simpleValue>
                    </name>
                </property>
            </requirements>
        </specification>
        <specification name="Tragschicht" minOccurs="0" maxOccurs="unbounded" ifcVersion="IFC4">
            <applicability>
                <entity>
                    <name>
                        <simpleValue>IfcBuildingElementProxy</simpleValue>
                        <xs:annotation>
                            <xs:documentation>Identifkation:	FB-3
Art der Verortung:	Linear, Linie
eBKP-Zuweisung:	Zuweisung offen
LOGO-Klasse:	Schicht</xs:documentation>
                        </xs:annotation>	
                    </name>
                    <predefinedType>
                        <simpleValue>USERDEFINED</simpleValue>
                    </predefinedType>
                </entity>
            </applicability>
            <requirements>
                <property measure="IfcLabel" minOccurs="1" maxOccurs="unbounded" instructions="Eigentümer">
                    <propertySet>
                        <simpleValue>CHTBAZH_Organisation</simpleValue>
                    </propertySet>
                    <name>
                        <simpleValue>Owner</simpleValue>
                    </name>
                </property>
            </requirements>
        </specification>
        <specification name="Fundationsschicht" minOccurs="0" maxOccurs="unbounded" ifcVersion="IFC4">
            <applicability>
                <entity>
                    <name>
                        <simpleValue>IfcBuildingElementProxy</simpleValue>
                        <xs:annotation>
                            <xs:documentation>Identifkation:	FB-4
Art der Verortung:	Linear, Linie
eBKP-Zuweisung:	Zuweisung offen
LOGO-Klasse:	Schicht</xs:documentation>
                        </xs:annotation>	
                    </name>
                    <predefinedType>
                        <simpleValue>USERDEFINED</simpleValue>
                    </predefinedType>
                </entity>
            </applicability>
            <requirements>
                <property measure="IfcLabel" minOccurs="1" maxOccurs="unbounded" instructions="Eigentümer">
                    <propertySet>
                        <simpleValue>CHTBAZH_Organisation</simpleValue>
                    </propertySet>
                    <name>
                        <simpleValue>Owner</simpleValue>
                    </name>
                </property>
            </requirements>
        </specification>
        <specification name="Übergangsschicht" minOccurs="0" maxOccurs="unbounded" ifcVersion="IFC4">
            <applicability>
                <entity>
                    <name>
                        <simpleValue>IfcBuildingElementProxy</simpleValue>
                        <xs:annotation>
                            <xs:documentation>Identifkation:	FB-5
Art der Verortung:	Linear, Linie
eBKP-Zuweisung:	Zuweisung offen
LOGO-Klasse:	Schicht</xs:documentation>
                        </xs:annotation>
                    </name>
                    <predefinedType>
                        <simpleValue>USERDEFINED</simpleValue>
                    </predefinedType>
                </entity>
            </applicability>
            <requirements>
                <property measure="IfcLabel" minOccurs="1" maxOccurs="unbounded" instructions="Eigentümer">
                    <propertySet>
                        <simpleValue>CHTBAZH_Organisation</simpleValue>
                    </propertySet>
                    <name>
                        <simpleValue>Owner</simpleValue>
                    </name>
                </property>
            </requirements>
        </specification>
    </specifications>
</ids>

```

**Comment by Andrej730** [comment] 2023-07-21 11:14
Example files to reproduce the issue:

[sample.ids.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/12122970/sample.ids.txt)
[sample.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/12122971/sample.ifc.txt)

Full traceback:
```
Path: /ids/specifications/specification[2]/applicability/entity/name

Error: Python: Traceback (most recent call last):
  File "C:\Users\Andrej\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\bim\module\tester\operator.py", line 53, in execute
    specs = ifctester.ids.open(props.specs)
  File "C:\Users\Andrej\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blenderbim\libs\site\packages\ifctester\ids.py", line 35, in open
    get_schema().decode(filepath, strip_namespaces=True, namespaces={"": "http://standards.buildingsmart.org/IDS"})

xmlschema.validators.exceptions.XMLSchemaChildrenValidationError: failed validating <Element '{http://standards.buildingsmart.org/IDS}name' at 0x0000023626226110> with XsdGroup(model='choice', occurs=[1, 1]):

Reason: Unexpected child with tag 'ids:annotation' at position 1. Tag ('ids:simpleValue' | 'xs:restriction') expected.

Schema:

  <xs:complexType xmlns:xs="http://www.w3.org/2001/XMLSchema" name="idsValue">
      <xs:choice minOccurs="1">

          <xs:element name="simpleValue" type="xs:string" minOccurs="1" maxOccurs="1" />
          <xs:element ref="xs:restriction" minOccurs="1" maxOccurs="unbounded" />
      </xs:choice>
  </xs:complexType>

Instance:

  <name xmlns="http://standards.buildingsmart.org/IDS">
      <annotation>
          <documentation>Example Annotation</documentation>
      </annotation>
      <simpleValue>IFCWALLTYPE</simpleValue>
  </name>

Path: /ids/specifications/specification[2]/applicability/entity/name
```

**Comment by Andrej730** [comment] 2023-07-21 14:31
Seems to be related to https://github.com/buildingSMART/IDS/issues/154 

Is it currently unsupported by IDS and we can close this? 
Haven't found any mentions of it in ids schema. In ids schema they use `xs:annotation` and `xs:documentation` just for descriptions of the schema itself.

**Comment by Moult** [comment] 2023-07-30 23:12
Agreed this is simply invalid IDS. IDS doesn't support adding annotations like this.

**Closed by Moult** 2023-07-30 23:12 UTC
Labels: IfcTester

**Comment by hesrah** [comment] 2023-07-31 06:50
I do not agree. (Almost) every xml element can have an annotation element. This is xml. It is not an extension of IDS. Annotations are IDS because IDS is xml.
The xml parser for IDS can simply ignore these annotations. But it shouldn't throw an error. Otherwise IDS is not xml compatible.

**Comment by Moult** [comment] 2023-07-31 07:26
Annotations are not part of XML. Annotations are part of XSD: https://www.w3.org/TR/xmlschema-1/#cAnnotations

This means you can use annotations almost anywhere within an XSD, but it doesn't mean that it's valid IDS to use it wherever in an IDS document. That's why the xmlschema library we use gives errors when we validate against the IDS XSD.
