### ISSUE TITLE
I can't export to IFC from Blender

### ISSUE THREAD

**Issue by karina-ufa** [IfcOpenShell/IfcOpenShell#1036] opened 2020-10-13 12:37 UTC
![Screenshot_1](https://user-images.githubusercontent.com/72802782/95861156-809ee400-0d7a-11eb-8006-bee2121da1ad.jpg)

I did everything according to the instructions, but I will give an error. I tried it in different versions.
![image](https://user-images.githubusercontent.com/72802782/95861690-3ff39a80-0d7b-11eb-84e6-457671424019.png)
![image](https://user-images.githubusercontent.com/72802782/95861721-484bd580-0d7b-11eb-805b-0fb09636b2ec.png)

**Comment by Moult** [comment] 2020-10-13 21:49
You seem to have accidentally renamed `IfcBuildingStorey/Ground Floor` to `IfcFurniture/Ground Floor`.

**Comment by karina-ufa** [comment] 2020-10-14 04:35
![image](https://user-images.githubusercontent.com/72802782/95943877-66a7e480-0e00-11eb-9bf4-37f3e569a7b7.png)
I tried to rename it, it doesn't help

**Comment by Moult** [comment] 2020-10-14 04:39
Can you attach your file? If it is sensitive, send to dion@thinkmoult.com

**Comment by karina-ufa** [comment] 2020-10-14 08:33
> Вы можете прикрепить свой файл? Если он чувствительный, отправьте на [dion@thinkmoult.com](mailto:dion@thinkmoult.com)

I send my file! Thank you very much!!!

**Comment by Moult** [comment] 2020-10-15 11:59
I couldn't access the file you sent, it seems to be linked to a Google account. Can you grant the access request to dionmoult@gmail.com please?

**Comment by karina-ufa** [comment] 2020-10-16 08:00
> I couldn't access the file you sent, it seems to be linked to a Google account. Can you grant the access request to [dionmoult@gmail.com](mailto:dionmoult@gmail.com) please?

I send 
![image](https://user-images.githubusercontent.com/72802782/96228840-89c4c680-0faf-11eb-84c6-6d1ad0500624.png)

**Comment by Moult** [comment] 2020-10-24 10:35
So sorry, I've been quite busy! I forgot to download your file. However, I've just pushed a fix that I think will address your issue. Can you check if that works for you?

If you can resend your file one more time (so sorry!) I can confirm that the fix indeed works for you.

**Comment by Moult** [comment] 2020-10-24 10:39
Eh, sorry, I completely confused this with another issue. Can you please resend your file one more time? I suspect it has to do with a funky non-standard imperial unit name.

**Comment by karina-ufa** [comment] 2020-10-24 12:23
> Eh, sorry, I completely confused this with another issue. Can you please resend your file one more time? I suspect it has to do with a funky non-standard imperial unit name.

Thx you))) I send my file to dionmoult@gmail.com

**Comment by Moult** [comment] 2020-10-25 02:13
It should be fixed now. If you don't want to wait for the fix, you can explicitly set unit settings in your scene properties.

![2020-10-25-131259_352x269_scrot](https://user-images.githubusercontent.com/88302/97097386-d8ffab00-16c3-11eb-93e2-5b5d15f8ab2a.png)

By the way, your file has objects which are highly split into components, which I think in your scenario is not a particularly good way to store data in IFC. In addition, the mesh resolution is incredibly high - there are about 400,000 vertices.

This means that the exported file will become quite large (~40mb in my test) and be difficult for others to use. Can I recommend you remodel the object using a more efficient mesh? I suspect if remodeled, it can be under 1mb.

**Closed** 2020-10-25 02:12 UTC
Labels: BlenderBIM
