### ISSUE TITLE
API not available warning

### ISSUE THREAD

**Issue by Licini** [IfcOpenShell/IfcOpenShell#5200] opened 2024-08-20 16:00 UTC
Hi there, Is there a way to removing these warnings?
Using `0.7.10`, many thanks in advance!

```bash
Python 3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:40:31) [MSC v.1929 64 bit (AMD64)] on win32
>>> import ifcopenshell
>>> import ifcopenshell.api
>>> import ifcopenshell.api.context
Note: API not available due to missing dependencies: geometry.add_door_representation - No module named 'mathutils'
Note: API not available due to missing dependencies: geometry.add_railing_representation - No module named 'mathutils'
Note: API not available due to missing dependencies: geometry.add_representation - No module named 'bpy'
Note: API not available due to missing dependencies: geometry.add_window_representation - No module named 'mathutils'
Note: API not available due to missing dependencies: grid.create_axis_curve - No module named 'mathutils'
```
```bash
Python 3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:40:31) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from ifcopenshell.api.context import add_context
Note: API not available due to missing dependencies: geometry.add_door_representation - No module named 'mathutils'
Note: API not available due to missing dependencies: geometry.add_railing_representation - No module named 'mathutils'
Note: API not available due to missing dependencies: geometry.add_representation - No module named 'bpy'
Note: API not available due to missing dependencies: geometry.add_window_representation - No module named 'mathutils'
Note: API not available due to missing dependencies: grid.create_axis_curve - No module named 'mathutils'
>>>

**Comment by Andrej730** [comment] 2024-08-20 16:16
@Licini 

Install `mathutils`? Or you can use `pip install ifcopenshell[geometry]`.

**Comment by Moult** [comment] 2024-09-23 13:56
Duplicate of #5192.

**Closed by Moult** 2024-09-23 13:56 UTC
Labels: IfcOpenShell-Python
