### ISSUE TITLE
IfcAnnotation instances that are type driven get turned off, for some reason, when `IfcAnnotation` is used in the `Include` parameter.

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3427] opened 2023-07-11 18:40 UTC
IfcAnnotation instances that are type driven get turned off, for some reason, when `IfcAnnotation` is used in the `Include` parameter. 

file: [untitled.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/12017960/untitled.ifc.txt)

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/3489f589-f69b-4b22-b82d-90389bfc26b9

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/4b95a92c-6395-466a-8e6a-ff66c9c11083)

**Comment by Moult** [comment] 2023-07-12 02:04
Duplicate of #3417 . It's not because it's a type, it's due to its placement it's hitting a tolerance and it thinks "hey I'm behind the camera I should be invisible".

**Closed by Moult** 2023-07-12 02:04 UTC
Labels: BlenderBIM
