### ISSUE TITLE
BB Crash report

### ISSUE THREAD

**Issue by cadgiru** [IfcOpenShell/IfcOpenShell#1935] opened 2021-12-10 10:32 UTC
Trying to load a 2x3 ifc file , (same result in 2.93 and 3.0) BTW it loads without issues in BimSync and Solibri
Win 10, blenderbim-211210-py39-win
[211210Crash.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/7692030/211210Crash.txt)

**Comment by Moult** [comment] 2021-12-10 10:58
I think this is a duplicate of #1906 which I am seeing increasingly in more files. Hopefully it gets solved soon, potentially once the next IfcOpenBot build is out.

**Comment by cadgiru** [comment] 2021-12-10 11:12
BTW maybe not of concern.. But Originator 
IFC file generated by GRAPHISOFT ARCHICAD 23.0.0 NOR FULL Windows version

**Comment by cadgiru** [comment] 2021-12-10 14:26
Tried same file on NAME="Ubuntu" VERSION="20.04.3 LTS, Blender 3.0, bb211210
Sadly same result

**Comment by Moult** [comment] 2021-12-13 22:54
Hmm, I hoped that would fix it. Can you send me the file dion@thinkmoult.com to see if I can replicate the crash?

**Comment by Moult** [comment] 2021-12-19 22:41
@cadgiru bump - did I get a file?

**Comment by Moult** [comment] 2021-12-22 00:12
Bump :)

Also, when you tried the new build, before importing, in your blenderbim add-ons folder, can you be sure to delete all `*.h5` files in your `bim/data/cache/` folder?

**Comment by Moult** [comment] 2022-01-04 02:40
Closing until this can be replicated or retested.

**Closed by Moult** 2022-01-04 02:40 UTC
Labels: BlenderBIM
