### ISSUE TITLE
Create Drawing Error

### ISSUE THREAD

**Issue by aslejo0395** [IfcOpenShell/IfcOpenShell#5399] opened 2024-09-16 20:52 UTC
Python: Traceback (most recent call last):
  File "C:\Users\Gerardo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 272, in execute
    linework_svg = self.generate_linework(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gerardo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 778, in generate_linework
    self.serialiser.finalize()
  File "C:\Users\Gerardo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 5092, in finalize
    return _ifcopenshell_wrapper.SvgSerializer_finalize(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: An unknown error occurred

**Comment by Moult** [comment] 2024-09-19 06:35
Duplicate of #4924.

**Closed by Moult** 2024-09-19 06:35 UTC
Labels: Bonsai
