### ISSUE TITLE
Removed material is not remembered, upon import

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3147] opened 2023-05-13 01:17 UTC
In this [file](https://gitlab.com/openingdesign/mineral_point_residence/-/blob/ae1f140f8905b754bd67685c59bcb0959049ff10/Mineral_Point_Residence.ifc), the removed material is not remember upon import

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/3d33a3b0-e2af-4188-b217-6f9cdffe665a

**Comment by maxfb87** [comment] 2023-05-15 09:05
Hey, i'm trying to fix it.
I tried also to press "remove ifc material" in the same panel with this material selected and it doesn't fix.
It is strange also that this material is not viewed in panel ifc geometry -> ifc materials
I'm investigating

**Comment by maxfb87** [comment] 2023-05-15 20:31
@theoryshaw hey, so i partially managed to solve it with scripting.
Maybe i'm writing things that you already know, just tell me.
The problem is the material defined at id 76.
I deleted the material and relations with:
ifc = tool.Ifc.get()
for id in [76, 1141, 1142, 1143, 1144, 1145, 1146]:
    element = ifc.by_id(id)
    ifcopenshell.api.run("root.remove_product", ifc, product = entity)

In this way, the material is deleted, so it disappears from the menu you have showed.
The problem is if there is an object that uses this material: if so, this object looses the material also...

I'll investigate more and i'll tell you...

**Comment by theoryshaw** [comment] 2023-05-15 20:56
Just stumbled on this...
https://www.dropbox.com/s/n1vqz3u3jw6y8t7/2023-05-15_15-54-41_Blender_blender.mp4?dl=0

I think I had to delete the style, and then the material.  It seems to have fixed it. 
Sorry for the hassle, if that was it.

**Comment by maxfb87** [comment] 2023-05-15 21:09
Ah ok, this is good!
Basically the style deletion deletes the entities i wrote (id 1141, etc..)
Btw i found something strange (at least for me :-) ) for example it seems that the material 'Unknown' is not associated to that slab object...

**Comment by maxfb87** [comment] 2023-05-15 21:15
Maybe an improvement could be to remove also style and style attributes when ifcopenshell.api.run('material.remove_material', ...) no?
Because now it doesn't remove them...

**Comment by maxfb87** [comment] 2023-05-16 20:11
So, i learned a little bit more, thanks also to this thread
https://community.osarch.org/discussion/comment/13729/#Comment_13729

The 'unknown' is not an IfcMaterial, it is an IfcStyle...in fact, if you delete the IfcStyle from the IfcStyle menu, save the ifc file and after that reimport the ifc, 'unknown' doesn't show up anymore.

So the slab has a material assigned to it and the material has a IfcStyle assigned to it.
The confusion is because there is the IfcMaterial and the IfcStyle under the same menu and if you remove the style with the - button, it doesn't remove the IfcStyle from the ifc file...

**Comment by maxfb87** [comment] 2023-05-17 18:47
So @theoryshaw , as i wrote before, 'Unknown' is an IfcStyle not an IfcMaterial so it can be deleted with an 'IfcCommand'.
It can be done as i wrote before or also under scene tab -> Ifc Geometry -> IfcStyle
This one in particular is an IfcSurfaceStyle.
Any thought on this or can i close the issue?

**Comment by theoryshaw** [comment] 2023-05-17 19:53
cool. Sounds good to me.  Seems like a closer. :)

**Closed** 2023-05-17 20:44 UTC
Labels: BlenderBIM
