### ISSUE TITLE
Allow patching file on disk or from memory

### ISSUE THREAD

**Issue by CyrilWaechter** [IfcOpenShell/IfcOpenShell#2620] opened 2022-11-26 15:18 UTC
Currently some patch only works on files written on disk (eg. MergeDuplicateTypes) and some other works only on file from memory (eg. FixArchiCADToRevitSpaces).

It would be great to allow all patch recipes to work in both case like for IFC Tester:
![Load from memory checkbox](https://user-images.githubusercontent.com/9622862/204096036-03df5b37-6d31-45e7-944e-92668358e0bb.png)

**Comment by CyrilWaechter** [comment] 2023-02-01 08:46
Great ! Thanks !

**Comment by CyrilWaechter** [comment] 2023-02-14 08:06
I tested it today. It seems that a step is still missing.

# Issue
When you patch ifcfile from memory it might work but changes are not reflected in the UI and maybe even not in the currently working file as when you click on a type that should have been deleted, it is still there. When you patch the same file and save it elsewhere without `Load from Memory` option you get expected result.

Although maybe it is very complicated to have the currently working file updated ?

# Steps to reproduce
1. Import an IFC with duplicated types
2. Patch it with `MergeDuplicateTypes` using `Load from Memory` option

**Comment by Moult** [comment] 2023-02-14 09:45
The problem is that we have no idea what the patch actually does... The patch is a black box. Did it delete items? Create new ones? Generate entirely new files? The only safe way to handle it is either 1) to completely reload the model in a fresh session, which sounds undesirable especially on large models or 2) build some form of hook that let's each recipe decide how to update itself... Which is also Blender specific.

In my opinion its better to do nothing by default, but perhaps offer a "reload IFC function" which ATM is not yet built.

**Comment by aothms** [comment] 2023-02-14 09:51
If patching is wrapped in a transaction would it help (in the future) to determine the type of changes? Initially you could just inform the user of the type of changes in the transaction and leave it up to him to decide what to do. Later you could selectively reload automatically based on the change log?

**Comment by Moult** [comment] 2023-02-24 01:59
Closing this since apart from the transaction tricks (even how we'd communicate types of changes meaningfully to users is a tricky question) it's now a duplicate of #1922.

**Closed by Moult** 2023-02-24 01:59 UTC
Labels: BlenderBIM, IfcPatch
