### ISSUE TITLE
path error

### ISSUE THREAD

**Issue by ekswathi** [IfcOpenShell/IfcOpenShell#1370] opened 2021-03-10 06:32 UTC
![image](https://user-images.githubusercontent.com/51689618/110586584-743b7d80-8198-11eb-93bf-999777c1d0ad.png)

**Comment by Moult** [comment] 2021-03-10 06:58
Does this exist: `AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\util\schema\Pset_IFC4_ADD2.ifc`?

What triggers this error? What action were you performing?

Also, ping @CyrilWaechter

**Comment by Moult** [comment] 2021-03-10 08:08
You are using Blender 2.93. Can you confirm that you are using one of the builds from the Github releases? The download from the Blenderbim.org website is only for <Blender2.93.

To download the new builds, download the "py39-win" variant here:

https://github.com/IfcOpenShell/IfcOpenShell/releases

**Comment by ekswathi** [comment] 2021-03-10 08:39
This is the file i am try to enable
https://github.com/IfcOpenShell/IfcOpenShell/releases/download/blenderbim-210309/blender28-bim-210309-py39-win.zip

**Comment by Moult** [comment] 2021-03-10 09:28
@ekswathi try this small modification and see if it fixes your issue https://github.com/IfcOpenShell/IfcOpenShell/commit/4b64f09aaa6be6448a74b5a70a91da0a2db61516

**Comment by CyrilWaechter** [comment] 2021-03-10 11:03
I was not able to reproduce the error using following steps : 
* Install blender 2.93 alpha on windows
* Install blenderbim 210309 from zip
* I was able to both enable the addon and use psets as usual

**Comment by ekswathi** [comment] 2021-03-10 11:08
Sorry no change it shows the same first message and not able to enable
![image](https://user-images.githubusercontent.com/51689618/110620433-0191c880-81bf-11eb-9acc-90f6e8954afa.png)

**Comment by Moult** [comment] 2021-03-10 11:17
It does not look like you made the change in the code. You need to edit the file manually in a text editor then restart blender then try again.

**Comment by ekswathi** [comment] 2021-03-10 11:28
First I pasted the part of the script from the link, not working.  Then I replaced pset.py from the link still same message.
I am really sorry to waste your valuable time.

**Comment by Moult** [comment] 2021-03-10 21:33
@ekswathi as others cannot replicate it, and the fix I thought would work clearly didn't work, can we organise a quick 15 minute screenshare to debug? I'm available anytime during Sydney waking hours (8am to 10pm). You can send me a message either here or on the OSArch.org live chat when it's convenient for you and we can meet online at https://meet.jit.si/openbim

**Comment by ecke101** [comment] 2021-03-11 10:43
Could this be caused by another windows language or windows version maybe? I use english Win 10.

**Comment by Moult** [comment] 2021-03-15 08:07
@ecke101 I honestly think the easiest way for me to debug this is to share screens with you. Would it be possible to set up a time?

**Comment by ekswathi** [comment] 2021-03-15 08:42
Hello sorry not to answer.  I was busy with some urgent work.

**Comment by ekswathi** [comment] 2021-03-15 08:42
any time is ok.  I am in india.

**Comment by ekswathi** [comment] 2021-03-15 08:46
I tried blenderbim-210314 also.  It shows the same error.
blender 2.92 build is working properly

**Comment by Moult** [comment] 2021-03-15 10:05
@ekswathi let me know a time & date during the Sydney timezone waking hours and let's meet at https://meet.jit.si/openbim

**Comment by ekswathi** [comment] 2021-03-15 10:46
we can meet tomorrow afternoon if it is ok for you.  something like 3.pm Sydney time.

**Comment by Moult** [comment] 2021-03-15 22:00
@ekswathi sure, see you 3pm at https://meet.jit.si/openbim

**Comment by ekswathi** [comment] 2021-03-16 04:16
sorry i didn't get the link

**Comment by Moult** [comment] 2021-03-16 05:22
Closing bug - issue seems to be in custom Blender build (lanpr) that seems to have some funky build rules.

**Closed by Moult** 2021-03-16 05:22 UTC
Labels: BlenderBIM
