### ISSUE TITLE
Need to restart BlenderBIM Add-on after adding a new pset template

### ISSUE THREAD

**Issue by lpr91** [IfcOpenShell/IfcOpenShell#1401] opened 2021-03-23 00:04 UTC
OS: Windows 10
Blender 2.92
BlenderBIM 0.0.210221

1) When importing an IFC into an empty Blender workspace, the ifcspace collection that should contain all the entities that I have assigned to it does not appear and therefore they are not properly organized. However, I can still see the ifc spatial container in the items' properties.

2) When importing an IFC as in (1), I'm able to see the definded psets of all the entities in the object properties panel. However, in this scenario I'm not able to retreive the elements' properties from the python console using methods such as item.PsetProperties.properties. Anyway, if I edit the properties of an item from the object properties panel and save the changes, the approach in python works again for it.

3)When creating a new custom pset from the scene properties, I'm not immediately able to apply it to an object. This only works after I restart Blender.

**Comment by Moult** [comment] 2021-03-23 00:12
@lpr91 :

 1. Not a bug. Due to the large number of spaces in a project this is not usually something we represent as a collection - so the collection tree only goes down to the storey level by design. If you enable "import spaces" at import time you will see the space object.
 2. Not a bug. You should not be retrieving properties using item.PsetProperties. Instead, you should retrieve it directly from the IFC file. You can either query the blenderbim.bim.module.pset.data class, or simply use ifcopenshell directly, via ifcopenshell.util.element.get_psets(IfcStore.get_file().by_id(item.BIMObjectProperties.ifc_definition_id))). The latter is probably simpler. I need to sit down and document this.
 3. Known limitation, I should probably address this.

**Comment by Moult** [comment] 2021-07-29 06:15
A heads up that number 1 is also fixed now, I changed my mind ;)

**Closed** 2021-07-29 06:16 UTC
Labels: BlenderBIM
