### ISSUE TITLE
Python: Traceback

### ISSUE THREAD

**Issue by Berning47** [IfcOpenShell/IfcOpenShell#2670] opened 2023-01-01 21:18 UTC
Can you please suggest a solution to this problem?

I import ifc for the first time:
<img width="722" alt="Screenshot_1" src="https://user-images.githubusercontent.com/121771006/210184795-09c3ed9b-9745-4537-9cb4-ee805e3913aa.png">

I import ifc a second time:
<img width="638" alt="Screenshot_3" src="https://user-images.githubusercontent.com/121771006/210184741-066fcb82-364d-4e44-95ba-8c8fe22f31e9.png">

I export ifc:
<img width="794" alt="Screenshot_2" src="https://user-images.githubusercontent.com/121771006/210184846-6c07054e-43f2-4ef3-a6c7-e0cc0680254f.png">

**Comment by aothms** [comment] 2023-01-02 09:58
Duplicate of #2664 Please use a slightly older version until this is resolved.

**Closed by aothms** 2023-01-02 09:58 UTC

**Comment by Berning47** [comment] 2023-01-02 10:17
> Дубликат [# 2664](https://github.com/IfcOpenShell/IfcOpenShell/issues/2664) Пожалуйста, використовуйте более старую версию, пока проблема не будет устранена.

Are you talking about an older version of BIM-Add-on? If yes, then it didn't work.

**Comment by Berning47** [comment] 2023-01-02 10:18
> Дубликат [# 2664](https://github.com/IfcOpenShell/IfcOpenShell/issues/2664) Пожалуйста, выкористовуйте более старую версию, пока проблема не будет устранена.

Are you talking about an older version of BIM-Add-on? If yes, then it didn't work(

**Comment by aothms** [comment] 2023-01-02 10:23
I would assume a version before Dec 25 would work. @theoryshaw @Moult ?

**Comment by Berning47** [comment] 2023-01-02 10:32
Unfortunately, this didn't solve the problem either.

**Comment by theoryshaw** [comment] 2023-01-04 00:21
![image](https://user-images.githubusercontent.com/507113/210462671-95d57c9d-021f-422e-8c01-3f73a41b5ad7.png)
worked for me.
