### ISSUE TITLE
the door representation door not visible in the drawing

### ISSUE THREAD

**Issue by blenderarc** [IfcOpenShell/IfcOpenShell#3947] opened 2023-10-27 21:34 UTC
the door representation door not visible in the drawing
![door dont appear](https://github.com/IfcOpenShell/IfcOpenShell/assets/140309875/2f862152-ad30-4d9f-9fa4-086b1755cbd0)
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/140309875/e77dc8c9-88ae-4a18-bb46-43827e665c4c)

**Comment by blenderarc** [comment] 2023-10-27 22:05
[1.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/13193622/1.zip)
Ifc File

**Comment by Andrej730** [comment] 2023-10-31 12:10
It seems the cause of the issue is that door representation and slab are at exactly the same Z value.

**Comment by Moult** [comment] 2023-11-02 03:00
Ping @aothms how do you think this issue can be solved? Here's the ChatGPT thinks:

```
    Offsetting:
        Z-Buffer Offset: Adjust the Z-values of the line work very slightly so that they are rendered just above the surfaces they coincide with. This is a common technique used in OpenGL called "Polygon Offset", and similar functionality might be available in OpenCASCADE or through the underlying graphics API it uses.
        Geometry Offset: Manually modify the Z-coordinates of the 2D elements to lift them off the surfaces they coincide with by a small amount. However, if the view changes significantly, this might not be a robust solution as it may not look right from all angles.

    Rendering Order:
        Render the 3D objects first and the 2D linework second. By controlling the rendering order, you can ensure that the 2D elements are drawn last, which can help them appear on top without Z-fighting. This works well for orthographic projections where perspective isn't an issue.

    Separate Render Passes:
        Use separate render passes for the floor slab and the door swings. In the first pass, you would render all the 3D elements, and in the second pass, you render the 2D elements with depth testing against the 3D elements' depth buffer.

    Stenciling:
        Utilize a stencil buffer to control where the 2D elements can be drawn. This involves creating a stencil shape for the door swings and only allowing rendering within those stenciled areas.

    Depth Peeling:
        Depth peeling is an advanced technique where you render scenes in layers. While this is more computationally expensive, it can help avoid Z-fighting by separating elements at the same depth into different layers.

    Custom Shader:
        Write a custom shader that gives priority to certain types of geometry when Z values are similar. In the shader, you could add a small bias or use an algorithm to decide whether to draw the slab or door swing based on some additional criteria.

    Use 2D Projection:
        If the drawing generation is purely for 2D output (like construction plans), you could project the 3D data into 2D and handle overlaps in a 2D space where you have more control and where depth complexity is simplified.
```

**Comment by Andrej730** [comment] 2023-11-02 05:24
I'm curious how Blender solves it, since it appears in viewport fine without z-fighting.

**Comment by SavuGust27** [comment] 2023-11-02 21:45
i don't know if this helps, but can the door drawing representation have an offset from its origin by default? when i make a custom IFCelemment and assign it a 2d Plan representation i always offset it from the origin to not have this problem. For example a tree, that has its origin in the bottom, but in plan view i want to see it above my building in a landscape project, that really helps.

**Comment by Moult** [comment] 2023-11-02 22:04
@SavuGust27 there is no "automatic" or default offset for Plan context type bodies because they are inherently only 2D. If, however, you store them as `Model/Body/PLAN_VIEW` you can include a small Z offset which fixes the problem manually.

Same with trees. Trees are often on sloping terrain so storing "Plan" bodies with no Z offset makes little sense. Instead a "Model/Body/PLAN_VIEW" may be used to store the tree footprint at say a 500mm +Z offset.

![2023-11-03-090315_457x173_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/0d4f0528-7143-4039-a6c0-d91211e90a85)

![2023-11-03-090252_223x603_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/c0ca3df4-3304-4317-a69e-51f9e950d1e3)

**Comment by SavuGust27** [comment] 2023-11-02 22:26
Yes, i did notice that Model/Body/PLAN_VIEW is the one that lets you to add a Z offset from origin. I guess use that for some representations when needed?

**Comment by Moult** [comment] 2023-11-03 00:44
Yes. There is also the question on whether or not we should default to using that (similarly for ceiling plans ceiling services are often recessed and need to be shown regardless). And if we do default to using it, what is the point of using the "Plan" context at all. Maybe not much for 3D generated drawings.

**Comment by aothms** [comment] 2023-11-03 09:06
I don't have much input on this. You'd expect opencascade to handle this, When free edges are on the same Z as a face you'd expect the edge to win. But if they don't then I would indeed add an automatic Z offset somewhere in the pipeline. I guess in Python would be easiest and most configurable. The alternative is that we get much smarter in figuring out the obscuring relationships ourselves. So that we can exclude 2D linework from being hidden by e.g the floor slab. It would help performance as well as we'd reduce the amount of edge-face pairs to consider, but I don't think we should be doing that now.

**Comment by Moult** [comment] 2023-11-03 11:07
>  It would help performance as well as we'd reduce the amount of edge-face pairs to consider, but I don't think we should be doing that now.

I think I already do that if this is what you mean https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/module/drawing/operator.py#L572-L573

> But if they don't then I would indeed add an automatic Z offset somewhere in the pipeline.

Rather than require all users to use a Model representation and do their own Z offset, it would be super awesome if somewhere around [this step](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/module/drawing/operator.py#L499) we could specify a Z offset (is Z enough? I think this is only an issue in plans and ceiling plans)

What about the issue shown in #3561 in the isometric view drawing? That looks like a similar "face/edge fighting issue" which I'd _hope_ for OCC to solve automatically.

**Closed** 2024-01-20 10:53 UTC
Labels: BlenderBIM
