### ISSUE TITLE
Typed object doesn't inherit the predefined type

### ISSUE THREAD

**Issue by maxfb87** [IfcOpenShell/IfcOpenShell#4484] opened 2024-03-30 14:16 UTC
Step to reproduce:
- open a fresh shiny new bbim file
- create a new project with IFC4 demo template
- select a type (for example the covering type COV30)
- assign the predefined type CEILING to the type
- create a new COV30 typed object

The new typed object doesn't have the predefined type CEILING assigned to it

**Comment by theoryshaw** [comment] 2024-03-30 16:42
It seems to work for me, but I do have a question. 

It looks like the instance can have a `PredfinedType` that overrides the `PredfinedType` of from the type. Is that allowed in the schema?

...



https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/70a672f1-62c3-4c91-929f-d9d209e0deb3

...
I am confused by the UI a little, I would assume the PredefinedType on the instance, if driven by the PredefineType on the type, would show here...

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/f63926bd-9a28-4617-a12a-c804a30b1986)

**Comment by maxfb87** [comment] 2024-03-30 17:05
@theoryshaw unfortunately the UI is misleading...
If you go to debug panel (quality and coordination tab -> debug) and click to "inspect from object" you will see that the object hasn't the predefined type assigned ...
Or, in other words, the UI under "object metadata" is not correct and the UI under "attributes" is correct

**Comment by theoryshaw** [comment] 2024-03-30 17:18
> Is that allowed in the schema?

It seems, per the following, (if I'm interpreting it correctly), is that the PredefinedType of the instance is only used, if there's no IfcCoveringType driving the instance. 


![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/004bbd67-891a-481e-987a-e9d566c895ac)

**Comment by maxfb87** [comment] 2024-03-30 19:30
@theoryshaw ok, but if i have a type with PredefinedType = COVERING, shouldn't also the typed instance inherit the same PredefinedType?

**Comment by theoryshaw** [comment] 2024-03-30 20:01
> @theoryshaw ok, but if i have a type with PredefinedType = COVERING, shouldn't also the typed instance inherit the same PredefinedType?

Yes, that's how i understand it, as well.

**Comment by maxfb87** [comment] 2024-03-30 20:27
@theoryshaw ah ok, so there is a bug in BBim :-)

**Comment by Moult** [comment] 2024-03-31 04:42
Everything seems to be working as intended, but it sounds like the UI is misleading things.

If you have a type with a PredefinedType = CEILING, then the occurrence is not allowed to have its own predefined type. Unfortunately now you can actually still set it in the UI, but it's technically invalid.

The UI under object metadata still shows the (inherited) predefined type because it's trying to be useful. But yes, the UI in the attributes shows the true state which is that the occurrence has no value (i.e. the value is inherited).

**Comment by maxfb87** [comment] 2024-04-01 06:17
@Moult maybe i miss something but i tried now with the last update and still the object doesn't inherit the PredefinedType from the type...

**Comment by Moult** [comment] 2024-04-01 06:35
@maxfb87 have you got a screenshot or file to share to demonstrate?

**Comment by maxfb87** [comment] 2024-04-01 16:22
@Moult here is the video

https://github.com/IfcOpenShell/IfcOpenShell/assets/79401028/d64599a9-5c54-4f02-a7c3-2f0d7f1c8647

Sorry for the bad quality, i'm not very good at making videos :-) i hope i was clear

**Comment by Moult** [comment] 2024-04-01 23:05
Thanks for the video! Yes indeed it's not a bug, the predefined type of IfcCovering[CEILING] shows the _inherited_ predefined type. The occurrence _should not_ have any predefined type attribute (i.e. it should be set to null).

This is similar to how classifications can be inherited, or psets can be inherited from the type.

**Comment by maxfb87** [comment] 2024-04-02 04:59
@Moult ah thanks for the clarification, now i get it!
This is a pretty foundamental conceptual thing, i guess until now i understood it wrong!
Thanks again!

Can we close the issue or should we improve something about this aspect?

**Comment by Gorgious56** [comment] 2024-04-02 07:33
Maybe could be communicated with an upward arrow like the inherited materials ? 

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/094f14c2-d7ce-4c94-816a-1688a6b7e82c)

**Comment by maxfb87** [comment] 2024-04-02 17:14
@Gorgious56 this is a good idea!

**Comment by maxfb87** [comment] 2024-04-03 20:46
@Gorgious56 maybe also like this could help
![hp](https://github.com/IfcOpenShell/IfcOpenShell/assets/79401028/ceb69f67-ac2c-4ccf-86be-4c01eef7baeb)

**Comment by steverugi** [comment] 2024-04-04 05:32
I noticed, with the 240402 release, that new instances of a type do not immediately inherit the predefined type once created, but if you later select that type and reassign the predefined value (even the same already set with it) all related instances get the value as their type.
It's probably better than before but still a bit unintuitive for me

**Closed** 2024-04-14 23:28 UTC
Labels: BlenderBIM
