### ISSUE TITLE
Error opening the ifc file

### ISSUE THREAD

**Issue by BDSergeich** [IfcOpenShell/IfcOpenShell#5780] opened 2024-11-20 23:42 UTC
```
os: Windows
os_version: 10.0.19044
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 183 Stepping 1, GenuineIntel
blender_version: 4.2.3 LTS
bonsai_version: 0.8.0
bonsai_commit_hash: None
last_actions: 
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 66, "Name": "\u0411\u0438\u043e\u0442\u0443\u0430\u043b\u0435\u0442"}, "representation": {"cast_type": "entity_instance", "value": 645, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 645, "Name": null}}
# ifcopenshell.api: geometry.unassign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 66, "Name": "\u0411\u0438\u043e\u0442\u0443\u0430\u043b\u0435\u0442"}, "representation": {"cast_type": "entity_instance", "value": 641, "Name": null}}
# ifcopenshell.api: geometry.remove_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 641, "Name": null}}
# ifcopenshell.api: pset.remove_pset
>>> {"product": {"cast_type": "entity_instance", "value": 66, "Name": "\u0411\u0438\u043e\u0442\u0443\u0430\u043b\u0435\u0442"}, "pset": {"cast_type": "entity_instance", "value": 144, "Name": "PSKTP_\u0421\u0432\u043e\u0439\u0441\u0442\u0432\u0430"}}
# ifcopenshell.api: pset.remove_pset
>>> {"product": {"cast_type": "entity_instance", "value": 66, "Name": "\u0411\u0438\u043e\u0442\u0443\u0430\u043b\u0435\u0442"}, "pset": {"cast_type": "entity_instance", "value": 137, "Name": "PSKTP_\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0446\u0438\u044f"}}
# operator: BIM_OT_edit_attributes
# ifcopenshell.api: attribute.edit_attributes
>>> {"product": {"cast_type": "entity_instance", "value": 646, "Name": "Cylinder"}, "attributes": "{'GlobalId': '2FbV8ZKBbDCQmE6tl2HH4E', 'Name': '\u041b\u041e\u0421 60\u043c3', 'Description': None, 'ObjectType': None, 'Tag': None, 'PredefinedType': 'NOTDEFINED'}"}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 646, "Name": "\u041b\u041e\u0421 60\u043c3"}}
# operator: BIM_OT_save_project
last_error: Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\project\operator.py", line 751, in finish_loading_project
    bpy.ops.bim.load_project_elements()
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Ошибка: Python: Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\project\operator.py", line 832, in execute
    ifc_importer.execute()
  File "C:\Users\ADMIN\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\import_ifc.py", line 232, in execute
    self.set_units()
  File "C:\Users\ADMIN\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\import_ifc.py", line 1185, in set_units
    units = self.file.by_type("IfcUnitAssignment")[0]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Location: C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py:109


ifc: proxy_6_1.ifc
schema: IFC2X3
preprocessor_version: GeometryGymIFC v0.1.1.0 by Geometry Gym Pty Ltd built 2024-08-05T07:21:02
originating_system: RbRail v16.0.42.19
[proxy_6_1.zip](https://github.com/user-attachments/files/17837921/proxy_6_1.zip)

```
[proxy_6_1.zip](https://github.com/user-attachments/files/17837926/proxy_6_1.zip)

**Comment by Andrej730** [comment] 2024-11-21 13:16
@BDSergeich thank you for the bug report.
It's a duplicate of #5483, resolved in the latest release from https://github.com/IfcOpenShell/IfcOpenShell/releases/

**Closed as completed by Andrej730** 2024-11-21 13:16 UTC
Labels: Bonsai
