### ISSUE TITLE
Generated SVG prints out deleted elements (walls) and moved elements (windows and doors)

### ISSUE THREAD

**Issue by R2naizr** [IfcOpenShell/IfcOpenShell#2607] opened 2022-11-18 00:15 UTC
![image](https://user-images.githubusercontent.com/79116991/202586797-be1d9b85-0b08-4f1c-915b-c37ab8eaddaf.png)
The first image is of the model I want to be printed as SVG. I deleted a wall and moved windows and doors to new positions.

![image](https://user-images.githubusercontent.com/79116991/202586962-772d2ff0-c884-4efa-a2a6-29a7535a34cb.png)
The second image is of the generated SVG. The ifc shows only two doors, but there appears to be an additional door on the left. and there's an additional wall that appears to be still in the ifc file, though it has been deleted.

[test.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/10037442/test.txt)
Edit: The save function under the ifcproject settings doesn't seem to work. I repeatedly click save/save as and then generate a SVG, the result is the same. I've also tried to save the IFC via the ifcproject settings and then reopened the ifc and the ifc retains the wall, beam and door and windows that I deleted.

**Comment by theoryshaw** [comment] 2022-11-18 00:19
Can you upload the .ifc file, for troubleshooting?

**Comment by theoryshaw** [comment] 2022-11-18 00:24
btw, to upload an .ifc file, just change the .ifc extension to .txt

**Comment by R2naizr** [comment] 2022-11-18 03:16
sweet ok

**Comment by Moult** [comment] 2023-03-05 00:26
@R2naizr there have been a number of possibly related fixes since then. Can you confirm (from a fresh file, not your existing one) that this bug can still be reproduced?

**Comment by Moult** [comment] 2023-03-12 02:00
I've been testing this and cannot replicate issues with your IFC, so closing. I suspect the blend file is simply outdated. This speaks to a bigger issue of how to solve the Blend vs IFC issue. How should we discourage users from treating the blend file as the save file?

**Closed by Moult** 2023-03-12 02:00 UTC
Labels: BlenderBIM
