### ISSUE TITLE
BlenderBIM: crashes when reassigning class

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1281] opened 2021-01-31 20:27 UTC
blender28-bim-210131-win
2.91

video: https://www.dropbox.com/s/6qrp22xwjtwzo6c/2021-01-31_14-23-45.mp4?dl=0

**Comment by Moult** [comment] 2021-02-03 03:52
Cannot reproduce. Can you check your addons folder i.e. on windows AppData/Roaming/Blender Foundation/2.91/scripts/addons/ and in there do you see a folder called ifcopenshell? If so, delete it. It sounds like you may not have the latest IfcOpenShell for some reason.

**Comment by theoryshaw** [comment] 2021-02-03 04:04
delete that folder?

![image](https://user-images.githubusercontent.com/507113/106696575-a1e24500-65a2-11eb-9724-6c71d1ab3277.png)

**Comment by Moult** [comment] 2021-02-03 04:12
Hmmmmm... nope. Let's screenshare sometime.

**Comment by Moult** [comment] 2021-02-04 23:08
Closing, as @aothms seems to have fixed it in the latest build! :D

**Closed by Moult** 2021-02-04 23:08 UTC
Labels: BlenderBIM
