### ISSUE TITLE
IfcElementAssemblyType is added as Cube in BlenderBim

### ISSUE THREAD

**Issue by smr02** [IfcOpenShell/IfcOpenShell#4235] opened 2024-01-19 09:18 UTC
When importing a IfcElementAssemblyType, I get a Cube. See video. 
Attached also my IFC file. 

https://github.com/IfcOpenShell/IfcOpenShell/assets/67860835/a2fc5a33-c3b6-4fa1-ac0e-f2667002698c

[test_assembly.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/13986949/test_assembly.ifc.txt)

**Comment by Moult** [comment] 2024-01-19 11:00
Duplicate of #2052, but thank you for providing a handy test file :)

**Closed by Moult** 2024-01-19 11:00 UTC
