### ISSUE TITLE
2d door representation buried under a slab

### ISSUE THREAD

**Issue by maxfb87** [IfcOpenShell/IfcOpenShell#4228] opened 2024-01-16 20:17 UTC
Sometimes it happens that if there is a slab and a door at the same height, the 2d swing representation door doesn't show up in the drawing.
It happens sometimes when the door object has the same height of the slab, like this:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/79401028/929ca7e5-b48b-4feb-aa7c-f48053d20fa2)
In this case, the generated drawing doesn't show the 2d swing door representation.
It shows if i hide the slab or if i move the slab, let's say, -5mm in Z direction.
So i guess that the problem is because of the same height.
I tried also in css about slab to fill:none or fill:transparent or opacity:0 or z-index:-1 but it doesn't solved the problem.
Also, i can't always reproduce the problem because it isn't always there...
Is there any advice about it?
Thanks,
Massimo

**Comment by Moult** [comment] 2024-01-17 22:26
Duplicate of #3947.

**Closed by Moult** 2024-01-17 22:26 UTC
Labels: BlenderBIM
