### ISSUE TITLE
Door arcs on off axis models

### ISSUE THREAD

**Issue by motjokk** [IfcOpenShell/IfcOpenShell#2263] opened 2022-07-05 05:59 UTC
Hi,
Using IfcConvert 0.7.0

Door arcs do not seem to rotate 

![image](https://user-images.githubusercontent.com/33512457/177259425-300d2c2f-6d9a-4d06-9a43-a4d083f915d8.png)

**Comment by aothms** [comment] 2022-07-05 06:49
These are based on the placement of the door. So if the rotation is in the geometry coordinates and not in the placement you'd get this kind of result. Note that there are many assumptions on placements. See the red X and Y axis in the illustrations here for ex. http://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcDoorTypeOperationEnum.htm Can you confirm this is the case?

**Comment by motjokk** [comment] 2022-07-05 08:23
I am struggling to confirm weather the rotation is in placement or the geometry (not sure how). Here is the file in question:

[Building.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/9044644/Building.txt)

**Comment by motjokk** [comment] 2022-07-05 08:59
Thank you, I know what to look for now. This seems like an Archicad issue. The model was placed and rotated on a map before being eksported.  I know software vendors prefer using the footprint. Maybe this could be used to represent door arcs?

**Comment by aothms** [comment] 2022-07-05 09:42
Sure, I get decent results with:

    IfcConvert Building.ifc -y Building.svg --plan --model --section-height-from-storeys --svg-project --bounds=1024x1024 --exclude entities IfcOpeningElement

![afbeelding](https://user-images.githubusercontent.com/1096535/177299778-2f7a7d96-b928-4d0c-b228-62ef543920d7.png)

**Comment by motjokk** [comment] 2022-07-05 11:02
--svg-project can be very memory hungry, and paths are missing information, which makes it hard to identify the geometry. loading bigger models; > 10.000m2,  normally ends in a crash (experience from v0.6.0).

**Comment by aothms** [comment] 2022-07-05 11:37
Could very well be. It seems that only for IfcAnnotation we insert line geometry into the view based on z-range [0], not for arbitrary footprint geometries. It seems like this is something that could be unified.

Hidden Line Projection (--svg-project) will also be made more efficient, but it's a big effort that progresses slowly.

[0] https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/serializers/SvgSerializer.cpp#L1238

**Comment by motjokk** [comment] 2022-07-05 12:20
I Really appreciate your replies! I doubt that I can be very helpful, due to the lack of experience working with geometry. I will however try to contribute.

**Comment by Moult** [comment] 2022-09-23 10:41
Closing as the issue is with the incorrect axis usage in the file.

**Closed by Moult** 2022-09-23 10:41 UTC
