### ISSUE TITLE
Swood Design (SolidWorks) - IFC read error

### ISSUE THREAD

**Issue by toporivskiy** [IfcOpenShell/IfcOpenShell#3182] opened 2023-05-22 06:50 UTC
**I have such a file exported from SW:**

```
ISO-10303-21;
HEADER;
FILE_DESCRIPTION (( 'IFC4' ),'2;1' );
FILE_NAME ('1233.IFC',
     '2023-05-05T21:28:18',
    ( '' ),
    ( '' ),
    'SwIFC',
    'SolidWorks 2022',
    '' );
FILE_SCHEMA (( 'IFC4' ));
ENDSEC;
...
#45 = IFCBUILDINGELEMENTPROXY ( '0qav$il1TEuhWfGjYAIbKE',#2,'\X2\04210442043e0439043a0430\X0\ \X2\041b0432\X0\._S2_kh1_7_Default<Как обработанный>','','\X2\04210442043e0439043a0430\X0\ \X2\041b0432\X0\._S2_kh1_7_Default<Как обработанный>',#47,#46,'33D4F9E3-2F5E-4BA3-BA-36-BF5F4FBA19E3',.ELEMENT. ) ;
```

**When reading a file in Python, I have the following exception:**
```
Traceback (most recent call last):
  File "D:\PyProjects\swood2vp\main.py", line 22, in <module>
    print(model[45])
  File "D:\PyProjects\swood2vp\venv\Lib\site-packages\ifcopenshell\entity_instance.py", line 277, in __repr__
    return repr(self.wrapped_data)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyProjects\swood2vp\venv\Lib\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 4843, in __repr__
    return _ifcopenshell_wrapper.entity_instance___repr__(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Unexpected 'e' at offset 4062
```
**Please, help to understand what is the problem?**

**Comment by aothms** [comment] 2023-05-22 07:13
> `'\X2\04210442043e0439043a0430\X0\ \X2\041b0432\X0._S2_kh1_7_Default<Как обработанный>','','\X2\04210442043e0439043a0430\X0\ \X2\041b0432\X0._S2_kh1_7_Default<Как обработанный>'`

This is not valid IFC. IFC follows the step physical file string encoding mechanism of e.g `\X2\` followed by hex characters (as you have in your model). The Cyrillic characters are not valid and need to be encoded as well. So somehow you have triggered a bug in your exporter. There's very little we can do about it. Syntax errors are hard to recover from.

**Comment by toporivskiy** [comment] 2023-05-22 12:19
I understood that 04210442043e0439043a0430 are ascii codes of characters (4 digits per character). The decoding result is as follows: "стойка", which corresponds to "\u0421\u0442\u043E \u0439\u043A\u0430".
Is it a problem to finish decoding Cyrillic?

**Comment by aothms** [comment] 2023-05-23 06:38
> For me, the following file preparation works:

The issue is not the encoding though, it's the characters outside of the ascii readable characters range. The file format IFC uses predates unicode.

I'd propose this:

```python
with open(FILE, encoding='windows-1251') as f:
    file = f.read()
file = ''.join(c for c in s if ord(c) in range(0x20, 0xe7+1))
with open(FILE, 'w', encoding='ascii') as f:
    f.write(file)
```

**Comment by Moult** [comment] 2023-05-28 05:09
Closing as the file is simply invalid so not a bug.

**Closed by Moult** 2023-05-28 05:09 UTC
Labels: IfcOpenShell-Core
