### ISSUE TITLE
Blenderbim - status Pset visibility not working

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#3721] opened 2023-09-06 07:52 UTC
Using this version:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/98329235-aba0-4f3a-af40-c6f5ea571f31)

When attempting to toggle the visibility of the status pset it does not do anything:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/0b6b6bbe-0f51-4ba0-bcd3-32adff096d9f)

**Comment by Andrej730** [comment] 2023-09-06 10:59
Does it work if after "Activate Status Filters"? 
I've changed that it will update on toggling the eye icons to make it more intuitive - currently it's just changing objects visibility so it shouldn't be a performance issue.

**Comment by Moult** [comment] 2023-09-06 11:47
It is a performance issue on large projects. Changing visibility when you have 50,000 objects is not a small task. Also does the update function get called when the statuses are being detected for the first time? That sounds very expensive.

**Comment by Andrej730** [comment] 2023-09-06 11:59
No, it's not triggered when we setup the statuses because (atleast currently) statused are created and all visible by default.
Another idea is add some viewport icon button to disable live viewport update on large projects.

**Comment by Plae-Blue-Dot** [comment] 2023-09-06 14:33
> Does it work if after "Activate Status Filters"? I've changed that it will update on toggling the eye icons to make it more intuitive - currently it's just changing objects visibility so it shouldn't be a performance issue.

No it does not work

**Comment by Plae-Blue-Dot** [comment] 2023-09-06 14:34
> It is a performance issue on large projects. Changing visibility when you have 50,000 objects is not a small task. Also does the update function get called when the statuses are being detected for the first time? That sounds very expensive.

The reference file only has 4 walls and a camera in it, not certain what triggers it in this case

**Comment by Andrej730** [comment] 2023-09-06 14:39
>No it does not work
@Plae-Blue-Dot can you please send the .ifc?

**Comment by Plae-Blue-Dot** [comment] 2023-09-06 14:53
yes here it is
[status check - Copy.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/12539138/status.check.-.Copy.ifc.txt)

just remove the .txt

**Comment by Andrej730** [comment] 2023-09-07 09:42
Can't reproduce this :\ Tried it both on the latest commit and on 07579ee

https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/a5819c39-4359-44d3-bcf3-51a411bf38a8

**Comment by Andrej730** [comment] 2023-09-08 14:50
@Plae-Blue-Dot can you try it after reopening ifc file in the current BBIM version, it still doesn't work?
If it works after reload then it's something about the .blend file

**Comment by Plae-Blue-Dot** [comment] 2023-09-11 07:09
Sorry @Andrej730 for the delay, I've been away,
I opened the file in: 
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/6db8d872-d993-41cb-a4e5-ed8cace20f32)

and it works as expected:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/c3631690-5f6b-41d8-81ce-6e15f7575ca5)
not sure what the issue was

**Comment by Andrej730** [comment] 2023-09-12 03:57
I'll close this for now then

**Closed by Andrej730** 2023-09-12 03:57 UTC
Labels: BlenderBIM
