### ISSUE TITLE
IfcConvert 0.8.0 --model-offset doesn't work

### ISSUE THREAD

**Issue by berry4u** [IfcOpenShell/IfcOpenShell#5294] opened 2024-09-03 20:55 UTC
applying to any IFC conversion the x-axis translation using --model-offset “10;0;0” the model seems to be unaffected by it.
what am I doing wrong?

**Comment by Moult** [comment] 2024-09-04 02:25
Duplicate of https://github.com/IfcOpenShell/IfcOpenShell/issues/5231

**Closed by Moult** 2024-09-04 02:25 UTC
