### ISSUE TITLE
Error message when opening 

### ISSUE THREAD

**Issue by Ave-5D** [IfcOpenShell/IfcOpenShell#4982] opened 2024-07-05 13:04 UTC
Attached is the error report and the IFC file.
Please advise my error.
Thanks for your efforts. 

```
os: Windows
os_version: 10.0.19045
python_version: 3.10.13
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
blender_version: 4.0.2
blenderbim_version: 0.7.9.240626
last_actions: 
# operator: BIM_OT_load_type_thumbnails
# operator: BIM_OT_load_type_thumbnails
last_error: Traceback (most recent call last):
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\project\operator.py", line 691, in finish_loading_project
    bpy.ops.bim.load_project_elements()
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\project\operator.py", line 777, in execute
    tool.Project.load_default_thumbnails()
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\tool\project.py", line 56, in load_default_thumbnails
    bpy.ops.bim.load_type_thumbnails(ifc_class=ifc_class, offset=0, limit=9)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\ifc.py", line 381, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\bim\module\model\product.py", line 396, in _execute
    if tool.Model.update_thumbnail_for_element(element):
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\tool\model.py", line 802, in update_thumbnail_for_element
    tool.Profile.draw_image_for_ifc_profile(draw, profile, size)
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\tool\profile.py", line 40, in draw_image_for_ifc_profile
    shape = ifcopenshell.geom.create_shape(settings, profile)
  File "C:\Users\Roel\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\geom\main.py", line 361, in create_shape
    ifcopenshell_wrapper.create_shape(settings, inst.wrapped_data, repr.wrapped_data if repr is not None else None),
AttributeError: 'NoneType' object has no attribute 'wrapped_data'
Location: C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py:109
Location: C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py:109


ifc: 1bd house-IFC4X3.ifc
schema: IFC4X3
preprocessor_version: IfcOpenShell 0.0.0
originating_system: BlenderBIM 0.7.9.240626-de00429
```

[1bd house-IFC4X3.txt](https://github.com/user-attachments/files/16110025/1bd.house-IFC4X3.txt)

**Comment by Ave-5D** [comment] 2024-07-08 06:54
This error happens when I try to make a profile beam, deleted the type and now the error message is gone.

**Comment by Moult** [comment] 2024-07-09 01:12
Somehow, that IfcBeamType has a material profile... without a profile. Do you remember exactly how you created that IfcBeamType? I see it has the word "Copy" which suggests you duplicated an existing type. Do you recall what other steps you took? (see 'No profile' in the screenshot)

![2024-07-09-111221_334x650_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/7c45ff85-93d0-4a75-af06-631831f7e013)

**Comment by Moult** [comment] 2024-07-09 01:34
Oh, this is duplicate of #4978 - it's the same root cause.

**Closed by Moult** 2024-07-09 01:34 UTC
Labels: BlenderBIM

**Comment by Ave-5D** [comment] 2024-07-09 07:13
I used the library import to use IFCTypes from another IFCProject and I think I imported the profiles as well.
