### ISSUE TITLE
BlenderBIM: Highlighting the class of highlighted object in the properties pane

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#946] opened 2020-08-08 19:47 UTC
Just a simple UI suggestion. 

as you click on objects with different classes, it seems like it should reflect the current class of that object in the properties tab.

![2020-08-08_14-36-17](https://user-images.githubusercontent.com/507113/89718485-95c75300-d984-11ea-8791-7f3625df0f73.gif)

![image](https://user-images.githubusercontent.com/507113/89718494-a2e44200-d984-11ea-8cef-4d968b3b7a34.png)

---

BTW, is it okay to post these feature requests/suggestions here in the IfcOpenShell issue tracker?

Cheers, Ryan

**Comment by Moult** [comment] 2020-08-09 00:57
Absolutely - posting feature requests are are good :)

The screenshot you've shown is of the scene properties. Scene properties are not meant to be object specific - they are properties for the model as as whole.

In the object properties, the object class and name is displayed as shown. You are then allowed to browse the IFC class hierarchy before potentially reassigning the class.

![image](https://user-images.githubusercontent.com/88302/89722578-93b9ce80-da2e-11ea-8427-5fd85d831b2b.png)

The reason they don't reflect the current class is because the user may want to explore the class list prior to reassignment. Reassignment has implications for related qtos and psets, so it is not a light decision. If I made it a dropdown that always reflected the current class, then a misclick could be problematic.

That said, there are ways to make it less confusing to the user - but first I need to design the workflow of how to reassign classes safely (right now, it seems quick and easy, but potentially may lead to ISO-invalid pset and qto assignments).

**Comment by theoryshaw** [comment] 2020-08-09 14:51
> That said, there are ways to make it less confusing to the user - but first I need to design the workflow of how to reassign classes safely

Cool, yeah, minor suggestions.

Similar to how the 'PredefinedType' toggles, as you click on different objects, from a UI perspective, it seems Products/Class would toggle as well.  

![2020-08-09_09-43-06](https://user-images.githubusercontent.com/507113/89734968-c78ff680-da24-11ea-8c19-0b923be54519.gif)

---

> The screenshot you've shown is of the scene properties. Scene properties are not meant to be object specific - they are properties for the model as as whole.

Makes sense. By that logic, it would seem that the following should not be in 'scene properties'?--but only in 'object properties'.
![image](https://user-images.githubusercontent.com/507113/89735060-6f0d2900-da25-11ea-9080-e7e55b3278c0.png)

**Comment by Moult** [comment] 2020-08-09 23:30
Yeah - it should toggle ideally. The only way I know how to achieve that effect right now is to store it as an object property - right now the class is stored in the name. So if I don't find another way, for the moment, it's a "won't fix". Sorry, annoying answer, I know :(

In your second screenshot, the top half allows bulk assignment and selection of classes. Therefore it is not related to a single object. The bottom half deals with aggregates - which are more than one object.

**Comment by Moult** [comment] 2020-08-29 08:58
An update that I think I know how to fix this one now. It's back on the menu.

**Comment by Moult** [comment] 2020-11-03 12:00
So I kinda fixed this in a different way to the way I thought I would, but I think it's less confusing now, so I'm closing the bug.

**Closed** 2020-11-03 11:59 UTC
Labels: BlenderBIM

**Comment by CyrilWaechter** [comment] 2020-12-11 15:51
IfcClass is now kind of hidden and has not its own visible field which feels awkward. If the issue is a misclick maybe it is possible in Blender to lock field until you click on Reassign IFC Class ?
