### ISSUE TITLE
Cannot delete / duplicate elements or strange behaviour with other add-ons enabled

### ISSUE THREAD

**Issue by CyrilWaechter** [IfcOpenShell/IfcOpenShell#2645] opened 2022-12-11 22:20 UTC
# Expected behavior
Objects deleted in Blender are deleted in ifc file.
# Current behavior
Objects deleted in Blender are not deleted in ifc file.
# Steps to reproduce
1. Import [FirstBlenderBIM_BEM_Model.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/10203414/FirstBlenderBIM_BEM_Model.zip)
2. Delete Wall.001 from scene or outliner
3. Delete Space.001 and Space.002 from scene or outliner
4. Save Project in scene properties -> IfcProject
5. Open a new blender session or blender file
6. Import file saved at step 4
# System infos
OS: Manjaro Linux
BlenderBIM Add-on version: 05cd11a locally compiled
Blender version: 3.3.1

**Comment by CyrilWaechter** [comment] 2022-12-13 21:09
@theoryshaw Thanks for testing. And yes it is actually an interference with another plugin which is unfortunately ArchiPack (2.5.1). @s-leger any idea where it could come from and it could be fixed from blenderbim or ArchiPack ?

**Comment by s-leger** [comment] 2022-12-14 00:03
In order to confirm and as workaround, open archipack's main ´´´__init__.py``` and comment the line  
'io_export_ifc',
in modules list.

**Comment by CyrilWaechter** [comment] 2022-12-14 00:59
> In order to confirm and as workaround, open archipack's main ´´´__init__.py``` and comment the line 'io_export_ifc', in submodules list.

Commenting line 93 (io_export_ifc) has no effect.

**Comment by s-leger** [comment] 2022-12-14 01:05
So it definitely is not an issue related to archipack.

**Comment by Moult** [comment] 2022-12-14 01:08
The BlenderBIM Add-on overrides the delete operator in order to catch IFC deletions. https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/module/geometry/operator.py#L393 @s-leger can you think how this might be related?

**Comment by s-leger** [comment] 2022-12-14 01:34
Any other addon also overriding that operator may prevent your call.
Archipack override delete operator while manipulate mode is active (so if any archipack's object is active it may interfer in the process)

**Comment by Moult** [comment] 2022-12-14 01:51
@CyrilWaechter can you throw in a random print statement or something into that override operator to make sure that the event is bubbling up and that it's being triggered?

**Comment by CyrilWaechter** [comment] 2022-12-14 19:48
@Moult I did. When ArchiPack is activated `OverrideDelete.execute` is not triggered but is when ArchiPack is deactivated.

**Comment by s-leger** [comment] 2022-12-15 01:49
@Moult
@CyrilWaechter 
With auto-manipulate active or when you delete archipack object using "delete" button, archipack does take care of removing objects + hierarchy and relevant datablocks using archipack's delete operator with low level api calls bypassing regular blender delete operator and any overriden one.

So i think the workaround is to disable auto-manipulate and ensure manipulate mode is not active before deleting your objects (no visible manipulators).

**Comment by Moult** [comment] 2022-12-15 01:51
@s-leger I don't think it's to do with whether auto-manipulate is active or not, I think when ArchiPack registers its operators, it has already bypassed the BlenderBIM Add-on's operator.

**Comment by s-leger** [comment] 2022-12-15 01:55
Archipack does not override any blender operator, they are all namespaced.
But when manipulate modal is running, it does listen for keyboard "X" events (or any associated key) and disable manipulate mode, then delete the objects by calling bpy.archipack.delete() operator.

**Comment by Moult** [comment] 2022-12-15 03:11
@CyrilWaechter can you confirm that it only occurs with auto-manipulate active? You can also test deleting items in the outliner.

**Comment by CyrilWaechter** [comment] 2022-12-16 21:35
> @CyrilWaechter can you confirm that it only occurs with auto-manipulate active? You can also test deleting items in the outliner.

Nope. It occurs if auto-manipulate is not active.
Deleting items from 3D view or outliner have same effect.

**Comment by Tudjack** [comment] 2022-12-18 11:46
I have the same problem and it's not Archipak (or not only) related. I tested it on two Windows machines and on Manjaro and I still have no idea which add-on is causing the issue. It might be one of the add-ons which ship with Blender by default.

**Comment by Moult** [comment] 2023-01-06 02:37
@Tudjack can you follow the instructions in FAQ number 3 https://blenderbim.org/docs/users/installation.html#faq and see if you can recreate the issue on a vanilla Blender?

**Comment by Tudjack** [comment] 2023-01-06 08:29
On a vanilla Blender installation I do not get this issue. I also tested a few third party add-ons and also some add-ons which come with Blender and I found out the following are problematic (so far):

- Machine Tools, HardOps, BoxCutter, MeasureitArch
- enabling Mesh Extra Objects, Modifier Tools, Bool Tool, Carver

Third party add-ons which are not producing the issue:
- CadTransfom, ConstructionLines
- enabling Measureit, 3D Print Toolbox, tinyCad

**Comment by Moult** [comment] 2023-02-22 04:02
@Tudjack thanks! That research was critical to helping debug this. It seems to me that this bug is not caused by any code, but instead due to the sheer volume of operators being registered in Blender (the BlenderBIM Add-on itself has nearly 900 operators!).

I've filed a bug upstream to Blender here https://projects.blender.org/blender/blender/issues/105063

However this bug is effectively a ticking time bomb if upstream doesn't have a solution fast and / or we want to continue supporting Blender 3.4. Thoughts @ecke101 @Gorgious56 @s-leger ?

**Comment by Gorgious56** [comment] 2023-02-22 08:40
That is bad, indeed. One immediate ugly, hacky workaround I can see is at least for operators that don't directly override builtin operators, to have a "main" operator where we use custom parameters to execute custom functionality. 

I don't think that would be too hard to implement, thanks to the efforts you made to abstract as much as possible the blender logic from the ifcopenshell logic. eg these 2 operators could (?) be merged as one https://github.com/IfcOpenShell/IfcOpenShell/blob/921a185ffa96851e3b8300a7bacb5e1976cbb6cd/src/blenderbim/blenderbim/bim/module/bimtester/operator.py#L82-L113  It would be *very* time consuming though.

I realize writing this that it would in the mid-long term be a bad design decision, but I don't really see another way to circumvent the problem. Apart from maybe un-registering operators that are never used in the context of the BlenderBIM Add-on, eg sculpting operators, video editing operators, movie tracking operators, etc.

**Comment by s-leger** [comment] 2023-02-22 11:03
As temporary workaround, would create a "Workspace" and use addon filtering to disable everything but blenderbim and minimal set of other addons allowing mesh editing.

**Comment by Andrej730** [comment] 2023-02-23 14:49
It's seems that for now we should count operators at some point and atleast give a warning to the addons users.
It also would be nice to find some way to test if operator was overridden or not to make this warning more relevant. Yet can't find any way to determine it for now.

**Comment by Gorgious56** [comment] 2023-02-23 16:54
I seriously hope there is a better solution but if you're okay wint an ugly, hacky one :
- unregister the operator
- test if it is still present in `bpy.ops`. If it is, the operator was an override
- Alternatively you can try calling it and if it doesn't raise an error, it's an override. But I don't think it's practical
- register it again

```
import bpy


class OverrideOperator(bpy.types.Operator):
    bl_idname = "mesh.primitive_cube_add"
    bl_label = "Simple Object Operator"

    def execute(self, context):
        print("override")
        return {'FINISHED'}


class NotOverrideOperator(bpy.types.Operator):
    bl_idname = "mesh.test"
    bl_label = "Simple Object Operator"

    def execute(self, context):
        print("not override")
        return {'FINISHED'}


if __name__ == "__main__":
    bpy.utils.register_class(OverrideOperator)
    bpy.utils.register_class(NotOverrideOperator)

    bpy.utils.unregister_class(OverrideOperator)
    print("primitive_cube_add" in dir(bpy.ops.mesh))  # True
    bpy.ops.mesh.primitive_cube_add()  # no error
    bpy.utils.unregister_class(NotOverrideOperator)
    print("test" in dir(bpy.ops.mesh))  # False
    bpy.ops.mesh.test()  # error
```

**Comment by s-leger** [comment] 2023-02-23 17:12
Unfortunately this is not relevant as override is "register order" dependant. 
So basically any addon regitering after blenderbim may override the delete operator without any meanfull way to detect it - so such kind of hack is pretty fragile.

**Comment by Gorgious56** [comment] 2023-02-23 17:32
Alright, it makes sense. So another solution would be to ditch operator overrides altogether since they are visibly cumbersome, and mess with the keymaps. Unregister "X" and "Delete" in the 3D viewport and replace them with a call to blenderbim custom operators in the user keymaps. I do not know however if one can unergister builtin keymaps. Or if it's something we want to do UX wise.

**Comment by ecke101** [comment] 2023-02-23 19:27
I'm still hoping for some core developer to see that report and take care of it, but the Python API historically has not gotten much attention sadly.

**Comment by Moult** [comment] 2023-02-24 02:49
Keymap messing is not a solution either as there are lots of menu / context items where these operators are referenced, or other custom shortcuts, quick favourites, ...

**Comment by Andrej730** [comment] 2023-02-24 10:34
I've found some code that works identifying if operator was overriden or not.
To test it you can disable all your blender addons and run the example below.

If there is no pitfalls to this method we can actually use it to test if operator was previously overriden before us and warn users.
We also can add some check later on to warn user if our operators were overriden by some other addon. Not sure where to put this check though.

I guess it will be reasonable to add both these checks no matter how [blender issue](https://projects.blender.org/blender/blender/issues/105063) will be resolved.

```python
import bpy

bl_idname = 'object.delete'

def get_operator_by_idname(bl_idname):
    """
        Returns `None` if bl_idname is not defined by any other addon
        if it's built-in operator and it wasn't overriden that it will also return None
        So the method can be used to check if operator was overriden previously.
    """
    for module in dir(bpy.types):
        cls = getattr(bpy.types, module)
        if hasattr(cls, 'bl_idname') and cls.bl_idname == bl_idname:
            return cls, module


class OverrideDelete(bpy.types.Operator):
    bl_idname = "object.delete"
    bl_label = "Delete"
    bl_options = {"REGISTER", "UNDO"}
    use_global: bpy.props.BoolProperty(default=False)
    confirm: bpy.props.BoolProperty(default=True)

    @classmethod
    def poll(cls, context):
        return len(context.selected_objects) > 0

    def execute(self, context):
        print('RUNNING OVERRIDE DELETE')
        return {"FINISHED"}

print(get_operator_by_idname('object.delete'))
bpy.utils.register_class(OverrideDelete)
print(get_operator_by_idname('object.delete'))
```

**Comment by Moult** [comment] 2023-02-26 00:28
Agreed, there are two issues here: 1) colliding with another add-on trying to override the same operator and 2) the Blender bug where built-in overrides fail after N operators. If we can detect the first and warn the user that's a good thing.

Go ahead and implement @Andrej730  :)

**Comment by Moult** [comment] 2023-02-28 03:49
The Blender devs have spoken and said that overriding built-ins is now no longer allowed: https://projects.blender.org/blender/blender/issues/105063

I've responded on the ticket asking if we could make it possible, but if they disagree, then we need to urgently come up with a solution to this.

**Comment by s-leger** [comment] 2023-02-28 03:57
Alternative could be to ask for app.pre_delete() callback where you may register your own callbacks like the file_load_pre and post.

**Comment by Moult** [comment] 2023-02-28 04:06
@s-leger good idea, I've edited my post and asked for it.

**Comment by Andrej730** [comment] 2023-02-28 04:32
That's very unfortunate 
If they won't agree to revert the change and even if they agree to add some support for callbacks it's very possible that Blender 3.5 will be released without option to add something to built-ins using addons because 3.5 now is in fixing bugs stage so all new features like API callbacks would go atleast to 3.6 🥲
![image](https://user-images.githubusercontent.com/9417531/221753771-beb5659d-f489-4538-9afe-a3679be7407d.png)

**Comment by Moult** [comment] 2023-03-01 03:31
OK, we now rely on hotkey overriding, and for those who don't use these pretty fundamental hotkeys, well, it's their responsibility to manage their own keymap I guess :(

Also the IFC variants of the built-ins are also available in the object menu options.

**Closed** 2023-03-01 03:31 UTC
Labels: BlenderBIM

**Comment by ecke101** [comment] 2023-03-01 13:07
I want to try to fix this in some way but I'm trying to figure out what the handlers would have to be able to do.

The easiest to implement would probably be an `object_delete_pre` handler that just brings a read-only context.
From that BlenderBIM could check `selected_objects` to see which items are being deleted and do its thing.

It looks like Outliner Delete modifies the original hierarchical behaviour a bit, so that might be harder to cover with just a pre-handler?

What about `DuplicateMove` and `DuplicateMoveLinked`. I guess those would need both pre and post?

It will probably take a while to figure out the best design of this anyway.

**Comment by Moult** [comment] 2023-03-02 13:25
@ecke101 how do handlers work with undo/redo? And what is the best channel to propose improvements like this to Blender?

**Comment by ecke101** [comment] 2023-03-07 20:52
> @ecke101 how do handlers work with undo/redo? And what is the best channel to propose improvements like this to Blender?

It's hard to reach someone who wants to touch any of this stuff. Right now I'm trying to figure out if there is a way to get a unique identifier of an undo step, or generate one when the step is created that can be read later in Python. if that was the case, maybe that id could be saved somehow in ifcopenshell together with the operation run. And then on undo/redo the handler would roll back ifcopenshell to the current Blender undo id...
It's the solution I can think of to sync blender with ifcoopenshell. I guess the tiny problem here is implementing the undo in ifcopenshell too.

**Comment by ecke101** [comment] 2023-03-10 16:11
@Moult what do you think? would this project be helped by being able to get the undo stack and current undo hash from python?

**Comment by Moult** [comment] 2023-03-12 02:05
I'm actually pretty OK right now with the hotkey overriding approach, it seems pretty stable and there is also a different "IFC Delete" menu item to distinguish that we are doing something special.

However I do have another issue with the undo/redo system that would be super helpful to fix.

Right now we listen to undo/redo events which triggers ifcopenshell undo redos as well - this works well. However what doesn't work well is that we have a dictionary map of blender objects to IFC IDs (which is used in many places to conveniently select the Blender / IFC element equivalent). However during the undo/redo process some of these Blender objects become invalid and it is tricky to recover them (we use all sorts of strange tricks). I wonder if there is a better way. (A stable way to store the Blender IFC ID map is using Blender pointer properties and a collection property but it doesn't scale when you have 30,000+ objects).

**Comment by ecke101** [comment] 2023-03-12 20:55
@Moult it seems to me like still the undo/redo would break if a user jumps to an undo step other than the previous/next (using Edit -> Undo History for example).
In that case wouldn't it be helpful to have access to the hash of the undo step and match it with the `transaction_key` in ifcopenshell with a map?

About the invalidated objects it's likely hard to come up with a better solution than the current.

**Comment by Moult** [comment] 2023-03-13 07:30
@ecke101 yes you are right, it would break in that situation! A hash would really help.
