### ISSUE TITLE
Windows don't seem to print

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3510] opened 2023-07-26 21:24 UTC
Windows don't seem to print, for some reason.

file:
[elevation.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/12177237/elevation.ifc.txt)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/47b86f8c-58e8-4e93-9204-2ba3dc32d5e1)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/89c6e381-c403-4a41-bd56-d0d727bfe2f5)

**Comment by Moult** [comment] 2023-07-27 03:01
Ping @aothms this seems to be a regression in https://github.com/IfcOpenBot/IfcOpenShell/commit/fc50bdd3a0354cf332ad846f0a336a9bbfd4a769#comments

It works in 8f41ae0 - potentially fixed in https://github.com/IfcOpenBot/IfcOpenShell/commit/2ee0dcaf642897575b20f773f324c2f311af5767 but I don't have a bot build to test with. Can you help investigate or if you think it's already fixed go and bump the bot builds?

**Comment by Moult** [comment] 2023-07-27 12:34
BTW if you want to downgrade to https://github.com/IfcOpenBot/IfcOpenShell/commit/8f41ae0c1b865e529a13c275dd2723d70ce4822e#comments which is older but seems to not have a bunch of bugs that prefiltering introduced just download ifcopenshell from that link, then copy over ifcopenshell_wrapper.py and _ifcopenshell_wrapper.(dll? i think Windows will have a dll) to your blenderbim/libs/site/packages/ifcopenshell folder (it should overwrite the two existing files ... keep backups!) then comment out this line: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/module/drawing/operator.py#L841

**Comment by Plae-Blue-Dot** [comment] 2023-08-01 08:52
getting the same error on an ongoing project that was working previously:
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/78321676/05d0b23d-afb2-4e18-b049-535d8739f937)

Some windows are still working but most are not

**Comment by Moult** [comment] 2023-08-01 08:57
Unfortunately this is a critical bug until there is a new bot build out with a fix so for the moment I recommend downgrading just the IfcOpenShell build https://github.com/IfcOpenShell/IfcOpenShell/issues/3510#issuecomment-1653533697

**Comment by Plae-Blue-Dot** [comment] 2023-08-01 08:59
Thanks @Moult will do!

**Comment by aothms** [comment] 2023-08-10 02:55
Hm, I should look into getting a different email notification for mentions. I missed this one for some reason. I have implemented a quick work around that should be good enough for the foreseeable future. My hands are tied a bit because I don't want to implement a comprehensive solution using e.g boolean 2d intersection that would completely eliminate all performance gains of this approach. Bot builds should be running again starting next week.

**Comment by Moult** [comment] 2023-08-10 03:04
@aothms you can alternatively also filter issues by tag IfcOpenShell-Core :) or https://github.com/notifications?query=reason%3Amention ?

Cheers will test it out!

**Comment by Moult** [comment] 2023-08-13 07:16
Based off a local build it looks fixed here!

**Comment by Plae-Blue-Dot** [comment] 2023-08-14 12:16
Where could I find the build @Moult ? Still seem to have the issue with 230814

**Comment by theoryshaw** [comment] 2023-08-14 14:26
@Plae-Blue-Dot how to tell when a new IfcOpenShell build has been built...
https://github.com/IfcOpenShell/IfcOpenShell/commit/3345d7e08803e7c1bf677348083820214ff450fd#commitcomment-124250896

@Moult curious, why do these builds take longer, than the ifcopenshell daily release?

**Comment by theoryshaw** [comment] 2023-08-14 16:13
gotcha... figured it might be memory intensive.

**Comment by Plae-Blue-Dot** [comment] 2023-08-22 08:43
Tried today's build and windows seem to be working! Great Job!

**Closed** 2023-08-22 10:06 UTC
Labels: IfcOpenShell-Core
