### ISSUE TITLE
BlenderBim - Feature request - Joined hatches & walls

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2799] opened 2023-02-22 09:21 UTC
Hi all, I've come once again to see what could be possible,

The request is to have contiguous joins along the separate walls when using a hatch that isn't the default black

![image](https://user-images.githubusercontent.com/78321676/220575737-db027465-8985-47ad-b4b5-1e5629eccb8a.png)

As it is currently walls look like this when cut with a hatch:

![image](https://user-images.githubusercontent.com/78321676/220576445-05a28436-d724-4f98-b638-a7bcfc9ca379.png)

With the wall joins visible

Until now I have gotten around this is 3 ways

1. Using fill areas everywhere (on every individual drawing)
2. Using an IfcSlab @ 1600mm height & excluding walls in camera (& excluding the slab in elevations & sections)
3. editing the pdf in Gimp after exporting the drawing (Boo)

But it'd be cool to move on from these tricks

**Comment by Moult** [comment] 2023-02-22 09:27
Discussed first here https://github.com/IfcOpenShell/IfcOpenShell/issues/1153#issuecomment-1107447509

@aothms reckons this can be done in the svgfill part, which I have disabled in the BlenderBIM Add-on because from early tests it was prohibitively slow, even on small models. @aothms might know the current status of this.

I think first we can determine through RelConnects relationships whether or not the object should be shown merged in a drawing, and use those to figure out what to union in the svg world. @aothms thoughts? Is there some simple code sample I can use to get this prototyped?

**Comment by aothms** [comment] 2023-02-22 09:36
Hm, so my guess would be that the svgfill part is slow because it tries to do this on the projected data (which is very detailed when it comes from the faceted blender world). But the cut areas is usually much more modest in amount. So running the cell merging on the cut areas shouldn't be any performance concern. Note that strictly we're not doing a boolean, we're eliminating edges on a cgal arrangement to join one or more cells. I would be tempted to think you got everything available for this in terms of API, but I'm leaving for a quick holiday break tomorrow I don't have the capacity now to investigate.

**Comment by Moult** [comment] 2023-02-28 12:05
I ended up not using the svg_to_line_segments et all because from what I read those functions are meant for a soup of lines? Given that these are cut areas I think we can just merge the polygons and not have to worry about the whole raycasting thing.

Here's a first attempt with shapely - for now, hardcoded to walls, coverings, and slabs with the same material - later it can be made more flexible and perhaps also check for IfcRelConnects relationships:

![2023-02-28-225436_393x552_scrot](https://user-images.githubusercontent.com/88302/221849378-58cc032b-145e-4eb4-81ec-fdb3e862ec54.png)

**Comment by aothms** [comment] 2023-02-28 12:17
True, falling back to soup of lines (this is indeed the output of the occt hlr code) has advantages though in case of overlapping areas or maybe in the ability to delineate areas by means of non-area annotations (I don't know if that ever comes up) like dividing a wall in two by means of a simple line (that doesn't sound very bimy though)

**Comment by Moult** [comment] 2023-02-28 12:24
Hatch patterns in projection I feel is a bit more complex. That's because hatch patterns actually have meaning. For example, the hatch pattern may have a direction which distinguishes the fall of a roof (so either you split up your hipped roof into each segment, or you do some voodoo to manage per face(??) hatching). Or another example is hatch patterns for ceiling tile or floor board / tile setout points where the orientation and "start point" is object (or face?) dependent.

... I guess we just keep on chipping away and trying to solve problems one step at a time.

**Comment by aothms** [comment] 2023-02-28 12:30
Yes we encountered the same issue earlier. We had a hatch that indicated the direction of the roof shingles. This really doesn't work as a paper space element in case of complex roof shapes or non-standard view directions. We had a rather rudimentary hatch specification though, not sure what's possible in full IFC.

**Comment by Moult** [comment] 2023-02-28 12:47
I'm also curious what the performance difference is between svgfill and shapely. Shapely also has a "polygonize" from line soup function which we use to generate space shapes from bounding walls. Of course it also needs extra work to get a "point in poly" which svgfill provides. What other differences are there?

**Comment by aothms** [comment] 2023-02-28 13:36
Does `polygonize()` really create cells from inner regions bounded by non-end-to-end connected poly lines? (https://github.com/IfcOpenShell/svgfill#example)

**Comment by Moult** [comment] 2023-02-28 13:38
Yes. Line soup :)

**Comment by Moult** [comment] 2023-02-28 13:48
https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/module/model/space.py#L75-L76

**Comment by aothms** [comment] 2023-02-28 13:49
It doesn't. Not in the way at least I meant to imply.

![afbeelding](https://user-images.githubusercontent.com/1096535/221872721-31371634-2750-4909-9734-2dc566c9b67d.png)

```
>>> import numpy
>>> from matplotlib import pyplot as plt
>>> from shapely.ops import polygonize
>>>
>>> lines = [
...     ((2, 1), (2, 5)),
...     ((4, 1), (4, 5)),
...     ((1, 2), (5, 2)),
...     ((1, 4), (5, 4)),
... ]
>>> list(polygonize(lines))
[]
>>> lines = numpy.array(lines) 
>>> [plt.plot(*l.T) for l in lines]
[[<matplotlib.lines.Line2D object at 0x0000028C46B86A90>], [<matplotlib.lines.Line2D object at 0x0000028C46B86DC0>], [<matplotlib.lines.Line2D object at 0x0000028C46B9F0A0>], [<matplotlib.lines.Line2D object at 0x0000028C46B9F340>]]
>>> plt.show()
```

**Comment by aothms** [comment] 2023-02-28 14:03
Edit: and showing svgfill / cgal arrangement_2

```python
import numpy
import ifcopenshell
from matplotlib import pyplot as plt
lines = [
    ((2., 1.), (2., 5.)),
    ((4., 1.), (4., 5.)),
    ((1., 2.), (5., 2.)),
    ((1., 4.), (5., 4.)),
]
W = ifcopenshell.ifcopenshell_wrapper
ctx = W.context(W.FILTERED_CARTESIAN_QUOTIENT, 1.0e-3)
ctx.add(lines)
ctx.build()
ps = W.svg_groups_of_polygons()
ctx.write(ps)
lines = numpy.array(lines)
[plt.plot(*l.T) for l in lines]
plt.fill(numpy.array(ps[0][0].boundary).T[0], numpy.array(ps[0][0].boundary).T[1], alpha=0.2)
plt.show()
```

![afbeelding](https://user-images.githubusercontent.com/1096535/221876748-57506da0-a779-47f6-a973-d9b243ce4b61.png)

**Comment by Moult** [comment] 2023-02-28 14:12
Union all first?

**Comment by Moult** [comment] 2023-02-28 21:36
Sorry for the confusion, isn't this what you're after:

```python
import shapely
from shapely.ops import polygonize

lines = [
    ((2, 1), (2, 5)),
    ((4, 1), (4, 5)),
    ((1, 2), (5, 2)),
    ((1, 4), (5, 4)),
]
lines = [shapely.LineString(l) for l in lines]
results = polygonize(shapely.union_all(shapely.GeometryCollection(lines).geoms))
for poly in results:
    print(poly)
    # POLYGON ((2 2, 2 4, 4 4, 4 2, 2 2))
```

Which gives the same result as svgfill?

**Closed** 2023-03-01 06:53 UTC
Labels: BlenderBIM

**Comment by aothms** [comment] 2023-03-01 07:43
Thanks, yes I managed to get it to work as well, sorry for not posting back. The key difference here (as far as I can oversee) is the data model. The cgal arrangement is an interactive planar arrangement, so if we were to merge two cells (as we were talking about here) we can simply remove the edge and only that local operation causes the cells to be merged. The geometry collection approach is more static and would cause a lot of recomputation. Same for edge insertion. So if we were to compare performance we'd need to compare over a certain complex scenario.

If svgfill is the performance bottleneck I'd be tempted to say the problem is in the information we feed it, like many overlapping edges or something else that could simply be filtered out. The FILTERED_CARTESIAN_QUOTIENT is an interval math datatype using hardware floats that falls back to software number types in case of an uncertain result obtained from the limited precision hardware floats. I can imagine for example that this "wire-frame hack" we discussed earlier to ease out on the hidden line rendering complexity actually causes many overlapping edges and also more cells because of the otherwise hidden edges.

I think what we should be doing is creating much more minimal models of interaction between various elements. Detailed element obscuring simple element, detailed element obscuring detailed element, etc. 2 detailed elements 3 detailed elements 4 detailed elements so that we can really begin to understand what is the bottleneck and where.

Like I said, I'm not that pessimistic in that we can get this all to work, but in terms of where the performance suffers we're still completely in the dark.
