### ISSUE TITLE
BB: manually moving an object into a IfcSpatialElement, via the outliner, automatically updates the IFC Spatial Container assignment, as well. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1867] opened 2021-11-09 14:34 UTC
A UI suggestion: intuitively it feels when an object is manually moved into an **IfcSpatialElement** collection, via the outliner, that it would automatically update the **IFC Spatial Container** assignment, as well. 

Either that, or not automatically move it within the outliner when the object is assigned a new **IFC Spatial Container** via the object properties.  

Just to be consistent.

**Comment by Moult** [comment] 2021-11-10 00:58
Yeah the problem is that I can't know when an object has been reassigned to a different collection. Ping @ecke101 @Gorgious56 is there a way to subscribe to an event or know when the object's user collection has changed?

**Comment by Gorgious56** [comment] 2021-11-10 07:47
Unfortunately AFAIK there is no efficient way of keeping track of this. We'd have to keep a dict of dicts of all `Object > (N) Collections` in memory, recreate it on all [dependency graph updates](https://docs.blender.org/api/current/bpy.app.handlers.html#bpy.app.handlers.depsgraph_update_post) and compare both to get changes...

It's definitely doable on small scenes but I don't think it'd scale well with thousandths of objects.

However we may be able to overload `bpy.ops.outliner.collection_drop()` to get a feedback when a user moves an object in the outliner and `bpy.ops.object.collection_link` when it adds a new collection in the object properties ?

**Comment by Moult** [comment] 2021-11-10 08:22
Ah yes overloading sounds plausible. Would you be interested in trying to solve this one @Gorgious56 ? There's a bunch of already overridden operators [here](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/module/geometry/operator.py#L314-L469) but I suspect the collection link might be more annoying since it has to rebuild the popup menu hierarchy, and I'm not certain how collection_drop reads the drop target.

**Comment by Gorgious56** [comment] 2021-11-10 08:32
Yeah I'll poke around, see how it could work :) I horribly messed up my dev setup some time ago and haven't got around to fixing it that's why I haven't been contributing as much but I plan on spending some time fixing it tomorrow !

**Comment by Moult** [comment] 2021-11-11 11:28
@Gorgious56 by the way I just overrode the outliner.delete operator so there might be some code you might find useful - also I had no idea how to write a test for it since it depends on the context (I tried setting bpy.context.area.type = "OUTLINER" but it turns out bpy.context.area is None when running headless): https://github.com/IfcOpenShell/IfcOpenShell/commit/5ba155eb17ffd50be30d1d92a879c7adec8c9e51

**Comment by Gorgious56** [comment] 2021-11-16 08:07
NGL I'm stuck... Seems like drag and drop functionality is not exposed to the python API so unless doing dirty magick to poll the cursor position an derive what's under it I don't even know if we can access which objects or collections are currently being dragged from or dropped on. And yeah I find outliner context override a mess in general...

**Comment by theoryshaw** [comment] 2021-11-16 17:30
Worth an upstream feature request? If you start it somewhere, I'll +1 it, and spread the word.

**Comment by Moult** [comment] 2021-11-16 22:32
From @ecke101 - perhaps you can investigate @Gorgious56 ? Btw there is an existing subscribe_to function you can use in blenderbim.bim.handler:

> 09:04 <erab> Moult, gorgious56[m], looks like i have managed to add a msgbus message on bpy.types.Collection.object when an item is dragged in the outliner.. is this what you wanted?
> 09:04 <erab> it should be "objects", not "object".
> 09:11 <Moult> erab: woooo! yes indeed that could be it!
> 09:12 <erab> any other messages missing?
> 09:12 <erab> i seem to recall "collections" on the object is implemented in python so that's probably not possible.
> 09:22 <erab> i guess "children" on the collection could be useful for someone as well.
> 09:31 <Moult> erab: yep. i tried subscribing to users_collection without luck. i'll post it in the bugreport

**Comment by theoryshaw** [comment] 2021-11-17 00:30
from convo here: https://matrix.to/#/!ssOmSJysZpXBupsgjO:matrix.org/$uLTbV3RhxPBj1sNvZHEyeSgnxWXxaitdamGaqwKGEXQ?via=libera.chat&via=matrix.org&via=tchncs.de

Just logging.

**Comment by theoryshaw** [comment] 2021-11-17 00:32
To log your token (+1) love...
https://developer.blender.org/D13253

**Comment by Moult** [comment] 2022-01-17 05:39
It looks as though this one is impractical to solve on the Blender side. We also already sync this on export. So perhaps it's not such a huge deal?

**Comment by Moult** [comment] 2024-06-05 02:52
Ping @Andrej730 this is the bug I was referring to when we had issues trying to sync the outliner in the past.

**Comment by Moult** [comment] 2024-06-28 05:06
This is finally resolved as the outliner organisation is now decoupled from spatial decomposition.

**Closed by Moult** 2024-06-28 05:06 UTC
Labels: BlenderBIM
