### ISSUE TITLE
Can't add Door's or Window's TAGs

### ISSUE THREAD

**Issue by aslejo0395** [IfcOpenShell/IfcOpenShell#5355] opened 2024-09-09 12:01 UTC
```
os: Windows
os_version: 10.0.19045
python_version: 3.11.7
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
blender_version: 4.2.1 LTS
bonsai_version: 0.8.1-alpha240909
bonsai_commit_hash: 09b8c44
last_actions: 
# ifcopenshell.api: attribute.edit_attributes
>>> {"product": {"cast_type": "entity_instance", "value": 1970, "Name": "Door"}, "attributes": "{'GlobalId': '2gK6NqB3P5Bxo2n3tAZbUJ', 'Name': 'Door', 'Description': None, 'ObjectType': None, 'Tag': 'D-1', 'OverallHeight': 2000.0, 'OverallWidth': 900.0, 'PredefinedType': None, 'OperationType': None, 'UserDefinedOperationType': None}"}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 1970, "Name": "Door"}}
# operator: BIM_OT_annotation_hotkey
# ifcopenshell.api: root.create_entity
>>> {"ifc_class": "IfcAnnotation", "predefined_type": "TEXT", "name": "DOOR-TAG"}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: type.assign_type
>>> {"related_objects": [{"cast_type": "entity_instance", "value": 5579, "Name": "DOOR-TAG"}], "relating_type": {"cast_type": "entity_instance", "value": 144, "Name": "DOOR-TAG"}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 5496, "Name": null}}
# ifcopenshell.api: type.map_type_representations
>>> {"related_object": {"cast_type": "entity_instance", "value": 5579, "Name": "DOOR-TAG"}, "relating_type": {"cast_type": "entity_instance", "value": 144, "Name": "DOOR-TAG"}}
# ifcopenshell.api: geometry.map_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 142, "Name": null}}
# ifcopenshell.api: geometry.assign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 5579, "Name": "DOOR-TAG"}, "representation": {"cast_type": "entity_instance", "value": 5586, "Name": null}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 5579, "Name": "DOOR-TAG"}}
# operator: BIM_OT_annotation_hotkey
# ifcopenshell.api: root.create_entity
>>> {"ifc_class": "IfcAnnotation", "predefined_type": "TEXT", "name": "DOOR-TAG"}
# ifcopenshell.api: owner.create_owner_history
>>> {}
# ifcopenshell.api: type.assign_type
>>> {"related_objects": [{"cast_type": "entity_instance", "value": 5588, "Name": "DOOR-TAG"}], "relating_type": {"cast_type": "entity_instance", "value": 144, "Name": "DOOR-TAG"}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 5496, "Name": null}}
# ifcopenshell.api: type.map_type_representations
>>> {"related_object": {"cast_type": "entity_instance", "value": 5588, "Name": "DOOR-TAG"}, "relating_type": {"cast_type": "entity_instance", "value": 144, "Name": "DOOR-TAG"}}
# ifcopenshell.api: geometry.map_representation
>>> {"representation": {"cast_type": "entity_instance", "value": 142, "Name": null}}
# ifcopenshell.api: geometry.assign_representation
>>> {"product": {"cast_type": "entity_instance", "value": 5588, "Name": "DOOR-TAG"}, "representation": {"cast_type": "entity_instance", "value": 5595, "Name": null}}
# ifcopenshell.api: owner.update_owner_history
>>> {"element": {"cast_type": "entity_instance", "value": 5588, "Name": "DOOR-TAG"}}
last_error: Traceback (most recent call last):
  File "C:\Users\Gerardo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ifc.py", line 408, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gerardo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\workspace.py", line 278, in _execute
    getattr(self, f"hotkey_{self.hotkey}")()
  File "C:\Users\Gerardo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\workspace.py", line 304, in hotkey_S_A
    create_annotation()
  File "C:\Users\Gerardo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\workspace.py", line 184, in create_annotation
    create_annotation_occurrence(bpy.context)
  File "C:\Users\Gerardo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\workspace.py", line 171, in create_annotation_occurrence
    bonsai.core.type.assign_type(tool.Ifc, tool.Type, element=element, type=relating_type)
  File "C:\Users\Gerardo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\core\type.py", line 39, in assign_type
    type_tool.change_object_data(obj, type_data, is_global=False)
  File "C:\Users\Gerardo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\type.py", line 33, in change_object_data
    tool.Geometry.change_object_data(obj, data, is_global)
  File "C:\Users\Gerardo\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\tool\geometry.py", line 55, in change_object_data
    obj.data = data
    ^^^^^^^^
TypeError: bpy_struct: item.attr = val: Object.data expected a Image type, not Mesh

ifc: 2024-09-05_OfficeSpace.ifc
schema: IFC4
preprocessor_version: IfcOpenShell 0.8.1-alpha240908
originating_system: Bonsai 0.8.1-alpha240908-2f02621
```

**Comment by Andrej730** [comment] 2024-09-09 12:08
Duplicate of #5300

**Comment by theoryshaw** [comment] 2024-09-09 12:08
Probably related: https://github.com/IfcOpenShell/IfcOpenShell/issues/5350

**Closed by Andrej730** 2024-09-09 12:08 UTC
