### ISSUE TITLE
Implementing IFC type with decomposition 

### ISSUE THREAD

**Issue by myoualid** [IfcOpenShell/IfcOpenShell#3592] opened 2023-08-16 15:05 UTC
Following on from https://community.osarch.org/discussion/908/
Probably a pandara's box kinda thing, but this is a cool concept we need to implement at some point :D

**Comment by Moult** [comment] 2023-08-17 06:04
Yeah this is a bit of a complex implementation which will take time to get sorted correctly.

**Comment by Moult** [comment] 2023-08-17 06:05
Duplicate of #2052

**Closed by Moult** 2023-08-17 06:05 UTC
Labels: BlenderBIM
