### ISSUE TITLE
Error with csv to ifc import. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#3588] opened 2023-08-15 16:15 UTC
Error with csv to ifc import. 

files: https://gitlab.com/openingdesign/milwaukee_st_4429/-/tree/be567571b17103707e5bc4b3302437f164eefd0c/Models/BlenderBIM

https://github.com/IfcOpenShell/IfcOpenShell/assets/507113/9e04b2dc-3a4b-4a43-9180-72f97d8a79ad

```
Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\bim\module\csv\operator.py", line 181, in execute
    ifc_csv.Import(ifc_file, self.filepath, delimiter=sep)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifccsv.py", line 297, in Import
    element = IfcAttributeSetter.set_element_key(ifc_file, element, headers[i], value)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifccsv.py", line 65, in set_element_key
    IfcAttributeSetter.set_qto_property(qto, prop, value)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifccsv.py", line 89, in set_qto_property
    setattr(prop, prop.is_a()[len("IfcQuantity") :] + "Value", value)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 225, in __setattr__
    self[index] = value
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\entity_instance.py", line 245, in __setitem__
    self.method_list[idx](self.wrapped_data, idx, entity_instance.unwrap_value(value))
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 4914, in setArgumentAsDouble
    return _ifcopenshell_wrapper.entity_instance_setArgumentAsDouble(self, i, v)
TypeError: in method 'entity_instance_setArgumentAsDouble', argument 3 of type 'double'

```

**Comment by Moult** [comment] 2023-08-16 03:52
Duplicate of  #3556

**Closed by Moult** 2023-08-16 03:52 UTC
Labels: BlenderBIM

**Comment by theoryshaw** [comment] 2023-08-16 07:14
this error persists even with https://github.com/IfcOpenShell/IfcOpenShell/commit/7afd358c3cd8eab33da380caa0c0b8c40f3c7fd4.

**Comment by Moult** [comment] 2023-08-16 07:18
Are you sure you've updated the blenderbim/libs/site/packages/ifccsv/*? If so, the error message should at least be different since that line of code has changed.

**Comment by theoryshaw** [comment] 2023-08-16 13:41
That was it, my bad.  Up to this point, i only looked at the changes to the .make file to let me know when i should copy the `libs` directory over.

**Comment by theoryshaw** [comment] 2023-08-16 13:53
related: https://github.com/IfcOpenShell/IfcOpenShell/issues/3590
