### ISSUE TITLE
IFC file conversion obj file, some cases will be rotated 90 °

### ISSUE THREAD

**Issue by gisspace** [IfcOpenShell/IfcOpenShell#1097] opened 2020-11-10 06:17 UTC
IFC file conversion obj file will be rotated 90°, because of the problem of the X axis up or Y axis up, can you provide parameters to specify。
/src/serializers/WavefrontObjSerializer.cpp

 for ( std::vector<real_t>::const_iterator it = mesh.verts().begin(); it != mesh.verts().end(); ) {
        const real_t x = *(it++);
        const real_t y = *(it++);
        const real_t z = *(it++);
		obj_stream << "v " << x << " " << y << " " << z << "\n";
	}

**Comment by aothms** [comment] 2020-11-11 10:49
Most importers allow to specify OBJ Up-axis during import. Select Z up. Is that really not an option?

Otherwise feel free to send in a Pull Request :) Something like `std::swap(y,z); z *= -1.;` (rotating 90 degrees is quick) and remove `const` then some stuff to have a `--y-up` flag in IfcConvert using boost program options and add it to the Settings. https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/serializers/GeometrySerializer.h#L36

**Comment by whwlei** [comment] 2020-12-10 02:04
I have modified this question, how to submit the merge code

**Comment by aothms** [comment] 2020-12-10 09:17
> how to submit the merge code

Please submit a pull request https://github.com/IfcOpenShell/IfcOpenShell/pulls

https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by Moult** [comment] 2024-04-04 21:20
Closing as duplicate of #657

**Closed by Moult** 2024-04-04 21:20 UTC
Labels: IfcConvert, First time contributor? Try this one!
