### ISSUE TITLE
BlenderBIM: Model imported to incorrect coordinates

### ISSUE THREAD

**Issue by tldddd** [IfcOpenShell/IfcOpenShell#2150] opened 2022-04-19 17:07 UTC
A number of IFC models from Tekla do not import to the correct location, I have attached a minimal example with one object.

Two models federated correctly in Navisworks:

![FederatedNavisworks](https://user-images.githubusercontent.com/33082902/164057973-1bffb0f8-f13a-4da1-8025-4d4593a40952.png)

Correct location in Navisworks, incorrect location in Blender:

![PourLocationNavisworks](https://user-images.githubusercontent.com/33082902/164057251-83f68ef5-0788-410c-a996-10bf65fac4b0.png)

![PourLocationBlender](https://user-images.githubusercontent.com/33082902/164057270-8d27fc32-26d3-4038-b89f-4bef1237ba41.png)

This is as opposed to another similar model from Tekla where objects in a similar position import correctly in both Navisworks and Blender.

![RebarLocationNavisworks](https://user-images.githubusercontent.com/33082902/164057720-a1a0f565-53ba-4ddf-8360-e7d2e064fcda.png)

![RebarLocationBlender](https://user-images.githubusercontent.com/33082902/164057762-5122e978-6d8f-4e61-ad83-a81ad03412f5.png)

[2Models.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/8514996/2Models.zip)

**Comment by Moult** [comment] 2022-04-21 00:04
Thanks so much for this sample file! I've added it to the test suite.

A little background on this issue - IFC viewers typically only show geometry but not "invisible" things like object placements. However, the BlenderBIM Add-on shows both geometry and object placements since object placements is quite important for authoring.

This creates a problem, for example in IFC2X3 since you can't geolocate, people tend to simply shift their coordinates to map coordinates. However, sometimes they only shift the geometry coordinates, but not the object placements. So when Blender is presented with the situation of how to display an object placement of say, an IfcSite, at 0,0,0 and a coordinate of an IfcWall at 1990000,5480000,21000, then it has to choose one extreme to create a "false origin" at and sacrifice precision at the other extreme.

There was a couple bugs in the "autodetect false origin" code. In the past, when coordinates were offset I typically came across this in civil files where the object placements were always an identity matrix. So I wrote the code assuming that the object placement was an identity matrix (which was a poor assumption, but the code was easier to write :). Your file offset coordinates, but also has object placements that aren't an identity matrix, so I had to fix my code. Thanks for helping spot the bug!

Should be fixed now :)

**Closed** 2022-04-21 23:22 UTC
Labels: BlenderBIM

**Comment by Moult** [comment] 2022-05-30 13:06
They come in at different locations because the autodetected false origin is arbitrary. At import time choose advanced import and manually specify the coords of the false origin and thatll make it all line up.

**Comment by tldddd** [comment] 2022-05-30 13:09
Ah, I guess this is a different bug but checking "Enable Advanced Mode" doesn't show any extra options to manually set the coordinates either.

![image](https://user-images.githubusercontent.com/33082902/170998838-0fa1e156-4b7d-490c-988a-f23589ff3227.png)

**Comment by Moult** [comment] 2022-05-30 13:10
Not a bug, if you enable advanced mode, it'll load but not create geometry. That geometry is then left for you to specify in the scene project panel, which includes coordinates.

**Comment by tldddd** [comment] 2022-05-30 13:12
Great, I get it! Thanks for explanation @Moult!
