### ISSUE TITLE
BlenderBim - Shift-R (repeat last action) does not perform properly with ifc project open

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2931] opened 2023-04-03 09:05 UTC
In attempting to quickly duplicate an empty

Shift-D, Z-3000, LMB

Then Shift-R to repeat that function

In normal blender result is a repeat of the duplicate and the Z translation:
![image](https://user-images.githubusercontent.com/78321676/229462954-9adda3a5-6724-4b12-9088-53e7b75fba99.png)

In Blender with an Ifc project open it only repeats the Z translation:
![image](https://user-images.githubusercontent.com/78321676/229463155-6c4d8a1c-17d5-41a8-9000-d43e77851a90.png)

Not sure what is happening but it seems to break up the duplicate into 2 steps and only repeats the last one,
This kinda changes default Blender working while you have an Ifc project open.

This would be quite useful especially for duplicating storey empties for new floors

**Comment by Moult** [comment] 2023-04-03 09:36
Duplicate of #2114.

**Closed by Moult** 2023-04-03 09:36 UTC

**Comment by Moult** [comment] 2023-04-03 09:48
Out of curiosity as a workaround I wonder if the IFC Array tool works for your usecase.

**Comment by Plae-Blue-Dot** [comment] 2023-04-03 11:59
That would be first prize,

The IFC Array doesn't currently work for this as far as I am aware?

You can't array an empty in Blender as far as I've seen

**Comment by Moult** [comment] 2023-04-03 12:04
Ah yeah, we don't have that restriction in IFC but I guess the UI doesn't show up so users can't access it.

**Comment by Moult** [comment] 2023-04-04 12:02
@Plae-Blue-Dot yeah I'd need to think about how to expose that UI. I wish we could add our own tabs in the Blender properties panel, that would be ideal. In any case the bug is fixed so hopefully that helps :)

**Comment by Plae-Blue-Dot** [comment] 2023-04-06 08:13
It works and it's brilliant thanks @Moult !

![image](https://user-images.githubusercontent.com/78321676/230316305-70979cce-45e5-46f1-aef5-b9156aff1ece.png)
