### ISSUE TITLE
Error with TypeData.data["relating_type_classes"]

### ISSUE THREAD

**Issue by vulevukusej** [IfcOpenShell/IfcOpenShell#1917] opened 2021-12-06 08:25 UTC
I keep getting this error in my console.  I thought maybe it was my install, so I downloaded a fresh portable blender file and the latest BB version (blenderbim-211203-py39-win).

```
WARN (bpy.rna): C:\Users\blender\git\blender-v300\blender.git\source\blender\python\intern\bpy_rna.c:1352 pyrna_enum_to_py: current value '0' matches no enum in 'BIMProperties', '', 'contexts'
Traceback (most recent call last):
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\module\type\prop.py", line 40, in get_relating_type_class
    return TypeData.data["relating_type_classes"]
KeyError: 'relating_type_classes'
File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\module\type\prop.py", line 37, in get_relating_type_class
WARN (bpy.rna): C:\Users\blender\git\blender-v300\blender.git\source\blender\python\intern\bpy_rna.c:1352 pyrna_enum_to_py: current value '0' matches no enum in 'BIMTypeProperties', '', 'relating_type_class'
```

**Comment by Gorgious56** [comment] 2021-12-07 08:24
This is a really nasty warning because it is really cryptic. It is caused by accessing a dynamic enum with 0 elements somewhere in the interface. Without looking to deep into the code I'd say it is caused by this line : https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/module/type/ui.py#L69 and it is usually fixed by calling the `EnumProperty`'s `items` method and checking if it is not empty before trying to draw it in the layout. https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/module/type/prop.py#L37-L40 

See here for an example of how it may be handled : https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/module/type/ui.py#L70-L74

But the message may be a symptom of a bug, maybe this dynamic enum is never supposed to be empty ?

**Comment by vulevukusej** [comment] 2021-12-07 08:52
I set a series of breakpoints and found that the error pops up on line 63: 
![image](https://user-images.githubusercontent.com/83825269/144997018-6897307a-337f-4f93-b1d4-1f2f2336bb7c.png)

Maybe I´m misinterpreting the flow of the code wrong, but it seems as if we are trying to access `bpy.context.active_object.BIMTypeProperties.relating_type_class` before the TypeData.load() method is finished populating it ?

**Comment by Moult** [comment] 2021-12-10 01:05
A note that this is actually three separate bugs. All minor and more an annoyance than something that breaks functionality.

Issue 1: dynamic contexts enum referenced without any items. Hopefully should go away once we incrementally refactor to the new data classes.

```
WARN (bpy.rna): C:\Users\blender\git\blender-v300\blender.git\source\blender\python\intern\bpy_rna.c:1352 pyrna_enum_to_py: current value '0' matches no enum in 'BIMProperties', '', 'contexts'
```

Issue 2: some funky bug in the data loading. Will investigate.

```
Traceback (most recent call last):
  File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\module\type\prop.py", line 40, in get_relating_type_class
    return TypeData.data["relating_type_classes"]
KeyError: 'relating_type_classes'
File "C:\Users\vpaji\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blenderbim\bim\module\type\prop.py", line 37, in get_relating_type_class
```

Issue 3: potentially related to 2, but another empty dynamic enum to deal with.

```
WARN (bpy.rna): C:\Users\blender\git\blender-v300\blender.git\source\blender\python\intern\bpy_rna.c:1352 pyrna_enum_to_py: current value '0' matches no enum in 'BIMTypeProperties', '', 'relating_type_class'
```

**Closed** 2021-12-10 03:07 UTC
Labels: BlenderBIM
