### ISSUE TITLE
Multiple issues with Blender 

### ISSUE THREAD

**Issue by hpi-pg** [IfcOpenShell/IfcOpenShell#4284] opened 2024-02-01 12:52 UTC
I think most of the issues I've encountered when using Blender-BIM with Blender are related to the fact that the plugin is a system level add-on. Therefore, I list them all here instead of creating one ticket for each.

1. When trying to save the Blender scene with keyboard shortcut Ctrl-S, the add-on starts to saving the IFC instead (which may actually fail once I've processed the Blender scene in various ways) since the add-on has hijacked the default functionality. Really annoying. 
2. When trying to copy a IFC object to be used for other purposes (for instance, for a boolean object), renaming the object will force the IFC type in the beginning of the name (like **IfcSpace**/boolean_object). This can cause some weird behaviour especially with scripting, although when renaming is done from the Python script, the add-on does not mess with the name. 
3. When I got really annoyed with the add-on, I tried disabling it altogether so that it would not mess up Blender once I had already imported the IFC model to the scene. However, for some reason disabling the add-on caused the Blender Scene settings to disappear with all the BIM related Scene settings, meaning that I was no longer able to change the Units etc. since those settings were not available anywhere. 
4. This is something I'm not quite sure of but it certainly looks really odd indeed. I had made copies of certain space objects and joined them to an object to be used as a boolean object with a Python script. When I then tried to edit the object, most of the geometry just disappeared right away once I moved into the edit mode in Blender. The geometry wasn't just hidden, it just vanished and when I moved back from the edit mode, the object mesh was still broken. So something really fishy is happening there, and I've never seen anything like that before. That's why I suspect it has something to do with the BIM add-on. 

I think that is all for now, but I will add new things to the list if I forgot something.

**Comment by Andrej730** [comment] 2024-02-02 05:48
1. Unlinking IFC file? (Quality and Coordination -> Quality Control -> Debug -> Purge IFC Links)
2. Unlinking IFC object after duplication? (Object Information -> Object Metadata -> Unlink Object)
3. There used to be issues when some scene UI didn't come back after BlenderBIM addon unregister, should be resolved now. Please report if any tabs are still appear missing.
4. If there is no intention to join those spaces in IFC then the solution probably would be to duplicate space objects, then unlink them from IFC and then join.

**Comment by Bhoopsing** [comment] 2024-02-07 05:18
Not open the blender in my pc

**Comment by Andrej730** [comment] 2024-02-07 05:32
@Bhoopsing 
> Not open the blender in my pc please help me

BlenderBIM doesn't load or what do you mean? If so check the system console for errors (Window - Toggle System Console to see the console).

**Comment by Bhoopsing** [comment] 2024-02-07 05:45
I have i3 10th gen processor
2gb gigabyte graphic card
8gb ram
Full hd display

**Comment by Andrej730** [comment] 2024-02-07 05:47
@Bhoopsing 
> I have i3 10th gen processor
> 2gb gigabyte graphic card
> 8gb ram
> Full hd display

Please describe the issue.

**Comment by Bhoopsing** [comment] 2024-02-07 05:52
Blender installed in my pc but don't open this

**Comment by Andrej730** [comment] 2024-02-07 05:56
> Blender installed in my pc but don't open this

Doesn't open BlenderBIM? Please describe the steps how you installed it and check Blender system console for errors after you enable BlenderBIM.

**Comment by Bhoopsing** [comment] 2024-02-07 07:13
Hello

**Comment by Bhoopsing** [comment] 2024-02-07 07:14
Please help me

**Comment by Bhoopsing** [comment] 2024-02-07 07:24
Blender installed in my pc but don't open this please help

**Comment by Bhoopsing** [comment] 2024-02-07 07:29
I installed the blender from official site. When i click on launcher icon, it doesn't show any response and unable to open. Since i have the hardwares with all system requirements.

**Comment by Andrej730** [comment] 2024-02-07 07:31
@Bhoopsing this issue is about BlenderBIM addon conflicts with Blender. If you have general Blender issue you should ask in Blender community.

**Comment by Moult** [comment] 2024-10-09 01:30
Closing because there isn't something really actionable here - Bonsai by design changes a whole bunch of how Blender works. If you don't want to use IFC editing, there is now the "geometry only" import modes which have been reintroduced where you can basically use Blender vanilla and it won't get in the way.

**Closed by Moult** 2024-10-09 01:30 UTC
Labels: Bonsai
