### ISSUE TITLE
Georeferenced linked models

### ISSUE THREAD

**Issue by maxfb87** [IfcOpenShell/IfcOpenShell#4539] opened 2024-04-11 03:36 UTC
It would be useful that linked models were gereferenced.
In this way, if i create a new georeferenced file and i link a new georeferenced file, the result would be a real assembly of two models.
I know that at the moment it is possible to define an offset during the linking procedure, but in this way i think it would be better.
Thanks,
Massimo

**Comment by Moult** [comment] 2024-04-12 04:42
Duplicate of #4510. This is on the roadmap :)

**Closed by Moult** 2024-04-12 04:42 UTC
Labels: BlenderBIM
