### ISSUE TITLE
[BCF] Solibri only imports version 2.1 and not 3 from BCF-XML file created with BCF library

### ISSUE THREAD

**Issue by Martin15135215** [IfcOpenShell/IfcOpenShell#4887] opened 2024-06-18 10:55 UTC
I created with the following script a BCF-XML version 3:

```python
from bcf.v3.bcfxml import BcfXml
import numpy as np
import ifcopenshell.util.placement
import ifcopenshell

from bcf.v3.model.markup import Header, HeaderFiles, File

ifc_file_name = "two-cube-built-element.ifc"

ifc_model = ifcopenshell.open(ifc_file_name)

ifcproject = ifc_model.by_type("IfcProject")[0]

element1, element2  = ifc_model.by_type("IfcBuiltElement")

project_name = "One-Topic-one-Viewpoint-one-Component"

bcf_file = BcfXml.create_new(project_name)

topic_data = {
    "title": "Title: One-Topic-one-Viewpoint-one-Component",
    "description": "Des: One-Topic-one-Viewpoint-one-Component",
    "author": "test@ifc.com", # creation_author
    "topic_type":"Unknown",
    "topic_status":"Open",
}

topic = bcf_file.add_topic(**topic_data)

topic.markup.header = Header(files=HeaderFiles(file=File(
    filename=ifc_model.wrapped_data.header.file_name.name,
    date=ifc_model.wrapped_data.header.file_name.time_stamp,
    ifc_project=ifcproject.GlobalId)))

topic.add_viewpoint(element1)

file_name = "One-Topic-one-Viewpoint-one-Component.bcf"

bcf_file.save(file_name)

```

I am not sure why, however, Solibri could not import this BCF file. I tried new things like the stuff with topic.markup.header however it did not make any difference.

If I tried the same script for a BCF-XML version 2.1, Solibri can import it:

```python
from bcf.v2.bcfxml import BcfXml
import numpy as np
import ifcopenshell.util.placement
import ifcopenshell

ifc_file_name = "two-cube-built-element.ifc"

ifc_model = ifcopenshell.open(ifc_file_name)

element1, element2  = ifc_model.by_type("IfcBuiltElement")

project_name = "One-Topic-one-Viewpoint-one-Component" 

bcf_file = BcfXml.create_new(project_name)

topic_data = {
    "title": "Title: One-Topic-one-Viewpoint-one-Component",
    "description": "Des: One-Topic-one-Viewpoint-one-Component",
    "author": "test@ifc.com", # creation_author
    "topic_type":"Unknown",
    "topic_status":"Open",
}

topic = bcf_file.add_topic(**topic_data)

viewpoint = topic.add_viewpoint(element1)

file_name = "One-Topic-one-Viewpoint-one-Component-version-2-1.bcf"

bcf_file.save(file_name)
```

So right now I am using version 2.1, because I do not know anymore what went wrong with Solibri.

Side note, something which I noticed during my research: 

topic.add_viewpoint(element1) in v3 does return None

https://github.com/IfcOpenShell/IfcOpenShell/blob/82496e8126b99477e96673e69c5657353003ef12/src/bcf/src/bcf/v3/topic.py#L167-L176

topic.add_viewpoint(element1) in v2.1 does return the Viewpoint as a object

https://github.com/IfcOpenShell/IfcOpenShell/blob/82496e8126b99477e96673e69c5657353003ef12/src/bcf/src/bcf/v2/topic.py#L270-L279

**Comment by Andrej730** [comment] 2024-08-09 10:14
> Side note, something which I noticed during my research:
> topic.add_viewpoint(element1) in v3 does return None
> topic.add_viewpoint(element1) in v2.1 does return the Viewpoint as a object

Nice catch, fixed in 3e7a2c1b83.

**Comment by Andrej730** [comment] 2024-08-13 13:27
Btw logs with errors can be found in `Solibri\SOLIBRI\log\output.log`. For this issue error is the one below. It appears that issue is related to `topic.add_viewpoint(element1)` as simple bcf v3 project with a topic imports fine.

```
2024-08-13 18:24:51.558+0500 [Import Bcf] ERROR c.s.s.p.p.ui.PresentationPluginPanel - Error while importing of the BCF file: One-Topic-one-Viewpoint-one-Component-version-v3.bcf
java.lang.NullPointerException: inputStream
	at java.base/java.util.Objects.requireNonNull(Objects.java:235)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1479)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1107)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1456)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1085)
	at com.solibri.bcf.v3_0.b.b(Unknown Source)
	at com.solibri.bcf.v3_0.b.a(Unknown Source)
	at com.solibri.bcf.v3_0.b.a(Unknown Source)
	at com.solibri.bcf.v3_0.b.a(Unknown Source)
	at com.solibri.bcf.v3_0.BCF3_0Agent.importBCF(Unknown Source)
	at com.solibri.bcf.BCFAgent.importBCF(Unknown Source)
	at com.solibri.saf.plugins.presentationplugin.ui.PresentationPluginPanel.a(Unknown Source)
	at com.solibri.saf.plugins.presentationplugin.ui.PresentationPluginPanel$ImportBCFAction.a(Unknown Source)
	at com.solibri.saf.plugins.presentationplugin.ui.aj.construct(Unknown Source)
	at com.solibri.sae.ui.ae.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by Andrej730** [comment] 2024-08-14 07:23
Okay, I've figured it out. It looks like a bug in Solibri. It seems Solibri can't load bcf v3 files that have a viewpoint but this viewpoint doesn't have a snapshot. Since snapshot is optional and it's valid bcf case when you have just a camera without a screenshot, we couldn't add any precautions for this to the library and this issue can be closed.

![image](https://github.com/user-attachments/assets/9bd82845-6485-40e1-b30e-60b6d3c2f487)


See example code how to generate broken/fixed .bcf file. 

I've also reported this bug to Solibri (attached the bug report below) - no idea if they're going to answer me since I have just free Solibri Anywhere. If someone has a payed version of Solibri - please, rereport this issue to them as this way it will be less likely it will be overlooked.

```python
from bcf.v3.bcfxml import BcfXml
import numpy as np
import ifcopenshell.util.placement
import ifcopenshell
from pathlib import Path

ifc_file_name = r"two-cube-built-element.ifc"
ifc_model = ifcopenshell.open(ifc_file_name)
element1 = ifc_model.by_type("IfcBuiltElement")[0]
project_name = "One-Topic-one-Viewpoint-one-Component"

bcf_file = BcfXml.create_new(project_name)

topic_data = {
    "title": "Title: One-Topic-one-Viewpoint-one-Component",
    "description": "Des: One-Topic-one-Viewpoint-one-Component",
    "author": "test@ifc.com",
    "topic_type":"Unknown",
    "topic_status":"Open",
}
topic = bcf_file.add_topic(**topic_data)
viewpoint = topic.add_viewpoint(element1)

# disable this block and file will stop opening in solibri
if True:
    image_path = Path(r"824f2442-fe98-42f0-b9d3-95be2b69a74e.png")
    viewpoint.snapshot = image_path.read_bytes()
    vp = next(v for v in topic.topic.viewpoints.view_point if v.guid == viewpoint.guid)
    vp.snapshot = image_path.name

file_name = Path("bcflib_test.bcf")

bcf_file.save(file_name)
```



-----
Bug report to Solibri:


Solibri Anywhere 24.5.0.31 (2024-05-28)

When I'm import .bcf file I get an error "The BCF file import for (C:\bcflib_test_no_snapshot.bcf) is unsuccessful.".

To reproduce this you can download attached files, open two-cube-built-element.ifc, then open "Communication" tab and drag'n'drop "bcflib_test_no_snapshot.bcf" to "Presentation" window, it will show this error.

Here's output.log contents for this error:

```
[Import Bcf] ERROR c.s.s.p.p.ui.PresentationPluginPanel - Error while importing of the BCF file: C:\bcflib_test_no_snapshot.bcf

java.lang.NullPointerException: inputStream

    at java.base/java.util.Objects.requireNonNull(Objects.java:235)

    at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1479)

    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1107)

    at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1456)

    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1085)

    at com.solibri.bcf.v3_0.b.b(Unknown Source)

    at com.solibri.bcf.v3_0.b.a(Unknown Source)

    at com.solibri.bcf.v3_0.b.a(Unknown Source)

    at com.solibri.bcf.v3_0.b.a(Unknown Source)

    at com.solibri.bcf.v3_0.BCF3_0Agent.importBCF(Unknown Source)

    at com.solibri.bcf.BCFAgent.importBCF(Unknown Source)

    at com.solibri.saf.plugins.presentationplugin.ui.PresentationPluginPanel.a(Unknown Source)

    at com.solibri.saf.plugins.presentationplugin.ui.PresentationPluginPanel$ImportBCFAction.a(Unknown Source)

    at com.solibri.saf.plugins.presentationplugin.ui.aj.construct(Unknown Source)

    at com.solibri.sae.ui.ae.run(Unknown Source)

    at java.base/java.lang.Thread.run(Thread.java:840)
```

Investigating error further I've found that issue appears for bcf v3 (doesn't appear for bcf <v2) when .bcf file doesn't have a snapshot file though it is optional in bcf v3, see documentation - https://github.com/BuildingSMART/BCF-XML/tree/release_3_0/Documentation#viewpoints (you can provide just a camera position without attaching a screenshot). It can be confirmed by importing 'bcflib_test_has_snapshot.bcf' (also attached to this report) - the only difference of this .bcf from the previous one - it has a png snapshot.


Found this issue by user report to bcf library that generates .bcf files (https://github.com/IfcOpenShell/IfcOpenShell/issues/4887).

[bcflib_test_no_snapshot.bcf.txt](https://github.com/user-attachments/files/16608929/bcflib_test_no_snapshot.bcf.txt)
[two-cube-built-element.ifc.txt](https://github.com/user-attachments/files/16608930/two-cube-built-element.ifc.txt)
[bcflib_test_has_snapshot.bcf.txt](https://github.com/user-attachments/files/16608931/bcflib_test_has_snapshot.bcf.txt)

**Closed by Andrej730** 2024-08-14 07:23 UTC
Labels: BCF

**Comment by Andrej730** [comment] 2024-08-19 19:14
Update - Solibri registered this issue as a bug on their internal bug tracker.

**Comment by Andrej730** [comment] 2025-07-14 12:22
Update - just got response from Solibri that issue was resolved in March.
