### ISSUE TITLE
Hiding elements or annotations from drawings

### ISSUE THREAD

**Issue by WeenDwijler** [IfcOpenShell/IfcOpenShell#3700] opened 2023-09-03 14:47 UTC
BlenderBim V 0.0.230828
Blender 3.6.2
Ubuntu 22.04

I keep trying to hide elements or annotations from drawings. As soon I click the camera, everything reappears. How can I exclude elements and/or annotations from showing on drawings?

**Comment by Moult** [comment] 2023-09-03 22:40
Include / exclude filters currently need to be written as a query in the EPset_Drawing of the drawing camera. We also need to build a graphical version of this.

See https://blenderbim.org/docs-python/ifcopenshell-python/selector_syntax.html for instructions of how to use the selector syntax.

**Comment by WeenDwijler** [comment] 2023-09-04 03:24
That's not the issue. I want to hide elements in the drawings. For example: you can switch on or off the annotations in the view screen. However, when I print the drawing, they're visible on it. I.e., when printing, everything hidden before becomes visible again. Now, it is possible to delete them in the final .svg, but that doesn't work for the drawing of the elements themselves. They're all connected. Delete one, the rest goes too.

**Comment by Moult** [comment] 2023-09-04 03:39
Yes I understand, you will need to put the exclude filter in this field. Toggling the "eye" visibility is purely temporary and is not saved in the drawing settings.

![2023-09-04-133858_362x705_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/06bcc900-eeee-4bf3-9b41-9ee0f53a91c0)

**Comment by WeenDwijler** [comment] 2023-09-04 03:45
This is a very labor-intensive method if one needs to hide a couple of items. Let's say I would want to hide two grid lines, a couple of doors, 2 windows, and some furniture parts. It will take ages to get it all in there. Provided that I can put multiple elements in there.

**Comment by Moult** [comment] 2023-09-04 03:49
Yes, it is labour intensive, that's why as mentioned earlier we need to build a graphical version (similar to how it works in the saved searches interface).


Typically though in the majority of cases you wouldn't hide arbitrary items, you hide items semantically (e.g. hide all non-concrete elements, or hide all demolished items). In that case just put your filter there (see earlier link about the selection syntax) and then you can bulk assign the relevant property that triggers the filter.

**Comment by WeenDwijler** [comment] 2023-09-04 04:04
They are not arbitrary items. For some drawings, there is no need for grid lines or a specific group of annotations. Well, that can be handled with Inkscape by deleting them. I can work with that.
However, if I want to hide some elements while keeping the rest visible for clarity to the readers of the drawings, that should be possible in an easy way (Blender style) so quick adjustments can be made.
What you have now might work in a large office with dedicated roles for each part of the process, i.e. someone taking care of these "special" elements in drawings. But, that kind of office already works with Revit and other (non-open software) solutions. They are not your target for BlenderBim. It's the remaining 40% of smaller architects that would want this solution. Often having limited manpower in their offices, the task is for the one making the whole project (designing in Blender, presentation from Blender, and then moving on to setting up the IFC part for planning, permitting, AND the drawings for councils, engineers, plumbers, electricians, and other contractors.

To be honest, I think most would abandon this and look for other solutions or give up on it.

**Comment by Moult** [comment] 2023-09-04 04:10
Arbitrary as in they are manually selected, as opposed to meeting a selection criteria. We simply need to improve the UI in this regard.

**Comment by WeenDwijler** [comment] 2023-09-04 04:13
Trying to get my head around this.

It looks like the visibility of an element is coupled to the camera. If I refresh the camera, previously hidden elements will become visible again. So, can this be de-coupled? The camera only shows those elements and annotations that are NOT hidden, the rest stays hidden.

**Comment by Moult** [comment] 2023-09-04 04:19
Sorry no, I don't think it should work like that. Each drawing has its own set of visibility rules. For example, you might have a demolition plan version a concrete outline drawing vs a partitions drawing, each one turning different things on and off. This is why each drawing has its own include / exclude settings.

**Comment by WeenDwijler** [comment] 2023-09-04 04:27
The drawing is just a representation of any of those versions. The camera is registering that. So, I think that whatever version is needed (demolition, concrete outline, partitioning) should be linked to the elements and combination thereof. This is the same for the annotations.

Come to think of it...why not simply add a camera (or group) that can be used in this way? Still shows all IFC elements and annotations, but now they can be switched off or on?

**Comment by Moult** [comment] 2023-09-04 04:30
I'm not quite sure what you're proposing. I believe this issue will be solved once we add a graphical filtering UI so that users don't need to type out a query.

**Comment by WeenDwijler** [comment] 2023-09-04 04:37
Well, you now have 5 types of drawing cams. Plan, elevation, Section, RCP, and Model. Plan and RCP both show levels, the rest ESWN (East, South, West, North).
A 6th type drawing cam can have ESWN and level, and can show all IFC notations and elements, but allows for each element or notation to be hidden or visible on the printed drawing.

**Comment by WeenDwijler** [comment] 2023-09-04 04:38
By the way, the model cam shows ESWN options but opens as a level (top view) cam, whatever option (ESWN) you choose.

**Comment by Moult** [comment] 2023-09-04 04:40
The types of drawings correlate to drawing types (which IFC calls target views). They all can show and hide elements with custom filters. They all can point in any direction (in theory, though we offer some sensible defaults).

**Comment by WeenDwijler** [comment] 2023-09-04 04:41
> The types of drawings correlate to drawing types (which IFC calls target views). They all can show and hide elements with custom filters. They all can point in any direction (in theory, though we offer some sensible defaults).

Ok, I get that.

**Comment by WeenDwijler** [comment] 2023-09-04 04:47
I'll try to give an example of what I think is a useful option.

I have a building with doors and windows. There are 5 different types of doors, 6 different types of windows. I need detailed drawings of each. So, I align my cam/drawing with door #1 in front view, hiding everything but the door and its elements, adding the relevant annotation, and having a detailed drawing of that door with dimensions, etc.

**Comment by Moult** [comment] 2023-09-04 04:54
Sure, in that case you can use an Include filter (rather than an exclude filter).

For that note it's worth mentioning that we don't have a nice user friendly way yet to do those types of "door / window" drawings, you can see this issue: https://github.com/IfcOpenShell/IfcOpenShell/issues/3675

**Comment by WeenDwijler** [comment] 2023-09-04 04:56
Include will automatically exclude everything else?

**Comment by WeenDwijler** [comment] 2023-09-04 04:59
By the way, "which IFC calls target views". Do you mean IFC as in Issued For Construction?

**Comment by Moult** [comment] 2023-09-04 05:05
First the include filter is applied, then the exclude filter is applied.

IFC refers to Industry Foundation Classes, it is the ISO standard which describes how digital BIM data must be structured. But yes it is a common confusion with IFC = Issued For Construction ;)

**Comment by WeenDwijler** [comment] 2023-09-04 05:07
> First the include filter is applied, then the exclude filter is applied.
> 
> IFC refers to Industry Foundation Classes, it is the ISO standard which describes how digital BIM data must be structured. But yes it is a common confusion with IFC = Issued For Construction ;)

I googled it to learn more about it, but only got Issued For Construction. You've got a link at hand to Industry Foundation Classes standard views?

**Comment by Moult** [comment] 2023-09-04 05:10
- https://en.wikipedia.org/wiki/Industry_Foundation_Classes
 - https://www.iso.org/standard/70303.html
 - https://technical.buildingsmart.org/standards/ifc/
 - https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcgeometricprojectionenum.htm

**Comment by WeenDwijler** [comment] 2023-09-04 05:12
Thanks!
In the meantime, struggling with the include. Not a programmer here, just a simple user. How do I write the element in include? .IfcWall/Wall.009, IfcWall/Wall.009, the globalid? Non works. Python error messages.

**Comment by Moult** [comment] 2023-09-04 05:15
You can see examples in the link I posted earlier: https://blenderbim.org/docs-python/ifcopenshell-python/selector_syntax.html#filtering-elements

**Comment by WeenDwijler** [comment] 2023-09-04 05:23
globalid not working!

**Comment by WeenDwijler** [comment] 2023-09-04 05:33
I tried everything you mentioned. It simply doesn't work. I'm aware that a simple mistyping can ruin things, so paid extra attention to that. To be honest, it starts to become annoying. The way this works is very inaccessible for a non-programmer.

**Comment by Moult** [comment] 2023-09-04 05:39
What version are you using? The selection syntax has completely changed significantly recently (perhaps in the past week or so) so the documentation link I shared is for the latest version. If you downloaded a version from blenderbim.org prior to the most recent release a few days ago, you're on an old version and that would explain why it doesn't work.

Please keep in mind this is alpha software. It is a work in progress, many things are incomplete and changing frequently.

**Comment by WeenDwijler** [comment] 2023-09-04 05:41
BlenderBim V 0.0.230828

**Comment by Moult** [comment] 2023-09-04 05:44
Yeah that's too old. Please upgrade to the latest one here: https://blenderbim.org/

**Comment by WeenDwijler** [comment] 2023-09-04 05:45
So, this is what I did.
![Screenshot from 2023-09-04 12-36-26](https://github.com/IfcOpenShell/IfcOpenShell/assets/80776914/cef144ca-8e68-4b50-8763-c453e8852e47)
![Screenshot from 2023-09-04 12-38-50](https://github.com/IfcOpenShell/IfcOpenShell/assets/80776914/c6dd07cb-9310-443f-a8b7-95a26c976a8d)
Got an error.
Tried .globalid and {{globalid}} and globalid and .{{globalid}}.
Not working.

**Comment by WeenDwijler** [comment] 2023-09-04 05:53
New version installed. Still not working.

**Comment by Moult** [comment] 2023-09-04 05:59
Thanks! Yes, that's a bug and it's now fixed. Excludes should work though.

**Comment by WeenDwijler** [comment] 2023-09-04 06:00
Yes, my friend. But it is include what we want. ;-)

**Comment by WeenDwijler** [comment] 2023-09-04 06:02
Confirmed! Exclude works. Please, now include too.

**Comment by Gorgious56** [comment] 2023-09-04 06:35
Make sure you download the latest version, the fix was released after your last message.

**Comment by WeenDwijler** [comment] 2023-09-04 06:37
> Make sure you download the latest version, the fix was released after your last message.

You deserve your username! Will get it! :-)

**Comment by WeenDwijler** [comment] 2023-09-04 06:46
Confirm it works!

**Comment by WeenDwijler** [comment] 2023-09-04 08:32
Eh, small problem occurred. After using exclude, and returning to showing everything. The excluded element has shifted position and is now where it doesn't belong.

**Comment by theoryshaw** [comment] 2023-09-04 14:41
This is probably due to another issue outside the exclude/include thing. 

When this happens for me, it was because the IFC file wasn't updated, or synced.  Did you move this door in the past?

If you reopen the ifc file, is the door located in the wrong position?

**Comment by WeenDwijler** [comment] 2023-09-04 15:06
The door is in the right position in the 3D Viewport. It is moved only in the drawings. All drawings!!!

**Comment by WeenDwijler** [comment] 2023-09-04 15:18
Ok. So I closed Blender. Powered of the PC, waited, restarted PC, restarted Blender, opened the IFC file, and found that all drawings crashed. So, closed Blender, reopened Blender, this time opened the Blender file, and voila, the door is back in place on the drawings. ???????????????????

**Comment by theoryshaw** [comment] 2023-09-04 15:46
Also btw, good practice is to open the IFC file every time... and not the .blend file.  As there's sometimes these syncing problems, when you save both the .ifc and .blend file.   

For majority of my projects, i don't even save the .blend file.

**Comment by WeenDwijler** [comment] 2023-09-04 15:54
I will give that a try, next time. First, need to check if everything is there in the IFC file. But it makes some sense what you say. Anyway, I was having this vision of horror to have to do all the drawings again, which cost me many days to get done (with my limited knowledge of the subject). Today was a BIM day and very little project day. Gladly I'm my own boss, or I would be in trouble.

**Comment by theoryshaw** [comment] 2023-09-04 15:56
you're drawings should be saved in the .ifc file.  You shouldn't have to recreate them.

**Comment by WeenDwijler** [comment] 2023-09-04 15:59
> you're drawings should be saved in the .ifc file. You shouldn't have to recreate them.

Well, the door was moved in all drawings where it was in. It's OK now, ... I hope.

**Comment by theoryshaw** [comment] 2023-09-04 16:05
Did you modify the door type in any way?  that is, move it's origin?  

Regardless, more than likely, the moved door is not a drawing issue.

**Comment by WeenDwijler** [comment] 2023-09-04 16:10
> Did you modify the door type in any way? that is, move it's origin?
> 
> Regardless, more than likely, the moved door is not a drawing issue.

No, I didn't. Said that before. Another thing springs to mind. I'm using Firefox, and experienced some strange behavior recently. The printing happens in the web browser, so maybe that's a factor of influence.

**Comment by theoryshaw** [comment] 2023-09-04 16:11
Also, it always helps sharing the IFC, in the future, if you have particular problems. Is easier to troubleshoot then.

**Comment by WeenDwijler** [comment] 2023-09-04 16:14
> Also, it always helps sharing the IFC, in the future, if you have particular problems. Is easier to troubleshoot then.

If I can, I will. Some are proprietary and under embargo. Doesn't make things easier...

**Comment by Gorgious56** [comment] 2023-09-04 18:18
Hey first of all thank you for bringing these issues to our attention and for your feedback. However and I only mean that as constructive criticism so if you're not open to it please disregard the rest of this message. The BlenderBIM addon is clearly advertised as alpha software

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/25156105/c84090ec-4396-43c1-aa25-74a57401ec2c)

So it is kind of agreed upon when you download and use it that you will face some bugs, and you tacitly accept it by doing so. The dev ressources as for any other open source software organisation are stretched as thin as can be on as many topics as you can imagine, so you're also expected to treat them (us) with a minimal amount of respect. You have several times in this thread used a passive-aggressive tone that is IMO not warranted at all since several people (including the main developer) have reached out to help you out in the span of less than 24hours since your OP. 

We are commited to fix bugs and develop features, and any constructive feedback is welcome. But please, please take a bit of time to consider all of that when writing your feedback.

Cheers

**Comment by WeenDwijler** [comment] 2023-09-04 18:39
> Hey first of all thank you for bringing these issues to our attention and for your feedback. However and I only mean that as constructive criticism so if you're not open to it please disregard the rest of this message. The BlenderBIM addon is clearly advertised as alpha software
> 
> ![image](https://user-images.githubusercontent.com/25156105/265520574-c84090ec-4396-43c1-aa25-74a57401ec2c.png)
> 
> So it is kind of agreed upon when you download and use it that you will face some bugs, and you tacitly accept it by doing so. The dev ressources as for any other open source software organisation are stretched as thin as can be on as many topics as you can imagine, so you're also expected to treat them (us) with a minimal amount of respect. You have several times in this thread used a passive-aggressive tone that is IMO not warranted at all since several people (including the main developer) have reached out to help you out in the span of less than 24hours since your OP.
> 
> We are commited to fix bugs and develop features, and any constructive feedback is welcome. But please, please take a bit of time to consider all of that when writing your feedback.
> 
> Cheers

I understand your point and agree that my frustration must have seeped through while commenting. In the heat of my wrestling match with BlenderBim and Blender, I must have dropped my normal cool a bit. However, I think I found it again, under the table with the cats. Nevertheless, my apologies for that.

I like to state here that despite that, the rapid response and solutions were impressive. Showing that we're dealing here with very motivated and professional people. Let it be noted that I sincerely appreciate that. It's quite a learning curve for me, working with IFC and BlenderBim. But I think it is a great solution to couple it with Blender and has certainly a future.

So, in my quest to master this, I expect to run into much more trouble. Knowing now that this team is paying real attention, I will do my best to give you as much feedback as I can and contribute to help get this to a full-blown BIM solution for Blender.

My warmest regards

**Comment by WeenDwijler** [comment] 2023-09-05 02:23
> Hey first of all thank you for bringing these issues to our attention and for your feedback. However and I only mean that as constructive criticism so if you're not open to it please disregard the rest of this message. The BlenderBIM addon is clearly advertised as alpha software
> 
> ![image](https://user-images.githubusercontent.com/25156105/265520574-c84090ec-4396-43c1-aa25-74a57401ec2c.png)
> 
> So it is kind of agreed upon when you download and use it that you will face some bugs, and you tacitly accept it by doing so. The dev ressources as for any other open source software organisation are stretched as thin as can be on as many topics as you can imagine, so you're also expected to treat them (us) with a minimal amount of respect. You have several times in this thread used a passive-aggressive tone that is IMO not warranted at all since several people (including the main developer) have reached out to help you out in the span of less than 24hours since your OP.
> 
> We are commited to fix bugs and develop features, and any constructive feedback is welcome. But please, please take a bit of time to consider all of that when writing your feedback.
> 
> Cheers

I understand your point and agree that my frustration must have seeped through while commenting. In the heat of my wrestling match with BlenderBim and Blender, I must have dropped my normal cool a bit. However, I think I found it again, under the table with the cats. Nevertheless, my apologies for that.

I like to state here that despite that, the rapid response and solutions were impressive. Showing that we're dealing here with very motivated and professional people. Let it be noted that I sincerely appreciate that. It's quite a learning curve for me, working with IFC and BlenderBim. But I think it is a great solution to couple it with Blender and has certainly a future.

So, in my quest to master this, I expect to run into much more trouble. Knowing now that this team is paying real attention, I will do my best to give you as much feedback as I can and contribute to help get this to a full-blown BIM solution for Blender.

My warmest regards

**Comment by WeenDwijler** [comment] 2023-09-05 02:26
I think this has been solved now.

**Comment by Moult** [comment] 2023-09-05 02:28
The moving door unfortunately would be hard to fix without knowing exactly what you did. Its also possible that if you saved both a .blend and an .ifc, and reopened your .blend, that this issue was triggered "by design".

I'd advise to only save and load .ifc models, never save and load .blend files (until you get a bit more experience).

I'd also like to keep this issue open since it is a known problem that certain drawing settings have no UI and only can be edited in the pset editor which is a clear UX flaw.

**Comment by WeenDwijler** [comment] 2023-09-05 02:44
> The moving door unfortunately would be hard to fix without knowing exactly what you did. Its also possible that if you saved both a .blend and an .ifc, and reopened your .blend, that this issue was triggered "by design".
> 
> I'd advise to only save and load .ifc models, never save and load .blend files (until you get a bit more experience).
> 
> I'd also like to keep this issue open since it is a known problem that certain drawing settings have no UI and only can be edited in the pset editor which is a clear UX flaw.

Ok. I did move on to only use the .ifc. Used include to create a couple of drawings. All good. then tried to print a sheet with elevations and noticed the "raised" door again. So, checked in Inkscape and found it was in the East elevation. The other 3 not affected. Removed the East elevation from the sheet, refreshed the drawing, and added the drawing again to the sheet. The raised door was no longer there. That seemed to work.

I noticed that removing the include from a camera, caused a heap of Python errors, but the drawing was okay. It didn't freeze up the program or crash, just errors displayed.

If there is a log file of those errors, let me know where to find it. I can send it to you, or isolate the specific problem and copy paste it here.

**Comment by Moult** [comment] 2023-09-05 03:03
> I noticed that removing the include from a camera, caused a heap of Python errors

If you removed it by blanking it out e.g. just deleting the contents, this is news and please report the errors.

If you removed it by using the null toggle (the circle icon next to the property) then this is a known bug for @aothms to address. See #2939.

**Comment by WeenDwijler** [comment] 2023-09-05 03:43
> If you removed it by blanking it out e.g. just deleting the contents, this is news and please report the errors.

Yes, I used deleting the contents. Love to report the errors, but as soon the mouse moves, the messages disappear. That's why I asked if there is some kind of log. Can use that to show the errors. Combined with a fine description of all the steps made, this should help to find the problem and solve it.

**Comment by WeenDwijler** [comment] 2023-09-05 04:49
Blender freezes while creating a drawing.

Using the icon produced a group of errors. Unfortunately, no way to screenshot it. When the mouse moves away the screen disappears.

**Comment by WeenDwijler** [comment] 2023-09-05 05:23
This is what happens (so the error is visible).

[Screencast from 05-09-23 12:20:32.webm](https://github.com/IfcOpenShell/IfcOpenShell/assets/80776914/51fa83a5-3f57-4599-8720-2c26cbb3ab86)

**Comment by Moult** [comment] 2023-09-05 05:32
If you launch Blender from a console, the error will be available in the console for you to copy paste.

That error is generic and suggests that either you are not solely loading from the IFC, or you are doing things in Blender which are incompatible with IFC, or in doing so in the past have corrupted an object. Are you absolutely sure you're getting this error after loading the .ifc only in a fresh session?

It would really help if you could share your model. You can send it to dion@thinkmoult.com if it is private.

**Comment by WeenDwijler** [comment] 2023-09-05 05:34
You want the .ifc only or also the .blend?

**Comment by Moult** [comment] 2023-09-05 05:35
Only the .ifc. The .blend should not be used.

**Comment by WeenDwijler** [comment] 2023-09-05 05:45
On its way to you.

**Comment by Moult** [comment] 2023-09-05 06:27
I took a quick peek and there are some corrupt doors in the model. There are three doors named "Lado B" which you will see as empties (i.e. no geometry). It is possible that these were corrupted earlier and only now the results are being seen. If you delete those three doors things should work again.

**Comment by WeenDwijler** [comment] 2023-09-05 06:29
The lado are hinges, parented to the door.

**Comment by WeenDwijler** [comment] 2023-09-05 06:47
I looked at them. There are 3 sets of hinges. It consists of 3 parts: Lado A, Lado B, and cylinder principal. But I also see a grey-colored block around them, actually hiding them from view. This is strange because it's not in the original file and doesn't belong there. I can't select it separately.

**Comment by Moult** [comment] 2023-09-05 07:33
The box you see is probably because somehow you have changed the geometry to bounding box view. You can toggle it back to the body view in the representations panel.

![2023-09-05-173232_548x334_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/05341864-e1a3-4808-ab06-f5ff4dbf8425)

Note that the actual issue is Lado B which are empties which you can just delete to fix your issue:

![2023-09-05-173313_177x62_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/bb3a151c-c95b-41e8-bc55-062cb8fd49cf)

**Comment by WeenDwijler** [comment] 2023-09-05 07:42
I tried some things with one of them, IfcDoor/LadoA.002. The origin was set to the 3D cursor, which was located at the World Origin at that moment (before converting it all to ifc).

Leaving it as is, under representations, I added Model/Annotation/PLAN_VIEW with outline. This projects the outline at Z0. Then I deleted that view. The icon in the outliner changed from mesh to empty, and the geometry disappeared. The empty was placed at the origin of the element.

![Screenshot from 2023-09-05 14-27-30](https://github.com/IfcOpenShell/IfcOpenShell/assets/80776914/15c3b065-d93f-4183-9adb-d272986e68b1)

With Ctrl-Z I returned to the start point of this exercise.

Next, set the origin to geometry. Add .. with outline again. Now the outline is projected at the center of ladoA.002. Switching back to tesselation, the element is moved. It looks at a distance and coordinates similar to before setting the origin to geometry.

I think that for the purpose of drawings, the PLAN_VIEW, ELEVATION_VIEW etc. are selected and something goes wrong when switching back from outline view back to tesselation, and vice versa.

**Comment by WeenDwijler** [comment] 2023-09-05 07:51
> The box you see is probably because somehow you have changed the geometry to bounding box view. You can toggle it back to the body view in the representations panel.
> 
> ![2023-09-05-173232_548x334_scrot](https://user-images.githubusercontent.com/88302/265620946-05341864-e1a3-4808-ab06-f5ff4dbf8425.png)
> 
> Note that the actual issue is Lado B which are empties which you can just delete to fix your issue:
> 
> ![2023-09-05-173313_177x62_scrot](https://user-images.githubusercontent.com/88302/265621072-bb3a151c-c95b-41e8-bc55-062cb8fd49cf.png)

I think that's not correct. I never changed the view to the bounding box. This happens spontaneously or due to some error in the program. The empties seem to be caused by what I reproduced (see my previous answer). This can have something to do with where the origin is placed, or that the program is not updating the changes made in that context, i.e. somehow keeping origins from before.

By the way, you can see that the bounding boxes are not parallel with the direction of the hinges. This is a problem I noticed before, due to all the various angles of the geodesic panels. This in turn causes problems with generating the quantities, giving wild outcomes.

**Comment by Moult** [comment] 2023-09-05 12:20
> Then I deleted that view. The icon in the outliner changed from mesh to empty, and the geometry disappeared. The empty was placed at the origin of the element.

This is expected behaviour, since you've removed the active geometry. We should improve the behaviour to either switch to another one or provide a fallback, but it shouldn't cause the geometry corruption that I'm seeing.

> Next, set the origin to geometry. Add .. with outline again. Now the outline is projected at the center of ladoA.002. Switching back to tesselation, the element is moved. It looks at a distance and coordinates similar to before setting the origin to geometry.

What you're describing is normal because you're using the Blender "set origin" command whereas instead you should use the "IFC Set Origin" command (see the bottom of the 3D View's Object menu). However again it seems unrelated to the geometry corruption bug.

> I think that's not correct. I never changed the view to the bounding box. This happens spontaneously or due to some error in the program. 

Agreed it could be due to a bug, though nothing yet jumps out as a cause.

> Also, deleting the elements is not really an option

What I'm describing is that if you open the .ifc model, you can see those three IfcDoor/Lado B empties. These are corrupt objects and they don't do anything so it's safe to delete them. They are the cause for your errors described here https://github.com/IfcOpenShell/IfcOpenShell/issues/3700#issuecomment-1705961677

**Comment by WeenDwijler** [comment] 2023-09-05 12:32
I'm in Thailand, so the time difference is not so much. Let me know how.

**Comment by Moult** [comment] 2023-09-05 13:23
You can hang around https://osarch.org/chat/ and perhaps at a good time when we're both online we can jump on a chat session such as https://meet.jit.si/openbim - alternatively we can agree on a particular time between 9 to 5 Sydney timezone and be at https://meet.jit.si/openbim.

**Comment by WeenDwijler** [comment] 2023-09-05 13:33
I'm not the hang-around type, we better set a time and date. It's 3 hours time difference, you're later. Anywhere between your 2 and 5 is fine with me.

**Closed** 2023-11-04 02:56 UTC
Labels: BlenderBIM
