### ISSUE TITLE
Missing geometry

### ISSUE THREAD

**Issue by rubendel** [IfcOpenShell/IfcOpenShell#236] opened 2017-06-23 12:49 UTC
In this zipfile there is one IFC file with 4 IfcSlab entities. Only the first IfcSlab generates geometry (but it's not a solid as it's supposed to be). The other 3 don't generate any geometry (in the BIMserver plugin there are no IfcOpenShellEntityInstance objects generated).

Both Solibri and DDS-CAD open this file the same way, both seem to be as expected. Also tried in Blender with version 0.5.0p2 of IOS and the same result (only one object visualized).

[IfcSlab-1.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/1097790/IfcSlab-1.zip)

**Comment by aothms** [comment] 2017-06-24 18:23
Technically, IfcOpenShell is correct here, but the reason is not overly satisfying.

The issues arise at the curved segments, which are trimmed with a parameter value of 90 degrees. However, the angular unit in this file is not properly set for degrees: `pi / 180 = 0.017453292519943295` and not `0.01745`. You're close though, Revit. The deviation `cos(90 * 0.01745) = 0.0002963267905598908` is larger than the defined precision in the file of `0.00001`. So IfcOpenShell refuses to join the segments.

So you have two options to fix this file, increase the precision on the `IfcGeometricRepresentationContext` or fix the conversion factor in the `IfcConversionBasedUnit`. Somebody should contact Autodesk about this I recon.

But there of course options to work around this as well, we can either adjust the unit if we detect it is close to `pi / 180`, but this might come at a risk. We can fill in the gap with a straight line segment, but it could introduce errors lateron due to the tiny line segments. We can also locally increase the precision.

~~~
#20=IfcCompositeCurve((#21,#22,#23,#24,#25,#26),.F.)
#21=IfcCompositeCurveSegment(.CONTINUOUS.,.T.,#69)
#69=IfcPolyline((#70,#71))
#70=IfcCartesianPoint((18.49944,-17.54022))
#71=IfcCartesianPoint((16.63,-17.54022))
#22=IfcCompositeCurveSegment(.CONTINUOUS.,.T.,#66)
#66=IfcPolyline((#67,#68))
#67=IfcCartesianPoint((16.63,-17.54022))
#68=IfcCartesianPoint((16.63,-18.43577))
#23=IfcCompositeCurveSegment(.CONTINUOUS.,.T.,#63)
#63=IfcPolyline((#64,#65))
#64=IfcCartesianPoint((16.63,-18.43577))
#65=IfcCartesianPoint((16.63,-18.49222))
#24=IfcCompositeCurveSegment(.CONTINUOUS.,.T.,#60)
#60=IfcPolyline((#61,#62))
#61=IfcCartesianPoint((16.63,-18.49222))
#62=IfcCartesianPoint((17.585,-18.49222))
#25=IfcCompositeCurveSegment(.CONTINUOUS.,.T.,#158)
#158=IfcTrimmedCurve(#133,(IfcParameterValue(90.)),(IfcParameterValue(180.)),.T.,.PARAMETER.)
#133=IfcCircle(#134,0.91444)
#134=IfcAxis2Placement2D(#143,#215)
#143=IfcCartesianPoint((17.585,-17.57778))
#215=IfcDirection((-1.,0.))
#26=IfcCompositeCurveSegment(.CONTINUOUS.,.T.,#57)
#57=IfcPolyline((#58,#59))
#58=IfcCartesianPoint((18.49944,-17.57778))
#59=IfcCartesianPoint((18.49944,-17.54022))
~~~

~~~
#196=IfcConversionBasedUnit(#197,.PLANEANGLEUNIT.,'DEGREE',#198)
#197=IfcDimensionalExponents(0,0,0,0,0,0,0)
#198=IfcMeasureWithUnit(IfcRatioMeasure(0.01745),#123)
#123=IfcSIUnit(*,.PLANEANGLEUNIT.,$,.RADIAN.)
~~~

~~~
#201=IfcGeometricRepresentationContext($,'Model',3,0.00001,#194,#202)
~~~

**Comment by youaresoomean** [comment] 2017-08-23 09:04
Hi, i am not sure if the problem is related. Attached is an ifc export from RevIT 2018 which displays correctly in Solibri Model Viewer but generates the following error in IfcOpenShell.
```

[Error] {1vKYgRoZLDAuu9IwTKeHqf} Failed to join curve segments:
#1078=IfcCompositeCurve((#179,#187,#194,#201,#211,#218,#225,#232,#239,#246,#253,#260,#267,#274,#281,#288,#295,#302,#309,#316,#323,#330,#337,#344,#354,#361,#371,#378,#388,#395,#405,#412,#422,#429,#439,#446,#456,#463,#473,#480,#490,#497,#507,#514,#524,#531,#541,#548,#558,#565,#575,#582,#592,#599,#609,#616,#626,#633,#643,#650,#660,#667,#677,#684,#694,#701,#708,#715,#722,#729,#736,#743,#750,#760,#767,#777,#784,#794,#801,#811,#818,#828,#835,#845,#852,#862,#869,#879,#886,#896,#903,#913,#920,#930,#937,#947,#954,#964,#971,#981,#988,#998,#1005,#1015,#1022,#1032,#1039,#1049,#1056,#1063,#1070,#1077),.F.)
[Error] {1vKYgRoZLDAuu9IwTKeHqf} Last vertex at (-5.989 9.125 0)
[Error] {1vKYgRoZLDAuu9IwTKeHqf} Segment starts at (-6.065 9.101 0) for:
#777=IfcCompositeCurveSegment(.CONTINUOUS.,.T.,#774)
[Error] {1vKYgRoZLDAuu9IwTKeHqf} Failed to convert:
#1198=IfcExtrudedAreaSolid(#1192,#1197,#20,400.)
[Error] No geometrical entities found
```
Zip file contains ifc4 export + RevIT 2018 source file.

[missing_geo_with_rvt.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/1244786/missing_geo_with_rvt.zip)

**Comment by aothms** [comment] 2017-09-10 15:06
Well, the debugging messages are a bit improved now (especially the last vertex message was wrong) and now reads:

~~~
[Error] {1vKYgRoZLDAuu9IwTKeHqf} Failed to join curve segments:
#1078=IfcCompositeCurve((#179,#187,#194,#201,#211,#218,#225,#232,#239,#246,#253,
#260,#267,#274,#281,#288,#295,#302,#309,#316,#323,#330,#337,#344,#354,#361,#371,
#378,#388,#395,#405,#412,#422,#429,#439,#446,#456,#463,#473,#480,#490,#497,#507,
#514,#524,#531,#541,#548,#558,#565,#575,#582,#592,#599,#609,#616,#626,#633,#643,
#650,#660,#667,#677,#684,#694,#701,#708,#715,#722,#729,#736,#743,#750,#760,#767,
#777,#784,#794,#801,#811,#818,#828,#835,#845,#852,#862,#869,#879,#886,#896,#903,
#913,#920,#930,#937,#947,#954,#964,#971,#981,#988,#998,#1005,#1015,#1022,#1032,#
1039,#1049,#1056,#1063,#1070,#1077),.F.)
[Notice] {1vKYgRoZLDAuu9IwTKeHqf} Last vertex at (-6.065419 9.10148 0)
[Notice] {1vKYgRoZLDAuu9IwTKeHqf} Segment starts at (-6.065379 9.101349 0), dist
ance 0.0001370819 > precision 0.0000100 for:
#777=IfcCompositeCurveSegment(.CONTINUOUS.,.T.,#774)
~~~

If somebody wants to pick this up with adsk I'll happily chime in. The lead developer there is very responsive: https://sourceforge.net/p/ifcexporter/discussion/general/

**Comment by JickYang** [comment] 2017-10-19 07:18
Hi, I also had this problem. We use the version " IfcOpenShell-0.5.0-dev-2". The IFC file is 
[Test.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/1397433/Test.zip)

Can you tell me how do you solve? Thanks.

**Comment by Moult** [comment] 2022-09-06 03:26
Original now works fine in latest IfcOpenShell:

![image](https://user-images.githubusercontent.com/88302/188540467-ed900f2d-bde8-4034-aadf-bd41b417c483.png)

No issues with @youaresoomean model:

![image](https://user-images.githubusercontent.com/88302/188540703-9217d819-4322-47e0-9bbc-44134911a3c5.png)

Also cannot see any issues with @JensenYY 's model:

![image](https://user-images.githubusercontent.com/88302/188540610-0808180f-0df4-4378-9790-1dbee76248f3.png)

Closing :)

**Closed by Moult** 2022-09-06 03:26 UTC
