### ISSUE TITLE
The conversion result of ifcconvert 0.6.0 is correct, but it is wrong in 0.7.0

### ISSUE THREAD

**Issue by chh320** [IfcOpenShell/IfcOpenShell#2308] opened 2022-07-22 01:16 UTC
I downloaded the 0.7.0 and 0.6.0 executable files of IfcConvert from the official website to test IFC - > OBJ, but in the 0.7.0 version, the result was wrong.

The result as follows：
.ifc :
![image](https://user-images.githubusercontent.com/69209706/180340724-133ef496-e54f-4f9f-9b7a-7c0e312d08f4.png)
.obj (0.6.0) :
![image](https://user-images.githubusercontent.com/69209706/180340743-fcb08816-6bfc-41b3-b2fc-88793633f5f2.png)
.obj (0.7.0) :
![image](https://user-images.githubusercontent.com/69209706/180340844-4fffa872-af50-4423-9a0c-0e369bffa95d.png)

**Comment by Moult** [comment] 2022-07-22 03:36
Can you provide a sample file? models@ifcopenshell.org if private.

**Comment by chh320** [comment] 2022-07-22 05:30
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IfcOpenShell/IfcOpenShell"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月22日(星期五) 中午11:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [IfcOpenShell/IfcOpenShell] The conversion result of ifcconvert 0.6.0 is correct, but it is wrong in 0.7.0 (Issue #2308)





 
Can you provide a sample file? ***@***.*** if private.

**Comment by Moult** [comment] 2022-08-01 03:14
Bump - did you provide a sample?

**Comment by chh320** [comment] 2022-08-01 05:12
I have sent the sample to ***@***.*** on July 22.




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "IfcOpenShell/IfcOpenShell"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月1日(星期一) 中午11:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [IfcOpenShell/IfcOpenShell] The conversion result of ifcconvert 0.6.0 is correct, but it is wrong in 0.7.0 (Issue #2308)





 
Bump - did you provide a sample?

**Comment by Moult** [comment] 2022-08-18 07:01
It seems @aothms is on holiday, would you mind sending it to dion@thinkmoult.com and I can see what I can do about isolating the problem further? No promises but better than waiting.

**Comment by chh320** [comment] 2022-08-18 12:52
OK, I'll send it now




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IfcOpenShell/IfcOpenShell"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月18日(星期四) 下午3:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [IfcOpenShell/IfcOpenShell] The conversion result of ifcconvert 0.6.0 is correct, but it is wrong in 0.7.0 (Issue #2308)





 
It seems @aothms is on holiday, would you mind sending it to ***@***.*** and I can see what I can do about isolating the problem further? No promises but better than waiting.

**Comment by Moult** [comment] 2022-08-19 02:59
The issue is that your file is invalid. I assume v0.7.0 got stricter and since your file is invalid, the behaviour is unpredictable.

 1. The GlobalIds do not follow the base64 encoding requirements of IFC (important, but not the cause of what you see)
 2. Your IfcLocalPlacements have a PlacementRelTo pointing to an IfcAxis2Placement3D. Instead, it should point to either nothing or an IfcObjectPlacement. This is the cause of what you're seeing.

You can run a validation function using ifcopenshell.validate in code, or use the BlenderBIM Add-on to help with this. Here is a sample of the validation errors reported:

```
#23=IfcAxis2Placement3D(#22,#21,#19) not valid for <attribute PlacementRelTo?: <entity IfcObjectPlacement>>
2022-08-19:12:57:35,398 ERROR   [validate.py:200] In #802=IfcRelContainedInSpatialStructure('3847e51d-1337-4de0-966b-0ca8700f6f41',#23,$,$,(#801),#52)
#23=IfcAxis2Placement3D(#22,#21,#19) not valid for <attribute OwnerHistory: <entity IfcOwnerHistory>>
2022-08-19:12:57:35,398 ERROR   [validate.py:200] In #800=IfcLocalPlacement(#23,#799)
#23=IfcAxis2Placement3D(#22,#21,#19) not valid for <attribute PlacementRelTo?: <entity IfcObjectPlacement>>
2022-08-19:12:57:35,402 ERROR   [validate.py:200] In #783=IfcRelContainedInSpatialStructure('727ac311-e3f7-4d7c-aedc-6d21e6ffc61e',#23,$,$,(#782),#52)
#23=IfcAxis2Placement3D(#22,#21,#19) not valid for <attribute OwnerHistory: <entity IfcOwnerHistory>>
2022-08-19:12:57:35,403 ERROR   [validate.py:200] In #781=IfcLocalPlacement(#23,#780)
#23=IfcAxis2Placement3D(#22,#21,#19) not valid for <attribute PlacementRelTo?: <entity IfcObjectPlacement>>
2022-08-19:12:57:35,407 ERROR   [validate.py:200] In #764=IfcRelContainedInSpatialStructure('c625ec2e-ab5c-45c0-a140-9939c0e2ef14',#23,$,$,(#763),#52)
#23=IfcAxis2Placement3D(#22,#21,#19) not valid for <attribute OwnerHistory: <entity IfcOwnerHistory>>
2022-08-19:12:57:35,408 ERROR   [validate.py:200] In #762=IfcLocalPlacement(#23,#761)
#23=IfcAxis2Placement3D(#22,#21,#19) not valid for <attribute PlacementRelTo?: <entity IfcObjectPlacement>>
2022-08-19:12:57:35,412 ERROR   [validate.py:200] In #740=IfcRelContainedInSpatialStructure('acf37fed-cdea-4fa9-8886-b110385a00c7',#23,$,$,(#739),#52)
#23=IfcAxis2Placement3D(#22,#21,#19) not valid for <attribute OwnerHistory: <entity IfcOwnerHistory>>
2022-08-19:12:57:35,412 ERROR   [validate.py:200] In #738=IfcLocalPlacement(#23,#737)
#23=IfcAxis2Placement3D(#22,#21,#19) not valid for <attribute PlacementRelTo?: <entity IfcObjectPlacement>>
2022-08-19:12:57:35,417 ERROR   [validate.py:200] In #713=IfcRelContainedInSpatialStructure('44d82c21-6f58-46ed-bf63-a1d90f30f98b',#23,$,$,(#712),#52)
#23=IfcAxis2Placement3D(#22,#21,#19) not valid for <attribute OwnerHistory: <entity IfcOwnerHistory>>
2022-08-19:12:57:35,418 ERROR   [validate.py:200] In #711=IfcLocalPlacement(#23,#710)
#23=IfcAxis2Placement3D(#22,#21,#19) not valid for <attribute PlacementRelTo?: <entity IfcObjectPlacement>>
2022-08-19:12:57:35,422 ERROR   [validate.py:200] In #694=IfcRelContainedInSpatialStructure('2212e28a-fadd-45cd-b310-bd329d75331e',#23,$,$,(#693),#52)
#23=IfcAxis2Placement3D(#22,#21,#19) not valid for <attribute OwnerHistory: <entity IfcOwnerHistory>>
```

Hope the explanation helps! I'm closing this bug :)

**Closed by Moult** 2022-08-19 02:59 UTC

**Comment by walidsamoud** [comment] 2023-10-19 16:07
how can I download ifcConvert 0.6 ?? i couldn't find it, can you help me please ? and thanks in advance

**Comment by aothms** [comment] 2023-10-22 09:19
@walidsamoud https://github.com/IfcOpenBot/IfcOpenShell/commit/721fe4729aa5302efe1602971aae2558934ad098#comments
