### ISSUE TITLE
Done scanning file

### ISSUE THREAD

**Issue by hujiaxin0** [IfcOpenShell/IfcOpenShell#410] opened 2018-07-09 13:48 UTC
The executable program is generated by compiling the source code. After “Done scanning file”, the executable program has no output for a long time.

**Comment by Stinkfist0** [comment] 2018-07-09 14:12
Related issue I made in the past, apparently the issue was forgotten open although I think at the time the problem was resolved, https://github.com/IfcOpenShell/IfcOpenShell/issues/122

**Comment by aothms** [comment] 2018-07-09 15:17
> Related issue I made in the past, apparently the issue was forgotten open although I think at the time the problem was resolved, #122

Seems to be applicable to XML only now.

Could also be that the first geometry item to interpret takes a very long time I think?

> is generated by compiling the source code

Did you enable compiler optimizations? What platform are you on.

What kind of file are we talking about in terms of file size / complexity? And what are you converting to?

**Comment by Jeffrey-Heart** [comment] 2018-07-10 02:18
My goal is to convert IFC files into OBJ files. The size of the IFC file is 197M.  

If I use your compiled executable program "IfcOpenShell-0.5.0-preview1", then it can run quickly. 

When I use your compiled executable program "IfcOpenShell-0.5.0-preview2",  the program will stop running after output "##............................"( only output two "#") .

When I  compile the source code to get an executable program.
The  program executes this statement `"context_iterator.initialize()"`
`
`            IfcSchema::IfcProduct::list::ptr products = ifc_file->entitiesByType<IfcSchema::IfcProduct>();
            for (IfcSchema::IfcProduct::list::it iter = products->begin(); iter != products->end(); ++iter) {
                IfcSchema::IfcProduct* product = *iter;
                if (product->hasObjectPlacement()) {
					// Use a fresh trsf every time in order to prevent the result to be concatenated
                    gp_Trsf trsf; 
					bool success = false;
					
					try {
						success = kernel.convert(product->ObjectPlacement(), trsf);
					} catch (const std::exception& e) {
						Logger::Error(e);
					} catch (...) {
						Logger::Error("Failed to construct placement");
					}
					
					if (!success) {
						continue;
					}

                    const gp_XYZ& pos = trsf.TranslationPart();
                    bounds_min_.SetX(std::min(bounds_min_.X(), pos.X()));
                    bounds_min_.SetY(std::min(bounds_min_.Y(), pos.Y()));
                    bounds_min_.SetZ(std::min(bounds_min_.Z(), pos.Z()));
                    bounds_max_.SetX(std::max(bounds_max_.X(), pos.X()));
                    bounds_max_.SetY(std::max(bounds_max_.Y(), pos.Y()));
                    bounds_max_.SetZ(std::max(bounds_max_.Z(), pos.Z()));
                }
            }``

 in the "bool initialize()" function of the source file "IfcGeomIterator.h" which takes a very long time.  

I was use the tool Visula Studio 2015 in Win10. This project is generated by your tools. 

> Did you enable compiler optimizations?
Sorry, I use the default configuration.

**Comment by Stinkfist0** [comment] 2018-07-10 06:20
The Debug build configuration should be only used when developing and debugging. For production use Release or RelWithDebInfo with `-DENABLE_BUILD_OPTIMIZATIONS=1` (pass this for `run-cmake.bat`) is recommended.

**Comment by Jeffrey-Heart** [comment] 2018-07-10 13:02
Thank you very much @Stinkfist0 and @aothms. I have recompiled the project with Release x64, and the speed has been greatly improved. But the program you provide is running 3 times faster than the program I compiled. How can I configure the compiler to achieve the speed of your programs?



.

**Comment by Stinkfist0** [comment] 2018-07-10 13:15
The IfcOpenShell-0.5.0-preview builds are really old. It's very possible that some conversion performance degrade has sneaked in since the builds as Thomas has been focusing mainly on conversion correctness recently.

**Comment by Stinkfist0** [comment] 2018-07-11 08:30
@Jeffrey-Heart also, make sure to use  `-DENABLE_BUILD_OPTIMIZATIONS=1` for the best performace:
```
>run-cmake.bat vs2017-x64 -DENABLE_BUILD_OPTIMIZATIONS=1
>build-ifcopenshell.bat
```

I can remember it having a substantial boost for performance.

**Comment by Jeffrey-Heart** [comment] 2018-07-14 12:48
I compiled the source code of IfcOpenShell-0.4.0, and found performance improved. However, it was found that memory was growing fast during the process of creating geometric even if I wrote the file with flush operation. Is it possible caused by the memory leak?

**Comment by aothms** [comment] 2018-08-10 13:36
No, flushing the file to disk is likely not going to have any impact. You might want to look here [1], and either add the preprocessor definition or just edit the source and disable caching. Caching is not very intelligent and depending on the type of file can result in a much larger memory footprint.

[1] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcgeom/IfcGeom.h#L62

**Comment by Moult** [comment] 2024-10-09 02:41
Closing as it seems performance has improved and likely doesn't compare at all to recent builds :)

**Closed by Moult** 2024-10-09 02:41 UTC
Labels: IfcOpenShell-Core
