### ISSUE TITLE
Lost scene info

### ISSUE THREAD

**Issue by Ave-5D** [IfcOpenShell/IfcOpenShell#4106] opened 2023-12-12 13:02 UTC
Please note the screen shot attached, the scene information is lost.

![Skermskoot (67)](https://github.com/IfcOpenShell/IfcOpenShell/assets/36395977/317908df-2abd-41d6-bb84-72dba2575983)
[2130 AIR BAG LEVELER IFC-IFC4.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/13648357/2130.AIR.BAG.LEVELER.IFC-IFC4.txt)

**Comment by Andrej730** [comment] 2023-12-12 13:54
Hi! Can't reproduce it. Can you please try the latest build (could be fixed with 7246e75)? 
If issue still persists please check console for errors (Window-Toggle System Console to open Blender console).

**Comment by Ave-5D** [comment] 2023-12-13 11:54
@Andrej730 , thanks for the feedback, I had to go back to to 231208
2df5b4c, download before the Scene info cameback.

**Comment by Andrej730** [comment] 2023-12-13 12:00
@Ave-5D new build (231213) doesn't work too? Any console errors?

**Comment by Ave-5D** [comment] 2023-12-13 12:26
Thanks its working again

**Closed** 2023-12-13 12:31 UTC
Labels: BlenderBIM
