### ISSUE TITLE
IFC4 file authored by BlenderBIM does not pass the buildingSMART online validation test

### ISSUE THREAD

**Issue by trhyder** [IfcOpenShell/IfcOpenShell#4240] opened 2024-01-20 16:04 UTC
My file was authored with BlenderBIM v0.0231104. I reported an issue relating to adding doors to element assemblies https://github.com/IfcOpenShell/IfcOpenShell/issues/4231 , which was closed. To test the fix I installed the latest build but when I went to open the ifc file, it would not load. There was no error message just the default cube remained.

I then tried to validate the ifc file with buildingSMART online validator (I had never done this before), and it failed - see below links

http://validate.buildingsmart.org/report_syntax_schema/QSwOUnvtErAPXaxerOcXBuUmqFcwUdVK
http://validate.buildingsmart.org/report_rules/QSwOUnvtErAPXaxerOcXBuUmqFcwUdVK
http://validate.buildingsmart.org/report_bsdd/QSwOUnvtErAPXaxerOcXBuUmqFcwUdVK

Should ifc files issued by BlenderBIM pass the buildingSMART validator?

[Mashoobra  Structure.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/13998457/Mashoobra.Structure.ifc.zip)

**Comment by Moult** [comment] 2024-01-20 23:01
Can you screenshot or copy paste the validation errors? My validate.buildingsmart account seems to be broken.

**Comment by trhyder** [comment] 2024-01-21 01:50
@Moult here are some screenshots:

syntax: passed

schema:
<img width="734" alt="Screenshot 2024-01-20 at 8 39 57 PM" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/59872808/3909154e-1f55-4478-af1c-286d55f6c0e7">


rules:
<img width="590" alt="Screenshot 2024-01-20 at 8 49 19 PM" src="https://github.com/IfcOpenShell/IfcOpenShell/assets/59872808/54019067-7f25-490b-9023-de92db4d3391">
plus another 10 pages (let me know if this is useful)

bsdd: passed

**Comment by trhyder** [comment] 2024-01-21 02:32
I was able to get the rules to pass by deleting all windows and doors

**Comment by Moult** [comment] 2024-01-21 04:03
> There was no error message

The error message is in the system console. It looks as though there are some orphaned IfcRelNest entities. I'm not entirely sure what might cause this. One possibility is that you were modeling MEP objects (e.g. pipes) which nest ports, and somehow it was not deleted properly. However I tried to recreate it but couldn't.

Another possibility is that you were doing some sort of schedule (cost schedule, or work schedule?) which uses nesting. This had a bug which would corrupt your model, but that bug was fixed last week: https://github.com/IfcOpenShell/IfcOpenShell/issues/4203 - if you deleted a cost schedule or nested cost item but didn't have this fix, that would explain the "broken file".

**Comment by trhyder** [comment] 2024-01-21 04:22
Thanks @Moult, I believe it was the latter. I was trying to add a schedule but was having difficulties and gave up on it.

What do I need to do to fix my file?

**Comment by Moult** [comment] 2024-01-21 04:31
Well, that's just the tip of the iceberg. Your file contains a ton of validation errors. Some of which seem pretty absurd. Can you help answer these questions to help decipher exactly what's going on?

 1. Did you only use BBIM for this, or did you append assets or start with IFCs from other software?
 2. Did you ever create detailed mesh objects (e.g. high poly counts, not just simple rectangles) and then delete them again? I'm currently noticing some high polygon mechanical fasteners, anything else?
 3. Did you ever manually edit your IFC model (i.e. with a text editor) or use any of the debug panel's special purge tools or any other purge data tool?
 4. Did you ever run any optimisation tool? (e.g. IfcPatch optimise / recycle recipe, Solibri optimiser, etc).

**Comment by Moult** [comment] 2024-01-21 11:19
So your file is still full of validation errors, but the ones that I can pinpoint the cause of are fixed. I've attached your "recovered" file, but keep in mind it's still full of problems which may turn up again later.

I think there's only one (or perhaps two) more possible causes for validation, which seems to be related to deleting objects. The screenshot shows one of the types of objects that exhibit problems. Can you remember anything about this object, such as where it came from, how you created it, how you deleted it (in detail, do you press the delete key, do you delete the type or the occurrence...), etc?

![2024-01-21-220742_195x501_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/8e20f9c0-3fe3-40d0-99c0-93b7b4da0578)

**Comment by trhyder** [comment] 2024-01-21 12:30
Thanks @Moult, did you mean to attach my file?

I have been having some issues with deleting arrayed objects. It seems that if you array an object, and apply the array, you cannot IFC Delete the children. I think I tried to force delete these in the Outlier just using blender delete.

Here is my error log

```
Python: Traceback (most recent call last):
  File "/Users/tim/Library/Application Support/Blender/4.0/scripts/addons/blenderbim/bim/module/geometry/operator.py", line 509, in execute
    return IfcStore.execute_ifc_operator(self, context)
  File "/Users/tim/Library/Application Support/Blender/4.0/scripts/addons/blenderbim/bim/ifc.py", line 336, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "/Users/tim/Library/Application Support/Blender/4.0/scripts/addons/blenderbim/bim/module/geometry/operator.py", line 542, in _execute
    self.process_arrays(context)
  File "/Users/tim/Library/Application Support/Blender/4.0/scripts/addons/blenderbim/bim/module/geometry/operator.py", line 587, in process_arrays
    data = [(i, data) for i, data in enumerate(tool.Blender.Modifier.Array.get_modifiers_data(array_parent))]
  File "/Users/tim/Library/Application Support/Blender/4.0/scripts/addons/blenderbim/bim/module/geometry/operator.py", line 587, in <listcomp>
    data = [(i, data) for i, data in enumerate(tool.Blender.Modifier.Array.get_modifiers_data(array_parent))]
  File "/Users/tim/Library/Application Support/Blender/4.0/scripts/addons/blenderbim/tool/blender.py", line 616, in get_modifiers_data
    for modifier_data in json.loads(array_pset["Data"]):
TypeError: 'NoneType' object is not subscriptable
```

**Comment by trhyder** [comment] 2024-01-21 12:35
To respond to your earlier questions:
1. I imported ifc types from an ifc file created with an earlier version of BBim
2. guilty
3. guilty - at one point I used a text editor to delete a child of an applied array
4. nope

**Comment by trhyder** [comment] 2024-01-22 02:20
@Moult, is there a way I can copy things over to a new file so that I can get rid of the errors?

**Comment by Moult** [comment] 2024-01-23 01:55
OK, I think I've exhausted all information here in terms of being able to fix things. I can't recreate the array bug you mention right now (potentially already fixed in latest builds). If you haven't already, I highly recommend upgrading to the latest Github build. The last "stable" release is very old now.

Because the damage is already done, I've recovered your file as best I can and it should now be 100% valid. Hope it helps. Please do report any bugs you come across and I'll do what I can.

[test4.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/14017319/test4.ifc.txt)

**Closed by Moult** 2024-01-23 01:55 UTC
Labels: BlenderBIM
