### ISSUE TITLE
Separate group tags on converting ifc 2d representations to svg

### ISSUE THREAD

**Issue by Andrej730** [IfcOpenShell/IfcOpenShell#3330] opened 2023-06-21 11:59 UTC
In BlenderBIM when we convert ifc to svg to print the drawing there is a bit an of issue that all 2d representations of elements are presentes as bunch of paths inside single `<g>` tag with  `class="projection"`. So we can't specify any separate styles with css for all those representations - for example, we can't add some class to display this element demolished with red dashed line.

Ifc project example for tests - [demolish.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/11817220/demolish.zip)

In the printed svg walls, window without 2d representation have separate `<g>` tags. 
Door and window with 2d representations (Plan/Body/PLAN_VIEW Curve2d) have all their paths under the same tag. Also some parts of the wall and the window without 2d repr is also under this tag.
![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/9fe5e973-1b34-4bca-9c98-bb137a2dad4b)

Any way around it? Maybe I'm missing some feature we already have or some option in `SvgSerializer`?

**Comment by theoryshaw** [comment] 2023-06-21 19:59
+1
related: https://github.com/IfcOpenShell/IfcOpenShell/issues/3002

**Comment by Moult** [comment] 2023-07-12 11:29
Yeah this is a duplicate of #3002. @aothms needs to tackle this aspect in C++ I believe.

**Closed by Moult** 2023-07-12 11:29 UTC
Labels: BlenderBIM, IfcOpenShell-Core
