### ISSUE TITLE
Bonsai v0.8 - error when printing to SVG - cannot print SVG

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#5393] opened 2024-09-15 20:10 UTC
these versions:
![image](https://github.com/user-attachments/assets/7d0ea0a5-5ffd-412b-8bd8-86be6640dddb)
![image](https://github.com/user-attachments/assets/66b0585b-c216-4b53-a469-6a95d8d64876)

When printing to SVG after adding doors and windows on any file I get this error:

Python: Traceback (most recent call last):
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 272, in execute
    linework_svg = self.generate_linework(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 778, in generate_linework
    self.serialiser.finalize()
  File "C:\Users\user-pc\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 5092, in finalize
    return _ifcopenshell_wrapper.SvgSerializer_finalize(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: An unknown error occurred

without doors and windows it prints fine:
![image](https://github.com/user-attachments/assets/1f9430c8-8dcb-4b74-a315-3d83cb740750)

Ifc file to test:
[Bonsai plan - Copy.ifc.txt](https://github.com/user-attachments/files/17007239/Bonsai.plan.-.Copy.ifc.txt)

Opened and printed with ![image](https://github.com/user-attachments/assets/ee425545-7fd3-4cca-b73b-7ffb57086103)
no issue printing to SVG:
![image](https://github.com/user-attachments/assets/3de4a5a3-0e59-45b1-b395-b3997b1920aa)

**Comment by Plae-Blue-Dot** [comment] 2024-09-15 20:19
After testing on versions from the last few days,
The last version it worked was: 
![image](https://github.com/user-attachments/assets/f4ddc67e-db57-453a-9176-d09fe2e20d13)
From 0.8.1-alpha240912 onwards, there is this issue, so it was probably caused by a commit between 0.8.1-alpha240911 and 0.8.1-alpha240912

**Comment by Moult** [comment] 2024-09-19 01:53
Duplicate of #4924.

**Closed by Moult** 2024-09-19 01:53 UTC
Labels: Bonsai
