### ISSUE TITLE
Error running drawing

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5380] opened 2024-09-12 17:14 UTC
I tried to run `FLOOR PLAN - 1ST FLOOR ` drawing and got the following error.

```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 272, in execute
    linework_svg = self.generate_linework(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 778, in generate_linework
    self.serialiser.finalize()
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 5092, in finalize
    return _ifcopenshell_wrapper.SvgSerializer_finalize(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: An unknown error occurred

```

file: https://www.dropbox.com/scl/fi/z3i1henh50s8kuswq4acm/2917_International_Ln_old.ifc?rlkey=53vijt80mj84ol8f48i8ocpwq&dl=0

when i tried running `bpy.ops.bim.debug_active_drawing()`, i got... https://gist.github.com/theoryshaw/7988cbfb418041bcc246c7b6ef64591e

**Comment by theoryshaw** [comment] 2024-09-12 17:16
fyi, this might be from running 

bpy.ops.bim.purge_unused_objects(object_type='MATERIAL')
and
bpy.ops.bim.purge_unused_objects(object_type='STYLE')

**Comment by theoryshaw** [comment] 2024-09-12 17:47
> fyi, this might be from running

not the case, as this file has the same problem--which is before the purge:
https://hub.openingdesign.com/OpeningDesign/2917_International_Ln/src/commit/c030130ffced43b47550d6e8724ea625e0a04d48/Open/Models/BlenderBIM/2917_International_Ln.ifc

**Comment by theoryshaw** [comment] 2024-09-12 18:18
Upon further research... 
it works on: bonsai-0.8.1-alpha240911 (unstable)
but doesn't work on: bonsai-0.8.1-alpha240912 (unstable)

**Comment by Plae-Blue-Dot** [comment] 2024-09-16 06:47
These might be the same issue:
https://github.com/IfcOpenShell/IfcOpenShell/issues/5393

**Comment by Moult** [comment] 2024-09-19 01:53
Duplicate of #4924.

**Closed by Moult** 2024-09-19 01:53 UTC
Labels: Bonsai
