### ISSUE TITLE
AttributeError: module 'ifcopenshell.util' has no attribute 'shape_builder'

### ISSUE THREAD

**Issue by captainvoldemort** [IfcOpenShell/IfcOpenShell#5458] opened 2024-09-23 12:55 UTC
I am getting the error 
```
builder = ifcopenshell.util.shape_builder.ShapeBuilder(model)
AttributeError: module 'ifcopenshell.util' has no attribute 'shape_builder'
```
while creating [custom representations](https://docs.ifcopenshell.org/ifcopenshell-python/geometry_creation.html#custom-representations). I am using it as 

```
import ifcopenshell
from ifcopenshell.api import run

model = ifcopenshell.file()
project = run("root.create_entity", model, ifc_class="IfcProject", name='project_name')
length_unit = run("unit.add_conversion_based_unit", model, name="FOOT")
run("unit.assign_unit", model, units=[length_unit])
context = run("context.add_context", model, context_type="Model")
body = run("context.add_context", model, context_type="Model",
           context_identifier="Body", target_view="MODEL_VIEW", parent=context)
site = run("root.create_entity", model, ifc_class="IfcSite", name='site_name')
building = run("root.create_entity", model, ifc_class="IfcBuilding", name='building_name')
storey = run("root.create_entity", model, ifc_class="IfcBuildingStorey", name='storey_name')
run("aggregate.assign_object", model, relating_object=project, products=[site])
run("aggregate.assign_object", model, relating_object=site, products=[building])
run("aggregate.assign_object", model, relating_object=building, products=[storey])
element = run("root.create_entity", model, ifc_class='IfcPipeSegment')

builder = ifcopenshell.util.shape_builder.ShapeBuilder(model)

# Sweep a 10mm radius disk along a polyline with a couple of straight segments and an arc.
curve = builder.polyline(
    [(0., 0., 0.), (100., 0., 0.), (171., 29., 0.), (200., 100., 0.), (200., 200., 0.)],
    arc_points=[2])
swept_curve = builder.create_swept_disk_solid(curve, 10)

# Create a body representation
body = ifcopenshell.util.representation.get_context(model, "Model", "Body", "MODEL_VIEW")
representation = builder.get_representation(body, swept_curve)
run("geometry.assign_representation", model, product=element, representation=representation)
run("spatial.assign_container", model, relating_structure=storey, products=[element])
output_file = "ifcopenshell_trial.ifc"
model.write(output_file)
print(f"IFC file saved as {output_file}")
```

The ifcopenshell version I am using is `'0.8.0'` and python version is `Python 3.9.0`

**Comment by Moult** [comment] 2024-09-23 12:57
Do `import ifcopenshell.util.shape_builder`

**Comment by captainvoldemort** [comment] 2024-09-23 13:12
`import ifcopenshell.util.shape_builder` gives an `no module found mathutils` error, I have installed `ifcopenshell` without dependencies and was able to run my code smoothly using the `shape_builder` functionalities, before the update, could you please point me to the version of `ifcopenshell` which should run `shape_builder` without the above import 🙏🙏

**Comment by Moult** [comment] 2024-09-23 13:17
Shape_builder requires mathutils and always has since the beginning unfortunately.

**Comment by Moult** [comment] 2024-09-23 13:56
Duplicate of #5192.

**Closed by Moult** 2024-09-23 13:56 UTC
Labels: IfcOpenShell-Python

**Comment by captainvoldemort** [comment] 2024-09-24 11:59
@Moult it seems that blender 4.2 LTS is crashing while opening the IFC file produced from the above code, the IFC file is only around 4.006 MB and I've opened bigger files than that, there's no error or log produced. Thanks

**Comment by Moult** [comment] 2024-09-24 13:06
Cheers, BTW there is an issue with your model in that you are missing placements. Placements are not optional if you have geometry. See how we run `ifcopenshell.api.geometry.edit_object_placement` here: https://docs.ifcopenshell.org/ifcopenshell-python/code_examples.html#create-a-simple-model-from-scratch (with no args to be at the origin)

However I think the segfault is a separate issue, I've reported it here: #5474 and you've unearthed a regression with the latest release reported at #5473.

**Comment by captainvoldemort** [comment] 2024-09-24 14:09
@Moult It seems to be working without specifying the `object_placement` , as we're creating a [custom representation](https://docs.ifcopenshell.org/ifcopenshell-python/geometry_creation.html#custom-representations), the path seems to be the object placement, here's a [example file](https://github.com/user-attachments/files/17115827/working_sample.ifc.txt) in which I've created some pipe like structures without specifying the object placement and it works as expected. Upon running the same code for two different sets of paths, I had encountered the "Blender crashing" issue.

**Comment by Moult** [comment] 2024-09-24 23:27
It may work in some viewers (such as Bonsai) but this is just luck, it's not correct, and so behaviour in viewers are not predictable.

**Comment by captainvoldemort** [comment] 2024-09-25 12:13
@Moult sorry for troubling again, but the [ifc file](https://github.com/user-attachments/files/17130618/sample.ifc.txt)
 isn't opening up in blender (bonsai) even after setting the object placement. Here's the crash report 
[blender.crash.txt](https://github.com/user-attachments/files/17130664/blender.crash.txt)

Is this a problem related to the newly issues opened in this thread and will be solved in the upcoming releases or is it a issue with my code. 

PS: huge thanks for replying to my earlier mails and i really appreciated your work and dedication 🙏🙏

**Comment by Moult** [comment] 2024-09-25 12:22
I think the crash is a bug and already reported here: #5474. When @aothms finds the time he can probably help figure out what's wrong. I can't spot anything wrong with the code so far.
