### ISSUE TITLE
IfcConvert crash

### ISSUE THREAD

**Issue by arzezniczak** [IfcOpenShell/IfcOpenShell#213] opened 2017-05-08 12:51 UTC
I have IFC file from Archicad that I can't convert to OBJ using IfcConvert - application is crashing during some OpenCascade bounding box calculations (?) That's all I can say from call stack after crash. I can't reproduce this crash on other files.
I can't share this specific IFC file here - on public forum, so if there is any option to send it directly to someone who would try to fix this problem - it would be great.

**Comment by Stinkfist0** [comment] 2017-05-08 13:05
I wonder if this is related to #210 Does the crash still occur on the very latest code?

**Comment by arzezniczak** [comment] 2017-05-08 13:10
Yes, I've made IfcOpenShell build from master branch downloaded something like 5 hours ago and it's crashing. I have some backup IfcConvert.exe from 21 january 2017 and it's crashing too.

**Comment by aothms** [comment] 2017-05-16 14:58
Hi, you can send it to models@ifcopenshell.org and I will have a look. Thanks.

**Comment by aothms** [comment] 2017-05-17 10:35
It seems to be related to wall (`11zdX0AtD6a85A9TSJLXqw`) with a shell of 14485 (!) faces and with openings. For the boolean operations a BVH tree is computed in OCC (these are the bounding box operations you are seeing). This amount of faces results in 72708 primitives added to the tree. The depth of this tree seems to overflow the stack.

As a work around: On windows you can set a larger stack size during compilation. On *nix you can control this with `ulimit -s`. At this point I don't know how much bigger the stack needs to be for this op to complete.

A more complete solution would be a non-recursive tree traversal. I'll have to talk to the OCC guys about this.

**Comment by aothms** [comment] 2017-05-18 08:00
Fyi, https://tracker.dev.opencascade.org/view.php?id=28746

**Comment by aothms** [comment] 2017-05-18 13:04
@arzezniczak Are you ok with me attaching brep serializations (so, no relation to IFC) of the wall shape and opening shape to the OCC ticket? It seems the issue is quite specific to the operands. I wasn't able to replicate the issue with similar generated geometries.

**Comment by arzezniczak** [comment] 2017-05-18 13:08
Yes, it's fine.

**Comment by Moult** [comment] 2022-09-06 03:20
It seems as though this has been solved upstream in OCCT (2019) so closing issue.

**Closed by Moult** 2022-09-06 03:20 UTC
