### ISSUE TITLE
Weird geometry distorsion

### ISSUE THREAD

**Issue by femesq** [IfcOpenShell/IfcOpenShell#432] opened 2018-08-13 04:17 UTC
While playing with `master`'s version, I'm getting this result (DAE on OSX's Preview):
![image](https://user-images.githubusercontent.com/1899668/44012403-37d5be98-9e95-11e8-9b04-6fb83a0a14f4.png)

The conversion log is:
```
IfcOpenShell IFC2X3 IfcConvert 0.5.0-dev (OCC 7.2.0)
Scanning file...
Done scanning file
Creating geometry...
Done creating geometry (2713 objects)

Log:
[Error] {2iidF6XKT8nuxM3i8rxUBt} Not enough edges for:
#115430=IfcPolyLoop((#114584,#114558,#114934))
[Error] {2iidF6XKT8nuxM3i8rxUBt} Failed to process face boundary loop
#115430=IfcPolyLoop((#114584,#114558,#114934))
[Error] {2iidF6XKT8nuxM3i8rxUBt} Not enough edges for:
#115440=IfcPolyLoop((#114548,#114614,#114616))
[Error] {2iidF6XKT8nuxM3i8rxUBt} Failed to process face boundary loop
#115440=IfcPolyLoop((#114548,#114614,#114616))
[Error] {2iidF6XKT8nuxM3i8rxUBt} Not enough edges for:
#115445=IfcPolyLoop((#114696,#114594,#114650))
[Error] {2iidF6XKT8nuxM3i8rxUBt} Failed to process face boundary loop
#115445=IfcPolyLoop((#114696,#114594,#114650))
[Error] {2iidF6XKT8nuxM3i8rxUBt} Not enough edges for:
#115450=IfcPolyLoop((#114640,#114574,#114920))
[Error] {2iidF6XKT8nuxM3i8rxUBt} Failed to process face boundary loop
#115450=IfcPolyLoop((#114640,#114574,#114920))
[Error] {2iidF6XKT8nuxM3i8rxUBt} Not enough edges for:
#115460=IfcPolyLoop((#114640,#114576,#114612))
[Error] {2iidF6XKT8nuxM3i8rxUBt} Failed to process face boundary loop
#115460=IfcPolyLoop((#114640,#114576,#114612))
[Error] {2iidF6XKT8nuxM3i8rxUBt} Not enough edges for:


....... many (~1000's) repeated errors ....

[Error] {0iaBnUxYn6MOJVN6O2kwIr} Failed to process face boundary loop
#4602287=IfcPolyLoop((#4600311,#4600373,#4599977))
[Error] {0iaBnUxYn6MOJVN6O2kwIr} Not enough edges for:
#4603167=IfcPolyLoop((#4600515,#4600505,#4600013))
[Error] {0iaBnUxYn6MOJVN6O2kwIr} Failed to process face boundary loop
#4603167=IfcPolyLoop((#4600515,#4600505,#4600013))
[Error] {0iaBnUxYn6MOJVN6O2kwIr} Not enough edges for:
#4603172=IfcPolyLoop((#4600509,#4600549,#4600049))
[Error] {0iaBnUxYn6MOJVN6O2kwIr} Failed to process face boundary loop
#4603172=IfcPolyLoop((#4600509,#4600549,#4600049))

Conversion took 7 minutes 49 seconds
```

Using 0.5.0 release binary (OSX 64bits) this is the result:
![image](https://user-images.githubusercontent.com/1899668/44012426-64294cf8-9e95-11e8-982e-faf92caa9b15.png)

The conversion log is:
```
IfcOpenShell IFC2X3 IfcConvert 0.5.0-dev
Scanning file...
Done scanning file
Creating geometry...
Done creating geometry (2713 objects)

Log:
[Error] {2iidF6XKT8nuxM3i8rxUBt} Not enough edges for:
#164828=IfcPolyLoop((#164393,#164447,#164391))
[Error] {2iidF6XKT8nuxM3i8rxUBt} Failed to process face boundary loop
#164828=IfcPolyLoop((#164393,#164447,#164391))
[Error] {0ULrIx0Nj0_hWdvCIr_Lbz} Flattening face boundary
#720236=IfcFaceOuterBound(#720234,.T.)
[Error] {0ULrIx0Nj0_hWdvCIr_Lbz} Flattening face boundary
#720953=IfcFaceOuterBound(#720951,.T.)
[Error] {1O$PEMnMf41e9Ayemhrx4H} Flattening face boundary
#4056527=IfcFaceOuterBound(#4056525,.T.)
[Error] {1O$PEMnMf41e9Ayemhrx4H} Flattening face boundary
#4057288=IfcFaceOuterBound(#4057286,.T.)
[Error] {1O$PEMnMf41e9Ayemhrx4H} Flattening face boundary
#4082830=IfcFaceOuterBound(#4082828,.T.)
[Error] {1O$PEMnMf41e9Ayemhrx4H} Flattening face boundary
#4082835=IfcFaceOuterBound(#4082833,.T.)
[Error] {1O$PEMnMf41e9Ayemhrx4H} Flattening face boundary
#4083587=IfcFaceOuterBound(#4083585,.T.)
[Error] {1O$PEMnMf41e9Ayemhrx4H} Flattening face boundary
#4109117=IfcFaceOuterBound(#4109115,.T.)
[Error] {1O$PEMnMf41e9Ayemhrx4H} Flattening face boundary
#4109122=IfcFaceOuterBound(#4109120,.T.)
[Error] {1O$PEMnMf41e9Ayemhrx4H} Flattening face boundary
#4109874=IfcFaceOuterBound(#4109872,.T.)
[Error] {1O$PEMnMf41e9Ayemhrx4H} Flattening face boundary
#4135336=IfcFaceOuterBound(#4135334,.T.)
[Error] {1O$PEMnMf41e9Ayemhrx4H} Flattening face boundary
#4136093=IfcFaceOuterBound(#4136091,.T.)

Conversion took 8 minutes 6 seconds
```

The model is big (and I don't have authorization to make it public), so I'm planning to try to make a smaller PoC to find where is the problem.
The interesting thing is that it looks like it was doing fine up to some point, and them it got lost somehow, messing beetwen  objects:
![image](https://user-images.githubusercontent.com/1899668/44012515-11343822-9e96-11e8-8c4a-ccbe99d0b161.png)

This is how it looks in Solibri Viewer:
![image](https://user-images.githubusercontent.com/1899668/44012581-7f7e8a12-9e96-11e8-9a54-033f12542c7e.png)

**Comment by aothms** [comment] 2018-08-13 08:29
Interesting, quite artistic. The most obvious place where this regression would occur is in this file [1], but nothing remarkable happened there, afaict.

Perhaps it's an option to send the file confidentially to models@ifcopenshell.org?

Otherwise, if you have the time, you could try with `git bisect` to find the offending commit.

Another option could be that it's due to the different versions of Open CASCADE and some subtleties there, OCCT shapes are not immutable.

[1] https://github.com/IfcOpenShell/IfcOpenShell/commits/master/src/ifcgeom/IfcGeomShapes.cpp

**Comment by femesq** [comment] 2018-08-13 12:15
Hi @aothms,
I was just trying to re-build it against OCE. Had to change from `0.18` to `0.18.3` due to [this error](https://github.com/tpaviot/oce/issues/643) and now the building process passed and stopped in inside `IfcLogger` due to any `boost` error:
```
In file included from /Users/felipe/PycharmProjects/IfcOpenShell/src/ifcparse/IfcLogger.cpp:26:
In file included from /Users/felipe/PycharmProjects/IfcOpenShell/build/Darwin/x86_64/10.6/install/boost-1.59.0/boost/property_tree/ptree.hpp:21:
In file included from /Users/felipe/PycharmProjects/IfcOpenShell/build/Darwin/x86_64/10.6/install/boost-1.59.0/boost/multi_index_container.hpp:34:
In file included from /Users/felipe/PycharmProjects/IfcOpenShell/build/Darwin/x86_64/10.6/install/boost-1.59.0/boost/multi_index/detail/base_type.hpp:21:
In file included from /Users/felipe/PycharmProjects/IfcOpenShell/build/Darwin/x86_64/10.6/install/boost-1.59.0/boost/multi_index/detail/index_base.hpp:26:
/Users/felipe/PycharmProjects/IfcOpenShell/build/Darwin/x86_64/10.6/install/boost-1.59.0/boost/multi_index/detail/vartempl_support.hpp:237:23: error: no template named 'forward' in namespace 'std'; did you mean simply 'forward'?
```
[This](https://github.com/b45ch1/pyadolc/issues/19) look very similar...

The reason I believe that is OCCT problem is because I've just build `master` on linux (against OCE) and the resulting geometry don't look as *artistic* as the one on Mac.. 😆

**Comment by aothms** [comment] 2018-08-15 14:25
Seems specific to the gcc version on osx according to https://stackoverflow.com/questions/27748442/is-clangs-c11-support-reliable#27749118

Apparently the current IfcOpenShell code base can no longer be compiled using the Darwin 10.6 toolset due to this issue in boost.

Maybe for now you can just hard code the toolset to 10.9 here [1] and build again.

[1] https://github.com/IfcOpenShell/IfcOpenShell/blob/master/nix/build-all.py#L125

**Comment by femesq** [comment] 2018-08-15 16:31
I've done this and can confirm that using OCE `0.18.3` with `10.9` toolset on MacOS the build process succeed...
...But, the resulting `dae` is now even more **artistics** and file-size is more than doubled from the `0.5-binary` release (that works fine):
![image](https://user-images.githubusercontent.com/1899668/44159069-c376ab80-a08c-11e8-8b6e-cb106f6d497b.png)

Also tried exporting to `obj` (to verify if the problem was with Collada and/or any of it's dependencies - OpenCollada, libxml, etc) and the result looks similar:
![image](https://user-images.githubusercontent.com/1899668/44159907-308b4080-a08f-11e8-8188-830676674e0a.png)

While with `0.5-binary` we got:
![image](https://user-images.githubusercontent.com/1899668/44159725-b2c73500-a08e-11e8-9d8c-aa60c4131561.png)

Was planning to build on linux with OCE `0.18.3` to verify if it works and to try limiting searching the solution on MacOS side only, but not sure if its the right direction to go..

Any suggestion on how I could help?

**Comment by aothms** [comment] 2018-08-17 14:51
Thank you for your continued effort to look into this.

> Any suggestion on how I could help?

We need to find the offending commit then. I can look into this as well, but I don't really have easy access to an OSX machine.

You can find the offending commit with `git bisect`

- `git bisect start`
- `git bisect bad`
- `git bisect good 40f3447ad1874afe19c2c252129005795d9426ed`
- rebuild
- run IfcConvert
- check output
- `git bisect good` / `git bisect bad` based on result

`git bisect` will keep changing `nix/build-all.py` (might even switch to `.sh` version at some point) so it might be good to reset this to the most recent version every rebuild: `wget -O nix/build-all.py https://github.com/IfcOpenShell/IfcOpenShell/blob/master/nix/build-all.py`

Instead of using the build script, which will keep the dependencies but cleans the IfcOpenShell build files every time, you might also just cd to the directory in `./IfcOpenShell/build/.../build/ifcopenshell/build` or something and run `make install` there each time.

If we're unlucky and `git bisect` ends up on a commit that doesn't compile / results on other errors during execution, you can use `git bisect skip`.

Let me know whether you want to have a go with this. Otherwise it'll likely take me some time to free my OSX machine for this.

**Comment by femesq** [comment] 2018-08-20 13:04
Ok, I'll try it...

Just a correction for anyone else trying this. To update the `nix/build-all.py` script, the source should be:

`wget -O nix/build-all.py https://raw.githubusercontent.com/IfcOpenShell/IfcOpenShell/master/nix/build-all.py`

**Comment by femesq** [comment] 2018-08-20 18:11
I found it strange and I hope I'm not doing anything wrong, but by `bisect`ing and updating the `build-all.py` script I've discovered that even that working `0.5.0p2 release`'s commit was not working...
Tried the other way:  The current `master` code-base with the `build-all.py` script from that commit with this changes:

- Updated OCE to `0.18.3` [here](https://github.com/IfcOpenShell/IfcOpenShell/commit/40f3447ad1874afe19c2c252129005795d9426ed#diff-3452a816195514e564474325fd8538e2L52);
- And changed min-toolset from `10.6` to `10.9` [here](https://github.com/IfcOpenShell/IfcOpenShell/commit/40f3447ad1874afe19c2c252129005795d9426ed#diff-3452a816195514e564474325fd8538e2L356)

All other dependencies and versions are the same.

**Comment by aothms** [comment] 2018-09-05 09:57
Sorry for the late reply. I'll try to find some time to look into this.

> So it's not problem with any dependency neither IfcOpenShell code... (probably that's why master worked fine on linux)

Well that's the difficulty with C++. In these huge libraries there are always corner cases of undefined behaviour picked up differently by compilers or different optimization levels.

**Comment by femesq** [comment] 2018-09-06 02:00
Ok... If you need any help (like testing) let me know..
Things worked just switching `build_all.py` (if I didn't made any mistake), so maybe I could try compiling it using `cmake` only... Does it make any sense?

**Comment by aothms** [comment] 2019-05-24 12:34
I haven't had any more reports about this lately, so I'm inclined to assume this was a temporary glitch from the interaction of a recent clang version and OCCT 7.2.0.

A user on the forum reported that downgrading XCode and recompile OCCT helped solve the issue for him.

https://sourceforge.net/p/ifcopenshell/discussion/1782717/thread/bfcd877640/

**Comment by Moult** [comment] 2023-02-14 02:49
Closing as conclusion seems to be that it's fixed.

**Closed by Moult** 2023-02-14 02:49 UTC
Labels: IfcConvert
