### ISSUE TITLE
Issue with Offset Handling in GLB Export (Version 0.8.0) (IfcOpenShell Python)

### ISSUE THREAD

**Issue by DelarreAlexis** [IfcOpenShell/IfcOpenShell#5305] opened 2024-09-04 12:59 UTC
Hello,

I was previously using IfcOpenShell version 0.7.0.240423, and recently I upgraded to version 0.8.0. However, I've noticed a difference in behavior between the two versions when working with the same model.

In version 0.8.0, it seems that the offset is not being applied correctly during the GLB export. With version 0.7.0.240423, the offset was applied as expected, but now, in 0.8.0, it looks like the offset is ignored, leading to issues in the positioning of objects in the exported GLB file.

Has there been any change in how offsets are handled in the latest version? Any guidance on how to resolve this issue would be appreciated.

Thank you!

v0.7.0 : 
https://github.com/user-attachments/assets/a5b036b9-c8ed-4770-bc08-d08317331dc5

v0.8.0 : 
https://github.com/user-attachments/assets/b0131466-c171-4d55-ba1b-792a1ae9680d

Code : 
`import ifcopenshell as ifc
import ifcopenshell.geom
import ifcopenshell.api
import ifcopenshell.validate
import ifcopenshell.util.placement
import ifcopenshell.util.geolocation
import time
from ifcGeometry import IfcGeometry

class IfcOpenShellProcessing:
    def Open(self, filePath):
        self.filePath = filePath
        self.ifcStore = ifc.open(filePath)
        self.ifcProject = self.ifcStore.by_type("IfcProject")[0]
        self.ifcUnitAssignment = self.ifcStore.by_type("IfcUnitAssignment")[0]
        
        self.geometrySettings = ifcopenshell.geom.settings(
            APPLY_DEFAULT_MATERIALS=True,
            WELD_VERTICES=False
        )

        self.geometrySerializerSettings = ifcopenshell.geom.serializer_settings()
        self.geometrySerializerSettings.set("use-element-guids", True)

        self.offset = None
        self.ifcUnits = []
        self.ifcObjects = {}
        self.geometries = {}

    def Close(self):
        del(self.filePath)
        del(self.ifcStore)
        del(self.geometrySettings)
        del(self.geometries)

    def CalculOffset(self, projectVersion):
        if projectVersion < 2:
            self.geometrySettings.set(self.geometrySettings.SITE_LOCAL_PLACEMENT, True)
        else:
            ifcGeom = IfcGeometry(self.ifcStore)
            self.offset = ifcGeom.calculateModelOffset()

    def ExtractGeometries(self):
        num_threads = 2

        if self.offset is not None:
            offset = ifcopenshell.ifcopenshell_wrapper.float_array_3()
            offset[0] = -self.offset[0]
            offset[1] = -self.offset[2]
            offset[2] = -self.offset[1]
            self.geometrySettings.offset = offset
        
        iterator = ifcopenshell.geom.iterator(self.geometrySettings, self.ifcStore, num_threads)

        sr = ifcopenshell.geom.serializers.gltf(self.filePath + ".glb", self.geometrySettings,self.geometrySerializerSettings)
        sr.writeHeader()

        if iterator.initialize():
            while True:
                shape = iterator.get()
                element = self.ifcStore.by_guid(shape.guid)

                faces = shape.geometry.faces
                verts = shape.geometry.verts

                grouped_verts = [[verts[i], verts[i + 1], verts[i + 2]] for i in range(0, len(verts), 3)]
                grouped_faces = [[faces[i], faces[i + 1], faces[i + 2]] for i in range(0, len(faces), 3)]

                vertexCount = len(grouped_verts)
                faceCount = 2 + (len(shape.geometry.edges) / 4) - len(grouped_verts)
                triangleCount = len(grouped_faces)

                self.geometries[shape.guid] = (vertexCount, faceCount, triangleCount)

                if not element.is_a('IfcOpeningElement'):
                    sr.write(shape)
            
                if not iterator.next():
                    break

        sr.finalize()

# DEBUG
path = 'volumes/'
filename = 'Duplex.ifc'

extractToJson = False

if __name__ == '__main__':
    t = time.process_time()

    ifcProcessing_dic = {}

    ifcProcessing = IfcOpenShellProcessing()
    ifcProcessing.Open(path + filename)
    ifcProcessing.CalculOffset(2)
    ifcProcessing.ExtractGeometries()
    ifcProcessing.Close()

    del(ifcProcessing)`

**Comment by Moult** [comment] 2024-09-05 23:27
Duplicate of #5231.

**Closed by Moult** 2024-09-05 23:27 UTC
Labels: IfcOpenShell-Core
