### ISSUE TITLE
Error when converting ifc file using IfcConvert

### ISSUE THREAD

**Issue by klokoy** [IfcOpenShell/IfcOpenShell#8] opened 2015-11-19 14:29 UTC
I have tried this in both v4 and v5 with same result.

When I convert the attached ifc file It seems like some windows and opening elements are skewed a bit. Opening the file in solibri shows a different result. Do you have any suggestion on what is happening, is there anything I can do to fix this?

![screen shot 2015-11-19 at 15 25 11](https://cloud.githubusercontent.com/assets/973082/11273106/d65816a0-8ed1-11e5-96d0-267eece1683d.png)

This is a screenshot from solibri showing the ifc file.
![screen shot 2015-11-19 at 15 25 33](https://cloud.githubusercontent.com/assets/973082/11273107/d65ddc0c-8ed1-11e5-9e20-77cf6982e7c0.png)

This is the ifc file:

[wallwindow.ifc](https://files.zenhub.io/564ddc1680486a947e5e3b6b)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by aothms** [comment] 2015-11-23 09:37
Thanks for your report. I will look into it.

Kind regards,
Thomas

**Comment by klokoy** [comment] 2015-11-24 15:14
The first ifc file I added was IFC4, attached you will find a 2x3 file with the same 
problem[wallwindow.ifc](https://files.zenhub.io/56547e7b5b75e1023f093404)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

The file works in BimServer. I was under the impression that they use the IfcConvert, is that correct?  Is there someway I can use the same code as BimServer to convert from ifc to collada?

**Comment by Stinkfist0** [comment] 2015-11-24 15:43
Testing with the 2x3 version, the model seems to have a very wild offset (-114509.8, 0, -1185980). Using a --center-model command line switch (my own addition, not yet in official IfcOpenShell/IfcConvert) the wall seems fine:
![screenshot 2015-11-24 17 43 40](https://cloud.githubusercontent.com/assets/227876/11371774/e6c8f3ce-92d2-11e5-873a-8985ff24a07a.png)

**Comment by klokoy** [comment] 2015-11-26 11:14
Thanks @Stinkfist0 .  If we center the model in revit it works as expected.  Will the `center-model` command line switch be merged to master?

**Comment by Stinkfist0** [comment] 2015-11-26 12:44
Yes, eventually (assuming aothms will accept that). In the meantime you can build a version of IfcConvert with the feature (and couple other new options) from https://github.com/Tridify/IfcOpenShell-SourceForge

**Comment by aothms** [comment] 2015-11-30 22:03
I agree. There needs to be a way to skip placements that move the model overly far from the origin. The reason why this is not implemented now by default is that multiple models might need to me merged geometrically in which case these placements need to align across different models.

I did commit something to make use of more precision when outputting obj files [1], but depending on what kind of viewer you use, this extra precision is likely trimmed off again when being parsed by a viewer that only supports single precision floats (which I guess is a lot of them).

[1] https://github.com/aothms/IfcOpenShell/commit/bf292cccd00e9f2dc5232f035a9357233d95982b

**Comment by Stinkfist0** [comment] 2016-03-17 16:50
@klokoy Hi. Would it be OK for me to add wallwindow.ifc as a test case for --center-model to the repository?

**Comment by klokoy** [comment] 2016-03-18 07:29
@Stinkfist0 No problem.

**Closed** 2016-03-22 12:28 UTC

**Comment by Deadity** [comment] 2017-09-07 07:31
@Stinkfist0 Would it be possible to offset the whole ifc file instead of using --center-model. I have a lot of ifc files in global positions that I need to move to a local origin that I have preassigned. I used a simple script to simply change the IFCCARTESIANPOINT to the appropriate value. The problem is that that there are a lot of schemas and versions that have their own scaling and positioning particularities. If I could simply use the IfcOpenShell python module to do arbitrary position reading and translation regardless of ifc schema I would be more than pleased.

**Comment by Stinkfist0** [comment] 2017-09-07 07:36
I won't mind having an alternative solution, `--center-model` was kind of brute force approach after all.  I wonder if `--site-local-placement` has made `--center-model` even obsolete now?

**Comment by aothms** [comment] 2017-09-08 15:12
@Deadity @Stinkfist0 isn't this what the `--model-offset` is doing? https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/ifcconvert/IfcConvert.cpp#L294

>  I wonder if --site-local-placement has made --center-model even obsolete now?

Indeed there is overlap of their use cases if you are interested in resetting a large placement as this issue is about. Centering does a bit more though. might still be useful for large buildings or when the offset is introduced at another level.

**Comment by Stinkfist0** [comment] 2017-09-11 09:23
Ah yes, --model-offset is probably just what @Deadity needs.
