### ISSUE TITLE
Spreashseet Import Export Pset_.*Common.Status roundtrip

### ISSUE THREAD

**Issue by steverugi** [IfcOpenShell/IfcOpenShell#5812] opened 2024-11-27 11:23 UTC
on exporting the status of an element

![image](https://github.com/user-attachments/assets/c1406ba6-08b8-42a1-bb74-b3091450fee4)

to a .csv I have

![image](https://github.com/user-attachments/assets/76d02d51-13a7-4e93-858b-8772367c561f)

when I import back the same exported .csv it triggers an error

"Value "NEW" is not a valid value for enum property Status"

![image](https://github.com/user-attachments/assets/47e9f040-3699-4e89-8e6d-e48dbdd7f702)

I tried variations like 'NEW' or "NEW" but it returns the same

thanks in advance for your assistance

**Comment by Andrej730** [comment] 2024-11-27 13:26
Duplicate of #4608

**Closed as completed by Andrej730** 2024-11-27 13:26 UTC
Labels: Bonsai
