### ISSUE TITLE
Instance lengths of IfcMemberType are all connected. 

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#2982] opened 2023-04-13 22:19 UTC
Instance lengths of IfcMemberType are all connected. 

[Clothing_Boutique.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/11226946/Clothing_Boutique.txt)

video: https://www.dropbox.com/s/scfppmt15cxcall/2023-04-13_17-15-36_Blender_blender.mp4?dl=0

**Comment by Moult** [comment] 2023-04-15 12:53
I can't recreate this :( There are three members, a bottom horizontal transom, top horizontal transom, and side vertical mullion. The top one is completely missing its representation, which is definitely incorrect, but I don't know how it got into that state (unless you manually deleted its Body representation, which I doubt). So there must've been an earlier error which has sailed by that was the true issue (I guess the moment you see any Python error of any kind, report a bug).

The vertical mullion has a connection to the top one, but since the top one is corrupt, I'm unable to change the vertical one's extrusion depth unless I remove that parametric connection.

How did you create these members? Any other hints I can use to sleuth this one down?

**Comment by theoryshaw** [comment] 2023-04-15 18:11
Yeah, that's weird, having just opened this IFC I can't get that behavior to work either, again.

**Comment by theoryshaw** [comment] 2023-04-15 18:20
related? 
https://github.com/IfcOpenShell/IfcOpenShell/issues/2936#issuecomment-1509920722

**Comment by Moult** [comment] 2023-04-15 22:09
At a wild guess, a possible related bug which was recently addressed was the undo features for the array tool (if you happened to use the array tool during the same time). Unfortunately we'll need to close this as it's not reproducable. Keep a keen eye out (the very moment a Python error appears, even if it doesn't pop up, such as in the togglable System console, report it even if you don't remember what you did to cause it) and we'll see.

Hopefully we're getting increasingly stable.

**Closed by Moult** 2023-04-15 22:09 UTC
Labels: BlenderBIM
