### ISSUE TITLE
Error with bSDD assigning in Bonsai

### ISSUE THREAD

**Issue by MagdaKladz** [IfcOpenShell/IfcOpenShell#5404] opened 2024-09-17 09:53 UTC
I have a problem with **assigning classes and parameters from bSDD to my IFC 2x3 model in Bonsai.** Previously there was a message about matching 0 elements to property sets. Now an error message like this appears:
```
Python: Traceback (most recent call last):
  File "C:\Users\mkrolikowska\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\pset\ui.py", line 305, in draw
    ObjectQtosData.load()
  File "C:\Users\mkrolikowska\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\pset\data.py", line 140, in load
    "qtos": cls.psetqtos(tool.Ifc.get_entity(bpy.context.active_object), qtos_only=True),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mkrolikowska\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\pset\data.py", line 57, in psetqtos
    pset_uses = ifcopenshell.util.element.get_elements_by_pset(pset)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mkrolikowska\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\util\element.py", line 459, in get_elements_by_pset
    raise Exception(f"Unexpected pset type: '{pset.is_a()}' ({pset}).")
Exception: Unexpected pset type: 'IfcElementQuantity' (#41873=IfcElementQuantity('1L2XaKa6vCqOrAKIpcX6nl',#5,'BaseQuantities',$,$,(#41869,#41870,#41871,#41872))).
```

**Comment by Andrej730** [comment] 2024-09-18 13:45
@MagdaKladz Hi! The issue is that the error occurred when you tried to add a classification reference or the problem is that added quantity set is not visible after you added a reference? 
If it is the latter, it should be fixed in the latest version. 
If it's the issue adding a reference, then I couldn't reproduce this - please describe the exact steps to reproduce the problem.

**Comment by MagdaKladz** [comment] 2024-09-18 14:15
The error occurred when I tried to add a classification reference. I have the latest version of Bonsai.
 1. In budildingSMART Data Dictionary I load  and active bSDD with a Preview Status
 2. In Classifications I set a source as buildingSMART Data Dictionary and click on Add Classification from bSDD
 3. I select the element in the IFC model (column) and go to Object Information. In Classification References i search the relevant class
 4. I click on search bSDD class properties and know there is no problem but it still does not search for properties from the bSDD and information appears that 0 pset found for the active classification.
 
![Zrzut ekranu 2024-09-18 160933](https://github.com/user-attachments/assets/9b3a1023-aee7-4dee-a955-ce12a9e75a54)

**Comment by MagdaKladz** [comment] 2024-09-19 06:24
So it's impossible to use your own dictionaries with your own classes and properties in them? That doesn't make sense, because bSDD was created for exactly that purpose - not all classes and properties can be referenced in IFC. Even native software allows to assign own classification to elements in the model. Will there be such a possibility in Bonsai?

**Comment by Andrej730** [comment] 2024-09-19 13:58
I agree that it is useful, I'll implement an option to display and add non-ifc bsdd psets too.

**Comment by Andrej730** [comment] 2024-09-20 07:34
Supported after 4f64d044ac

**Closed by Andrej730** 2024-09-20 07:34 UTC
Labels: Bonsai
