### ISSUE TITLE
Bonsai tool shortcuts inconsistent, conflict with vanilla Blender

### ISSUE THREAD

**Issue by rungutter** [IfcOpenShell/IfcOpenShell#5203] opened 2024-08-20 23:35 UTC
While in Bonsai, I'm unable to use Tab to switch between object mode and edit mode. E.g. I have a wall selected in object mode, and hitting Tab returns the error "Object cannot be edited: IFCWall/Wall.008." I can, however, use the dropdown menu to select edit mode.

While in Object Mode> BIM Tool, with the Tool tab open, after I enter parameters for my desired wall, "Shift+A" does not work for adding the object, so I click the "Add" button instead and this works. After adding the object, "Shift+R" does not consistently work for rotating the object 90 degrees. Often it repeats the previous action, which is the vanilla Blender shortcut. Confusingly, sometimes it does rotate 90 degrees, though. It is unclear what makes Blender choose one action over the other. 

I'm running Blender 4.2 on Windows 10, with Bonsai vers 0.7.11-alpha240814. IFC and .blend files are attached.
[HealyHouse.zip](https://github.com/user-attachments/files/16683300/HealyHouse.zip)

**Comment by SavuGust27** [comment] 2024-08-21 02:47
Not entering edit mode on wall is a feature, not a bug. editing walls (those created from the type template or from the demo library) is not permited on purpose, because in the past it would break models and not save the changes. if you want to edit the wall normally, like in blender, you have to first create a mesh, like just adding a cube, and then assign it as an ifcelement. Then bonsai will let you enter edit mode, ,since it will take into acount that it is a mesh, and should let you edit it that way by pressing tab

Also, did you make sure that when you press a bonsai comand you have a tool selected?
you should be in any of those
![Screenshot 2024-08-20 223932](https://github.com/user-attachments/assets/ec269cce-4e47-476d-ab23-6532324179fe)

because if you have selected another tool, blender comands will execute

**Comment by rungutter** [comment] 2024-08-21 03:38
I'm needing to add a peak to an exterior wall. I see no other way to do so. I do see that the ifc file doesn't save these edits, which is frustrating, but I'm new to BIM so maybe this isn't a typical need? 

Yes, regarding the Bonsai shortcuts, I am staying in the BIM tool. I edit the dimensions of the wall, hit Shift+A, which rarely works, so then I just press "Add." Then, if I need to rotate, I immediately press Shift+R. This only works part of the time. Often it just adds the same wall again, per the Blender shortcut for Shift+R, "Repeat previous action"

**Comment by Moult** [comment] 2024-08-21 12:27
For the tab button, yes, it's purposely blocking you because it's a parametric, solid-extrusion wall (i.e. it's not actually a mesh, so naturally you can't edit it as a mesh). You need to convert it to a non parametric, tessellated wall if you want to start adding funny geometry to it :) We totally should add more specific messages that help explain this. At the bottom you should see "Object cannot be edited"

![2024-08-21-222640_267x38_scrot](https://github.com/user-attachments/assets/246c99ee-2ba1-40cd-b7e8-66eff1489832)

> While in Object Mode> BIM Tool, with the Tool tab open, after I enter parameters for my desired wall, "Shift+A" does not work for adding the object, so I click the "Add" button instead and this works. After adding the object, "Shift+R" does not consistently work for rotating the object 90 degrees. Often it repeats the previous action, which is the vanilla Blender shortcut. Confusingly, sometimes it does rotate 90 degrees, though. It is unclear what makes Blender choose one action over the other.

This is concerning. I can't recreate this issue, and the code behind this is pretty simple. Have you tried with a fresh factory install and no other add-ons? Alternatively, can we organise a screenshare session so I can debug together with you?

**Comment by rungutter** [comment] 2024-08-21 21:34
This is a fresh install with only BIM and grease pencil addons enabled, and now screencast keys as well in order to make the attached screencast for your reference. 

Starting at the 1-minute mark, you'll see me start a new IFC project, set measurements for a new wall, and when I press Shift+A, nothing happens. I add a wall using the "Add" button, and then attempt to rotate using Shift+R, which repeats my "add wall" action. I do this a few times before closing the recording. 

https://drive.google.com/file/d/19X7mPrQ0ZEaGMsV3Xs3069OCgcpkQeZk/view?usp=sharing

**Comment by Moult** [comment] 2024-08-21 22:48
Ah cool that's not a bug - that's just how Blender works.

Blender is a modal hotkey software. This means that hotkeys in Blender (any hotkey) depends on where your mouse is. If your mouse is hovering over a particular panel or area of the screen, that changes the meaning of the hotkey.

So if you press Shift-A, it only means "Add Object" if your mouse is hovering over the 3D viewport. So just be careful where your mouse is.

If this sounds strange, that's because you're right! Most software don't have modal behaviour. However Blender does, and that's just the way it is. Once you do get used to it, you'll probably start noticing benefits like shared homekey hotkeys across multiple panels that intuitively "just work" - and probably wish all software worked like that ;)

**Comment by rungutter** [comment] 2024-08-21 23:13
got it, thanks! That's great to know and I can see that being a perk once I get used to it

**Closed** 2024-08-22 00:32 UTC
Labels: Bonsai
