### ISSUE TITLE
type geometry from IfcBuildingElementPartTypes should show up in the project view

### ISSUE THREAD

**Issue by kurb70** [IfcOpenShell/IfcOpenShell#4654] opened 2024-05-10 11:37 UTC
Did some experiments with element types. I have created an IFC4 project with an IfcSolarDeviceType that is placed 5x. Works well.

In the next step, I want to define the type using two IfcBuildingElementPartTypes. Therefore I have defined a very simple geometry for ONE IfcBuildingElementPartType.

Unfortunately, the type geometry is not applied in the project view.

Should BlenderBIM be able to display this?
If yes, I would be grateful for tips on where I am setting up my model incorrectly.

[bim4bipv-model-with-parts.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/15274487/bim4bipv-model-with-parts.ifc.txt)
for comparing also [bim4bipv-model-without-parts.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/15274490/bim4bipv-model-without-parts.ifc.txt)

![Screenshot 2024-05-10 at 13 16 35](https://github.com/IfcOpenShell/IfcOpenShell/assets/1941141/717c1a83-4790-4015-8351-3b65e6a9c997)

**Comment by Moult** [comment] 2024-05-10 12:20
This is a limitation - we don't yet support instantiating aggregate types. Duplicate of #2052.

**Closed by Moult** 2024-05-10 12:20 UTC

**Comment by kurb70** [comment] 2024-05-10 14:35
Thank you. What a pity. I assume that this will not be implemented any time soon?

BTW The following software do not show the placed instances either:

- https://www.bimcollab.com/en/products/bimcollab-zoom/
- https://www.solibri.com/solibri-office (does not even recognize that types exist)

I'm also wondering whether there is software that can display such a construction.

**Comment by theoryshaw** [comment] 2024-05-10 15:56
@kurb70 
in the meantime, could you use the following instead?
https://community.osarch.org/discussion/2015/linked-aggregate/p1
