### ISSUE TITLE
Blend file doesn't store classifications, so if you move to another computer you can't export

### ISSUE THREAD

**Issue by cgieling** [IfcOpenShell/IfcOpenShell#1031] opened 2020-10-08 10:59 UTC
Hi,

I am having difficulties in exporting a Blender file to an IFC, using the Add-on.
This log appears:

_Traceback (most recent call last):
  File "C:\Users\Saxion\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\operator.py", line 107, in execute
    ifc_exporter.export(context.selected_objects)
  File "C:\Users\Saxion\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\export_ifc.py", line 1319, in export
    self.ifc_parser.parse(selected_objects)
  File "C:\Users\Saxion\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\export_ifc.py", line 102, in parse
    self.classifications = self.get_classifications()
  File "C:\Users\Saxion\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\export_ifc.py", line 632, in get_classifications
    schema.ifc.load_classification(classification.filename)
  File "C:\Users\Saxion\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\schema.py", line 70, in load_classification
    self.classification_files[filename] = ifcopenshell.open(classification_path)
  File "C:\Users\Saxion\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\__init__.py", line 67, in open
    raise IOError("Unable to open file for reading")
OSError: Unable to open file for reading

location: <unknown location>:-1_

 

=====================================================================

It seems to be that the __init__.py can not be read. But I can open it with Spyder Python3.7.
Unfortunately in Spyder (python 3.7) it gives an error: 

  __File "C:\Users\Saxion\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\__init__.py", line 55, in <module>
    raise ImportError("IfcOpenShell not built for '%s'" % python_distribution)

ImportError: IfcOpenShell not built for 'windows\64bit\python3.7'__

Can u please help me out with converting Blender's to IFC's with this add-on?!
Thank you in advance!

**Comment by Moult** [comment] 2020-10-09 02:32
It looks as though you have assigned invalid classifications to IFC objects. This may be a bug in the add-on, as it should ideally only allow the user to create valid data. Can you share your Blender file? If it is private, feel free to send to dion@thinkmoult.com and I will only use it for the purposes of debugging.

**Comment by aothms** [comment] 2020-10-11 08:45
In addition, re:

> Unfortunately in Spyder (python 3.7) it gives an error:
> 
> _File "C:\Users\Saxion\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\libs\site\packages\ifcopenshell_init.py", line 55, in
> raise ImportError("IfcOpenShell not built for '%s'" % python_distribution)
> 
> ImportError: IfcOpenShell not built for 'windows\64bit\python3.7'__

IfcOpenShell is a module written in C++ so it's specific to Operating System, Python version and 32/64 bits. But you can download all options here if you want to experiment: http://ifcopenshell.org/python

**Comment by Moult** [comment] 2020-10-12 20:55
Bump, ping @cgieling can you provide the IFC file that I asked in the email? That is necessary for debugging.

Aside from that, if the problem is moving the blend file from one computer to another, that can be fixed too. I'll make a note of it.

**Comment by cgieling** [comment] 2020-10-19 06:55
Dear Dion,

Excuse me for my late reply.
I was out of office due to an autumn holiday.

I’ve asked a partner of mine for the original IFC file before my holiday started, but I haven’t got a reply on it yet.
I’ll fish after the original IFC again. ;-)

I hope to send it to you soon.

Met vriendelijke groet,

Chris Gieling
Onderzoeker
Lectoraat Sustainable Building Technology (SBT)
Lectoraat Duurzame energievoorziening (DEV)


Saxion | University of Applied Science – School of Business, Building & Technology (BBT)
M.H. Tromplaan 28 | Postbus 70.000, 7500 KB Enschede | Kamer E1.06A
T: | M: 06 82 93 54 99 | c.w.j.gieling@saxion.nl<mailto:c.w.j.gieling@saxion.nl> | Website Lectoraat SBT<https://www.saxion.nl/onderzoek/areas-and-living/sustainable-building-technology>
Werkdagen: ma, wo, do en vrij

**Comment by Moult** [comment] 2020-10-24 10:43
Just an update on this, sorry for the slow response. I've fixed one of the issues: https://github.com/IfcOpenShell/IfcOpenShell/commit/8872a13fd846015c01b30ef225005b7640ba2596

Prior to this fix, you would need to transfer the blend plus a few auxiliary files to another computer - the Blender file itself was not fully self contained. This is now fixed.

However, I think there are still a few more improvements I can make... I'll keep you posted when I think it's fully resolved.

**Comment by Moult** [comment] 2020-10-25 01:49
I think it should be fixed now. Now, if you re-import the IFC, you can transfer the blend to another computer and export successfully. Please let me know if you're still experiencing issues!

**Comment by cgieling** [comment] 2020-10-26 08:24
Thanks a lot!
Is it necessary to do a re-install or update of the add-on?
Or is it fixed right away?

**Comment by Moult** [comment] 2020-10-26 08:27
Yep - you are required to uninstall the current version, and install the latest version. A new release was made yesterday.

**Comment by cgieling** [comment] 2020-10-26 10:55
Thank you for the new release!
Unfortunately, after removing the older version and installing the new version.
An error occurs when I’m checking the checkbox for activating the add-on:

[cid:image001.jpg@01D6AB8E.F1CA21B0]

[cid:image003.jpg@01D6AB8E.F1CA21B0]


Am I doing something wrong?

**Comment by cgieling** [comment] 2020-10-29 14:51
Hi,

the images: 

![blender1](https://user-images.githubusercontent.com/62999728/97589645-13d44c80-19fe-11eb-8e92-89840baac9eb.jpg)
![blender2](https://user-images.githubusercontent.com/62999728/97589643-12a31f80-19fe-11eb-83ca-a6c821e6c294.jpg)

I've done a uninstall and re-install on the add-on and Blender itself. Unfortunately the problem wasn't solved.

**Comment by Moult** [comment] 2020-10-29 15:12
This looks like a strange installation issue. Does this folder exist?

`C:/Program Files/Blender Foundation/Blender\2.90\scripts\addons\blenderbim\libs\site\packages`

**Comment by cgieling** [comment] 2020-10-30 10:16
That path doesn’t exist on my computer.

I can’t get any further than this:
C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons

In the folder “addons” I can’t find “blenderbim” after installing it.
In Blender itself I still have the possibility to enable the add-on BlenderBim:

[cid:image001.jpg@01D6AEAE.21D70310]

[cid:image002.jpg@01D6AEAE.21D70310]
I have followed the installation steps as mentioned on the website: https://blenderbim.org/install-blenderbim.html
The visuals in Blender are a bit different. I guess because Blender has gotten a few updates in time, but the basics look the same:

·        Overwrite is checked

·        Target path is set on ”default”

·        Installed directly from the downloaded .Zip file

When I’ve installed it, I have the following logs when I click on the pop-up in the :
bpy.data.window_managers["WinMan"].addon_support = {'TESTING'}
bpy.data.window_managers["WinMan"].addon_support = {'COMMUNITY'}
bpy.data.window_managers["WinMan"].addon_support = {'OFFICIAL'}
bpy.data.window_managers["WinMan"].addon_support = {'TESTING'}
bpy.data.window_managers["WinMan"].addon_support = {'COMMUNITY'}
bpy.data.window_managers["WinMan"].addon_search = "blender"
Modules Installed (blenderbim) from 'C:\\Users\\Saxion\\Downloads\\blender28-bim-201025-win (1).zip' into 'C:\\Users\\Saxion\\AppData\\Roaming\\Blender Foundation\\Blender\\2.90\\scripts\\addons'

I’ve tried to change the installation path of the Blenderbim Add-on during installing the add-on, but I don’t know where I can change it:
[cid:image004.jpg@01D6AEAE.21D70310]
Okay, user prefs. But where can I change it?

I have followed the red colored path and found the Blenderbim installed here. (I saw later on, that it was also mentioned in the pull-down information of the add-on in Preferences)
I have even copied and moved it from this red path to C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons
But that didn’t had any effect. When I enable-check the Blenderbim in the add-ons in Blender still this error occurs:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender 2.90\blenderbim\__init__.py", line 24, in <module>
    from .bim import *
  File "C:\Program Files\Blender Foundation\Blender 2.90\blenderbim\bim\__init__.py", line 8, in <module>
    from . import ui, prop, operator
  File "C:\Program Files\Blender Foundation\Blender 2.90\blenderbim\bim\operator.py", line 10, in <module>
    import ifcopenshell.util.selector
  File "C:\Program Files\Blender Foundation\Blender 2.90\blenderbim\libs\site\packages\ifcopenshell\util\selector.py", line 3, in <module>
    import lark
ModuleNotFoundError: No module named 'lark'

I went to the green colored path and didn’t found a Python file called “lark”.
I’ve opened “selector.py” in Spyder. Well my Python is quite elementar, but I didn’t see any file “Lark” in the repository:

[cid:image005.jpg@01D6AEAE.21D70310]

I did found “lark” here: C:\Program Files\Blender Foundation\Blender 2.90\blender28-bim-201025-win\blenderbim\libs\site\packages\lark

[cid:image013.png@01D6AEAE.21D04C50]


Unfortunatel, my search for anomalies ends here…

Still a strange thing since the installation of the previous Blenderbim 200912 in Blender went smooth without any troubles.

**Comment by Nevermind3r88** [comment] 2020-10-31 09:26
Hi guys and thanks for your great work!
Maybe is the same problem, so I write here... my log is almost the same.
The last version works well, only some problems exporting objects before imported from other BIM softwares.
Now, I'm not able to export every object in my file.
This path doesn't exist on my pc:
C:/Program Files/Blender Foundation/Blender\2.90\scripts\addons\blenderbim\libs\site\packages\lark
I updated using your guide: remove folders in AppData, next addon and then install new version.
THANKS!

Windows 10 - BlenderBIM 0.201025.

Traceback (most recent call last):
  File "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\operator.py", line 107, in execute
    ifc_exporter.export(context.selected_objects)
  File "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\export_ifc.py", line 1350, in export
    self.ifc_parser.parse(selected_objects)
  File "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\export_ifc.py", line 86, in parse
    self.projects = self.get_projects()
  File "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\export_ifc.py", line 886, in get_projects
    'attributes': self.get_object_attributes(obj)
  File "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blenderbim\bim\export_ifc.py", line 170, in get_object_attributes
    attributes = {'Name': self.get_ifc_name(obj.name)}
AttributeError: 'NoneType' object has no attribute 'name'

location: <unknown location>:-1

**Comment by Moult** [comment] 2020-10-31 09:32
> I did found “lark” here: C:\Program Files\Blender Foundation\Blender 2.90\blender28-bim-201025-win\blenderbim\libs\site\packages\lark

@cgieling this looks like a suspicious path. I think it's easiest if we simply screenshare and see if we can resolve the issue and I can ask to see various files via screenshare. If that's OK, let me know what time works for you, anytime during the Sydney timezone is OK, we can meet using https://meet.jit.si/openbim

@Nevermind3r88 I think your error is something else. It looks to be complaining about the lack of an IfcProject. All exports require an IfcProject object in the scene. Please feel free to send me dion@thinkmoult.com your blend file and I can try and re-create your issue.

As we're both online now, feel free to send me a message on IRC live chat at https://blenderbim.org/community.html and if you'd like we can screenshare as well and help to debug your issue!

**Comment by Nevermind3r88** [comment] 2020-10-31 09:39
I'm on IRC live

**Comment by Moult** [comment] 2020-11-01 23:28
Ping @cgieling - can we organise a time to screenshare?

**Comment by Moult** [comment] 2020-11-04 07:54
Confirmed as resolved after screensharing session.

**Closed by Moult** 2020-11-04 07:54 UTC
Labels: BlenderBIM
