### ISSUE TITLE
Merge project patch fail with Pset_BuildingStoreyCommon

### ISSUE THREAD

**Issue by enruilo1** [IfcOpenShell/IfcOpenShell#2276] opened 2022-07-12 06:59 UTC
Hi, i try to use Merge project recipe with some of ifc files (from Revit) and it fail in this line (when entity is Pset_BuildingStoreyCommon):

![image](https://user-images.githubusercontent.com/46839816/178427359-023cc79f-abb3-4cb4-bf4c-a28fe49fca53.png)

If I debug inside (inside de py wrapper of IfcOpenShell) , the real bug is in this constructor of entity_instance:
![image](https://user-images.githubusercontent.com/46839816/178428075-60f7e307-c546-4491-bb04-a7c3557278d5.png)

I dont know how to repair that and if fail for mayority of my ifc files because Pset_BuildingStoreyCommon is a common entity in ifc.

Thanks for your collaboration with this excelent ifc library

**Comment by aothms** [comment] 2022-07-12 07:06
`self.wrapped_data.add()` on file.py:337 is where the C++ code is called from python. We'll need the data to reproduce the bug. Can you attach a minimal case here or (if needed) confidentially to models@ifcopenshell.org? Thanks

**Comment by enruilo1** [comment] 2022-07-12 08:16
Ok, i have already sent to models@ifcopenshell.org. Thank you so much for your rapid response.

**Comment by Moult** [comment] 2022-08-01 05:33
Did we get any progress on this? Maybe there is something I can help with?

**Comment by IbimDesarrollo** [comment] 2022-08-01 07:26
Hi Dion, I have already sent ifc models to specific email but I don't know anything else. I don't know C++ to provide a solution to this error, sorry. I thought about filtering (from the Python side) these entities (Pset_BuildingStoreyCommon) to the merged file, but it's not a clean solution.

**Comment by IbimDesarrollo** [comment] 2022-08-02 10:40
Sorry, i'm enruilo1 user who open the issue too, same user but with my work count. Sorry for confusion.

**Comment by Moult** [comment] 2022-08-04 23:37
@IbimDesarrollo that email is manned by @aothms  and perhaps he's busy/missed it/etc would you mind resending the details to dion@thinkmoult.com and I can have a look? I can't promise I can solve it, but if it is something I can't solve, at the very least I can convert it into a MWE for @aothms  to investigate easily.

**Comment by enruilo1** [comment] 2022-08-06 16:37
@Moult its done to your mail too. Thanks¡¡¡

**Comment by Moult** [comment] 2022-08-16 04:00
Sorry for the delay. You sent me two files, so I merged them using the MergeProject recipe and I did not get any errors.

![2022-08-16-135839_755x168_scrot](https://user-images.githubusercontent.com/88302/184795139-f200d8a8-08a5-4f71-9c03-4a021d1a5c01.png)

**Comment by IbimDesarrollo** [comment] 2022-08-17 08:18
Hi @Moult , I tried the blenderBIM patch recipe and it works¡¡, I thought it was a version issue, and when I updated the version of ifcopenshell to the same as BlenderBIM (I retrieved it from the download package on BlenderBIM website, but I think it's version 0.7.0), the bugs disappeared. Thanks for the help, the problem is solved.

**Comment by Moult** [comment] 2022-08-17 08:36
Awesome :) Thanks for checking it out!

**Closed by Moult** 2022-08-17 08:36 UTC
Labels: BlenderBIM
