### ISSUE TITLE
BB 220104 install error

### ISSUE THREAD

**Issue by cadgiru** [IfcOpenShell/IfcOpenShell#1959] opened 2022-01-04 07:12 UTC
This error seems to have persisted since 211211
Win10, Blender 3.0
[bbTrace220105.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/7805908/bbTrace220105.txt)

**Comment by EloyRD** [comment] 2022-01-04 19:57
I also tried installing the latest build blenderbim-220104-py39-win and didn't work.
I was able to activate the build linked in blenderbim.org  blenderbim-211031-py39-win without further issues, but doing it in Admin mode.

**Comment by Moult** [comment] 2022-01-05 05:15
The issue is that the build bot is using a build from 26 days ago: https://github.com/IfcOpenBot/IfcOpenShell/commit/b9ea741e5eb3a0a020c9d36fa8e15deb1fc87dd0 and the build process overrides some Python files from the build bot.

Short term solution:

Grab this file: https://github.com/IfcOpenShell/IfcOpenShell/blob/0d49c899432197ec0854bd2f8cf5fc6e4ff55ac9/src/ifcopenshell-python/ifcopenshell/entity_instance.py and replace your file in blenderbim/libs/site/packages/ifcopenshell/entity_instance.py

Longer term solution, which we will wait for prior to the next "stable" release:

@aothms  can you help trigger another bot build? Is there a way I can trigger it without bothering you each time?

**Comment by cadgiru** [comment] 2022-01-07 09:02
Tried workaround on Ubuntu 20.04.3 LTS... It Works, thx

**Comment by Moult** [comment] 2022-01-19 01:24
Closing as next build should have the latest IfcOpenShell module :)

**Closed by Moult** 2022-01-19 01:24 UTC
Labels: BlenderBIM
