### ISSUE TITLE
Error when creating the `MY STOREY PLAN` drawing

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#5136] opened 2024-08-03 15:32 UTC
Error when creating the `MY STOREY PLAN` drawing

file: https://github.com/elschilling/class2layer/blob/ed64fff3265a23a12f811564f692bc4ce3786443/Sandbox/Sandbox.ifc

BlenderBlM Add-on vo. 7- I I -alpha240803-556c769

```
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\blenderbim\bim\module\drawing\operator.py", line 268, in execute
    linework_svg = self.generate_linework(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\blenderbim\bim\module\drawing\operator.py", line 565, in generate_linework
    self.serialiser.finalize()
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\.local\lib\python3.11\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 4828, in finalize
    return _ifcopenshell_wrapper.SvgSerializer_finalize(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: An unknown error occurred
```

**Comment by theoryshaw** [comment] 2024-08-03 15:53
Has something to do with any object that has Plan/Body/PLAN_VIEW context...

https://github.com/user-attachments/assets/1f75cd04-f77b-4cd3-9ff4-e024ce390801

**Comment by aothms** [comment] 2024-08-04 00:48
I think we had an earlier issue regarding this. Somehow in the more recent OCCT version the PolyAlgo we use doesn't seem to be happy mixing surfaces and line work in it's Hidden Line Rendering input. So we should either:

- switch from PolyAlgo to BRepAlgo
- revert the OCCT version bump back (but we need to assess the impact on the BVH additions to GeomTree, my mind is a bit fuzzy on how these line up on the version time line).
- investigate this issue in more detail, but the OCCT HLR code is near impenetrable to understand.

In the long run I don't think we can stick with the OCCT HLR code. There's frequently regressions (also earlier ones that I had to patch in the build script). Output is quite frequently missing lines. Performance is really quite bad. I think for 0.9 I would want to write my own based on a 3D Delaunay that can reuse occlusion information across multiple drawings.

@Moult @Andrej730 thoughts?

**Comment by Moult** [comment] 2024-08-04 01:29
Knowing nothing about the technical details of HLR, in general my gut feel is that it makes sense over time to move away from prepackaged solutions and build our own tailored, more domain specific functionality. Ive seen this happen quite a few times in BBIM (e.g. our own undo system, our own test framework, our own qto, our own UI...)

Can we redirect some funding to you / Richard / Scott? I feel as though there is a huge amount of C++ needed as we outgrow what OCC already does and the number of users grow.

**Comment by aothms** [comment] 2024-08-04 02:26
I think you're right. We need to be a bit more strategic in terms of identifying limitations, find the best way to address these, attract funds and move on. As an open source guy I tend to take many limitations for granted and sit and wait for the ecosystem to improve, but our usage often is rather domain specific.

But I we also need to make a quick decision on the points above for 0.8. I think OCCT 7.7 + PolyAlgo is an unlucky combination for our drawing use case. Do you have input on that?

**Comment by Moult** [comment] 2024-08-05 05:12
This seems to be (yet another) duplicate of #4924. This seems to be one of the few critical bugs left for the next release due to the number of reports.

**Closed by Moult** 2024-08-05 05:12 UTC
Labels: IfcOpenShell-Core

**Comment by SavuGust27** [comment] 2024-08-27 13:29
I can confirm this also happens to me

**Comment by theoryshaw** [comment] 2024-08-29 02:48
Fixed w/ https://github.com/IfcOpenShell/IfcOpenShell/releases/tag/bonsai-0.7.11-alpha240829 !
