### ISSUE TITLE
Bonsai | Activating the Perspective Drawing Shows error after the file is saved and reopened! | Blender 4.3.0 | Bonsai v0.8.0 | Windows OS

### ISSUE THREAD

**Issue by Arunarchitect** [IfcOpenShell/IfcOpenShell#5879] opened 2024-12-15 13:32 UTC
It works fine when the perspective camera is added and firstly activated, but when I save the file and reopens it, clicking to activate the perspective gives me error.
The file Link - https://github.com/Arunarchitect/SreekeshIFC.git

This is the error message shown- 

Python: Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 1791, in invoke
    return self.execute(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 1806, in execute
    core.activate_drawing_view(tool.Ifc, tool.Blender, tool.Drawing, drawing=drawing)
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\.local\lib\python3.11\site-packages\bonsai\core\drawing.py", line 488, in activate_drawing_view
    camera = drawing_tool.import_drawing(drawing)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\.local\lib\python3.11\site-packages\bonsai\tool\drawing.py", line 696, in import_drawing
    camera = tool.Loader.create_camera(drawing, representation, shape)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\.local\lib\python3.11\site-packages\bonsai\tool\loader.py", line 695, in create_camera
    width = max(x) - min(x)
            ^^^^^^
ValueError: max() arg is an empty sequence

**Comment by Arunarchitect** [comment] 2024-12-15 13:34
![Uploading Issue15dec.png…]()

**Comment by Arunarchitect** [comment] 2024-12-15 13:34
![Issue15dec](https://github.com/user-attachments/assets/ec0f737d-0a8e-43e2-bc40-140b960bf2e8)

**Comment by theoryshaw** [comment] 2024-12-15 16:17
I think this was fixed already if you want to try the latest releases...
https://github.com/IfcOpenShell/IfcOpenShell/releases

**Comment by Andrej730** [comment] 2024-12-16 06:55
Duplicate of #5241.

@Arunarchitect indeed, please try the latest build from the releases.

**Closed as completed by Andrej730** 2024-12-16 06:55 UTC
Labels: Bonsai

**Comment by Arunarchitect** [comment] 2024-12-16 10:03
Yes it worked fine for me in the latest release, thank you! @Andrej730 

os: Windows
os_version: 10.0.19044
python_version: 3.11.9
architecture: ('64bit', 'WindowsPE')
machine: AMD64
processor: Intel64 Family 6 Model 165 Stepping 3, GenuineIntel
blender_version: 4.3.0
bonsai_version: 0.8.1-alpha241212
