### ISSUE TITLE
BlenderBIM: No dropdowns for PredefinedType

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#1179] opened 2020-12-17 05:32 UTC
I *think* they existed at one time.

Video: https://www.dropbox.com/s/6qi9dkw16w33osv/2020-12-16_23-31-26.mp4?dl=0

**Comment by Moult** [comment] 2020-12-17 06:37
Not a bug, it was never there. Spooky.

Click on the "reassign ifc class" button just above it :) 

Buuut, I did have plans to support proper "clever" data types in the attributes not just text fields in the roadmap so even though I'm closing this bug, in the future expect for all dropdowns to appear for any attribute that can be selected. Similarly, any numeric attribute will magically turn into a slider, etc.

**Closed** 2020-12-17 06:37 UTC
Labels: BlenderBIM

**Comment by theoryshaw** [comment] 2020-12-17 18:14
there it is! spooky indeed. :)
