### ISSUE TITLE
IfcPatch - ExtractElements - Int32 error

### ISSUE THREAD

**Issue by TZwielehner** [IfcOpenShell/IfcOpenShell#2079] opened 2022-03-07 10:58 UTC
The ExtractElements doesn't work for me. The log file is empty; if I run it from an IDE (VS) I get the following error:
"Could not convert to integer: 3221226505. Path 'exitCode'.

Int32 too large or too small.

The IFC file is not too large. If the selector doesn't find any object (e.g. no windows in source model) the generated output is fine, only containing project data.

**Comment by Moult** [comment] 2022-03-14 01:28
That looks funky. Do you have sample code I can reproduce? Is it specific to an IFC file?

**Comment by aothms** [comment] 2022-03-14 09:22
My guess of what happens is that the python process crashes somehow (maybe there is something invalid'ish in the file) and returns a negative exit code, which VS has trouble interpreting.

**Comment by Moult** [comment] 2022-03-26 09:47
I might close this in the next few days if there isn't any data to reproduce, since I cannot reproduce it unfortunately.

**Comment by TZwielehner** [comment] 2022-03-30 08:45
Cannot reproduce it, too. Can be closed then. Thanks!

**Closed** 2022-03-30 08:48 UTC
Labels: IfcPatch
