### ISSUE TITLE
Unexpected geometry when convertig IfcFixedReferenceSweptAreaSolid into shape

### ISSUE THREAD

**Issue by stefanherle** [IfcOpenShell/IfcOpenShell#5502] opened 2024-09-27 07:44 UTC
Hi,
we recently ran into an issue with the conversion from IFC to gltf.

When converting a IfcFixedReferenceSweptAreaSolid into a gltf file by using the `ifcopenshell.geom.shape(...)` function, we run into unexpected behaviour.

First, we create an IfcFixedReferenceSweptAreaSolid with a profile and a 3D directrix. As directrix we use a IfcGradientCurve. The resulting ifc file can be found here: 
[Example_GitHub_IfcFixedReferenceSweptAreaSolid_Steep.ifc.txt](https://github.com/user-attachments/files/17160743/Example_GitHub_IfcFixedReferenceSweptAreaSolid_Steep.ifc.txt)

The IfcFixedReferenceSweptAreaSolid is visualized correctly in BIM software like DESITE or BIMCollab: 
<img width="1157" alt="ifc" src="https://github.com/user-attachments/assets/1984b833-0c20-417e-a6e1-1bbc86292a96">

In a second step, we use the shape function to receive the vertices of its shape in order to convert it to gltf ([FixedReferenceSweptAreaSolid_Steep.gltf.txt](https://github.com/user-attachments/files/17160752/FixedReferenceSweptAreaSolid_Steep.gltf.txt)). When visualising the gltf, it is depicted with jumps in the solid in z direction: 
<img width="1101" alt="gltf" src="https://github.com/user-attachments/assets/a7a2f456-c554-440f-ae1d-187ffd173ac9">

Since we do not expect this behaviour, we inspected the resulting vertices of the shape function. The jumps are already included in the vertices list:
<img width="294" alt="shapeGeomVerts_jump" src="https://github.com/user-attachments/assets/12a3d1f7-2d53-4133-8000-136318ad6b7e">
<img width="550" alt="groupedVerts_jump" src="https://github.com/user-attachments/assets/a3d438cb-ab7d-44ff-bcb4-99fde7670dc2">

We use: 
- ifcopenshell 0.8.0 (python API)
- IFC4x3

Can you think of something that causes this behaviour?

Thanks!
Stefan

**Comment by aothms** [comment] 2024-09-27 08:00
Interestingly ODA's viewer also renders Jumps:

![afbeelding](https://github.com/user-attachments/assets/5b5e8cb9-65a4-4f81-ba66-9e2e072f764b)

But RDF's implementation doesn't

![afbeelding](https://github.com/user-attachments/assets/bac3e1f3-f4b8-42cd-8c24-a69b3263f14f)

Maybe @RickBrice or @civilx64 can use their math skills to see who is right.

I personally wouldn't be surprised if it's due to non-normalized directions:

> #52=IFCDIRECTION((1.,1.));

and the use of parameter values:

> #58=IFCCURVESEGMENT(.CONTINUOUS.,#57,IFCPARAMETERVALUE(0.),IFCPARAMETERVALUE(1.E-06),#54);

Note that the IFC4X3 schema is withdrawn by bSI and superseded by IFC4X3_ADD2. The use of parameter values is at the moment no longer allowed and one is to use length measures.

**Comment by stefanherle** [comment] 2024-09-27 12:21
Thanks for your suggestions! In the following ifc file we switched to IFC4X3_ADD2 and replaced IfcParameterValue by IfcLengthMeasure: [github_min_example_IfcFixedReferenceSweptAreaSolid_IFC4x3_ADD2.ifc.txt](https://github.com/user-attachments/files/17164023/github_min_example_IfcFixedReferenceSweptAreaSolid_IFC4x3_ADD2.ifc.txt)


However, the geometry computation still produces the same unexpected results...

**Comment by RickBrice** [comment] 2024-09-27 14:23
I think the problems start with the IfcCompositeCurve. My plot of it looks like this
![image](https://github.com/user-attachments/assets/e19e1edb-635a-438d-9604-f42304562466)

There are non-normalized directions defining the IfcLine parent curves such as `#27=IFCDIRECTION((19.9379048245028,-1.5657538054511));` but I think this is valid.

I tried to deal with this in IFCOS, but perhaps I did it incorrectly. I will investigate and report back (and fix if it is my error).

**Comment by civilx64** [comment] 2024-09-27 18:17
> but I think this is valid.

Yes, per the schema the magnitudes of [IfcDirection](https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/HTML/lexical/IfcDirection.htm) do not need to be normalized.

**Comment by RickBrice** [comment] 2024-09-28 13:30
The problem was in the IfcCurveSegment code I wrote. I didn't handle the non-normalized IfcDirection correctly. That has been fixed and pushed. See commit https://github.com/IfcOpenShell/IfcOpenShell/commit/abe3d7e5db13d9cfb8945a3b4559d3f0015b66cd

The vertical steps look correct.

![image](https://github.com/user-attachments/assets/6344ae79-b402-45fd-a423-7796af4ab716)

Looking at this small subset of the curve segments of the IfcGradientCurve

~~~
#51=IFCCARTESIANPOINT((0.,0.));
#52=IFCDIRECTION((1.,0.));
#53=IFCVECTOR(#52,1.);
#54=IFCLINE(#51,#53);

#59=IFCCARTESIANPOINT((20.,-0.370586460673734));
#60=IFCDIRECTION((1.,0.));
#61=IFCAXIS2PLACEMENT2D(#59,#60);
#62=IFCCURVESEGMENT(.CONTINUOUS.,#61,IFCLENGTHMEASURE(0.),IFCLENGTHMEASURE(20.),#54);
#63=IFCCARTESIANPOINT((40.,-1.13551308653061));
#64=IFCDIRECTION((1.,0.));
#65=IFCAXIS2PLACEMENT2D(#63,#64);
#66=IFCCURVESEGMENT(.CONTINUOUS.,#65,IFCLENGTHMEASURE(0.),IFCLENGTHMEASURE(20.),#54);
~~~

The parent curve is a horizontal IfcLine. The placement of each trimmed segment of the IfcLine is also horizontal (`#60` and `#64`). Curve segments `#62` and `#65` are placed at different elevations creating a step.

If someone see it differently, let me know - otherwise I think this issue is resolved.

@aothms note that the steps are not plotted as true vertical lines. https://github.com/IfcOpenShell/IfcOpenShell/issues/5360 should resolve that problem.

**Comment by civilx64** [comment] 2024-09-28 13:38
I have not dug in to this issue but it appears the design intent is a (relatively) smooth solid without vertical jumps -  per the original screenshot from DESITE or BIMSite.

**Comment by civilx64** [comment] 2024-09-28 13:54
These types of vertical alignment layouts are exactly what I've used when modeling noise barrier walls like this one: 
![image](https://github.com/user-attachments/assets/a6846590-a673-4162-ab62-b1d7299985c1)

**Comment by RickBrice** [comment] 2024-09-28 14:07
The IfcCurveSegment.Transition = CONTINUOUS. Are we supposed to "force" the end point of one segment to match the start point of the next? I haven't done that. 

I interpreted the transition code to specify an intent and the actual geometric definition should match that intent. I haven't run this through the VS, would it flag the actual geometry and transition code mismatch as an error?

**Comment by civilx64** [comment] 2024-09-28 15:34
Excellent point! 

>I interpreted the transition code to specify an intent and the actual geometric definition should match that intent.

I agree.  On import the geometry should take precedence if it is calculated to conflict with the value of the Transition attribute. There's probably value in logging or displaying this as a warning to the user performing the input. 

As it currently stands this model (2nd version, IFC4X3_ADD2) is non compliant as IfcCurveSegment.Transition should have been coded as `.DISCONTINUOUS.`  since there is not continuity in position, tangency, or curvature at the provided start point of the following segments.

The validation service has a rule ALS016 that verifies the agreement between the geometric definition and Transition attribute for IfcCompositeCurve.  Rule ALS017 to do a similar check for IfcGradientCurve is underway but not released yet and currently a lower priority as we work to finalize v0.6.7.  A future rule ALS018 is planned that will cover this check for IfcSegmentedReferenceCurve.

All three of these validation checks regarding continuity between segments are classified as Industry Best Practices, meaning that they raise a warning, not an error.

**Comment by RickBrice** [comment] 2024-09-28 15:38
> IfcCurveSegment.Transition should have been coded as .DISCONTINUOUS. 

.DISCONTINUOUS. can only be used at a curve boundary.

**Comment by civilx64** [comment] 2024-09-28 15:57
Ok.  So perhaps I have the minority view and the value of Transition should govern over the calculated end point of a segment if the Direction of the line segment does not correspond to the direction calculated between start points of successive curve segments.  That appears to be the route taken by some of the viewers listed above.

That approach would be consistent with the number of segments defined in IfcGradientCurve in this example.
Said another way, if the design intent were to actually have vertical steps - as in my noise barrier example above - then IfcGradientCurve would need to alternate between segments with direction `(1., 0.)` for the flat portion and `(0., -1.)` for a vertical step to go lower in height, followed by another segment with direction `(1., 0.)`.

**Comment by RickBrice** [comment] 2024-09-28 16:22
> Regardless of the choice taken by an implementer during input, this model as-is will (in the future) still raise a warning in the validation service

But that warning would be based on IFCOS implementation of not considering the transition code when computing geometry. If the transition code were considered and the geometry was "smoothed" so there is positional continuity between end points, the warning would not be needed.

I though the idea of using the transition code to indicate how to "smooth" geometry was for "good enough" geometry from the days of hand drawn 2D plan sheets. Round off in numbers on plans might result in small discontinuities at segment boundaries. The transition code then provides the intent. This model seems to be in opposition to that idea.

**Comment by civilx64** [comment] 2024-09-28 17:07
> small discontinuities at segment boundaries

Yes, this is why we include a tolerance in the rule checking, with on-going discussions around what that tolerance should be and whether there should be additional options for an exporting application to provide additional clarity on design intent and how good is "good enough" regarding the interface points between segments.

Could the IFCOS implementation keep the current "geometry definition overrules Transition" attribute approach by default with an optional parameter to the `get_shape()` call that would allow for the alternate "Transition overrules geometry definition" stance?  (or the other way around in terms of which is the default approach if that is the community consensus). From what I recall there were initial thoughts about potentially distributing this error over the length of a segment but the implementation was quite difficult.

**Comment by RickBrice** [comment] 2024-09-28 17:48
The implementation is difficult. Applying a linear distribution of the mismatch over the length of a segment is easy but all of this becomes increasingly complicated if there must also be tangential and or curvature continuity smoothed out. There are also many approaches to smoothing. For example a circular curve, the radius and central angle can be modified instead of the linear approach. The complexity grows with the various spiral types. And to add another wrinkle, an IfcCurveSegment can simultaneously belong to different IfcCompositeCurve (and its subtypes) where the next segment, and its start point, tangency, and curvature can be different for each composite curve in which it belongs. It is impossible to grab a curve segment and compute its geometry without context, and in general, the context is not unique. Hence I took the easy way out and ignored the transition code.

**Comment by RickBrice** [comment] 2024-10-01 02:31
@civilx64 Please remind me which property sets and properties were proposed for alignment geometry tolerances. I looked back through the presentations from the general assembly but couldn’t find them.

**Comment by civilx64** [comment] 2024-10-01 12:46
There were two situations discussed at the August 2024 general assembly.  The first relates to the discussion in this thread regarding the nomination of an acceptable tolerance under which the calculated end point of a preceding segment would be considered geometrically continuous with the provided start point of the following segment.  I had suggested [Pset_Tolerance](https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/HTML/lexical/Pset_Tolerance.htm) for this purpose.  I envision this being  associated to IfcAlignmentHorizontalSegment, IfcAlignmentVerticalSegment, and IfcAlignmentCantSegment entities, which would allow for varying tolerances per segment if desired.

The second use case is related to exchanging alignment data from record plans or other historic sources where the tools and technology of the day limited the mathematical precision of the alignment geometry.  This was originally brought up by one of the vendors during conversations in the Software Certification pilot group.  I suggested [PsetUncertainty](https://standards.buildingsmart.org/IFC/RELEASE/IFC4_3/HTML/lexical/Pset_Uncertainty.htm) at the assembly to be used this purpose.  I would assume that this would be associated to IfcAlignment as I can't envision a situation where it would need to be specific to any of the horizontal, vertical, or cant layouts or any of the segments within a layout.

I arrived at these suggestions primarily by looking through the schema to find something that seems appropriate.  It's entirely possible that these property sets were developed with a radically different purpose than what I have recommended here.  As usual, take my input with the appropriately-sized grain of salt. :smile:

**Comment by RickBrice** [comment] 2024-10-01 15:17
Thanks @civilx64 - if I recall, IfcGeometricRepresentationContext.Precision would then be a fall back if Pset_Tolerance was not provided.

I ran the subject file through the validation service and there are several errors, but not having to do with the "stair step" vertical geometry. Rule ALS017 isn't deployed yet, but when it is, it should pick up the end-start IfcCurveSegment distance for IfcGradientCurve as exceeding tolerance.

Without clear guidance on how, or if, the geometry should be "smoothed" based on the Transition Code, I will leave the implementation as is for now.

If @aothms @civilx64 @stefanherle have specific changes in mind, let me know and we can figure out the details.

**Comment by RickBrice** [comment] 2024-10-01 15:58
![image](https://github.com/user-attachments/assets/66e8a7dc-c4d5-4049-a9e1-f96724ea0707)

Same as ODA and I think it is technically correct.

Not sure when the Bonsai deployment picks up changes to IfcOpenShell, but the fixes have been committed.

**Comment by thlemm** [comment] 2024-10-02 07:44
Hi everyone,
I am working on this project together with @stefanherle and wanted to share some feedback.

First, we really appreciate the effort you put into our issue.

We created three new models for testing purposes. All models share the following changes:
1.	All direction vectors are normalized 😉
2.	IFC4x3_ADD2
3.	A new gradient profile is used that is easier to compare. The segments alternate between one horizontal segment and one segment with gradient. 

Example_Model_1: The direction ratios are normalized. No other changes.
Example_Model_2: The direction ratios of the parent curve point into the direction of the start of the next curve segment.
Example_Model_3: The direction ratios of the segment placement point into the direction of the start of the next curve segment.
[github_issue_5502_example_1.ifc.txt](https://github.com/user-attachments/files/17221271/github_issue_5502_example_1.ifc.txt)
[github_issue_5502_example_2.ifc.txt](https://github.com/user-attachments/files/17221272/github_issue_5502_example_2.ifc.txt)
[github_issue_5502_example_3.ifc.txt](https://github.com/user-attachments/files/17221273/github_issue_5502_example_3.ifc.txt)

We tested the results with different viewers: The IFC-File in Desite and the Shape (ifcopenshell.geom.create_shape()) we converted to GLTF in 3dviewer.net

Example_Model_1: 
•	In Desite the behavor did not change compared to our initial approach. This is what we intended to accomplish.
![Example_1_Desite](https://github.com/user-attachments/assets/2fcbdf28-66b8-454a-a4b2-a92760345059)
•	The GLTF in 3dviewer.net now shows the same behavior as @RickBrice showed in his last answer.
![Example_1_3dviewer](https://github.com/user-attachments/assets/a9ab9417-4aff-4876-82f2-1387b8438c21)


Example_Model_2: 
•	The results in Desite again do not differ. We still get a continuous solid as we originally intended to do. 
•	The GLTF also shows no difference to Example_Model_1. We assume this is due to the fact, that the parent curve is still a straight line and the segment itself has a horizontal direction.

Example_Model_3: 
•	Now we have a different result in Desite. The segments with a gradient (intended to be a gradient in x-direction) now have an additional tilt or rotation around the x-axis. This rotation increases with the gradient in x-direction.
![Example_3_desite_detail](https://github.com/user-attachments/assets/e50651b2-8e8e-4212-a9cb-fc7f193db783)
•	The GLTF in 3dviewer.net now shows the same as the IFC in Desite. We get a continuous solid with slightly rotated segments.
![Example_3_3dviewer](https://github.com/user-attachments/assets/993d747d-6467-495c-8f06-091ed0d220bb)
![Example_3_3dviewer_detail](https://github.com/user-attachments/assets/8c2f948b-dc73-4759-abbe-5375213da962)


Is it possible, that the DirectionRatios we have set for the IfcAxis2Placement2D of the IfcCurveSegment are interpreted to be in x and y direction in stead of x and z? This could probably explain this behavior. Or are we missing something here?

> I interpreted the transition code to specify an intent and the actual geometric definition should match that intent.

From our point of view this is a very good point! Sadly we weren't able yet to define our intended geomety without the described sideeffect of a rotation of the segments round the x-axis.

Thanks again for your effort. This really helps us to improve out models.

**Comment by RickBrice** [comment] 2024-10-02 16:13
This is a very interesting problem. At first I thought the twist might be related to the horizontal curve defined by IfcCompositeCurve. The sloped portions of the vertical profile slope relative to the "distance along" coordinate system defined by the horizontal alignment. The slopes are in a rotated 2D coordinate system so maybe they look like twists in 3D.

To test that theory, I changed the IfcCompositeCurve to a single straight segment in the X-Y plane. The twist still occurs proving my theory wrong.

I'll investigate to see if there is a bug or if this is the proper geometry (and why).

Here is my file and screen image.

[github_issue_5502_example_4.ifc.txt](https://github.com/user-attachments/files/17232716/github_issue_5502_example_4.ifc.txt)

![image](https://github.com/user-attachments/assets/f3ed1dd4-99ff-4242-becb-5c0df96b89ac)

![image](https://github.com/user-attachments/assets/6f1718d3-c219-4961-97a6-3708f55e3d8e)

**Comment by RickBrice** [comment] 2024-10-03 03:40
I'm not really an expert with IfcFixedReferenceSweptAreaSolid, but I think the "twist" is coming from the FixedReference parameter.

~~~
#114=IFCDIRECTION((-0.707106781186547,-0.707106781186547,0.));
#115=IFCFIXEDREFERENCESWEPTAREASOLID(#113,$,#107,$,$,#114);
~~~

The downhill slope, combined with the -45 degree direction, is creating the twist.

The solid looks quite reasonable with 

~~~
#114=IFCDIRECTION((0.,1.,0.));
#115=IFCFIXEDREFERENCESWEPTAREASOLID(#113,$,#107,$,$,#114);
~~~

![image](https://github.com/user-attachments/assets/81f68d56-37c4-4d0b-8674-bb4575c3e085)

It would be good if someone more knowledgeable with IfcFixedReferenceSweptAreaSolid can confirm the problem is the FixedReference direction.

For now, I think the IFCOS implementation is working properly.

**Comment by aothms** [comment] 2024-10-03 07:10
Yes, most likely that's true.

FixedRefSweptArea has a fixed reference that is projected onto the normal plane along the directrix.

![afbeelding](https://github.com/user-attachments/assets/9e105690-d9e1-4266-acc2-8badcefc9219)

So when elevation is constant, directrix tangent z = 0, so projected ref z is also zero given that ref z is zero, but when directrix tangent z  (`n` in example below) is non zero a twist occurs.

```
>>> import numpy
>>> from math import *
>>> v = numpy.array((1 / sqrt(2), 1 / sqrt(2.), 0))
>>> v
array([0.70710678, 0.70710678, 0.        ])
>>> n = numpy.array((0.,1,0))
>>> v - n * (n @ v)
array([0.70710678, 0.        , 0.        ])
>>> n = numpy.array((0.,1,0.2)) / sqrt(1.04)
>>> n
array([0.        , 0.98058068, 0.19611614])
>>> v - n * (n @ v)
array([ 0.70710678,  0.02719641, -0.13598207])
>>>
```

Maybe our interpretation of this is wrong though, because what's the utility of this kind of operation? You have to be really careful about singularities (what if v == n?)

But yeah, that's mentioned in the informal propositions:

- The SweptArea shall lie in the plane z = 0.
- The FixedReference shall not be parallel to a tangent vector to the directrix at any point along this curve.
- The Directrix curve shall be tangent continuous.

https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcFixedReferenceSweptAreaSolid.htm

I guess the reason the twist is so ugly is also because of the violation of the informal prop 3?

**Comment by Moult** [comment] 2024-10-09 00:38
BTW with the bumped bot build the latest Bonsai should now visualise this result shown below.

I guess if there's no further bug here it's good to close this issue?

![2024-10-09-113725_260x228_scrot](https://github.com/user-attachments/assets/4c666f95-c062-43fb-bce6-c5dfef8c5be7)

**Comment by RickBrice** [comment] 2024-10-09 02:39
I think there is no bug here. Re-open if you disagree

**Closed by RickBrice** 2024-10-09 02:39 UTC
Labels: IfcOpenShell-Core
