### ISSUE TITLE
Save CAD model in .ifc file format

### ISSUE THREAD

**Issue by chavan-vjti** [IfcOpenShell/IfcOpenShell#300] opened 2017-11-17 11:33 UTC
Hello,
How can I export/save the displayed CAD model in .ifc file format using PythonOCC (Open CASCADE)?
Any help is highly appreciated.
Thank you!

**Comment by aothms** [comment] 2017-11-17 12:14
Hi,

You can use `ifcopenshell.geom.tesselate()` or  `ifcopenshell.geom.serialize()` to write a PythonOCC TopoDS_Shape to an IFC file. That'd just be the geometry, you can create the necessary project hierarchy for example using `ifcopenshell.template.create()`.

There is no fool proof way though of getting geometry out in this way. IFC importers will typically rely on a lot of other meta-data and conventions in order to construct a meaningful native interpretation again. Have a look for example at the IFC implementation guide for that [1].

[1] http://www.buildingsmart-tech.org/implementation/ifc-implementation/ifc-impl-guide/ifc-impl-guide-summary

Hope that helps,

Kind regards,
Thomas

**Comment by chavan-vjti** [comment] 2017-11-17 12:35
Any import statement needed for this?

**Comment by aothms** [comment] 2017-11-17 13:06
Yes

~~~
import ifcopenshell
import ifcopenshell.geom
~~~

**Comment by chavan-vjti** [comment] 2017-11-20 07:24
Hello,
I have Miniconda2 set as my python interpreter and I am installing python package ("ifcopenshell-0.5dev-py27_0.tar.bz2" in this case) by a command "conda install ifcopenshell-0.5dev-py27_0.tar.bz2" but it happens that ifcopenshell doesn't get installed properly. Consequently, I can't call an import statement to write TopoDS_shape to .ifc file.
Any suggestion?
I have also tried executing this command, " conda install -c lorinma ifcopenshell " but even though it couldn't install. :( :'(

**Comment by aothms** [comment] 2017-11-20 09:59
> `conda install ifcopenshell-0.5dev-py27_0.tar.bz2`

Can you use `conda install` like that? I thought it uses a repository to get its packages from.

You can just extract the contents from the zip to the site-packages directory (`impor site; site.getsitepackages()[-1]`).

**Comment by chavan-vjti** [comment] 2017-11-20 10:57
No existence of tesselate() or serialize() function in ifcopenshee.geo.__init__().py 
![ifcopenshell](https://user-images.githubusercontent.com/26323532/33015138-acb3e93a-ce0f-11e7-8166-6409ce5aa814.jpg)

**Comment by chavan-vjti** [comment] 2017-11-21 11:59
Hi,
In the context of using **ifcopenshell.geom.serialize()** or **ifcopenshell.geom.tesselate()**, I called a function **make_shape_function()** passing an argument of my TopoDS_Shape to convert the TopoDS_Shape into .ifc file format but still it didn't work.
Any suggestion on this?
Thank you in advance!

**Comment by aothms** [comment] 2017-11-22 09:48
They have been added about a year ago. What version are you using?

https://github.com/IfcOpenShell/IfcOpenShell/blame/master/src/ifcopenshell-python/ifcopenshell/geom/main.py#L178

Kind regards,
Thomas

**Comment by chavan-vjti** [comment] 2017-11-22 12:49
I'm using version 0.5 something of IFCOpenShell.
I'm bit confused about converting TopoDS_shape to IFC file format.
Do I have to call the whole script (main.py) or just the method, make_shape_function ?

Kind regards,
Siddhesh

**Comment by aothms** [comment] 2017-11-27 09:47
Hi,

Sorry for the late reply.

> I'm using version 0.5 something of IFCOpenShell.

That *something* might matter. Some features have been gradually added over time to the 0.5 version. I advise you to get the latest version.

> No existence of tesselate() or serialize() ... `make_shape_function()`

`make_shape_function` is introduced at the same time as `serialise` and `tesselate`. If you have one you have the others was well.

>  Do I have to call the whole script (main.py) or just the method, make_shape_function ?

`make_shape_function()` is a helper function (a higher order function, like a python decorator). It is not intended to be called by end users.

---

`serialise()` and `tesselate()` return a `IfcProductDefinitionShape` that you can assign to a product representation. For example.

~~~
ifcfile = ...
my_shape = ...
my_wall = ifcfile.createIfcWall(GlobalId='...', ...)
my_wall.Representation = ifcopenshell.geom.tesselate(my_shape)
~~~ 

HTH,

Kind regards,
Thomas

**Comment by chavan-vjti** [comment] 2017-11-27 10:38
Hello Thomas,

Thank you very much for your timely guidance. I appreciate it a lot.

Just last thing, I already have TopoDS_Shape displayed in my application's viewer (PthonOCC viewer). And I want to write that TopoDS_Shape into an IFC file. And this converted IFC file should have Header and Data section as well.

Any help?

**Comment by chavan-vjti** [comment] 2017-12-05 05:08
Hello Thomas,
Attached here is my IFC file (currently uploaded in **txt** file format since Git doesn't support **IFC** file format to upload).
Kindly, take a look over a file.
The issue here is that when I open this IFC file in any CAD viewer, it doesn't display the CAD model.
Any suggestion on this issue?
Thanks in advance!

Kind regards,
Siddhesh C.

[OsdagRef.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/1529769/OsdagRef.txt)

**Comment by aothms** [comment] 2017-12-16 08:53
Hi, sorry for the late reply.

Did you open the attached file in a text editor? There is nothing in the file related to geometry, e.g. an IfcExtrudedAreaSolid (or other IfcGeometricRepresentationItems) and no product (e.g. a IfcWindow, IfcWall). This is basically the equivalent of a more or less empty file, with only an IfcProject.

Perhaps attach the code you used to generate this file will be helpful.

**Comment by chavan-vjti** [comment] 2017-12-16 10:21
`import time`
`import uuid`

`create_guid = lambda: ifcopenshell.guid.compress(uuid.uuid1().hex)`

`timestamp = time.time()`
`timestring = time.strftime("%Y-%m-%dT%H:%M:%S", time.gmtime(timestamp))`
`creator = "Osdag developer"`
` organization = "Osdag"`
`application, application_version = "IfcOpenShell", "0.5"`
`project_globalid, project_name = create_guid(), "fossee"`
` Model = self.fuse_model`

` # A template IFC file to quickly populate entity instances for an IfcProject with its dependencies`
`template = """ISO-10303-21;`

`HEADER;`
`FILE_DESCRIPTION(('ViewDefinition [CoordinationView]'),'2;1');`
`FILE_NAME('%(fName)s','%(timestring)s',('%(creator)s'),('%(organization)s'),'%(application)s','%(application)s','');`
`FILE_SCHEMA(('IFC2X3'));`
`ENDSEC;`
`DATA;`
`#1=IFCPERSON($,$,'%(creator)s',$,$,$,$,$);`
`#2=IFCORGANIZATION($,'%(organization)s',$,$,$);`
`#3=IFCPERSONANDORGANIZATION(#1,#2,$);`
`#4=IFCAPPLICATION(#2,'%(application_version)s','%(application)s','');`
`#5=IFCOWNERHISTORY(#3,#4,$,.ADDED.,$,#3,#4,%(timestamp)s);`
`#6=IFCDIRECTION((1.,0.,0.));`
` #7=IFCDIRECTION((0.,0.,1.));`
`#8=IFCCARTESIANPOINT((0.,0.,0.));`
`#9=IFCAXIS2PLACEMENT3D(#8,#7,#6);`
`#10=IFCDIRECTION((0.,1.,0.));`
`#11=IFCGEOMETRICREPRESENTATIONCONTEXT($,'Model',3,1.E-05,#9,#10);`
`#12=IFCDIMENSIONALEXPONENTS(0,0,0,0,0,0,0);`
`#13=IFCSIUNIT(*,.LENGTHUNIT.,$,.METRE.);`
`#14=IFCSIUNIT(*,.AREAUNIT.,$,.SQUARE_METRE.);`
`#15=IFCSIUNIT(*,.VOLUMEUNIT.,$,.CUBIC_METRE.);`
`#16=IFCSIUNIT(*,.PLANEANGLEUNIT.,$,.RADIAN.);`
`#17=IFCMEASUREWITHUNIT(IFCPLANEANGLEMEASURE(0.017453292519943295),#16);`
`#18=IFCCONVERSIONBASEDUNIT(#12,.PLANEANGLEUNIT.,'DEGREE',#17);`
`#19=IFCUNITASSIGNMENT((#13,#14,#15,#18));`
`#20=IFCPROJECT('%(project_globalid)s',#5,'%(project_name)s',$,$,$,$,(#11),#19);`
`ENDSEC;`
`END-ISO-10303-21;`

`""" % locals()`
`import tempfile`
`temp_handle, temp_filename = tempfile.mkstemp(suffix=".ifc")`
`with open(temp_filename, "wb") as f:`
             `f.write(template)`
`ifcfile = ifcopenshell.open(temp_filename)`
`ifcfile.write(fName)`

To tell you brief about above codes, [`Osdag`](http://osdag.fossee.in/) is the name of application which will export the TopoDS_shape into IFC. `fuse_model` stores the fused CAD model of few sub-parts, done by using OCC function `BRepAlgoAPI_fuse()`.
And this `fuse_model`, I want to save/export to IFC with the name as `temp_filename.`

**Comment by aothms** [comment] 2017-12-17 10:43
You assign `Model = self.fuse_model`, but `Model` is never references anywhere wrt the creation of the IFC instances.

Did you try to follow the advise above to create a product and assign the geometry representation to it?

~~~
my_wall = ifcfile.createIfcWall(GlobalId='...', ...)
my_wall.Representation = ifcopenshell.geom.tesselate(my_shape)
~~~

If so, what errors are you getting?

**Comment by chavan-vjti** [comment] 2017-12-29 10:02
Hello Thomas,
Your timed advises and suggestions were really helpful to me. Now, I'm little confident in writing a script for IFC. 
I just want to know that, how can I create a cylinder in IFC with PythonOCC.
Thank you in advance!

**Comment by aothms** [comment] 2017-12-31 11:29
Did you try something like this?

~~~py
radius = 3
length = 4

import OCC.BRepPrimAPI
my_shape = OCC.BRepPrimAPI.BRepPrimAPI_MakeCylinder(radius, length).Shape()

my_wall = ifcfile.createIfcWall(GlobalId='...', ...)
my_wall.Representation = ifcopenshell.geom.tesselate(my_shape)
~~~

**Comment by chavan-vjti** [comment] 2018-01-01 07:25
Thank you for your suggestion. It worked well.

Just for the sake of curiosity, I just want to know, how can I create **circular cylinder** in IFC2X3 schema (using `IfcExtrudedAread` ) ?

**Comment by aothms** [comment] 2018-01-05 10:39
Have a look at the selected lines in this file. You can simply replicate those in Python, e.g. 

https://github.com/IfcOpenShell/IfcOpenShell/blob/master/test/input/IfcCircleProfileDef.ifc#L57-L66

~~~py
import ifcopenshell
f = ifcopenshell.open()
# #50=IFCDIRECTION((0.,0.,1.)); ->
f.createIfcDirection((0.,0.,1.))
...
f.write(...)
~~~

**Comment by chavan-vjti** [comment] 2018-01-05 13:34
Thank you, Thomas for suggestion. I can see here that `IfcCircleProfileDef` method has been utilized to generate a circle profile. However, I can also see that this method/function is available in C# , VB, C++ and F# but not available in Python. Am I right?
If it's unavailable in Python then how can I grab it in my Python codes? So as to create cylinder in IFC file.
Thanks!

**Comment by chavan-vjti** [comment] 2018-01-12 05:31
Can it be possible to combine two different IFC files into one?
Suppose, I've an IFC file for bolt head and another IFC file for shank part of bolt, so by combining these two different IFC files into one, will I be able to get a complete bolt?
Waiting.
Thanks!

**Comment by aothms** [comment] 2018-01-12 15:06
> C# , VB, C++ and F#

IfcOpenShell has a Python and C++ interface, not sure what else you have been seeing

> not available in Python

In Python, similar to we have been discussing above, the creation of entity instances happens by first create a file and then calling create___() on it. So, for example:

~~~py
f = ifcopenshell.open()
f.createIfcCircleProfileDef(...)
~~~

> combine two different IFC files into one

In theory this is possible, but you need to take care of creating a valid file yourself, i.e making sure that cardinalities are correct, relationships are meaningful, etc.

~~~py
f0, f1 = ifcopenshell.open(...), ifcopenshell.open(...)
for inst in f1:
    if ...:
        f0.add(f1)
~~~

**Comment by chavan-vjti** [comment] 2018-01-21 07:02
Hello sir,

It would be really helpful if I could get the python codes (.py file) for this IFC file 
[https://github.com/IfcOpenShell/IfcOpenShell/blob/master/test/input/IfcCircleProfileDef.ifc#L57-L66](url)

I tried several options among your suggestions but somewhere I'm missing something. So, just to conclude the things, it would be helpful if I get the right file.

Thanks!

Kind regards,
Siddhesh

**Comment by aothms** [comment] 2018-01-23 11:26
There is no Python file, it's generated in C++, here [1].

https://github.com/IfcOpenShell/IfcOpenShell/blob/master/src/examples/profiles.cpp#L171

Hope that helps,

Kind regards,
Thomas

**Comment by Moult** [comment] 2023-02-14 02:32
This is not a bug and I think the answers have been sufficient so closing.

**Closed by Moult** 2023-02-14 02:32 UTC
